import {test,expect} from '@playwright/test';
import {mkdir,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {apiURL} from './test-environment';

const local='+proj=aeqd +lat_0=0 +lon_0=0 +datum=WGS84 +units=m +type=crs';
async function json(request:any,path:string,data?:any){const r=data===undefined?await request.get(apiURL+path):await request.post(apiURL+path,{data});expect(r.ok(),await r.text()).toBe(true);return r.json()}
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:20000})}
async function shot(page:any,name:string,selector='.ac-preview'){await page.setViewportSize({width:1800,height:1250});const toast=page.getByRole('button',{name:'关闭提示',exact:true});if(await toast.isVisible())await toast.click();if(selector)await page.locator(selector).first().scrollIntoViewIfNeeded();const directory=process.env.OCEANROUTE_ARTIFACTS_DIR||'artifacts/development-0.11';await mkdir(directory,{recursive:true});await page.screenshot({path:join(directory,'altercourse-0.11-'+name+'.png'),fullPage:true})}
async function fixture(request:any,options:{four?:boolean;unknown?:boolean;second?:boolean;fixed?:boolean;shared?:boolean}={}){
 const p=await json(request,'/sample');p.id='ac-ui-'+Date.now()+'-'+Math.random().toString(16).slice(2);p.name='明确合成转向测试 '+p.id;p.events=[];
 const depth=options.unknown?null:1000;
 p.route={...p.route,curve:'geodesic',mode:options.fixed?'fixed':'flexible',slack_basis:'surface',slack_pct:0,points:[{id:'ac-a',label:'合成起点',longitude:0,latitude:0,depth_m:depth,note:''},{id:'ac-b',label:'合成转向B',longitude:.02,latitude:0,depth_m:depth,note:''},{id:'ac-c',label:options.four?'合成转向C':'合成终点',longitude:.02,latitude:.02,depth_m:depth,note:''},...(options.four?[{id:'ac-d',label:'合成终点',longitude:.04,latitude:.02,depth_m:depth,note:''}]:[])],legs:[]};
 p.route.legs=p.route.points.slice(1).map((_:any,i:number)=>({cable_type_id:p.cable_types[0].id,mode:options.fixed?'fixed':'flexible',slack_basis:'surface',slack_pct:0,fixed_cable_length_m:options.fixed?(i===0?2600:2700):null,allowance_m:0,burial:false}));
 p.bodies=[];p.layers=[];p.profile={samples:[],source:'明确合成路线点'};delete p.side_slopes;p.slope_rules=[];
 p.terrain_sources=options.unknown?[]:[{id:'ac-flat-source',name:'明确合成1000m平面',kind:'surfer',enabled:true,priority:100,source_crs:local,depth_positive:'down',depth_units:'m',vertical_datum:'SYNTHETIC_AC_DATUM',data_base64:Buffer.from('DSAA\n3 3\n-1000 5000\n-1000 5000\n1000 1000\n1000 1000 1000\n1000 1000 1000\n1000 1000 1000\n').toString('base64'),sampling:{method:'linear'}}];
 let w=(await json(request,'/workspace/migrate',{project:p})).workspace;w.ac_extension={retained:[0,null,'user-data']};
 w.automatic_rules=[{id:'retained-inline',name:'保留声明',enabled:false,path_id:w.active_path_id,kind:'slope',slope_basis:'inline',start_kp_m:0,end_kp_m:null,max_inline_slope_deg:89}];
 if(options.second||options.shared){const original=w.active_path_id;w=(await json(request,'/workspace/action',{workspace:w,config:{action:'copy_path',path_id:original,name:'未修改备选',assembly_policy:options.shared?'alternative':'unassigned'}})).workspace;w=(await json(request,'/workspace/action',{workspace:w,config:{action:'set_active',path_id:original}})).workspace}
 return (await json(request,'/workspaces',w)).workspace;
}
async function tools(page:any){await page.getByRole('button',{name:'工程工具',exact:true}).click();await page.locator('.engineering-menu button').filter({has:page.getByText('转向点处理',{exact:true})}).click();await expect(page.locator('.altercourse-tools')).toBeVisible()}
async function open(page:any,w:any){await page.goto('/');await ready(page);await page.getByRole('button',{name:'打开',exact:true}).click();await page.locator('.project-list button').filter({has:page.getByText(w.name,{exact:true})}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await ready(page);await tools(page);await page.getByLabel('内部转向点',{exact:true}).selectOption('ac-b');await expect(page.locator('.ac-selection')).toHaveAttribute('data-point-id','ac-b')}
async function preview(page:any,kind='split'){await page.getByLabel('转向操作',{exact:true}).selectOption(kind);const seen=page.waitForResponse((r:any)=>r.url().endsWith('/api/workspace/altercourse-preview'));await page.getByRole('button',{name:'预览转向候选',exact:true}).click();const r=await seen;expect(r.ok(),await r.text()).toBe(true);await expect(page.locator('.ac-preview')).toBeVisible();return r.json()}
async function apply(page:any){const seen=page.waitForResponse((r:any)=>r.url().endsWith('/api/workspace/action')&&r.request().postDataJSON()?.config?.action==='update_path');await page.getByRole('button',{name:'应用转向候选',exact:true}).click();const r=await seen;expect(r.ok(),await r.text()).toBe(true);expect(r.request().postDataJSON().config.update_shared).toBeUndefined();await expect(page.locator('.ac-preview')).toHaveCount(0);await ready(page);return r.json()}
async function save(page:any,revision:number){const seen=page.waitForResponse((r:any)=>r.url().endsWith('/api/workspaces')&&r.request().method()==='POST');await page.getByRole('button',{name:'保存',exact:true}).click();const r=await seen;expect(r.ok(),await r.text()).toBe(true);await expect(page.getByText('工程已保存 · 修订 '+revision,{exact:true})).toBeVisible();return r.json()}
async function held(page:any,url:string,predicate:(data:any)=>boolean=()=>true){let release!:()=>void,arrived!:(r:any)=>void;const gate=new Promise<void>(r=>release=r),seen=new Promise<any>(r=>arrived=r);await page.route('**/api/'+url,async(route:any)=>{if(!predicate(route.request().postDataJSON())){await route.continue();return}const actual=await route.fetch();arrived(actual);await gate;await route.fulfill({response:actual})});return {release,seen}}
function active(w:any){return w.paths.find((p:any)=>p.id===w.active_path_id).project}

test('Split AC previews actual internal points, applies a complete workspace once, then undo, redo and explicit save preserve other resources',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const before=await fixture(request,{second:true});await open(page,before);const saves:any[]=[];page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/workspaces'))saves.push(r.postDataJSON())});
 const candidate=await preview(page);expect(candidate.operation).toMatchObject({kind:'split',path_id:before.active_path_id,config:{point_id:'ac-b',max_turn_angle_deg:45,min_turn_distance_m:100}});expect(candidate.tool_report.changed).toBe(true);expect(candidate.project.route.points.length).toBeGreaterThan(active(before).route.points.length);expect(candidate.project.route.points.some((p:any)=>p.id==='ac-b')).toBe(true);
 const turns=candidate.analysis.active_path_analysis.rpl.map((p:any)=>p.turn_deg??p.turn_angle_deg).filter((v:any)=>typeof v==='number');expect(turns.length).toBeGreaterThan(0);expect(Math.max(...turns)).toBeLessThanOrEqual(45.0001);
 expect((await json(request,'/workspaces/'+before.id)).paths).toEqual(before.paths);expect(saves).toHaveLength(0);await shot(page,'split-full-candidate');const applied=await apply(page);expect(applied.workspace.ac_extension).toEqual(before.ac_extension);expect(applied.workspace.automatic_rules).toEqual(before.automatic_rules);expect(applied.workspace.layers).toEqual(before.layers);expect(applied.workspace.terrain_sources).toEqual(before.terrain_sources);const other=before.paths.find((p:any)=>p.id!==before.active_path_id);expect(applied.workspace.paths.find((p:any)=>p.id===other.id)).toEqual(other);expect(saves).toHaveLength(0);
 await page.getByRole('button',{name:'撤销 ⌘Z',exact:true}).click();await ready(page);await expect(page.getByRole('button',{name:'撤销 ⌘Z',exact:true})).toBeDisabled();await page.getByRole('button',{name:'路由位置表',exact:true}).click();expect(await page.locator('.rpl-table tbody tr').count()).toBe(active(before).route.points.length);await page.getByRole('button',{name:'重做 ⌘⇧Z',exact:true}).click();await ready(page);expect(await page.locator('.rpl-table tbody tr').count()).toBe(candidate.project.route.points.length);await save(page,2);const persisted=await json(request,'/workspaces/'+before.id);expect(active(persisted).route).toEqual(active(applied.workspace).route);expect(persisted.ac_extension).toEqual(before.ac_extension);expect(errors).toEqual([]);
});

test('Radius AC stores one true circular leg and renders analyzed curvature in geographic, projected, RPL and depth views after save and reopen',async({page,request})=>{
 const before=await fixture(request);await open(page,before);await page.getByLabel('转向操作',{exact:true}).selectOption('radius');await page.getByLabel('圆弧半径 / m',{exact:true}).fill('150');await page.getByLabel('圆弧半径 / m',{exact:true}).blur();const candidate=await preview(page,'radius'),p=candidate.project,a=candidate.analysis.active_path_analysis;
 expect(p.route.points).toHaveLength(4);const arcs=p.route.legs.map((leg:any,i:number)=>({leg,i})).filter((r:any)=>r.leg.geometry?.type==='circular_arc');expect(arcs).toHaveLength(1);const arc=arcs[0].leg.geometry;expect(arc).toMatchObject({schema_version:1,radius_m:150});expect(Math.abs(arc.sweep_deg)).toBeGreaterThan(80);expect(a.route_geometry.coordinates.length).toBeGreaterThan(p.route.points.length);
 const start=p.route.points[arcs[0].i],end=p.route.points[arcs[0].i+1],dx=end.longitude-start.longitude,dy=end.latitude-start.latitude;const cross=a.route_geometry.coordinates.filter((q:number[])=>q[0]>=Math.min(start.longitude,end.longitude)-1e-9&&q[0]<=Math.max(start.longitude,end.longitude)+1e-9&&q[1]>=Math.min(start.latitude,end.latitude)-1e-9&&q[1]<=Math.max(start.latitude,end.latitude)+1e-9).map((q:number[])=>Math.abs(dx*(q[1]-start.latitude)-dy*(q[0]-start.longitude)));expect(Math.max(...cross)).toBeGreaterThan(1e-9);
 await expect(page.locator('.ac-arcs tbody tr')).toHaveCount(1);await expect(page.locator('.ac-rpl tbody tr')).toHaveCount(4);const rendered=await page.locator('.ac-preview .active-route-geometry').evaluateAll((nodes:any[])=>nodes.reduce((n,node)=>n+Number(node.getAttribute('data-route-geometry-points')),0));expect(rendered).toBe(a.route_geometry_segments.reduce((n:number,s:any[])=>n+s.length,0));await shot(page,'radius-actual-geographic-profile','.ac-preview-map');
 await page.locator('.ac-preview').getByRole('button',{name:'投影视图',exact:true}).click();await page.locator('.ac-preview').getByLabel('地图显示投影 CRS',{exact:true}).fill(local);const projected=page.waitForResponse(r=>r.url().endsWith('/api/maps/project'));await page.locator('.ac-preview').getByRole('button',{name:'计算真实投影视图',exact:true}).click();const actual=await(await projected).json();expect(actual.can_display).toBe(true);expect(actual.routes.find((r:any)=>r.id===p.id).geometry.coordinates.flat().length).toBeGreaterThan(4);await expect(page.locator('.ac-preview .projected-map-canvas')).toBeVisible();await expect.poll(()=>page.locator('.ac-preview .projected-map-canvas>svg').evaluate((svg:any)=>{const b=svg.viewBox.baseVal;return [...svg.querySelectorAll('.projected-route-point circle')].every((c:any)=>{const x=Number(c.getAttribute('cx')),y=Number(c.getAttribute('cy')),r=Number(c.getAttribute('r'));return x-r>=b.x&&x+r<=b.x+b.width&&y-r>=b.y&&y+r<=b.y+b.height})})).toBe(true);await shot(page,'radius-actual-projected','.ac-preview-map');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载转向候选',exact:true}).click();expect(JSON.parse(await readFile((await(await download).path())!,'utf8')).project.route.legs[arcs[0].i].geometry).toEqual(arc);await apply(page);await save(page,2);const persisted=await json(request,'/workspaces/'+before.id);expect(active(persisted).route.legs.filter((l:any)=>l.geometry?.type==='circular_arc')).toHaveLength(1);await page.getByRole('button',{name:'打开',exact:true}).click();await page.locator('.project-list button').filter({has:page.getByText(before.name,{exact:true})}).click();await ready(page);await page.getByRole('button',{name:'路由位置表',exact:true}).click();await expect(page.locator('.rpl-table td[data-leg-geometry="circular_arc"]')).toHaveText('圆弧');await expect(page.locator('.rpl-table tbody tr')).toHaveCount(4);const arcRow=page.locator('.rpl-table tbody tr').filter({has:page.locator('td[data-leg-geometry="circular_arc"]')}),lon=arcRow.locator('td').nth(2).locator('input'),originalLon=await lon.inputValue();await lon.fill(String(Number(originalLon)+.0001));await lon.blur();await expect(lon).toHaveValue(originalLon);await expect(page.getByText('此点与真实圆弧相连，坐标编辑须先重构圆弧；原几何保持不变',{exact:true})).toBeVisible();expect(active(await json(request,'/workspaces/'+before.id)).route).toEqual(active(persisted).route);await shot(page,'radius-saved-rpl','.rpl-table');
});

test('actual endpoints cannot preview, impossible radii are rejected without mutation, and unknown depth remains null in an accepted arc',async({page,request})=>{
 const before=await fixture(request,{unknown:true});await open(page,before);await page.locator('.tree-points button').filter({has:page.getByText('合成起点',{exact:true})}).click();await expect(page.getByRole('button',{name:'预览转向候选',exact:true})).toBeDisabled();await expect(page.locator('.ac-form')).toContainText('路线端点不能作为转向点');await page.getByLabel('内部转向点',{exact:true}).selectOption('ac-b');await page.getByLabel('转向操作',{exact:true}).selectOption('radius');await page.getByLabel('圆弧半径 / m',{exact:true}).fill('1000000');await page.getByLabel('圆弧半径 / m',{exact:true}).blur();const seen=page.waitForResponse(r=>r.url().endsWith('/api/workspace/altercourse-preview'));await page.getByRole('button',{name:'预览转向候选',exact:true}).click();expect((await seen).status()).toBe(422);await expect(page.locator('.ac-error')).toBeVisible();await expect(page.locator('.ac-preview')).toHaveCount(0);expect((await json(request,'/workspaces/'+before.id)).paths).toEqual(before.paths);await shot(page,'real-radius-rejection','.ac-error');await page.getByLabel('圆弧半径 / m',{exact:true}).fill('150');await page.getByLabel('圆弧半径 / m',{exact:true}).blur();const candidate=await preview(page,'radius');expect(candidate.project.route.points.every((p:any)=>p.depth_m===null)).toBe(true);expect(candidate.analysis.active_path_analysis.profile.every((s:any)=>s.depth_m===null)).toBe(true);await expect(page.locator('.ac-preview .chart-empty')).toContainText('未测水深不会作为零处理');await shot(page,'unknown-depth-preserved');
});

test('held real previews reject unblurred inputs, selection away and back, and a changed save revision',async({page,request})=>{
 const before=await fixture(request,{four:true});await open(page,before);const raw=await held(page,'workspace/altercourse-preview');await page.getByRole('button',{name:'预览转向候选',exact:true}).click();expect((await raw.seen).status()).toBe(200);await page.getByLabel('最大单次转向角 / °',{exact:true}).fill('46');raw.release();await expect(page.locator('.ac-error')).toContainText('迟到预览已丢弃');await expect(page.locator('.ac-preview')).toHaveCount(0);await page.unroute('**/api/workspace/altercourse-preview');await page.getByLabel('最大单次转向角 / °',{exact:true}).fill('45');await page.getByLabel('最大单次转向角 / °',{exact:true}).blur();const selection=await held(page,'workspace/altercourse-preview');await page.getByRole('button',{name:'预览转向候选',exact:true}).click();expect((await selection.seen).status()).toBe(200);await page.locator('.tree-points button').filter({has:page.getByText('合成转向C',{exact:true})}).click();await page.locator('.tree-points button').filter({has:page.getByText('合成转向B',{exact:true})}).click();selection.release();await expect(page.locator('.ac-error')).toContainText('迟到预览已丢弃');await expect(page.locator('.ac-preview')).toHaveCount(0);await page.unroute('**/api/workspace/altercourse-preview');const saved=await held(page,'workspace/altercourse-preview');await page.getByRole('button',{name:'预览转向候选',exact:true}).click();expect((await saved.seen).status()).toBe(200);await save(page,2);saved.release();await expect(page.locator('.ac-error')).toContainText('迟到预览已丢弃');await page.unroute('**/api/workspace/altercourse-preview');expect((await json(request,'/workspaces/'+before.id)).paths).toEqual(before.paths);await shot(page,'preview-snapshot-guards','.ac-error');
});

test('held real workspace applies reject raw number changes and panel unmount, creating no saved alteration',async({page,request})=>{
 const before=await fixture(request);await open(page,before);await preview(page);const raw=await held(page,'workspace/action',d=>d?.config?.action==='update_path');await page.getByRole('button',{name:'应用转向候选',exact:true}).click();expect((await raw.seen).status()).toBe(200);await page.getByLabel('最小转向间距 / m',{exact:true}).fill('110');raw.release();await expect(page.locator('.ac-error')).toContainText('候选未通过应用校验');await page.unroute('**/api/workspace/action');await save(page,2);expect((await json(request,'/workspaces/'+before.id)).paths).toEqual(before.paths);await page.getByLabel('最小转向间距 / m',{exact:true}).fill('100');await page.getByLabel('最小转向间距 / m',{exact:true}).blur();await preview(page);const removed=await held(page,'workspace/action',d=>d?.config?.action==='update_path');await page.getByRole('button',{name:'应用转向候选',exact:true}).click();expect((await removed.seen).status()).toBe(200);await page.locator('.engineering-menu button').filter({has:page.getByText('路线加密',{exact:true})}).click();removed.release();await expect(page.getByRole('button',{name:'保存',exact:true})).toBeEnabled();await page.unroute('**/api/workspace/action');await save(page,3);const persisted=await json(request,'/workspaces/'+before.id);expect(persisted.paths).toEqual(before.paths);expect(persisted.assemblies).toEqual(before.assemblies);expect(persisted.associations).toEqual(before.associations);
});

test('candidate selection and active-path changes invalidate application without changing other paths',async({page,request})=>{
 const before=await fixture(request,{four:true,second:true});await open(page,before);await preview(page);await page.locator('.tree-points button').filter({has:page.getByText('合成转向C',{exact:true})}).click();await expect(page.locator('.ac-stale')).toBeVisible();await expect(page.getByRole('button',{name:'应用转向候选',exact:true})).toBeDisabled();await page.locator('.tree-points button').filter({has:page.getByText('合成转向B',{exact:true})}).click();await expect(page.getByRole('button',{name:'应用转向候选',exact:true})).toBeDisabled();await preview(page);await page.locator('.workspace-sidebar-paths button').filter({has:page.getByText('未修改备选',{exact:true})}).click();await ready(page);await expect(page.locator('.ac-stale')).toBeVisible();await expect(page.getByRole('button',{name:'应用转向候选',exact:true})).toBeDisabled();await shot(page,'active-path-invalidates-candidate','.ac-stale');await save(page,2);const persisted=await json(request,'/workspaces/'+before.id);expect(persisted.paths).toEqual(before.paths);expect(persisted.active_path_id).not.toBe(before.active_path_id);
});

test('a Split AC below its angle threshold reports no change and cannot manufacture an undo operation',async({page,request})=>{
 const before=await fixture(request);await open(page,before);await page.getByLabel('最大单次转向角 / °',{exact:true}).fill('120');await page.getByLabel('最大单次转向角 / °',{exact:true}).blur();const candidate=await preview(page);expect(candidate.tool_report.changed).toBe(false);await expect(page.getByRole('button',{name:'应用转向候选',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'撤销 ⌘Z',exact:true})).toBeDisabled();expect((await json(request,'/workspaces/'+before.id)).paths).toEqual(before.paths);await shot(page,'split-no-change');
});


test('fixed shared inventory survives a real radius apply and save, while flexible shared inventory changes are explicitly rejected',async({page,request})=>{
 const fixed=await fixture(request,{fixed:true,shared:true});await open(page,fixed);const candidate=await preview(page,'radius');expect(candidate.tool_report.manufacturing.mode).toBe('fixed');expect(Math.abs(candidate.tool_report.manufacturing.physical_delta_m)).toBeLessThan(1e-7);expect(candidate.workspace.assemblies).toEqual(fixed.assemblies);expect(candidate.workspace.associations).toEqual(fixed.associations);await expect(page.locator('.ac-manufacturing')).toContainText('固定');await shot(page,'fixed-shared-inventory-preserved');const result=await apply(page);expect(result.workspace.assemblies).toEqual(fixed.assemblies);expect(result.workspace.associations).toEqual(fixed.associations);await save(page,2);expect((await json(request,'/workspaces/'+fixed.id)).assemblies).toEqual(fixed.assemblies);
 const flexible=await fixture(request,{shared:true});await open(page,flexible);await page.getByLabel('转向操作',{exact:true}).selectOption('radius');const seen=page.waitForResponse(r=>r.url().endsWith('/api/workspace/altercourse-preview'));await page.getByRole('button',{name:'预览转向候选',exact:true}).click();expect((await seen).status()).toBe(422);await expect(page.locator('.ac-error')).toContainText('WORKSPACE_SHARED_ASSEMBLY_CHANGED');await expect(page.locator('.ac-preview')).toHaveCount(0);const unchanged=await json(request,'/workspaces/'+flexible.id);expect(unchanged.paths).toEqual(flexible.paths);expect(unchanged.assemblies).toEqual(flexible.assemblies);expect(unchanged.associations).toEqual(flexible.associations);await shot(page,'flexible-shared-inventory-rejected','.ac-error');
});
