import {test,expect} from '@playwright/test';
import {mkdir,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {apiURL} from './test-environment';
import {readFileSync} from 'node:fs';

const product=JSON.parse(readFileSync(new URL('../package.json',import.meta.url),'utf8')) as {version:string};

const productRelease=product.version.split('.').slice(0,2).join('.');
const exportVersion=product.version.replace(/\.0$/,'');

const local='+proj=aeqd +lat_0=0 +lon_0=0 +datum=WGS84 +units=m +type=crs';
async function json(request:any,path:string,data?:any){const r=data===undefined?await request.get(apiURL+path):await request.post(apiURL+path,{data});expect(r.ok(),await r.text()).toBe(true);return r.json()}
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:20000})}
function active(w:any){return w.paths.find((p:any)=>p.id===w.active_path_id).project}
async function fixture(request:any,{major=false,two=false,full=false,fixed=false,shared=false,second=false}={}){
 const p=await json(request,'/sample');p.id='arc-ui-'+Date.now()+'-'+Math.random().toString(16).slice(2);p.name='明确合成圆弧编辑 '+p.id;
 const xy=[{id:'a',x:-1000,y:1000},{id:'b',x:0,y:1000},{id:'c',x:full?0:1000,y:full?1000:0},...(two?[{id:'d',x:0,y:-1000}]:[]),{id:'z',x:two?1000:2000,y:two?-1000:0}];
 const result=await json(request,'/coordinates/transform',{source_crs:local,target_crs:'EPSG:4326',points:xy,error_policy:'collect'});expect(result.can_apply).toBe(true);
 const names:Record<string,string>={a:'前段起点',b:'圆弧入端',c:two?'相连圆弧点':'圆弧出端',d:'第二圆弧出端',z:'后段终点'};
 p.route={...p.route,curve:'geodesic',mode:fixed?'fixed':'flexible',slack_basis:'surface',slack_pct:0,points:result.points.map((q:any)=>({id:q.id,label:names[q.id],longitude:q.output.x,latitude:q.output.y,depth_m:1000,note:'明确合成1000m点位；移动后须重新测深',constraint:'rigid'})),legs:xy.slice(1).map((_,i)=>({cable_type_id:p.cable_types[0].id,mode:fixed?'fixed':'flexible',slack_basis:'surface',slack_pct:0,fixed_cable_length_m:fixed?i===1?7500:3500:null,allowance_m:0,burial:false}))};
 p.route.legs[1].geometry={type:'circular_arc',schema_version:1,center:[0,0],radius_m:1000,start_azimuth_deg:0,sweep_deg:full?360:major?-270:90};
 if(two)p.route.legs[2].geometry={type:'circular_arc',schema_version:1,center:[0,0],radius_m:1000,start_azimuth_deg:90,sweep_deg:90};
 p.bodies=[];p.layers=[];p.events=[];p.assembly_references=[];p.terrain_sources=[];delete p.side_slopes;p.slope_rules=[];p.profile={samples:[],source:'明确合成路线点'};
 const actual=await json(request,'/analyze',p);p.profile={samples:[{kp_m:0,depth_m:1000},{kp_m:actual.summary.surface_length_m,depth_m:1000}],source:'明确合成1000m常量剖面',route_signature:actual.route_signature};
 let w=(await json(request,'/workspace/migrate',{project:p})).workspace;w.arc_ui_extension={preserve:[0,null,'actual opaque extension']};
 if(second||shared){const original=w.active_path_id;w=(await json(request,'/workspace/action',{workspace:w,config:{action:'copy_path',path_id:original,name:'原样备选路径',assembly_policy:shared?'alternative':'unassigned'}})).workspace;w=(await json(request,'/workspace/action',{workspace:w,config:{action:'set_active',path_id:original}})).workspace}
 return (await json(request,'/workspaces',w)).workspace;
}
async function open(page:any,w:any){await page.goto('/');await ready(page);await page.getByRole('button',{name:'打开',exact:true}).click();await page.locator('.project-list button').filter({has:page.getByText(w.name,{exact:true})}).click();await ready(page)}
async function tool(page:any){await page.getByRole('button',{name:'工程工具',exact:true}).click();await page.locator('.engineering-menu button').filter({has:page.getByText('圆弧端点编辑',{exact:true})}).click();await expect(page.locator('.arc-edit-panel')).toBeVisible()}
async function select(page:any,label='圆弧入端'){await page.locator('.tree-points button').filter({has:page.getByText(label,{exact:true})}).click()}
async function preview(page:any,ok=true){const seen=page.waitForResponse((r:any)=>r.url().endsWith('/api/workspace/arc-edit-preview'));await page.getByRole('button',{name:'预览圆弧重建',exact:true}).click();const r=await seen;expect(r.status(),await r.text()).toBe(ok?200:422);if(ok)await expect(page.locator('.arc-preview')).toBeVisible();else await expect(page.locator('.arc-error')).toBeVisible();return r.json()}
async function apply(page:any){const seen=page.waitForResponse((r:any)=>r.url().endsWith('/api/workspace/action')&&r.request().postDataJSON()?.config?.action==='update_path');await page.getByRole('button',{name:'应用圆弧候选',exact:true}).click();const r=await seen;expect(r.ok(),await r.text()).toBe(true);expect(r.request().postDataJSON().config.update_shared).toBeUndefined();await expect(page.locator('.arc-preview')).toHaveCount(0);await ready(page);return r.json()}
async function save(page:any){const seen=page.waitForResponse((r:any)=>r.url().endsWith('/api/workspaces')&&r.request().method()==='POST');await page.getByRole('button',{name:'保存',exact:true}).click();const result=await(await seen).json();await expect(page.getByText('工程已保存 · 修订 '+result.revision,{exact:true})).toBeVisible();await ready(page);return result.workspace}
async function shot(page:any,name:string,selector='.arc-preview'){await page.setViewportSize({width:1800,height:1250});const toast=page.getByRole('button',{name:'关闭提示',exact:true});if(await toast.isVisible())await toast.click();if(selector)await page.locator(selector).first().scrollIntoViewIfNeeded();await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));const dir=process.env.OCEANROUTE_ARTIFACTS_DIR||'artifacts/development-0.12/arc-edit';await mkdir(dir,{recursive:true});await page.screenshot({path:join(dir,'arc-edit-0.12-'+name+'.png'),fullPage:true,animations:'disabled'})}
async function held(page:any,url:string,predicate:(data:any)=>boolean=()=>true){let release!:()=>void,arrived!:(r:any)=>void;const gate=new Promise<void>(r=>release=r),seen=new Promise<any>(r=>arrived=r);await page.route('**/api/'+url,async(route:any)=>{if(!predicate(route.request().postDataJSON())){await route.continue();return}const actual=await route.fetch();arrived(actual);await gate;await route.fulfill({response:actual})});return {release,seen}}
function moved(w:any,pid='b'){return active(w).route.points.find((p:any)=>p.id===pid)}

test('RPL arc endpoint edit previews true geometry, applies one workspace undo and saves only explicitly before reopening',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const before=await fixture(request,{second:true});await open(page,before);await page.getByRole('button',{name:'路由位置表',exact:true}).click();const row=page.locator('.rpl-table tbody tr').nth(1),lon=row.locator('td').nth(2).locator('input'),old=moved(before).longitude,target=old+.0003;const saves:any[]=[];page.on('request',r=>{if(r.url().endsWith('/api/workspaces')&&r.method()==='POST')saves.push(r.postDataJSON())});await lon.fill(String(target));await lon.blur();await expect(page.getByRole('dialog',{name:'圆弧端点编辑',exact:true})).toBeVisible();await expect(lon).toHaveValue(String(old));await expect(page.getByLabel('圆弧入端 圆弧目标经度',{exact:true})).toHaveValue(String(target));
 const c=await preview(page);expect(c.operation).toMatchObject({kind:'arc_edit',path_id:before.active_path_id,config:{moves:[{point_id:'b',longitude:target,latitude:moved(before).latitude}]}});expect(c.tool_report.arc_changes).toHaveLength(1);const change=c.tool_report.arc_changes[0];expect(change.new_geometry.radius_m).toBe(1000);expect(change.new_geometry.center).not.toEqual(change.old_geometry.center);expect(Math.sign(change.new_geometry.sweep_deg)).toBe(Math.sign(change.old_geometry.sweep_deg));expect(change.evidence.length_m).toBeGreaterThan(0);expect(c.tool_report.profile_invalidation.invalidated).toBe(true);expect(c.project.route.points.find((p:any)=>p.id==='b').depth_m).toBeNull();expect(c.analysis.active_path_analysis.profile.some((r:any)=>r.depth_m===null)).toBe(true);expect(c.analysis.active_path_analysis.route_geometry.coordinates.length).toBeGreaterThan(c.project.route.points.length);expect((await json(request,'/workspaces/'+before.id)).paths).toEqual(before.paths);expect(saves).toHaveLength(0);await expect(page.locator('.arc-changes')).toContainText('真实入端切向');await shot(page,'rpl-complete-candidate');const applied=await apply(page);expect(applied.workspace.arc_ui_extension).toEqual(before.arc_ui_extension);expect(applied.workspace.paths.find((p:any)=>p.id!==before.active_path_id)).toEqual(before.paths.find((p:any)=>p.id!==before.active_path_id));expect(saves).toHaveLength(0);await page.getByRole('button',{name:'撤销 ⌘Z',exact:true}).click();await ready(page);await expect(page.getByRole('button',{name:'撤销 ⌘Z',exact:true})).toBeDisabled();await expect(lon).toHaveValue(String(old));await page.getByRole('button',{name:'重做 ⌘⇧Z',exact:true}).click();await ready(page);await expect(lon).toHaveValue(String(target));const persisted=await save(page);expect(moved(persisted).longitude).toBe(target);await open(page,persisted);await page.getByRole('button',{name:'路由位置表',exact:true}).click();await expect(page.locator('.rpl-table tbody tr').nth(1).locator('td').nth(2).locator('input')).toHaveValue(String(target));expect(active(await json(request,'/workspaces/'+before.id)).route).toEqual(active(persisted).route);await shot(page,'saved-reopened-rpl','.rpl-table');expect(errors).toEqual([]);
});

test('geographic marker dragging enters a real arc candidate and restores the stored point until explicit apply',async({page,request})=>{
 const before=await fixture(request);await open(page,before);await select(page);const marker=page.locator('.leaflet-marker-icon').nth(1),box=(await marker.boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+14,box.y+box.height/2+8,{steps:8});await page.mouse.up();await expect(page.getByRole('dialog',{name:'圆弧端点编辑',exact:true})).toBeVisible();await expect(page.locator('.arc-source')).toContainText('地图拖动');const c=await preview(page);expect(c.operation.config.moves[0].point_id).toBe('b');expect(c.project.route.legs.some((l:any)=>l.geometry?.type==='circular_arc')).toBe(true);expect((await json(request,'/workspaces/'+before.id)).paths).toEqual(before.paths);await shot(page,'geographic-drag-candidate','.arc-preview-map');await page.getByRole('button',{name:'关闭对话框',exact:true}).click();await ready(page);expect((await json(request,'/workspaces/'+before.id)).paths).toEqual(before.paths);await expect(page.getByRole('button',{name:'撤销 ⌘Z',exact:true})).toBeDisabled();
});

test('projected XY performs a real horizontal transform then enters full arc reconstruction without submitting invalid endpoint geometry',async({page,request})=>{
 const before=await fixture(request);await open(page,before);await select(page);await page.getByRole('button',{name:'投影 X/Y 编辑',exact:true}).click();await page.getByLabel('投影编辑源 CRS',{exact:true}).fill(local);await page.getByRole('button',{name:'读取当前点的真实投影值',exact:true}).click();await expect(page.getByLabel('圆弧入端 投影 X',{exact:true})).not.toBeEmpty();await page.getByLabel('圆弧入端 投影 X',{exact:true}).fill('40');await page.getByLabel('圆弧入端 投影 Y',{exact:true}).fill('1000');const transform=page.waitForResponse(r=>r.url().endsWith('/api/coordinates/transform')&&r.request().postDataJSON()?.target_crs==='EPSG:4326');await page.getByRole('button',{name:'真实转换并预览',exact:true}).click();const actual=await(await transform).json();expect(actual.can_apply).toBe(true);await page.getByRole('button',{name:'进入圆弧重建候选',exact:true}).click();await expect(page.locator('.arc-source')).toContainText('真实投影 X/Y 转换');const c=await preview(page);expect(c.operation.config.moves[0]).toEqual({point_id:'b',longitude:actual.points[0].output.x,latitude:actual.points[0].output.y});expect((await json(request,'/workspaces/'+before.id)).paths).toEqual(before.paths);await shot(page,'projected-xy-candidate');await apply(page);const persisted=await save(page);expect(moved(persisted).longitude).toBe(actual.points[0].output.x);
});

test('projected map dragging submits true inverse XY coordinates to the same arc candidate',async({page,request})=>{
 const before=await fixture(request);await open(page,before);await select(page);await page.getByRole('button',{name:'投影视图',exact:true}).click();await page.getByLabel('地图显示投影 CRS',{exact:true}).fill(local);await page.getByRole('button',{name:'计算真实投影视图',exact:true}).click();const point=page.locator('.projected-route-point[data-point-id="b"] circle');await expect(point).toBeVisible();const box=(await point.boundingBox())!,inverse=page.waitForResponse(r=>r.url().endsWith('/api/coordinates/transform')&&r.request().postDataJSON()?.target_crs==='EPSG:4326');await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+10,box.y+box.height/2+8,{steps:6});await page.mouse.up();const actual=await(await inverse).json();expect(actual.can_apply).toBe(true);await expect(page.getByRole('dialog',{name:'圆弧端点编辑',exact:true})).toBeVisible();const c=await preview(page);expect(c.operation.config.moves[0]).toEqual({point_id:'b',longitude:actual.points[0].output.x,latitude:actual.points[0].output.y});await shot(page,'projected-map-candidate');expect((await json(request,'/workspaces/'+before.id)).paths).toEqual(before.paths);
});

test('moving a shared Rigid endpoint reconstructs both incident arcs including an original directed major arc',async({page,request})=>{
 const before=await fixture(request,{major:true,two:true});await open(page,before);await select(page,'相连圆弧点');await tool(page);await page.getByLabel('相连圆弧点 圆弧目标纬度',{exact:true}).fill(String(moved(before,'c').latitude+.0002));const c=await preview(page);expect(c.tool_report.arc_changes).toHaveLength(2);const first=c.tool_report.arc_changes.find((r:any)=>r.start_point_id==='b');expect(first.old_geometry.sweep_deg).toBe(-270);expect(first.new_geometry.sweep_deg).toBeLessThan(-180);expect(first.new_geometry.radius_m).toBe(1000);expect(c.tool_report.arc_changes.every((r:any)=>r.evidence.end_binding_errors_m.every((x:number)=>Math.abs(x)<.001))).toBe(true);await expect(page.locator('.arc-changes tbody tr')).toHaveCount(2);await shot(page,'connected-major-arcs');await apply(page);const persisted=await save(page);expect(active(persisted).route.legs.filter((l:any)=>l.geometry?.type==='circular_arc')).toHaveLength(2);expect(moved(persisted,'c').depth_m).toBeNull();
});

test('full-circle single endpoint and unreachable radius failures retain the complete original workspace',async({page,request})=>{
 const before=await fixture(request,{full:true});await open(page,before);await select(page);await tool(page);await page.getByLabel('圆弧入端 圆弧目标经度',{exact:true}).fill(String(moved(before).longitude+.0001));await preview(page,false);await expect(page.locator('.arc-error')).toContainText('ARC_EDIT_');await expect(page.locator('.arc-preview')).toHaveCount(0);expect((await json(request,'/workspaces/'+before.id)).paths).toEqual(before.paths);await shot(page,'full-circle-typed-rejection','.arc-error');await page.getByLabel('添加圆弧移动点',{exact:true}).selectOption('c');await page.getByRole('button',{name:'添加移动目标',exact:true}).click();await page.getByLabel('圆弧出端 圆弧目标经度',{exact:true}).fill(String(moved(before).longitude+.0001));await page.locator('.arc-options summary').click();await page.getByLabel('整圈移动策略 1',{exact:true}).selectOption('preserve_endpoint_center_bearing');const closed=await preview(page);expect(closed.tool_report.arc_changes[0].new_geometry.sweep_deg).toBe(360);expect(closed.project.route.points.find((p:any)=>p.id==='b').longitude).toBe(closed.project.route.points.find((p:any)=>p.id==='c').longitude);await shot(page,'full-circle-explicit-closed-candidate');const normal=await fixture(request);await open(page,normal);await select(page);await tool(page);await page.locator('.arc-options summary').click();await page.getByLabel('修改圆弧半径 1',{exact:true}).check();await page.getByLabel('重建圆弧半径 1',{exact:true}).fill('0.001');await preview(page,false);await expect(page.locator('.arc-error')).toContainText('ARC_EDIT_');expect((await json(request,'/workspaces/'+normal.id)).paths).toEqual(normal.paths);
});

test('held actual arc previews and applies discard unblurred inputs, selection changes, save revisions and unmounted panels',async({page,request})=>{
 const before=await fixture(request);await open(page,before);await select(page);await tool(page);const input=page.getByLabel('圆弧入端 圆弧目标经度',{exact:true});await input.fill(String(moved(before).longitude+.0002));const p=await held(page,'workspace/arc-edit-preview');await page.getByRole('button',{name:'预览圆弧重建',exact:true}).click();expect((await p.seen).status()).toBe(200);await input.fill(String(moved(before).longitude+.0003));p.release();await expect(page.locator('.arc-error')).toContainText('迟到圆弧预览已丢弃');await page.unroute('**/api/workspace/arc-edit-preview');await preview(page);await select(page,'圆弧出端');await select(page);await expect(page.getByRole('button',{name:'应用圆弧候选',exact:true})).toBeDisabled();await preview(page);await save(page);await expect(page.getByRole('button',{name:'应用圆弧候选',exact:true})).toBeDisabled();await preview(page);const a=await held(page,'workspace/action',d=>d?.config?.action==='update_path');await page.getByRole('button',{name:'应用圆弧候选',exact:true}).click();expect((await a.seen).status()).toBe(200);await input.fill(String(moved(before).longitude+.0004));a.release();await expect(page.locator('.arc-error')).toContainText('候选未通过应用校验');await page.unroute('**/api/workspace/action');await preview(page);const close=await held(page,'workspace/action',d=>d?.config?.action==='update_path');await page.getByRole('button',{name:'应用圆弧候选',exact:true}).click();expect((await close.seen).status()).toBe(200);await page.locator('.engineering-menu button').filter({has:page.getByText('路线加密',{exact:true})}).click();close.release();await expect(page.getByRole('button',{name:'保存',exact:true})).toBeEnabled();await page.unroute('**/api/workspace/action');await save(page);expect((await json(request,'/workspaces/'+before.id)).paths).toEqual(before.paths);await shot(page,'discarded-late-candidates','.engineering-main');
});

test('fixed shared stock remains exact while flexible shared changes reject an arc edit as a complete transaction',async({page,request})=>{
 const before=await fixture(request,{fixed:true,shared:true});await open(page,before);await select(page);await tool(page);await page.getByLabel('圆弧入端 圆弧目标经度',{exact:true}).fill(String(moved(before).longitude+.0002));const c=await preview(page);expect(c.workspace.assemblies).toEqual(before.assemblies);expect(c.tool_report.manufacturing.physical_delta_m).toBeCloseTo(0,7);await shot(page,'fixed-shared-stock');await apply(page);expect((await save(page)).assemblies).toEqual(before.assemblies);const flex=await fixture(request,{shared:true});await open(page,flex);await select(page);await tool(page);await page.getByLabel('圆弧入端 圆弧目标经度',{exact:true}).fill(String(moved(flex).longitude+.0002));await preview(page,false);await expect(page.locator('.arc-error')).toContainText('WORKSPACE_SHARED_ASSEMBLY_CHANGED');expect((await json(request,'/workspaces/'+flex.id)).paths).toEqual(flex.paths);await shot(page,'flexible-shared-rejection','.arc-error');
});

test('current product version is shared by empty UI and scoped Unicode exports with server filename precedence',async({page,request})=>{
 const before=await fixture(request);before.name='同名 / 海缆 α '+before.id;const stored=(await json(request,'/workspaces',before)).workspace;await open(page,stored);await expect(page.locator('.project-title .version')).toHaveText(`v${productRelease}`);await page.getByRole('button',{name:'导出成果',exact:true}).click();const response=page.waitForResponse(r=>r.url().endsWith('/api/workspace/export')),download=page.waitForEvent('download');await page.locator('.export-options button').filter({has:page.getByText('完整工程 · JSON',{exact:true})}).click();const r=await response,d=await download;expect(r.headers()['content-disposition']).toContain('filename*=UTF-8');expect(d.suggestedFilename()).toContain(exportVersion);expect(d.suggestedFilename()).toContain('workspace');expect(d.suggestedFilename()).toContain('海缆');expect(d.suggestedFilename()).not.toContain('/');expect(JSON.parse(await readFile((await d.path())!,'utf8')).name).toBe(stored.name);await page.getByRole('button',{name:'关闭对话框',exact:true}).click();const empty=structuredClone(stored);empty.id+='-empty';empty.name+=' 空工作区';empty.paths=[];empty.active_path_id=null;empty.associations=[];delete empty.saved_revision;const saved=(await json(request,'/workspaces',empty)).workspace;await open(page,saved);await expect(page.locator('.project-title .version')).toHaveText(`v${productRelease}`);await expect(page.locator('.statusbar')).toContainText(`OceanRoute ${productRelease}`);await shot(page,'empty-current-product-version','.empty-workspace');
});
