import {artifactPath} from './artifact-path';
import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:20000})}
async function constraints(page:any){await page.getByRole('button',{name:'工程工具',exact:true}).click();await page.locator('.engineering-menu button').filter({has:page.getByText('约束点与制造域',{exact:true})}).click()}
test('constraint configuration preserves manufacture, real anchor edits move clamped and sliding points, clear is explicit',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await ready(page);await page.getByRole('button',{name:'导入数据',exact:true}).click();await page.locator('.import-text').fill('label,longitude,latitude,depth_m\nStart,118,22,100\nMid,118.05,22,100\nEnd,118.1,22,100');await page.getByRole('button',{name:'解析预览',exact:true}).click();await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeEnabled();await page.getByRole('button',{name:'应用 RPL 导入',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await ready(page);const length=await page.locator('.metric').nth(2).locator('strong').innerText();await constraints(page);await page.getByRole('combobox',{name:'域模式',exact:true}).selectOption('fixed');await page.getByRole('combobox',{name:'Mid 约束类型',exact:true}).selectOption('clamped');const configuredResponse=page.waitForResponse(r=>r.url().endsWith('/api/constraints/configure'));await page.getByRole('button',{name:'配置并预览',exact:true}).click();await expect(page.getByRole('button',{name:'应用约束结果',exact:true})).toBeVisible();const configured=await(await configuredResponse).json();expect(configured.report.mode_switch_length_delta_m).toBe(0);await page.getByRole('button',{name:'应用约束结果',exact:true}).click();await ready(page);await expect(page.locator('.metric').nth(2).locator('strong')).toHaveText(length);
  await page.getByRole('button',{name:'路由工作空间',exact:true}).click();await page.locator('.tree-points button').filter({has:page.getByText('End',{exact:true})}).click();const movedResponse=page.waitForResponse(r=>r.url().endsWith('/api/constraints/edit'));await page.getByLabel('经度 / °E',{exact:true}).fill('118.14');await page.getByLabel('经度 / °E',{exact:true}).blur();const moved=await(await movedResponse).json();await ready(page);expect(moved.project.route.points.find((p:any)=>p.label==='Mid').longitude).toBeCloseTo(118.07,7);expect(moved.report.after_summary.cable_length_m).toBeCloseTo(configured.report.after_summary.cable_length_m,7);await page.locator('.tree-points button').filter({has:page.getByText('Mid',{exact:true})}).click();expect(Number(await page.getByLabel('锚线距离比例',{exact:true}).inputValue())).toBeCloseTo(.5,7);
  await constraints(page);await page.getByRole('combobox',{name:'Mid 约束类型',exact:true}).selectOption('sliding');await page.getByRole('button',{name:'配置并预览',exact:true}).click();await expect(page.getByRole('button',{name:'应用约束结果',exact:true})).toBeVisible();await page.getByRole('button',{name:'应用约束结果',exact:true}).click();await ready(page);await page.getByRole('button',{name:'路由工作空间',exact:true}).click();await page.locator('.tree-points button').filter({has:page.getByText('Mid',{exact:true})}).click();await expect(page.getByLabel('经度 / °E',{exact:true})).toBeDisabled();const slidingResponse=page.waitForResponse(r=>r.url().endsWith('/api/constraints/edit'));await page.getByLabel('实物 KP / m',{exact:true}).fill(String(configured.report.after_summary.cable_length_m*.3));await page.getByLabel('实物 KP / m',{exact:true}).blur();const sliding=await(await slidingResponse).json();await ready(page);expect(sliding.project.route.points.find((p:any)=>p.label==='Mid').longitude).toBeCloseTo(118.042,6);await page.screenshot({path:artifactPath('constraint-points.png'),fullPage:true});
  await constraints(page);await page.getByRole('button',{name:'解除旧域并预览',exact:true}).click();await expect(page.getByRole('button',{name:'应用约束结果',exact:true})).toBeVisible();await page.getByRole('button',{name:'应用约束结果',exact:true}).click();await ready(page);await expect(page.getByText('尚未配置约束域',{exact:true})).toBeVisible();await expect(page.locator('.metric').nth(2).locator('strong')).toHaveText(length);expect(errors).toEqual([]);
});
test('manufacturing CSV previews real bodies and references, applies, exports and round trips absolute stations',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await ready(page);await page.getByRole('button',{name:'电缆与装配',exact:true}).click();await page.getByRole('button',{name:'制造装配与实制回写',exact:true}).click();await page.getByRole('button',{name:'加载装配示例',exact:true}).click();const firstResponse=page.waitForResponse(r=>r.url().endsWith('/api/assembly/import'));await page.getByRole('button',{name:'解析并预览装配',exact:true}).click();await expect(page.locator('.assembly-preview')).toBeVisible({timeout:20000});const first=await(await firstResponse).json();expect(first.report.body_count).toBe(2);expect(first.report.reference_count).toBe(1);expect(first.report.material_conservation_checked).toBe(true);await page.getByRole('button',{name:'应用制造装配',exact:true}).click();await ready(page);
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出制造清单',exact:true}).click();const file=await download;const text=await readFile((await file.path())!,'utf8');expect(text).toContain('reference');expect(text).toContain('body');await page.getByRole('combobox',{name:'实物定位',exact:true}).selectOption('absolute');await page.getByRole('textbox',{name:'装配 CSV',exact:true}).fill(text);const roundResponse=page.waitForResponse(r=>r.url().endsWith('/api/assembly/import'));await page.getByRole('button',{name:'解析并预览装配',exact:true}).click();await expect(page.locator('.assembly-preview')).toBeVisible();const round=await(await roundResponse).json();expect(round.report.manufactured_total_m).toBeCloseTo(first.report.manufactured_total_m,5);expect(round.report.after_summary.body_cost).toBe(6000);await page.locator('.page-content').evaluate((e:HTMLElement)=>e.scrollTop=e.scrollHeight);await page.screenshot({path:artifactPath('manufacturing-assembly.png'),fullPage:true});expect(errors).toEqual([]);
});
test('sea spectra, user RAO dynamics and Monte Carlo display actual samples and trials',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await ready(page);await page.getByRole('button',{name:'敷设仿真',exact:true}).click();await page.getByRole('button',{name:'海况 / Monte Carlo',exact:true}).click();const spectrumResponse=page.waitForResponse(r=>r.url().endsWith('/api/sea/generate'));await page.getByRole('button',{name:'生成波谱与序列',exact:true}).click();const spectrum=await(await spectrumResponse).json();expect(spectrum.samples.length).toBeGreaterThan(10);await expect(page.locator('.sea-plot svg')).toHaveCount(3);
  await page.locator('.sea-layout .solver-tabs button').filter({has:page.getByText('海况动态',{exact:true})}).click();const simResponse=page.waitForResponse(r=>r.url().endsWith('/api/sea/simulate'));await page.getByRole('button',{name:'运行海况动态',exact:true}).click();const sim=await(await simResponse).json();expect(sim.simulation.frames.length).toBeGreaterThan(2);expect(sim.simulation.solver.converged).toBe(true);await expect(page.locator('.scene-host canvas')).toBeVisible();await expect(page.locator('.sea-layout .playback')).toContainText('帧');await page.locator('.sea-layout .sim-main').evaluate((e:HTMLElement)=>e.scrollTop=e.scrollHeight);await page.screenshot({path:artifactPath('sea-dynamics.png'),fullPage:true});
  await page.locator('.sea-layout .solver-tabs button').filter({has:page.getByText('Monte Carlo',{exact:true})}).click();await page.getByLabel('返回各次真实三维帧（最多 8 次）').check();const mcResponse=page.waitForResponse(r=>r.url().endsWith('/api/sea/montecarlo'));await page.getByRole('button',{name:'运行实际 Monte Carlo',exact:true}).click();const mc=await(await mcResponse).json();expect(mc.trials.length).toBe(3);expect(mc.summary.complete).toBe(true);expect(Object.keys(mc.distributions).length).toBeGreaterThan(3);await expect(page.getByRole('button',{name:'试验 2',exact:true})).toBeVisible();await page.getByRole('button',{name:'试验 2',exact:true}).click();await expect(page.locator('.scene-host canvas')).toBeVisible();const d=page.waitForEvent('download');await page.getByRole('button',{name:'下载完整结果',exact:true}).click();expect((await d).suggestedFilename()).toContain('montecarlo');await page.locator('.sea-layout .sim-main').evaluate((e:HTMLElement)=>e.scrollTop=0);await page.screenshot({path:artifactPath('sea-montecarlo.png'),fullPage:true});expect(errors).toEqual([]);
});
