import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {apiURL} from './test-environment';
import {artifactPath} from './artifact-path';

async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:25000})}
async function load(page:any){await page.goto('/');await ready(page);await page.getByRole('button',{name:'敷设仿真',exact:true}).click();await page.locator('.solver-tabs button').filter({has:page.getByText('动态敷设',{exact:true})}).click();await page.locator('.equilibrium-initial-settings>summary').click();await page.getByRole('button',{name:'加载明确合成分层流与异质初态',exact:true}).click()}
async function actual(page:any,path:string,button:string){const response=page.waitForResponse((r:any)=>r.url().endsWith('/api/'+path)&&r.request().method()==='POST');await page.getByRole('button',{name:button,exact:true}).click();return await response}
async function num(page:any,label:string,value:number,exact=true){const input=page.getByLabel(label,{exact});await input.fill(String(value));await input.blur()}
async function dismiss(page:any){const close=page.getByRole('button',{name:'关闭提示',exact:true});if(await close.isVisible())await close.click()}
async function open(page:any,selector:string){const details=page.locator(selector);if(!await details.evaluate((e:HTMLDetailsElement)=>e.open))await details.locator(':scope>summary').click()}
const json=(value:any)=>JSON.parse(JSON.stringify(value));
const proofSchema='oceanroute.dynamic.initial-equilibrium.provenance.v3';
const model='material-lumped-mass-xpbd-cable-lay-v5';

test('actual raw2 shear-flow proof exposes nodal drag and schema4 JSON continuation retains historical flow after a future profile override',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await load(page);await expect(page.locator('.equilibrium-diagnostics')).toHaveCount(0);await expect(page.locator('.scene-host canvas')).toHaveCount(0);
  const prepared=await actual(page,'simulation/prepare-equilibrium-initial','预备并独立验证动态初态');expect(prepared.status()).toBe(200);const preview=await prepared.json(),proof=preview.provenance,fluid=proof.fluid_loading;
  expect(proof.schema).toBe(proofSchema);expect(proof.verification.accepted).toBe(true);expect(proof.initial_material_length_m).toBe(27);expect(proof.initial_suspended_material_m).toBe(37);expect(proof.initial_paid_out_m).toBe(0);
  expect(fluid.initial_fluid.current_m_s).toEqual([1.7,-1.3,0]);expect(fluid.initial_fluid.current_profile).toHaveLength(2);expect(fluid.initial_fluid.water_density_kg_m3).toBe(1025);
  expect(fluid.node_fluid_velocity_m_s).toHaveLength(8);expect(Math.max(...fluid.node_cable_drag_n.map((r:number[])=>Math.abs(r[2])))).toBeGreaterThan(.01);
  fluid.node_external_force_n.forEach((r:number[],i:number)=>r.forEach((v:number,j:number)=>expect(v).toBeCloseTo(fluid.node_cable_drag_n[i][j]+fluid.node_body_drag_n[i][j]-(j===2?proof.initial_snapshot.node_wet_weight_n[i]:0),9)));
  expect(proof.material_loading.point_bodies.find((b:any)=>b.id==='buoyant-off-node').wet_weight_n).toBe(-25);
  await expect(page.locator('.equilibrium-initial-settings .equilibrium-diagnostics')).toContainText('稳恒流 / 材料证据 v3');await expect(page.locator('.equilibrium-fluid-history')).toContainText('分层流，覆盖恒定流');
  const run=await actual(page,'simulation/dynamic','运行计算');expect(run.status()).toBe(200);const result=await run.json();expect(result.initialization.fluid_loading).toEqual(fluid);expect(result.checkpoint.schema_version).toBe(4);expect(result.checkpoint.model).toBe(model);expect(result.checkpoint.numerical.scheme).toContain('current-equilibrium-prestress-v5');expect(result.frames[0].touchdown).toBeNull();expect(result.frames[0].bottom_tension_n).toBeNull();expect(result.summary.paid_out_m).toBe(0);
  const main=page.locator('.sim-main .equilibrium-diagnostics');await main.locator('.equilibrium-fluid-nodes>summary').click();await expect(main.locator('.equilibrium-fluid-nodes tbody tr')).toHaveCount(8);await expect(page.locator('.scene-legend')).toContainText('无实际触地点');
  await page.setViewportSize({width:1800,height:1600});await dismiss(page);await page.locator('.sim-main').evaluate((e:HTMLElement)=>e.scrollTop=0);await page.screenshot({path:artifactPath('current-initial-shear-nodal-drag-proof.png'),fullPage:true});
  const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'保存末状态',exact:true}).click();const path=(await(await downloaded).path())!;const saved=JSON.parse(await readFile(path,'utf8'));expect(saved.schema_version).toBe(4);expect(saved.state.initialization_provenance.fluid_loading).toEqual(json(fluid));
  await page.locator('.checkpoint-settings input[type=file]').setInputFiles(path);await expect(page.locator('.checkpoint-settings textarea')).not.toHaveValue('');await expect(page.getByLabel('模拟时长 / s',{exact:true})).toHaveValue('10');await num(page,'模拟时长 / s',.04);
  await page.getByLabel('用当前船速、放缆和环境参数覆盖后续作业',{exact:true}).check();await open(page,'.advanced-environment:has(>summary:text-is("分层海流与变化海床"))');const future=[{depth_m:0,x_m_s:-.2,y_m_s:.05},{depth_m:40,x_m_s:-.1,y_m_s:-.15}];await page.getByLabel('分层海流 JSON',{exact:true}).fill(JSON.stringify(future));await num(page,'X 向海流 / m·s⁻¹',-.15);
  const resumed=await actual(page,'simulation/dynamic','运行计算');expect(resumed.status()).toBe(200);const continued=await resumed.json();expect(continued.frames[0].nodes).toEqual(result.frames.at(-1).nodes);expect(continued.frames[0].time_s).toBeCloseTo(.08,10);expect(continued.frames.at(-1).time_s).toBeCloseTo(.12,10);expect(continued.checkpoint.config.current_profile).toEqual(future);expect(continued.checkpoint.config.current_x_m_s).toBe(-.15);expect(json(continued.initialization)).toEqual(saved.state.initialization_provenance);expect(continued.initialization.fluid_loading.initial_fluid).toEqual(fluid.initial_fluid);expect(continued.summary.paid_out_m).toBe(0);expect(continued.frames.at(-1).touchdown).toBeNull();
  const moved=Math.max(...continued.frames.at(-1).nodes.slice(1,-1).flatMap((p:number[],i:number)=>p.map((v:number,j:number)=>Math.abs(v-continued.frames[0].nodes[i+1][j]))));expect(moved).toBeGreaterThan(1e-9);await expect(page.locator('.sim-main .equilibrium-fluid-profile tbody tr').first().locator('td').nth(1)).toHaveText('0.2');expect(errors).toEqual([]);
});

test('late actual raw2 preview is discarded, fresh current and density mismatches reject, explicit redeclaration and constant-flow solving succeed without weakening raw1',async({page})=>{
  await load(page);let enter!:()=>void,release!:()=>void;const entered=new Promise<void>(resolve=>enter=resolve),gate=new Promise<void>(resolve=>release=resolve);await page.route('**/api/simulation/prepare-equilibrium-initial',async route=>{const response=await route.fetch();enter();await gate;await route.fulfill({response})});
  await page.getByRole('button',{name:'预备并独立验证动态初态',exact:true}).click();await entered;await num(page,'水密度 / kg·m⁻³',1026);release();await expect(page.getByRole('button',{name:'预备并独立验证动态初态',exact:true})).toBeEnabled();await expect(page.locator('.equilibrium-diagnostics')).toHaveCount(0);await page.unroute('**/api/simulation/prepare-equilibrium-initial');
  const mismatch=await actual(page,'simulation/prepare-equilibrium-initial','预备并独立验证动态初态');expect(mismatch.status()).toBe(422);await expect(page.locator('.equilibrium-initial-error')).toContainText('must match');await num(page,'水密度 / kg·m⁻³',1025);await num(page,'X 向海流 / m·s⁻¹',.1);expect((await actual(page,'simulation/prepare-equilibrium-initial','预备并独立验证动态初态')).status()).toBe(422);
  await open(page,'.advanced-environment:has(>summary:text-is("分层海流与变化海床"))');await page.getByLabel('分层海流 JSON',{exact:true}).fill('');await num(page,'Y 向海流 / m·s⁻¹',.12);await page.getByRole('button',{name:'重新声明当前初始流场',exact:true}).click();const raw=JSON.parse(await page.getByLabel('明确动态定端初态 JSON',{exact:true}).inputValue());expect(raw.schema).toBe('oceanroute.dynamic.initial-equilibrium.v2');expect(raw.initial_fluid.current_m_s).toEqual([.1,.12,0]);expect(raw.initial_fluid.current_profile).toBeNull();
  const constant=await actual(page,'simulation/prepare-equilibrium-initial','预备并独立验证动态初态');expect(constant.status()).toBe(200);expect((await constant.json()).provenance.fluid_loading.initial_fluid.current_profile).toBeNull();await expect(page.locator('.equilibrium-fluid-history')).toContainText('声明水平恒定流');
  raw.solver={max_work_units:1};await page.getByLabel('明确动态定端初态 JSON',{exact:true}).fill(JSON.stringify(raw));expect((await actual(page,'simulation/prepare-equilibrium-initial','预备并独立验证动态初态')).status()).toBe(422);await expect(page.locator('.equilibrium-diagnostics')).toHaveCount(0);await expect(page.locator('.scene-host canvas')).toHaveCount(0);await expect(page.getByRole('button',{name:'下载结果',exact:true})).toBeDisabled();
  delete raw.solver;delete raw.initial_fluid;raw.schema='oceanroute.dynamic.initial-equilibrium.v1';await page.getByLabel('明确动态定端初态 JSON',{exact:true}).fill(JSON.stringify(raw));expect((await actual(page,'simulation/prepare-equilibrium-initial','预备并独立验证动态初态')).status()).toBe(422);await expect(page.locator('.equilibrium-initial-error')).toContainText('zero initial current');await dismiss(page);await page.screenshot({path:artifactPath('current-initial-failure-no-stale-proof.png'),fullPage:true});
});

test('actual raw2 geographic preparation and durable job retain fluid, signed point and stock across a child continuation',async({page,request})=>{
  const example=JSON.parse(await readFile(new URL('../../examples/current-initial-plan-voyage.json',import.meta.url),'utf8'));const project={...example.project,id:'current-initial-ui-'+Date.now(),name:'稳恒流地理制造窗口 '+Date.now(),schema_version:1};const migrated=await request.post(apiURL+'/workspace/migrate',{data:{project}});expect(migrated.status()).toBe(200);const envelope=await migrated.json();envelope.workspace.name=project.name;expect((await request.post(apiURL+'/workspaces',{data:envelope.workspace})).status()).toBe(200);
  await page.goto('/');await ready(page);await page.getByRole('button',{name:'打开',exact:true}).click();await page.getByRole('button').filter({has:page.getByText(project.name,{exact:true})}).click();await ready(page);await page.getByRole('button',{name:'敷设仿真',exact:true}).click();await page.getByRole('button',{name:'持续计算 / 网格审查',exact:true}).click();await page.locator('.plan-voyage-preparation>summary').click();
  await page.getByLabel('预备窗口初态方法',{exact:true}).selectOption('equilibrium');await page.getByLabel('预备地理二维床格 JSON',{exact:true}).fill(JSON.stringify(example.config.seabed_grid));await page.getByLabel('预备地理定端初态 JSON',{exact:true}).fill(JSON.stringify(example.config.equilibrium_start));await num(page,'预备窗口时长 / s',.08);await num(page,'原计划开始时刻 / s',example.config.start_time_s,false);await num(page,'预备海床张力 / N',10);await num(page,'原计划采样站距 / m',30);await page.getByLabel('预备动力求解与环境参数 JSON',{exact:true}).fill(JSON.stringify(example.config.simulation));await page.getByLabel('预备任务预算与网格策略 JSON',{exact:true}).fill(JSON.stringify({...example.config.voyage,max_chunks:1,max_total_work_units:120000000,max_output_frames:256,max_mesh_records:64}));
  const response=await actual(page,'shipplan/prepare-voyage','预备并审查计划窗口');expect(response.status()).toBe(200);const prepared=await response.json(),proof=prepared.mapping.initial_equilibrium_preparation.provenance;expect(proof.schema).toBe(proofSchema);expect(proof.fluid_loading.initial_fluid.current_profile).toEqual(example.config.simulation.current_profile);expect(proof.material_loading.point_bodies[0].wet_weight_n).toBe(-50);expect(prepared.mapping.manufacturing_origin_m).toBeCloseTo(4,10);expect(prepared.mapping.initial_manufacturing_top_m).toBeCloseTo(31,10);expect(prepared.mapping.initial_natural_length_m).toBe(27);expect(prepared.config.simulation.initial_equilibrium.schema).toBe('oceanroute.dynamic.initial-equilibrium.v2');
  await expect(page.locator('.plan-voyage-preparation .equilibrium-diagnostics')).toContainText('稳恒流 / 材料证据 v3');await page.getByRole('button',{name:'应用预备窗口到任务配置',exact:true}).click();const submitted=await actual(page,'voyage/jobs','提交后台持续计算');expect(submitted.status()).toBe(200);const job=await submitted.json();await expect(page.locator('.voyage-job-status>div:first-child>strong')).toHaveText('达到限制后停止',{timeout:30000});const first=await(await request.get(apiURL+'/voyage/jobs/'+job.id+'/result')).json();expect(first.checkpoint.physical_checkpoint.schema_version).toBe(4);expect(json(first.checkpoint.physical_checkpoint.state.initialization_provenance.fluid_loading)).toEqual(json(proof.fluid_loading));expect(first.frames[0].paid_out_m).toBe(0);expect(first.frames[0].touchdown).toBeNull();expect(first.frames[0].node_material_m[0]).toBeCloseTo(31,10);
  await num(page,'请求继续计算时长 / s',.04);await num(page,'本次分块数量上限',10);const resumed=await actual(page,'voyage/jobs/'+job.id+'/resume','按当前时长继续为子任务');expect(resumed.status()).toBe(200);const child=await resumed.json();await expect(page.locator('.voyage-job-status>div:first-child>strong')).toHaveText('已完成请求时段',{timeout:30000});const continued=await(await request.get(apiURL+'/voyage/jobs/'+child.id+'/result')).json();expect(continued.summary.end_time_s).toBeCloseTo(.08,10);expect(continued.frames[0].nodes).toEqual(first.frames.at(-1).nodes);expect(json(continued.checkpoint.physical_checkpoint.state.initialization_provenance)).toEqual(json(first.checkpoint.physical_checkpoint.state.initialization_provenance));expect(continued.frames.at(-1).inline_bodies[0].deployed_wet_weight_n).toBe(-50);expect(continued.plan_mapping).toEqual(first.plan_mapping);await expect(page.locator('.sim-main>.equilibrium-diagnostics')).toContainText('稳恒流 / 材料证据 v3');await page.locator('.plan-voyage-preparation>summary').click();await page.setViewportSize({width:1800,height:1400});await dismiss(page);const mainProof=page.locator('.sim-main>.equilibrium-diagnostics');await mainProof.locator('.equilibrium-point-bodies>summary').click();await expect(mainProof.locator('.equilibrium-point-bodies tbody tr').first().locator('td').nth(4)).toHaveText('-50');await mainProof.scrollIntoViewIfNeeded();await page.screenshot({path:artifactPath('current-initial-geographic-frozen-flow-proof.png'),fullPage:true});await page.locator('.voyage-layout .sim-view').scrollIntoViewIfNeeded();await expect(page.locator('.scene-legend')).toContainText('无实际触地点');await expect(page.locator('.scene-legend')).toContainText('非刚体形状');const view=await page.locator('.voyage-layout .sim-view').boundingBox(),legend=await page.locator('.scene-legend').boundingBox();expect(legend!.y+legend!.height).toBeLessThanOrEqual(view!.y+view!.height+1);await page.screenshot({path:artifactPath('current-initial-geographic-inventory-job.png'),fullPage:true});
});
