import {test,expect} from '@playwright/test';
import {mkdir,readFile} from 'node:fs/promises';
import {apiURL} from './test-environment';
async function json(request:any,path:string,data?:any){const r=data===undefined?await request.get(apiURL+path):await request.post(apiURL+path,{data});expect(r.ok(),await r.text()).toBe(true);return r.json()}
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:20000})}
async function save(page:any,revision:number){await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText(`工程已保存 · 修订 ${revision}`,{exact:true})).toBeVisible();await ready(page)}
test('a legitimate empty workspace saves, gains an explicit path, retains orphan inventory, restores and imports without fabricated resources',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const source={schema_version:2,id:'ui-empty-'+Date.now(),name:'合法空工作区 '+Date.now(),currency:'CNY',active_path_id:null,cable_types:[{id:'GENERIC',name:'未测量材料'}],layers:[],paths:[],assemblies:[],associations:[],custom_extension:{retained:'user-owned inventory metadata',exact_number:12.5}};
 const w=(await json(request,'/workspaces',source)).workspace;expect((await json(request,'/workspaces/'+w.id)).paths).toEqual([]);await page.goto('/');await ready(page);await page.getByRole('button',{name:'打开',exact:true}).click();await page.locator('.project-list button').filter({has:page.getByText(w.name,{exact:true})}).click();await expect(page.locator('.empty-workspace')).toBeVisible();await ready(page);await expect(page.getByRole('heading',{name:'工作区尚无规划路线',exact:true})).toBeVisible();await expect(page.locator('.empty-resource').first()).toContainText('湿重 未测量');await expect(page.getByRole('button',{name:'复制活跃路径',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'由活跃规划捕获新库存',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'核验并加入第一条路线',exact:true})).toBeDisabled();await save(page,2);const unchanged=await json(request,'/workspaces/'+w.id);expect(unchanged.paths).toEqual([]);expect(unchanged.active_path_id).toBeNull();expect(unchanged.assemblies).toEqual([]);expect(unchanged.cable_types).toEqual(source.cable_types);expect(unchanged.custom_extension).toEqual(source.custom_extension);
 await page.getByLabel('空工作区新增路线名称',{exact:true}).fill('明确输入第一条路线');await page.getByLabel('空工作区新增路线缆型',{exact:true}).selectOption('GENERIC');for(const [label,value] of [['空工作区起点经度 / °E','118'],['空工作区起点纬度 / °N','22'],['空工作区终点经度 / °E','118.01'],['空工作区终点纬度 / °N','22']]){await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel(label,{exact:true}).blur()}const added=page.waitForResponse(r=>r.url().endsWith('/api/workspace/action')&&r.request().postDataJSON()?.config?.action==='add_path');await page.getByRole('button',{name:'核验并加入第一条路线',exact:true}).click();const addResult=await(await added).json();expect(addResult.workspace.paths).toHaveLength(1);expect(addResult.workspace.cable_types).toEqual(source.cable_types);expect(addResult.project.route.points.every((p:any)=>p.depth_m===null)).toBe(true);expect(addResult.workspace.assemblies).toHaveLength(1);await expect(page.locator('.empty-workspace')).toHaveCount(0);await ready(page);await save(page,3);const planned=await json(request,'/workspaces/'+w.id);const originalStock=planned.assemblies;expect(originalStock[0].total_length_m).toBeGreaterThan(1000);expect(planned.cable_types[0].wet_weight_n_m).toBeUndefined();expect(planned.cable_types[0].ea_n).toBeUndefined();
 await page.getByRole('button',{name:'工程路径与装配',exact:true}).click();await page.getByRole('button',{name:'移除路径 明确输入第一条路线',exact:true}).click();await expect(page.locator('.empty-workspace')).toBeVisible();await save(page,4);const orphaned=await json(request,'/workspaces/'+w.id);expect(orphaned.paths).toEqual([]);expect(orphaned.associations).toEqual([]);expect(orphaned.assemblies).toEqual(originalStock);await expect(page.locator('.workspace-assembly-list')).toContainText(originalStock[0].name);await mkdir('artifacts/dev-next',{recursive:true});if(await page.getByRole('button',{name:'关闭提示',exact:true}).isVisible())await page.getByRole('button',{name:'关闭提示',exact:true}).click();await page.screenshot({path:'artifacts/dev-next/empty-workspace-retained-inventory.png',fullPage:true});
 const file=page.waitForEvent('download');await page.getByRole('button',{name:'导出完整工作区',exact:true}).click();const exported=JSON.parse(await readFile((await(await file).path())!,'utf8'));expect(exported.assemblies).toEqual(originalStock);expect(exported.custom_extension).toEqual(source.custom_extension);expect(exported.saved_revision).toBe(4);await page.getByRole('button',{name:'修订历史',exact:true}).click();const restore=page.waitForResponse(r=>r.url().endsWith('/restore/2'));await page.getByRole('button').filter({has:page.getByText(`修订 2 · ${w.name}`,{exact:true})}).click();const restored=await(await restore).json();expect((restored.workspace||restored).saved_revision).toBe(5);await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.empty-workspace')).toBeVisible();expect((await json(request,'/workspaces/'+w.id)).assemblies).toEqual([]);
 await page.getByRole('button',{name:'导入工作区 JSON',exact:true}).click();await page.getByLabel('完整空工作区 JSON',{exact:true}).fill(JSON.stringify(exported));const importedResponse=page.waitForResponse(r=>r.url().endsWith('/api/workspace/import'));await page.getByRole('button',{name:'核验并导入完整工作区',exact:true}).click();const imported=await(await importedResponse).json();expect(imported.workspace.id).not.toBe(w.id);expect(imported.project).toBeNull();expect(imported.workspace.assemblies).toEqual(originalStock);await expect(page.getByRole('dialog')).toHaveCount(0);await save(page,1);const importedID=imported.workspace.id;const inventoryOnly=await json(request,'/workspaces/'+importedID);expect(inventoryOnly.custom_extension).toEqual(source.custom_extension);expect(inventoryOnly.assemblies).toEqual(originalStock);
 const path={schema_version:1,id:'explicit-route',name:'JSON明确路线',route:{points:[{id:'start',longitude:118,latitude:22},{id:'end',longitude:118.015,latitude:22}],legs:[{cable_type_id:'GENERIC'}]},cable_types:inventoryOnly.cable_types,layers:inventoryOnly.layers,terrain_sources:inventoryOnly.terrain_sources||[],costs:{currency:'CNY'}};await page.getByLabel('装配关系策略',{exact:true}).selectOption('unassigned');await page.getByText('从单路径 JSON 加入当前工程',{exact:true}).click();await page.getByLabel('加入当前工作区的单路径 JSON',{exact:true}).fill(JSON.stringify(path));await page.getByRole('button',{name:'加入规划路径',exact:true}).click();await expect(page.locator('.empty-workspace')).toHaveCount(0);await ready(page);await save(page,2);const final=await json(request,'/workspaces/'+importedID);expect(final.paths).toHaveLength(1);expect(final.assemblies).toEqual(originalStock);expect(final.associations).toEqual([]);expect(final.cable_types).toEqual(source.cable_types);expect(final.custom_extension).toEqual(source.custom_extension);await page.getByRole('button',{name:'导入数据',exact:true}).click();await page.getByRole('button',{name:'工程 JSON',exact:true}).click();await page.locator('.import-text').fill(JSON.stringify(exported));const secondImport=page.waitForResponse(r=>r.url().endsWith('/api/workspace/import'));await page.getByRole('dialog').getByRole('button',{name:'导入数据',exact:true}).click();const again=await(await secondImport).json();expect(again.project).toBeNull();expect(again.workspace.assemblies).toEqual(originalStock);await expect(page.locator('.empty-workspace')).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);await save(page,1);const durableAgain=await json(request,'/workspaces/'+again.workspace.id);expect(durableAgain.paths).toEqual([]);expect(durableAgain.assemblies).toEqual(originalStock);expect(durableAgain.custom_extension).toEqual(source.custom_extension);expect(errors).toEqual([]);
});
