import {test,expect} from '@playwright/test';
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:20000})}
async function importDone(page:any){await expect(page.getByRole('dialog')).not.toBeVisible();await ready(page)}

test('KML round trip, projected Shapefile ZIP and complete manual work',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await ready(page);
  await page.getByRole('button',{name:'导出成果',exact:false}).click();const download=page.waitForEvent('download');await page.getByRole('button').filter({has:page.getByText('地理路线 · KML',{exact:true})}).click();const kml=await download;
  await page.getByRole('button',{name:'关闭对话框',exact:true}).click();await page.getByRole('button',{name:'导入数据',exact:true}).click();await page.getByRole('button',{name:'KML',exact:true}).click();await page.locator('.file-drop input').setInputFiles((await kml.path())!);
  const kmlResponse=page.waitForResponse((r:any)=>r.url().endsWith('/api/import/kml'));await page.getByRole('button',{name:'导入数据',exact:true}).last().click();await importDone(page);const kmlLayer=await(await kmlResponse).json();expect(kmlLayer.geojson.features.length).toBeGreaterThan(0);await expect(page.locator('.layer-row')).toHaveCount(3);
  await page.getByRole('button',{name:'导入数据',exact:true}).click();await page.getByRole('button',{name:'Shapefile',exact:true}).click();await page.locator('.file-drop input').setInputFiles('tests/fixtures/projected-line.zip');await page.getByLabel('属性编码（可选）',{exact:true}).fill('gbk');
  const shpResponse=page.waitForResponse((r:any)=>r.url().endsWith('/api/import/shapefile'));await page.getByRole('button',{name:'导入数据',exact:true}).last().click();await importDone(page);const layer=await(await shpResponse).json();expect(layer.source.source_crs).toBe('EPSG:3857');expect(layer.geojson.features[0].geometry.coordinates[0][0]).toBeCloseTo(118,9);expect(layer.geojson.features[0].geometry.coordinates[0][1]).toBeCloseTo(22,9);expect(layer.geojson.features[0].properties.NAME).toBe('已敷海缆');await expect(page.locator('.layer-row')).toHaveCount(4);
  await page.getByRole('button',{name:'用户指南',exact:true}).click();await page.getByRole('button',{name:'阅读完整用户手册',exact:true}).click();await expect(page.locator('.full-manual h1')).toHaveText('OceanRoute 用户手册');expect(await page.locator('.full-manual h2').count()).toBeGreaterThanOrEqual(10);expect(await page.locator('.full-manual pre').count()).toBeGreaterThan(0);await page.locator('.modal').evaluate((e:HTMLElement)=>e.scrollTop=e.scrollHeight);await page.screenshot({path:'artifacts/complete-manual.png',fullPage:true});expect(errors).toEqual([]);
});

test('independent route search previews real obstacle avoidance, applies and undoes',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await ready(page);await page.getByRole('button',{name:'新建',exact:true}).click();await expect(page.locator('header strong')).toHaveText('未命名海缆工程');await ready(page);
  await page.getByRole('button',{name:'导入数据',exact:true}).click();await page.getByRole('button',{name:'GIS 图层',exact:true}).click();await page.getByLabel('图层名称',{exact:true}).fill('避让方区');await page.getByRole('combobox',{name:'图层类型',exact:true}).selectOption('restricted');await page.locator('.import-text').fill(JSON.stringify({type:'FeatureCollection',features:[{type:'Feature',properties:{name:'block'},geometry:{type:'Polygon',coordinates:[[[118.03,22.03],[118.07,22.03],[118.07,22.07],[118.03,22.07],[118.03,22.03]]]}}]}));await page.getByRole('button',{name:'导入数据',exact:true}).last().click();await importDone(page);
  await page.getByLabel('显示 避让方区',{exact:true}).uncheck();await ready(page);await page.getByRole('button',{name:'工程工具',exact:true}).click();await page.locator('.engineering-menu button').filter({has:page.getByText('避障候选搜索',{exact:true})}).click();await expect(page.getByLabel('禁止穿越 避让方区',{exact:true})).toBeChecked();
  const response=page.waitForResponse((r:any)=>r.url().endsWith('/api/routing/search'));await page.getByRole('button',{name:'搜索候选路线',exact:true}).click();await expect(page.locator('.routing-result')).toBeVisible({timeout:45000});const result=await(await response).json();expect(result.report.constraint_validation.selected_section_passed).toBe(true);expect(result.report.constraint_validation.obstacle_collision).toBe(false);expect(result.project.route.points.length).toBeGreaterThan(2);expect(result.report.after_summary.surface_length_m).toBeGreaterThan(result.report.before_summary.surface_length_m);
  await page.locator('.engineering-main').evaluate((e:HTMLElement)=>e.scrollTop=500);await page.screenshot({path:'artifacts/obstacle-candidate.png',fullPage:true});await page.getByRole('button',{name:'应用候选到工程',exact:true}).click();await ready(page);await page.getByRole('button',{name:'路由位置表',exact:true}).click();await expect(page.locator('.rpl-table tbody tr')).toHaveCount(result.project.route.points.length);await page.getByRole('button',{name:'撤销 ⌘Z'}).click();await ready(page);await expect(page.locator('.rpl-table tbody tr')).toHaveCount(2);expect(errors).toEqual([]);
});

test('imported map tooltip names remain literal text',async({page})=>{
  await page.goto('/');await ready(page);await page.getByRole('button',{name:'新建',exact:true}).click();await expect(page.locator('header strong')).toHaveText('未命名海缆工程');await ready(page);
  const label='<img src=x onerror="window.__point_xss=1">';await page.getByLabel('名称',{exact:true}).fill(label);await page.getByLabel('名称',{exact:true}).blur();await ready(page);await page.locator('.route-marker').first().hover();await expect(page.locator('.leaflet-tooltip')).toHaveText(label);expect(await page.evaluate(()=>(window as any).__point_xss)).toBeUndefined();await expect(page.locator('.leaflet-tooltip img')).toHaveCount(0);
  await page.getByRole('button',{name:'导入数据',exact:true}).click();await page.getByRole('button',{name:'GIS 图层',exact:true}).click();const name='<img src=x onerror="window.__layer_xss=1">';await page.getByLabel('图层名称',{exact:true}).fill(name);await page.locator('.import-text').fill(JSON.stringify({type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'Point',coordinates:[118.05,22.07]}}]}));await page.getByRole('button',{name:'导入数据',exact:true}).last().click();await importDone(page);await page.locator('.leaflet-overlay-pane path.leaflet-interactive').first().hover();await expect(page.locator('.leaflet-tooltip')).toHaveText(name);expect(await page.evaluate(()=>(window as any).__layer_xss)).toBeUndefined();await expect(page.locator('.leaflet-tooltip img')).toHaveCount(0);
});
