import {apiURL} from './test-environment';
import {artifactPath} from './artifact-path';
import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:25000})}
async function manage(page:any){await page.getByRole('button',{name:'工程路径与装配',exact:true}).click()}
test('a same-project alternative shares stock until an explicit fork, retains all path drafts and restores full relations',async({page,request})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await ready(page);await page.getByRole('button',{name:'工程设置',exact:true}).click();const name='MultiPath '+Date.now();await page.getByLabel('工程名称',{exact:true}).fill(name);await page.getByLabel('工程名称',{exact:true}).blur();await ready(page);await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText('工程已保存 · 修订 1',{exact:true})).toBeVisible();await ready(page);
  let list=await(await request.get(apiURL+'/workspaces')).json();const saved=list.find((p:any)=>p.name===name);const initial=await(await request.get(apiURL+'/workspaces/'+saved.id)).json();expect(initial.schema_version).toBe(2);const original=initial.paths[0];const stock=initial.assemblies[0].total_length_m;
  await manage(page);await page.getByLabel('新增 / 复制路径名称',{exact:true}).fill('备用路由');await page.getByLabel('装配关系策略',{exact:true}).selectOption('alternative');const copiedResponse=page.waitForResponse(r=>r.url().endsWith('/api/workspace/action')&&r.request().postDataJSON().config.action==='copy_path');await page.getByRole('button',{name:'复制活跃路径',exact:true}).click();const copied=await(await copiedResponse).json();await ready(page);expect(copied.workspace.paths).toHaveLength(2);expect(copied.workspace.assemblies).toHaveLength(1);expect(copied.analysis.summary.manufactured_total_m).toBeCloseTo(stock,6);expect(copied.analysis.summary.deployment_path_count).toBe(1);expect(copied.analysis.summary.alternative_path_count).toBe(1);await expect(page.locator('.workspace-path-list>div')).toHaveCount(2);await expect(page.getByRole('img',{name:'同工程路径与物理装配关系',exact:true})).toBeVisible();if(await page.getByRole('button',{name:'关闭提示',exact:true}).isVisible())await page.getByRole('button',{name:'关闭提示',exact:true}).click();await page.locator('.workspace-manager').evaluate((e:HTMLElement)=>e.scrollTop=0);await page.screenshot({path:artifactPath('multiple-path-shared-assembly.png'),fullPage:true});
  await page.getByRole('button',{name:'路由工作空间',exact:true}).click();const oldLongitude=original.project.route.points[0].longitude;await page.getByLabel('经度 / °E',{exact:true}).fill(String(oldLongitude+.02));await page.getByLabel('经度 / °E',{exact:true}).blur();await expect(page.locator('.workspace-draft-error')).toContainText('WORKSPACE_SHARED_ASSEMBLY_CHANGED');await expect(page.getByLabel('经度 / °E',{exact:true})).toHaveValue(String(oldLongitude+.02));await expect(page.locator('.workspace-sidebar-paths>button').first()).toBeDisabled();const forkResponse=page.waitForResponse(r=>r.url().endsWith('/api/workspace/action')&&r.request().postDataJSON().config.assembly_policy==='fork');await page.getByRole('button',{name:'为当前草稿建立独立装配',exact:true}).click();const fork=await(await forkResponse).json();await ready(page);expect(fork.workspace.assemblies).toHaveLength(2);expect(fork.workspace.paths[0].project.route.points[0].longitude).toBe(oldLongitude);expect(fork.workspace.paths[1].project.route.points[0].longitude).toBe(oldLongitude+.02);expect(fork.analysis.summary.deployment_path_count).toBe(2);await page.locator('.workspace-sidebar-paths>button').first().click();await ready(page);await expect(page.getByLabel('经度 / °E',{exact:true})).toHaveValue(String(oldLongitude));await page.locator('.workspace-sidebar-paths>button').last().click();await ready(page);await expect(page.getByLabel('经度 / °E',{exact:true})).toHaveValue(String(oldLongitude+.02));
  await manage(page);if(await page.getByRole('button',{name:'关闭提示',exact:true}).isVisible())await page.getByRole('button',{name:'关闭提示',exact:true}).click();await page.locator('.workspace-manager').evaluate((e:HTMLElement)=>e.scrollTop=0);await page.screenshot({path:artifactPath('multiple-path-relations.png'),fullPage:true});const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载完整工作区',exact:true}).click();const file=await download;const json=JSON.parse(await readFile((await file.path())!,'utf8'));expect(json.paths).toHaveLength(2);expect(json.saved_revision).toBe(1);expect(json.paths[0].project.cable_types).toBeUndefined();await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText('工程已保存 · 修订 2',{exact:true})).toBeVisible();await ready(page);const document=await(await request.get(apiURL+'/workspaces/'+saved.id)).json();expect(document.associations.filter((a:any)=>a.role==='deployment')).toHaveLength(2);
  await page.getByRole('button',{name:'修订历史',exact:true}).click();const restoreResponse=page.waitForResponse(r=>r.url().endsWith('/restore/1'));await page.getByRole('button').filter({has:page.getByText('修订 1 · '+name,{exact:true})}).click();const restore=await restoreResponse;expect(restore.request().postDataJSON().expected_revision).toBe(2);await ready(page);await manage(page);await expect(page.locator('.workspace-path-list>div')).toHaveCount(1);const restored=await(await request.get(apiURL+'/workspaces/'+saved.id)).json();expect(restored.saved_revision).toBe(3);expect(restored.assemblies).toHaveLength(1);expect(errors).toEqual([]);
});
test('independent paths reference one edited shared cable library and shared GIS collection',async({page,request})=>{
  await page.goto('/');await ready(page);await manage(page);await page.getByLabel('新增 / 复制路径名称',{exact:true}).fill('独立路由');await page.getByRole('button',{name:'复制活跃路径',exact:true}).click();await expect(page.locator('.workspace-path-list>div')).toHaveCount(2);await ready(page);await page.getByRole('button',{name:'电缆与装配',exact:true}).click();const edited=page.waitForResponse(r=>r.url().endsWith('/api/workspace/action')&&r.request().postDataJSON().config.action==='update_path');await page.locator('.cable-card').first().locator('.cable-card-heading input').fill('共享材料验证');await page.locator('.cable-card').first().locator('.cable-card-heading input').blur();const result=await(await edited).json();await ready(page);expect(result.workspace.cable_types[0].name).toBe('共享材料验证');expect(result.workspace.paths.every((p:any)=>p.project.cable_types===undefined)).toBe(true);await page.locator('.workspace-sidebar-paths>button').first().click();await ready(page);await expect(page.locator('.cable-card').first().locator('.cable-card-heading input')).toHaveValue('共享材料验证');
  await page.getByRole('button',{name:'导入数据',exact:true}).click();await page.getByRole('button',{name:'GIS 图层',exact:true}).click();await page.locator('.import-text').fill(JSON.stringify({type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:[118,22]},properties:{name:'shared'}}]}));await page.getByRole('button',{name:'导入数据',exact:true}).last().click();await expect(page.getByRole('dialog')).not.toBeVisible();await ready(page);const count=await page.locator('.layer-row').count();await page.locator('.workspace-sidebar-paths>button').last().click();await ready(page);await expect(page.locator('.layer-row')).toHaveCount(count);await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText('工程已保存 · 修订 1',{exact:true})).toBeVisible();const list=await(await request.get(apiURL+'/workspaces')).json();const saved=await(await request.get(apiURL+'/workspaces/'+list[0].id)).json();expect(saved.layers).toHaveLength(count);expect(saved.paths).toHaveLength(2);expect(saved.assemblies).toHaveLength(2);
});
