import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:25000})}
async function open(page:any){await page.goto('/');await ready(page);await page.getByRole('button',{name:'导入数据',exact:true}).click();await page.getByLabel('RPL 源记录',{exact:true}).fill('label,longitude,latitude,depth_m\nStart,118,22,10\nEnd,118.003,22,10');await page.getByRole('button',{name:'解析预览',exact:true}).click();await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeEnabled();await page.getByRole('button',{name:'应用 RPL 导入',exact:true}).click();await ready(page);await page.getByRole('button',{name:'敷设仿真',exact:true}).click();await page.getByRole('button',{name:'持续计算 / 网格审查',exact:true}).click();await page.locator('.plan-voyage-preparation>summary').click();await page.getByLabel('预备窗口时长 / s',{exact:true}).fill('2');await page.getByLabel('预备窗口时长 / s',{exact:true}).blur()}
async function prepare(page:any){const response=page.waitForResponse((r:any)=>r.url().endsWith('/api/shipplan/prepare-voyage'));await page.getByRole('button',{name:'预备并审查计划窗口',exact:true}).click();const received=await response;expect(received.status()).toBe(200);return await received.json()}

test('project manufacturing inventory maps to a real bounded dynamic job without paying initial stock again',async({page,request})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await open(page);const prepared=await prepare(page);expect(prepared.mapping.initial_manufacturing_top_m).toBeGreaterThan(0);expect(prepared.mapping.initial_natural_length_m).toBeGreaterThan(0);expect(prepared.mapping.source_plan_start_s).toBeGreaterThan(0);await expect(page.locator('.plan-voyage-instructions tbody tr').first()).not.toContainText('—');const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载预备配置与映射',exact:true}).click();const artifact=JSON.parse(await readFile((await(await download).path())!,'utf8'));expect(artifact.config.plan_mapping).toEqual(prepared.mapping);await page.getByRole('button',{name:'应用预备窗口到任务配置',exact:true}).click();await expect(page.getByLabel('明确动态物性与作业控制 JSON',{exact:true})).toBeDisabled();await expect(page.locator('.plan-voyage-applied')).toContainText('初始库存与制造映射');await page.locator('.plan-voyage-preparation .tool-summary').scrollIntoViewIfNeeded();if(await page.getByRole('button',{name:'关闭提示',exact:true}).isVisible())await page.getByRole('button',{name:'关闭提示',exact:true}).click();await page.screenshot({path:'artifacts/project-plan-voyage-mapping.png',fullPage:true});
  const response=page.waitForResponse(r=>r.url().endsWith('/api/voyage/jobs')&&r.request().method()==='POST');await page.getByRole('button',{name:'提交后台持续计算',exact:true}).click();const received=await response;const submitted=received.request().postDataJSON();expect(submitted.config).toEqual(prepared.config);const job=await received.json();await expect(page.locator('.voyage-job-status>div:first-child>strong')).toHaveText('已完成请求时段',{timeout:30000});await expect(page.locator('.voyage-plan-mapping')).toBeVisible();const actual=await(await request.get('http://127.0.0.1:8765/api/voyage/jobs/'+job.id+'/result')).json();expect(actual.plan_mapping).toEqual(prepared.mapping);expect(actual.checkpoint.plan_mapping).toEqual(prepared.mapping);expect(actual.summary.end_time_s).toBe(2);expect(actual.summary.paid_out_m).toBeCloseTo(prepared.mapping.final_manufacturing_top_m-prepared.mapping.initial_manufacturing_top_m,7);expect(actual.frames[0].node_material_m[0]).toBeCloseTo(prepared.mapping.initial_manufacturing_top_m,7);expect(actual.summary.paid_out_m).not.toBeCloseTo(prepared.mapping.final_manufacturing_top_m,3);await page.locator('.plan-voyage-preparation>summary').click();await page.getByRole('button',{name:'跳转持续计算末帧',exact:true}).click();await page.locator('.voyage-layout .sim-view').scrollIntoViewIfNeeded();if(await page.getByRole('button',{name:'关闭提示',exact:true}).isVisible())await page.getByRole('button',{name:'关闭提示',exact:true}).click();await page.screenshot({path:'artifacts/project-plan-voyage-window.png',fullPage:true});
  await page.getByLabel('请求继续计算时长 / s',{exact:true}).fill('1');await page.getByLabel('请求继续计算时长 / s',{exact:true}).blur();await expect(page.getByRole('button',{name:'提交后台持续计算',exact:true})).toBeDisabled();
  const checkpoint=await(await request.get('http://127.0.0.1:8765/api/voyage/jobs/'+job.id+'/checkpoint')).json();await page.getByRole('button',{name:'导入数据',exact:true}).click();await page.getByLabel('RPL 源记录',{exact:true}).fill('label,longitude,latitude,depth_m\nChanged,118,22,10\nEnd,118.004,22,10');await page.getByRole('button',{name:'解析预览',exact:true}).click();await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeEnabled();await page.getByRole('button',{name:'应用 RPL 导入',exact:true}).click();await ready(page);await page.locator('.voyage-layout .advanced-environment input[type=file]').setInputFiles({name:'original-voyage-checkpoint.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(checkpoint))});await expect(page.getByRole('button',{name:'提交后台持续计算',exact:true})).toBeEnabled();const rejectedResponse=page.waitForResponse(r=>r.url().endsWith('/api/voyage/jobs')&&r.request().method()==='POST');await page.getByRole('button',{name:'提交后台持续计算',exact:true}).click();const rejected=await(await rejectedResponse).json();await expect(page.locator('.voyage-job-status>div:first-child>strong')).toHaveText('计算失败',{timeout:30000});await expect(page.locator('.voyage-layout .sim-view')).toHaveCount(0);await expect(page.getByRole('button',{name:'保存最近完整断点',exact:true})).toBeDisabled();const rejectedStatus=await(await request.get('http://127.0.0.1:8765/api/voyage/jobs/'+rejected.id)).json();expect(rejectedStatus.status).toBe('failed');expect(rejectedStatus.result_available).toBe(false);expect(errors).toEqual([]);
});

test('planning preparation refuses stale previews and changing bathymetry honestly',async({page})=>{
  await open(page);await prepare(page);await page.getByLabel('预备海床张力 / N',{exact:true}).fill('20');await page.getByLabel('预备海床张力 / N',{exact:true}).blur();await expect(page.locator('.plan-voyage-stale')).toBeVisible();await expect(page.getByRole('button',{name:'应用预备窗口到任务配置',exact:true})).toHaveCount(0);await prepare(page);await expect(page.getByRole('button',{name:'应用预备窗口到任务配置',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'导入数据',exact:true}).click();await page.getByLabel('RPL 源记录',{exact:true}).fill('label,longitude,latitude,depth_m\nStart,118,22,10\nEnd,118.003,22,20');await page.getByRole('button',{name:'解析预览',exact:true}).click();await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeEnabled();await page.getByRole('button',{name:'应用 RPL 导入',exact:true}).click();await ready(page);const response=page.waitForResponse(r=>r.url().endsWith('/api/shipplan/prepare-voyage'));await page.getByRole('button',{name:'预备并审查计划窗口',exact:true}).click();expect((await response).status()).toBe(422);await expect(page.locator('.plan-voyage-preparation .inline-warning').filter({hasText:'flat'})).toBeVisible();await expect(page.getByRole('button',{name:'应用预备窗口到任务配置',exact:true})).toHaveCount(0);
});
