import {test,expect} from '@playwright/test';
import {artifactPath} from './artifact-path';
import {apiURL} from './test-environment';
const api=apiURL,utm='EPSG:32650';
const feet='+proj=utm +zone=50 +datum=WGS84 +units=ft +type=crs';
async function json(request:any,path:string,data?:any){const r=data===undefined?await request.get(api+path):await request.post(api+path,{data});expect(r.ok(),await r.text()).toBe(true);return r.json()}
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:20000})}
async function base(request:any){const p=await json(request,'/sample');p.name='ProjectedEdit '+Date.now()+' '+Math.random();p.route={...p.route,name:'用户明确三点路线',mode:'flexible',slack_basis:'surface',slack_pct:1,curve:'rhumb',points:[{id:'start',label:'Start',longitude:118,latitude:22,depth_m:100,note:'用户原备注',custom_point:{retained:1}},{id:'mid',label:'Mid',longitude:118.05,latitude:22,depth_m:100,note:''},{id:'end',label:'End',longitude:118.1,latitude:22,depth_m:100,note:''}],legs:[{cable_type_id:p.cable_types[0].id,slack_pct:1,mode:'flexible',slack_basis:'surface',allowance_m:7,custom_leg:{preserve:true}},{cable_type_id:p.cable_types[0].id,slack_pct:1,mode:'flexible',slack_basis:'surface',allowance_m:9,custom_leg:{preserve:true}}]};p.layers=[];p.bodies=[];p.assembly_references=[];p.profile={samples:[],source:'user'};p.custom_extension={unknown:'must survive projected editing'};delete p.manufacturing;return p}
async function store(request:any,p:any,alternative=false){let w=(await json(request,'/workspace/migrate',{project:p})).workspace;w.custom_workspace={preserve:'opaque user workspace extension'};if(alternative)w=(await json(request,'/workspace/action',{workspace:w,config:{action:'copy_path',name:'明确共享备选',assembly_policy:'alternative'}})).workspace;return (await json(request,'/workspaces',w)).workspace}
async function open(page:any,w:any){await page.goto('/');await ready(page);await page.getByRole('button',{name:'打开',exact:true}).click();await page.locator('.project-list button').filter({has:page.getByText(w.name,{exact:true})}).click();await ready(page);await page.getByRole('button',{name:'路由工作空间',exact:true}).click()}
async function project(page:any,crs=utm){await page.getByRole('button',{name:'投影视图',exact:true}).click();await page.getByLabel('地图显示投影 CRS',{exact:true}).fill(crs);const pending=page.waitForResponse((r:any)=>r.url().endsWith('/api/maps/project'));await page.getByRole('button',{name:'计算真实投影视图',exact:true}).click();const result=await(await pending).json();expect(result.can_display).toBe(true);await expect(page.locator('.projected-route-point').first()).toBeVisible();return result}
function point(page:any,pid:string){return page.locator('.projected-route-point[data-point-id="'+pid+'"]')}
function inverseResponse(page:any){return page.waitForResponse((r:any)=>r.url().endsWith('/api/coordinates/transform')&&r.request().postDataJSON().target_crs==='EPSG:4326')}
async function drag(page:any,pid:string,dx=25,dy=-18){const b=(await point(page,pid).locator('circle').boundingBox())!;const inverse=inverseResponse(page);await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+dx,b.y+b.height/2+dy,{steps:6});await page.mouse.up();return await(await inverse).json()}
async function submitted(page:any){await expect(page.locator('.projected-edit-status')).toHaveClass(/submitted/);await ready(page);await expect(page.getByRole('img',{name:'实际投影路线与 GIS 工程平面',exact:true})).toBeVisible()}
async function save(page:any){const r=page.waitForResponse((r:any)=>r.url().endsWith('/api/workspaces')&&r.request().method()==='POST');await page.getByRole('button',{name:'保存',exact:true}).click();const actual=await(await r).json();await expect(page.getByText('工程已保存 · 修订 '+actual.revision,{exact:true})).toBeVisible();await ready(page);return actual.workspace}
async function shot(page:any,name:string){await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await page.screenshot({path:artifactPath(name+'.png'),fullPage:true,animations:'disabled'})}
async function undo(page:any){await page.getByRole('button',{name:'撤销 ⌘Z',exact:true}).click();await ready(page)}
async function tool(page:any,name:string){await page.getByRole('button',{name:'工程工具',exact:true}).click();await page.locator('.engineering-menu button').filter({has:page.getByText(name,{exact:true})}).click()}

test('UTM pointer drag really converts XY and commits once with viewport, extensions, undo, save and reopen intact',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const p=await base(request),w=await store(request,p);await open(page,w);const displayed=await project(page);expect(displayed.points[0].coordinates[0]).toBeCloseTo(603224.6404290784,5);
 const plane=page.getByRole('img',{name:'实际投影路线与 GIS 工程平面',exact:true});const camera=await Promise.all(['data-camera-x','data-camera-y','data-camera-span'].map(k=>plane.getAttribute(k))); const startX=Number(await point(page,'start').getAttribute('data-x'));const r=await drag(page,'start');expect(r.can_apply).toBe(true);expect(r.operation.ballpark).toBe(false);expect(r.source_crs.input).toBe(utm);await submitted(page);
 const longitude=r.points[0].output.x,latitude=r.points[0].output.y;expect(Number(await page.getByLabel('经度 / °E',{exact:true}).inputValue())).toBeCloseTo(longitude,8);expect(Number(await page.getByLabel('纬度 / °N',{exact:true}).inputValue())).toBeCloseTo(latitude,8);expect(Number(await point(page,'start').getAttribute('data-x'))).not.toBe(startX);expect(await Promise.all(['data-camera-x','data-camera-y','data-camera-span'].map(k=>plane.getAttribute(k)))).toEqual(camera);await expect(page.locator('.projected-candidate-point')).toHaveCount(0);
 const saved=await save(page);expect(saved.saved_revision).toBe(2);expect(saved.custom_workspace).toEqual(w.custom_workspace);expect(saved.cable_types).toEqual(w.cable_types);expect(saved.paths[0].project.custom_extension).toEqual(p.custom_extension);expect(saved.paths[0].project.route.points[0].custom_point).toEqual(p.route.points[0].custom_point);expect(saved.paths[0].project.route.points[0].depth_m).toBe(100);
 await undo(page);expect(Number(await page.getByLabel('经度 / °E',{exact:true}).inputValue())).toBeCloseTo(118,8);const undone=await save(page);expect(undone.saved_revision).toBe(3);expect(undone.paths[0].project.route.points[0].longitude).toBe(118);await expect(page.getByRole('button',{name:'撤销 ⌘Z',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'重做 ⌘⇧Z',exact:true}).click();await ready(page);const redone=await save(page);expect(redone.saved_revision).toBe(4);await open(page,redone);expect(Number(await page.getByLabel('经度 / °E',{exact:true}).inputValue())).toBeCloseTo(longitude,8);await project(page);await shot(page,'projected-utm-drag');expect(errors).toEqual([]);
});

test('projected feet are native coordinates during pan, zoom and dragging, and inverse operation matches the real API',async({page,request})=>{
 const p=await base(request),w=await store(request,p);await open(page,w);const displayed=await project(page,feet);expect(displayed.target_crs.axis_units[0].conversion_to_m).toBeCloseTo(.3048,10);expect(displayed.points[0].coordinates[0]).toBeCloseTo(603224.6404290784/.3048,5);
 await page.getByRole('button',{name:'投影视图放大',exact:false}).click();const plane=page.getByRole('img',{name:'实际投影路线与 GIS 工程平面',exact:true}),box=(await plane.boundingBox())!;const camera=await Promise.all(['data-camera-x','data-camera-y','data-camera-span'].map(k=>plane.getAttribute(k)));await page.mouse.move(box.x+box.width*.12,box.y+box.height*.8);await page.mouse.down();await page.mouse.move(box.x+box.width*.12+36,box.y+box.height*.8+14,{steps:5});await page.mouse.up();expect(Number(await plane.getAttribute('data-camera-x'))).toBeCloseTo(Number(camera[0])-36/box.width*Number(camera[2]),6);expect(Number(await plane.getAttribute('data-camera-y'))).toBeCloseTo(Number(camera[1])+14/box.width*Number(camera[2]),6);const inverse=await drag(page,'mid',38,-24);expect(inverse.source_crs.axis_units[0].conversion_to_m).toBeCloseTo(.3048,10);const input=inverse.points[0].input;const expected=await json(request,'/coordinates/transform',{source_crs:feet,target_crs:'EPSG:4326',points:[{id:'oracle',x:input.x,y:input.y}],error_policy:'collect'});await submitted(page);const saved=await save(page),actual=saved.paths[0].project.route.points.find((v:any)=>v.id==='mid');expect(actual.longitude).toBeCloseTo(expected.points[0].output.x,9);expect(actual.latitude).toBeCloseTo(expected.points[0].output.y,9);expect(actual.depth_m).toBe(100);expect(saved.paths[0].project.route.points[0].longitude).toBe(118);await shot(page,'projected-native-feet');
});

test('projected append and deletion preserve explicit fixed lengths, allowances and unknown leg fields without missing-length zero fallback',async({page,request})=>{
 const p=await base(request);p.route.mode='fixed';p.route.legs.forEach((l:any,i:number)=>{l.mode='fixed';l.fixed_cable_length_m=i?6000:5800});const w=await store(request,p);await open(page,w);await project(page);
 await point(page,'mid').click();await page.getByRole('button',{name:'删除投影选中路线点',exact:false}).click();await submitted(page);const merged=await save(page);expect(merged.paths[0].project.route.points).toHaveLength(2);const leg=merged.paths[0].project.route.legs[0];expect(leg.fixed_cable_length_m).toBe(11800);expect(leg.allowance_m).toBe(16);expect(leg.custom_leg).toEqual({preserve:true});await expect(page.getByRole('button',{name:'删除投影选中路线点',exact:false})).toBeDisabled();await undo(page);const restored=await save(page);expect(restored.paths[0].project.route.legs.map((l:any)=>l.fixed_cable_length_m)).toEqual([5800,6000]);
 await page.getByRole('button',{name:'在投影画布点击追加路线点',exact:false}).click();await page.getByLabel('投影追加点名称',{exact:true}).fill('用户追加 · 未测水深');await page.getByLabel('投影追加段模式',{exact:true}).selectOption('fixed');const plane=page.getByRole('img',{name:'实际投影路线与 GIS 工程平面',exact:true}),box=(await plane.boundingBox())!;
 // A missing declared fixed quantity is rejected, rather than manufacturing a zero-length segment.
 await plane.click({position:{x:box.width*.78,y:box.height*.4}});await expect(page.locator('.projected-edit-status.rejected')).toContainText('明确填写');await expect(page.locator('.projected-route-point')).toHaveCount(3);await page.getByLabel('投影追加固定缆长 / m',{exact:true}).fill('1200');const inverse=inverseResponse(page);await plane.click({position:{x:box.width*.78,y:box.height*.4}});const transformed=await(await inverse).json();expect(transformed.can_apply).toBe(true);await submitted(page);const added=await save(page);expect(added.paths[0].project.route.points).toHaveLength(4);expect(added.paths[0].project.route.points[3].depth_m).toBeNull();expect(added.paths[0].project.route.legs[2].fixed_cable_length_m).toBe(1200);expect(added.paths[0].project.route.legs[0].custom_leg).toEqual({preserve:true});expect(added.cable_types).toEqual(w.cable_types);await shot(page,'projected-append-fixed');await page.setViewportSize({width:900,height:900});await shot(page,'projected-append-narrow');await page.setViewportSize({width:1512,height:982});await undo(page);expect((await save(page)).paths[0].project.route.points).toHaveLength(3);
 const incompatible=await base(request);incompatible.route.legs[1].custom_leg={preserve:false};const other=await store(request,incompatible);await open(page,other);await project(page);await point(page,'mid').click();await page.getByRole('button',{name:'删除投影选中路线点',exact:false}).click();await expect(page.locator('.projected-edit-status.rejected')).toContainText('custom_leg');expect((await json(request,'/workspaces/'+other.id)).paths[0].project.route.points).toHaveLength(3);
});

test('projected constrained dragging uses actual clamped placement, explicitly moves rigid anchors and locks Fixed Sliding and structural edits',async({page,request})=>{
 const p=await base(request);const configured=await json(request,'/constraints/configure',{project:p,config:{mode:'fixed',points:[{point_id:'start',constraint:'rigid'},{point_id:'mid',constraint:'clamped'},{point_id:'end',constraint:'rigid'}]}});const w=await store(request,configured.project);await open(page,w);await project(page);const solve=page.waitForResponse((r:any)=>r.url().endsWith('/api/constraints/edit'));const inverse=await drag(page,'mid',30,-38);const solved=await(await solve).json();await submitted(page);const mid=solved.project.route.points.find((v:any)=>v.id==='mid');expect(inverse.points[0].output.y).not.toBeCloseTo(22,5);expect(mid.latitude).toBeCloseTo(22,7);expect(Number(await page.getByLabel('纬度 / °N',{exact:true}).inputValue())).toBeCloseTo(mid.latitude,8);expect(solved.report.after_summary.cable_length_m).toBeCloseTo(solved.report.before_summary.cable_length_m,7);await expect(page.locator('.projected-edit-actual')).toBeVisible();await expect(page.getByRole('button',{name:'在投影画布点击追加路线点',exact:false})).toBeDisabled();await expect(page.getByRole('button',{name:'删除投影选中路线点',exact:false})).toBeDisabled();
 const rigidSolve=page.waitForResponse((r:any)=>r.url().endsWith('/api/constraints/edit'));await drag(page,'end',20,-10);const rigid=await(await rigidSolve).json();await submitted(page);expect(rigid.project.route.points.find((v:any)=>v.id==='end').longitude).not.toBe(118.1);expect(rigid.project.route.points.find((v:any)=>v.id==='start').longitude).toBe(118);const saved=await save(page);expect(saved.assemblies[0].total_length_m).toBeCloseTo(w.assemblies[0].total_length_m,7);await shot(page,'projected-domain-solver');
 const sliding=await json(request,'/constraints/configure',{project:p,config:{mode:'fixed',points:[{point_id:'start',constraint:'rigid'},{point_id:'mid',constraint:'sliding'},{point_id:'end',constraint:'rigid'}]}});const sw=await store(request,sliding.project);sw.name='Sliding '+sw.id;const named=(await json(request,'/workspace/action',{workspace:sw,config:{action:'update_metadata',name:sw.name}})).workspace;const stored=(await json(request,'/workspaces',named)).workspace;await open(page,stored);await project(page);await expect(point(page,'mid')).toHaveAttribute('data-locked','true');let attempts=0;page.on('request',(r:any)=>{if(r.url().endsWith('/api/coordinates/transform')&&r.postDataJSON().target_crs==='EPSG:4326')attempts++});const b=(await point(page,'mid').locator('circle').boundingBox())!;await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+20,b.y+b.height/2-20,{steps:5});await page.mouse.up();await expect(page.locator('.projected-edit-tools')).toContainText('Fixed Sliding');await expect(page.locator('.projected-candidate-point')).toHaveCount(0);expect(attempts).toBe(0);expect((await json(request,'/workspaces/'+sw.id)).assemblies[0].total_length_m).toBeCloseTo(sw.assemblies[0].total_length_m,7);
});

test('multi-path bottom-slack edits keep failed drafts and original shared inventory, while real atomic resampling rejects divergent alternatives',async({page,request})=>{
 const e=await json(request,'/terrain/sources/example'),p=await base(request);p.terrain_sources=e.sources;p.route.points=e.project.route.points.map((v:any,i:number)=>({...v,label:i?'End':'Start',depth_m:55,note:'明确合成，不是测量'}));p.route.slack_basis='bottom';p.route.slack_pct=2;p.route.legs=[{cable_type_id:p.cable_types[0].id,mode:'flexible',slack_basis:'bottom',slack_pct:2}];const sampled=await json(request,'/terrain/profile',{project:p,config:{spacing_m:200}}),w=await store(request,sampled.project,true);await open(page,w);const active=w.paths.find((v:any)=>v.id===w.active_path_id),endpoint=active.project.route.points[1].id;await project(page);const inverse=await drag(page,endpoint,35,-15);expect(inverse.can_apply).toBe(true);await expect(page.locator('.projected-edit-status.submitted')).toBeVisible();await expect(page.locator('.workspace-draft-error')).toBeVisible();await expect(page.locator('.calculation-status')).toContainText('检查制造关系');await expect(page.getByRole('img',{name:'实际投影路线与 GIS 工程平面',exact:true})).not.toBeVisible();
 await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.locator('.toast.error')).toBeVisible();expect(await json(request,'/workspaces/'+w.id)).toEqual(w);await tool(page,'多源测深库');await page.getByLabel('原子重采样最大站距 / m',{exact:true}).fill('200');await page.getByLabel('原子重采样最大站距 / m',{exact:true}).blur();const pending=page.waitForResponse((r:any)=>r.url().endsWith('/api/workspace/terrain/preview'));await page.getByRole('button',{name:'预览工作区原子重采样',exact:true}).click();const preview=await(await pending).json();expect(preview.can_apply).toBe(false);expect(preview.workspace).toBeNull();expect(preview.errors.some((v:any)=>v.code.includes('SHARED'))).toBe(true);await expect(page.getByRole('button',{name:'原子应用完整工作区',exact:true})).toBeDisabled();expect(preview.paths.some((v:any)=>v.samples?.some((s:any)=>s.source_id))).toBe(true);expect(await json(request,'/workspaces/'+w.id)).toEqual(w);await shot(page,'projected-shared-bottom-draft');await undo(page);const restored=await save(page);expect(restored.assemblies).toEqual(w.assemblies);expect(restored.associations).toEqual(w.associations);expect(restored.terrain_sources).toEqual(w.terrain_sources);expect(restored.custom_workspace).toEqual(w.custom_workspace);
 // Real concurrent revision conflict preserves the point draft rather than overwriting another window.
 await page.getByRole('button',{name:'路由工作空间',exact:true}).click();await project(page);const current=await json(request,'/workspaces/'+w.id);const external=structuredClone(current);external.name+=' external revision';const latest=(await json(request,'/workspaces',external)).workspace;expect(latest.saved_revision).toBe(current.saved_revision+1);await page.getByLabel('备注',{exact:true}).fill('本窗口未丢的备注草稿');await page.getByLabel('备注',{exact:true}).blur();await ready(page);await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.locator('.toast.error')).toContainText('修订');await expect(page.getByLabel('备注',{exact:true})).toHaveValue('本窗口未丢的备注草稿');expect((await json(request,'/workspaces/'+w.id)).name).toBe(latest.name);
});

test('late actual inverse responses are discarded after CRS or whole-workspace revision changes and true domain failure leaves no old candidate',async({page,request})=>{
 const p=await base(request),w=await store(request,p);await open(page,w);await project(page);let release:()=>void=()=>{},captured:()=>void=()=>{};let gate=Promise.resolve(),hold=false;let waitCaptured=Promise.resolve();
 await page.route('**/api/coordinates/transform',async route=>{const body=route.request().postDataJSON();if(hold&&body.target_crs==='EPSG:4326'){hold=false;const actual=await route.fetch();captured();await gate;await route.fulfill({response:actual})}else await route.continue()});
 function prepare(){hold=true;gate=new Promise<void>(r=>{release=r});waitCaptured=new Promise<void>(r=>{captured=r})}
 async function begin(){const b=(await point(page,'mid').locator('circle').boundingBox())!;await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+25,b.y+b.height/2-15,{steps:5});await page.mouse.up();await waitCaptured}
 prepare();await begin();await page.getByLabel('地图显示投影 CRS',{exact:true}).fill('EPSG:3857');release();await expect(page.locator('.projected-edit-status.rejected')).toContainText('已丢弃');await expect(page.locator('.projected-candidate-point')).toHaveCount(0);expect(await json(request,'/workspaces/'+w.id)).toEqual(w);
 await project(page);prepare();await begin();const saved=await save(page);expect(saved.saved_revision).toBe(2);release();await expect(page.locator('.projected-edit-status.rejected')).toContainText('已丢弃');expect((await json(request,'/workspaces/'+w.id)).paths[0].project.route.points.find((v:any)=>v.id==='mid').longitude).toBe(118.05);
 await page.unroute('**/api/coordinates/transform');await page.getByRole('button',{name:'取消投影点位操作 / 关闭结果',exact:false}).click();for(let i=0;i<40;i++)await page.getByRole('button',{name:'投影视图缩小',exact:false}).click();const invalid=await drag(page,'end',140,0);expect(invalid.can_apply).toBe(false);await expect(page.locator('.projected-edit-status.rejected')).toBeVisible();await expect(page.locator('.projected-edit-actual')).toHaveCount(0);await expect(page.locator('.projected-candidate-point')).toHaveCount(0);expect((await json(request,'/workspaces/'+w.id)).paths[0].project.route.points).toEqual(saved.paths[0].project.route.points);await shot(page,'projected-late-and-domain-failure');
});
