import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const api='http://127.0.0.1:8765/api';
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:20000})}
async function imports(page:any){await page.goto('/');await ready(page);await page.getByRole('button',{name:'导入数据',exact:true}).click();await expect(page.locator('.rpl-import-panel')).toBeVisible()}
async function parse(page:any){const response=page.waitForResponse((r:any)=>r.url().endsWith('/api/import/rpl'));await page.getByRole('button',{name:'解析预览',exact:true}).click();const received=await response;expect(received.status()).toBe(200);return await received.json()}
async function terrain(page:any){await page.goto('/');await ready(page);await page.getByRole('button',{name:'工程工具',exact:true}).click();await page.locator('.engineering-menu button').filter({has:page.getByText('测深网格与地形',{exact:true})}).click()}
async function number(page:any,label:string,value:string){await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel(label,{exact:true}).blur()}
const xyz='longitude latitude depth_m\n118 22 100\n118.002 22 105\n118.004 22 112\n118 22.002 106\n118.002 22.002 112\n118.004 22.002 120\n118 22.004 115\n118.002 22.004 122\n118.004 22.004 130';
const bln='5,0,"include"\n117.999,21.999\n118.005,21.999\n118.005,22.005\n117.999,22.005\n117.999,21.999\n5,1,"hole"\n118.0015,22.0015\n118.0025,22.0015\n118.0025,22.0025\n118.0015,22.0025\n118.0015,22.0015';

test('CSV mapping collects physical-row errors and skips only after explicit reparse',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await imports(page);
  await page.getByLabel('RPL 源记录',{exact:true}).fill('点序,东经,北纬,测深\n甲,118,22,30\n坏记录,invalid,22,45\n乙,118.01,22.01,60');
  for(const [field,header] of [['label','点序'],['longitude','东经'],['latitude','北纬'],['depth_m','测深']])await page.getByLabel('RPL 列映射 '+field,{exact:true}).fill(header);
  const collected=await parse(page);expect(collected.can_apply).toBe(false);expect(collected.points).toHaveLength(2);expect(collected.errors[0].line_start).toBe(3);await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeDisabled();await expect(page.locator('.rpl-record-errors')).toContainText('源行 3');await expect(page.locator('.rpl-parse-preview tr.invalid')).toHaveCount(1);
  await page.getByLabel('RPL 坏记录处理',{exact:true}).selectOption('skip');await expect(page.locator('.rpl-preview-stale')).toBeVisible();await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeDisabled();const skipped=await parse(page);expect(skipped.can_apply).toBe(true);expect(skipped.rejected_rows).toBe(1);await expect(page.locator('.rpl-import-panel')).toContainText('可能跨过缺失记录');await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeEnabled();
  await page.screenshot({path:'artifacts/rpl-mapping-diagnostics.png',fullPage:true});await page.getByRole('button',{name:'应用 RPL 导入',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await ready(page);await page.getByRole('button',{name:'路由位置表',exact:true}).click();await expect(page.locator('.rpl-table tbody tr')).toHaveCount(2);expect(errors).toEqual([]);
});

test('real multiline Unicode template retains fixed manufactured legs and JSON roundtrip',async({page,request})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const examples=await(await request.get(api+'/import/rpl/templates')).json();expect(examples.examples).toHaveLength(2);await imports(page);await page.getByLabel('RPL 示例模板',{exact:true}).selectOption('0');await expect(page.getByLabel('RPL 源记录',{exact:true})).toHaveValue(examples.examples[0].text);await expect(page.getByLabel('每条记录行数',{exact:true})).toHaveValue('2');const output=await parse(page);expect(output.points).toHaveLength(3);expect(output.legs).toHaveLength(2);expect(output.legs[0].fixed_cable_length_m).toBe(1750);expect(output.legs[1].fixed_cable_length_m).toBe(1750);expect(output.points[1].longitude).toBeCloseTo(118+1/60,10);expect(output.records[0].line_start).toBe(2);expect(output.records[0].line_end).toBe(3);
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载模板 JSON',exact:true}).click();const file=await download;const template=JSON.parse((await readFile((await file.path())!)).toString());expect(template.column_units).toBe('unicode_code_points');expect(template.fields.cable_kp_m.line).toBe(2);
  await page.getByLabel('longitude 起始字符',{exact:true}).fill('8');await page.getByLabel('longitude 起始字符',{exact:true}).blur();await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeDisabled();const validation=page.waitForResponse(r=>r.url().endsWith('/api/import/rpl/template'));await page.getByLabel('载入 RPL 模板 JSON',{exact:true}).setInputFiles({name:'roundtrip-template.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(template))});expect((await validation).status()).toBe(200);await expect(page.getByLabel('longitude 起始字符',{exact:true})).toHaveValue('7');await parse(page);await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeEnabled();await page.screenshot({path:'artifacts/rpl-multiline-template.png',fullPage:true});await page.getByRole('button',{name:'应用 RPL 导入',exact:true}).click();await ready(page);await expect(page.locator('.metric').nth(2).locator('strong')).toHaveText('3.500');await page.getByRole('button',{name:'路由位置表',exact:true}).click();await expect(page.locator('.rpl-table tbody tr')).toHaveCount(3);expect(errors).toEqual([]);
});

test('DMS delimited template reports partial multiline records and unknown cables explicitly',async({page,request})=>{
  const examples=await(await request.get(api+'/import/rpl/templates')).json();await imports(page);await page.getByLabel('RPL 示例模板',{exact:true}).selectOption('1');const result=await parse(page);expect(result.points[0].label).toBe('起点,甲');expect(result.points[0].note).toBe('中文,备注');expect(result.points[1].latitude).toBeCloseTo(22+1/60,10);expect(result.legs[0].slack_pct).toBe(1.5);await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeEnabled();
  await page.getByLabel('默认路由参数 JSON',{exact:true}).fill(JSON.stringify({...examples.examples[1].template.defaults,cable_type_id:'UNKNOWN'}));await parse(page);await expect(page.locator('.rpl-import-panel')).toContainText('工程缆型库中不存在：UNKNOWN');await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeDisabled();await page.getByLabel('默认路由参数 JSON',{exact:true}).fill(JSON.stringify(examples.examples[1].template.defaults));const mapped=await parse(page);expect(mapped.legs[0].cable_type_id).toBe('LW');await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeEnabled();
  await page.getByLabel('RPL 示例模板',{exact:true}).selectOption('0');await page.getByLabel('RPL 源记录',{exact:true}).fill(examples.examples[0].text.replaceAll('LW    ','轻缆    '));await page.getByLabel('缆型名称映射 JSON',{exact:true}).fill('{"轻缆":"LW"}');const sourceMapped=await parse(page);expect(sourceMapped.legs[0].cable_type_id).toBe('LW');await page.getByLabel('RPL 源记录',{exact:true}).fill(examples.examples[0].text+'\n尾记录');const partial=await parse(page);expect(partial.can_apply).toBe(false);expect(partial.records.at(-1).accepted).toBe(false);await expect(page.locator('.rpl-record-errors')).toContainText('记录');await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeDisabled();
});

test('minimum-curvature BLN clip and full-raster slice preserve the declared hole',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await terrain(page);await page.getByLabel('XYZ 测深源数据',{exact:true}).fill(xyz);await number(page,'网格间距 / m','50');await number(page,'最大测点距离 / m','500');await number(page,'等深距 / m','5');await page.getByLabel('DTM 插值方式',{exact:true}).selectOption('minimum_curvature');await page.getByLabel('DTM 裁剪边界格式',{exact:true}).selectOption('bln');await page.getByLabel('DTM 裁剪边界',{exact:true}).fill(bln);await page.getByLabel('BLN 边界 CRS',{exact:true}).fill('EPSG:4326');const generated=page.waitForResponse(r=>r.url().endsWith('/api/dtm/grid'));await page.getByRole('button',{name:'生成地形成果',exact:true}).click();const grid=await(await generated).json();expect(grid.metadata.converged).toBe(true);expect(grid.metadata.solver.iterations).toBeGreaterThan(0);expect(grid.metadata.solver.work_units).toBeGreaterThan(0);expect(grid.metadata.boundary.include_count).toBe(1);expect(grid.metadata.boundary.exclude_count).toBe(1);expect(grid.metadata.missing_cells).toBeGreaterThan(0);await expect(page.locator('.terrain-solver h3')).toContainText('已收敛');await page.locator('.terrain-result').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/dtm-minimum-curvature-grid.png',fullPage:true});
  await page.getByLabel('DTM 切片参考线',{exact:true}).fill('[[118.001,22.001],[118.003,22.003]]');const sampled=page.waitForResponse(r=>r.url().endsWith('/api/dtm/slice'));await page.getByRole('button',{name:'提取实际切片',exact:true}).click();const received=await sampled;const body=received.request().postDataJSON();expect(Object.keys(body.grid)).toEqual(['geotiff_base64']);const slice=await received.json();expect(slice.summary.missing_count).toBeGreaterThan(0);expect(slice.summary.bottom_length_m).toBeNull();expect(slice.valid_segments.length).toBeGreaterThanOrEqual(2);await expect(page.locator('.terrain-slice-table')).toContainText('NoData');await expect(page.locator('.slice-valid-segment')).toHaveCount(slice.valid_segments.length);
  const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'切片 CSV',exact:true}).click();const csv=await readFile((await(await downloaded).path())!,'utf8');expect(csv).toBe(slice.csv_text);const blnDownloaded=page.waitForEvent('download');await page.getByRole('button',{name:'有效切片 BLN',exact:true}).click();expect(await readFile((await(await blnDownloaded).path())!,'utf8')).toBe(slice.slice_bln_text);await page.screenshot({path:'artifacts/dtm-minimum-curvature-slice.png',fullPage:true});
  await page.getByLabel('DTM 切片参考线',{exact:true}).fill('[[118.001,22.001],[118.0035,22.0035]]');await expect(page.locator('.terrain-slice-stale')).toBeVisible();await expect(page.getByRole('button',{name:'切片 CSV',exact:true})).toHaveCount(0);await number(page,'残差张力（0–1）','0.2');await expect(page.locator('.terrain-result-stale')).toBeVisible();await expect(page.getByRole('button',{name:'四波段 GeoTIFF',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'添加等深线到地图',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'提取实际切片',exact:true})).toBeDisabled();expect(errors).toEqual([]);
});

test('unconverged curvature remains a candidate and JSON polygon clipping supports complete slice',async({page})=>{
  await terrain(page);await page.getByLabel('XYZ 测深源数据',{exact:true}).fill(xyz);await number(page,'网格间距 / m','50');await number(page,'最大测点距离 / m','500');await page.getByLabel('DTM 插值方式',{exact:true}).selectOption('minimum_curvature');await number(page,'求解最大迭代数','1');let generated=page.waitForResponse(r=>r.url().endsWith('/api/dtm/grid'));await page.getByRole('button',{name:'生成地形成果',exact:true}).click();const candidate=await(await generated).json();expect(candidate.metadata.converged).toBe(false);await expect(page.locator('.terrain-not-converged')).toBeVisible();await expect(page.getByRole('button',{name:'添加等深线到地图',exact:true})).toBeDisabled();
  await number(page,'求解最大迭代数','2000');await page.getByLabel('DTM 裁剪边界格式',{exact:true}).selectOption('geojson');await page.getByLabel('DTM 裁剪边界',{exact:true}).fill(JSON.stringify({type:'Polygon',coordinates:[[[117.999,21.999],[118.005,21.999],[118.005,22.005],[117.999,22.005],[117.999,21.999]]]}));generated=page.waitForResponse(r=>r.url().endsWith('/api/dtm/grid'));await page.getByRole('button',{name:'生成地形成果',exact:true}).click();const grid=await(await generated).json();expect(grid.metadata.converged).toBe(true);expect(grid.metadata.boundary.source_kind).toBe('geojson');await page.getByLabel('切片参考线格式',{exact:true}).selectOption('bln');await page.getByLabel('DTM 切片参考线',{exact:true}).fill('2,1,"reference"\n118.001,22.001\n118.003,22.003');const sampled=page.waitForResponse(r=>r.url().endsWith('/api/dtm/slice'));await page.getByRole('button',{name:'提取实际切片',exact:true}).click();const slice=await(await sampled).json();expect(slice.summary.complete).toBe(true);expect(slice.summary.bottom_length_m).toBeGreaterThan(slice.summary.horizontal_length_m);expect(slice.metadata.line_source_crs).toBe('EPSG:4326');await expect(page.locator('.terrain-slice-table tr.invalid')).toHaveCount(0);
});

test('malformed CSV quoting cannot silently become accepted even under explicit skip',async({page})=>{
  await imports(page);await page.getByLabel('RPL 源记录',{exact:true}).fill('label,longitude,latitude,depth_m\nGood,118,22,30\n"Unclosed,118.01,22.01,40\nOther,118.02,22.02,50');await page.getByLabel('RPL 坏记录处理',{exact:true}).selectOption('skip');const actual=await parse(page);expect(actual.can_apply).toBe(false);expect(actual.errors.length).toBeGreaterThan(0);await expect(page.locator('.rpl-record-errors')).toBeVisible();await expect(page.getByRole('button',{name:'应用 RPL 导入',exact:true})).toBeDisabled();
});
