import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {resolve} from 'node:path';
import {apiURL} from './test-environment';
import {artifactPath} from './artifact-path';

// Chromium's intercepted multipart request omits File bytes. Keep the native browser
// upload intact, then hold the real fetch response before React receives it.
async function delayNativeImport(page:any){
 await page.evaluate(()=>{const scope=window as any;const original=window.fetch;let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);scope.__s57NativeGate={release,original};window.fetch=async(input,init)=>{const response=await original.call(window,input,init);const url=input instanceof Request?input.url:String(input);if(new URL(url,location.href).pathname==='/api/import/s57')await gate;return response}});
 return async()=>page.evaluate(()=>{const scope=window as any;const gate=scope.__s57NativeGate;window.fetch=gate.original;delete scope.__s57NativeGate;gate.release()});
}

const fixtures=resolve('../tests/fixtures/s57/noaa');
const cellJ='ENC_ROOT/US5A1KMJ/US5A1KMJ.000',cellK='ENC_ROOT/US5A1KMK/US5A1KMK.000';
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:20000})}
async function dismiss(page:any){const button=page.getByRole('button',{name:'关闭提示',exact:true});if(await button.count())await button.click()}
async function action(page:any,endpoint:string,label:string){const result=page.waitForResponse((r:any)=>r.url().endsWith('/api/'+endpoint)&&r.request().method()==='POST');await page.getByRole('button',{name:label,exact:true}).click();return result}
async function importTab(page:any,file:any){await page.getByRole('button',{name:'导入数据',exact:true}).click();await page.getByRole('button',{name:'S-57海图',exact:true}).click();await page.getByLabel('S-57 原生海图文件',{exact:true}).setInputFiles(file);const response=await action(page,'import/s57/inspect','读取海图文件目录');expect(response.status()).toBe(200);return response.json()}
async function catalog(page:any,paths:string[]){for(const path of paths)await page.getByLabel('选择海图单元 '+path,{exact:true}).check();const response=await action(page,'import/s57/catalog','读取所选单元对象类目录');expect(response.status()).toBe(200);return response.json()}
async function preview(page:any,classes:string[]){for(const name of classes)await page.getByLabel('选择 S-57 对象类 '+name,{exact:true}).check();const response=await action(page,'import/s57','预览所选海图图层');expect(response.status()).toBe(200);await expect(page.locator('.s57-bundle-preview')).toBeVisible();return response.json()}
function nativeZip(mode:'both'|'gap'){const python=resolve('..',process.platform==='win32'?'.venv/Scripts/python.exe':'.venv/bin/python');return execFileSync(python,['-c',"import io,sys,zipfile,pathlib\nout=io.BytesIO()\nwith zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED) as target:\n for i,name in enumerate(sys.argv[3:]):\n  with zipfile.ZipFile(pathlib.Path(sys.argv[1])/name) as original:\n   for item in original.infolist():\n    ext=pathlib.PurePosixPath(item.filename).suffix\n    if ext in (('.000','.002') if sys.argv[2]=='gap' else ('.000','.001','.002')):target.writestr(item.filename,original.read(item))\nsys.stdout.buffer.write(out.getvalue())",fixtures,mode,...(mode==='both'?['US5A1KMJ.zip','US5A1KMK.zip']:['US5A1KMJ.zip'])],{maxBuffer:2*1024*1024})}
function coordinatePositions(g:any):number[][]{if(!g)return [];if(g.type==='FeatureCollection')return g.features.flatMap((f:any)=>coordinatePositions(f.geometry));if(g.type==='GeometryCollection')return g.geometries.flatMap(coordinatePositions);const found:number[][]=[];const visit=(value:any)=>{if(Array.isArray(value)&&typeof value[0]==='number')found.push(value);else if(Array.isArray(value))value.forEach(visit)};visit(g.coordinates);return found}
async function savedWorkspace(page:any,request:any,multiple=false){const sample=await(await request.get(apiURL+'/sample')).json();let result=await(await request.post(apiURL+'/workspace/migrate',{data:{project:sample}})).json();if(multiple)result=await(await request.post(apiURL+'/workspace/action',{data:{workspace:result.workspace,config:{action:'copy_path',path_id:result.workspace.active_path_id,name:'海图共享备选',assembly_policy:'alternative'}}})).json();result.workspace.name='S57 native UI '+Date.now();result.workspace.s57_extension_guard={unknown_nested:{keep:['inventory','datum',0]}};const stored=await(await request.post(apiURL+'/workspaces',{data:result.workspace})).json();await page.goto('/');await ready(page);await page.getByRole('button',{name:'打开',exact:true}).click();await page.getByRole('button').filter({has:page.getByText(stored.workspace.name,{exact:true})}).click();await ready(page);return stored.workspace}

test('native binary S57 catalog and chosen classes apply atomically to shared workspace and preserve Z, inventory and revisions',async({page,request})=>{
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const before=await savedWorkspace(page,request,true),originalLayers=before.layers.length;
 const directory=await importTab(page,resolve(fixtures,'US5A1KMJ/US5A1KMJ.000'));expect(directory.stage).toBe('inspect');expect(directory.reader.native).toBe(false);expect(directory.classes_catalog).toEqual([]);await expect(page.getByRole('button',{name:'读取所选单元对象类目录',exact:true})).toBeDisabled();
 const native=await catalog(page,['US5A1KMJ.000']);expect(native.reader.driver).toBe('S57');expect(native.reader.process_isolated).toBe(true);expect(native.cells[0].datum_units.horizontal_datum_code).toBe(2);expect(native.classes_catalog.find((c:any)=>c.name==='SOUNDG').feature_count).toBe(4);await expect(page.getByRole('button',{name:'预览所选海图图层',exact:true})).toBeDisabled();
 const bundle=await preview(page,['DEPARE','SOUNDG']);expect(bundle.source.sha256).toBe(directory.source.sha256);expect(bundle.layers).toHaveLength(2);expect(bundle.layers.every((l:any)=>l.kind==='reference')).toBe(true);const soundings=bundle.layers.find((l:any)=>l.source.object_class==='SOUNDG'),positions=coordinatePositions(soundings.geojson);expect(positions).toHaveLength(657);expect(positions.every(p=>p.length===3&&Number.isFinite(p[2]))).toBe(true);expect(soundings.source.depth_is_engineering_water_depth).toBe(false);await expect(page.locator('.s57-sounding-notice')).toContainText('不会未经声明采纳到工程测深');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载完整海图解析结果',exact:true}).click();const downloaded=JSON.parse(await readFile((await(await download).path())!,'utf8'));expect(downloaded).toEqual(bundle);await page.setViewportSize({width:1800,height:1400});await dismiss(page);await page.locator('.s57-bundle-preview').scrollIntoViewIfNeeded();await page.screenshot({path:artifactPath('s57-native-binary-depth-area-preview.png'),fullPage:true});await page.getByLabel('S-57 预览图层',{exact:true}).selectOption(String(bundle.layers.findIndex((l:any)=>l.source.object_class==='SOUNDG')));await expect(page.locator('.s57-chart-preview svg')).toBeVisible();await page.screenshot({path:artifactPath('s57-native-binary-sounding-preview.png'),fullPage:true});
 const appliedResponse=page.waitForResponse(r=>r.url().endsWith('/api/workspace/action')&&r.request().postDataJSON()?.config?.action==='update_shared');await page.getByRole('button',{name:'应用全部所选海图图层',exact:true}).click();const applied=await(await appliedResponse).json();await expect(page.getByRole('dialog')).not.toBeVisible();await ready(page);expect(applied.workspace.layers.length).toBe(originalLayers+2);expect(applied.workspace.paths).toEqual(before.paths);expect(applied.workspace.cable_types).toEqual(before.cable_types);expect(applied.workspace.assemblies).toEqual(before.assemblies);expect(applied.workspace.associations).toEqual(before.associations);expect(applied.workspace.terrain_sources).toEqual(before.terrain_sources);expect(applied.workspace.s57_extension_guard).toEqual(before.s57_extension_guard);expect(applied.workspace.saved_revision).toBe(before.saved_revision);await expect(page.locator('.layer-row')).toHaveCount(originalLayers+2);
 await page.getByRole('button',{name:'撤销 ⌘Z',exact:true}).click();await ready(page);await expect(page.locator('.layer-row')).toHaveCount(originalLayers);await page.getByRole('button',{name:'重做 ⌘⇧Z',exact:true}).click();await ready(page);await expect(page.locator('.layer-row')).toHaveCount(originalLayers+2);await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText('工程已保存 · 修订 2',{exact:true})).toBeVisible();const stored=await(await request.get(apiURL+'/workspaces/'+before.id)).json();expect(stored.layers.slice(-2)).toEqual(bundle.layers);expect(stored.paths).toEqual(before.paths);expect(stored.assemblies).toEqual(before.assemblies);
 await page.getByRole('button',{name:'打开',exact:true}).click();await page.getByRole('button').filter({has:page.getByText(before.name,{exact:true})}).click();await ready(page);await expect(page.locator('.layer-row')).toHaveCount(originalLayers+2);await page.getByRole('button',{name:'修订历史',exact:true}).click();const restoredResponse=page.waitForResponse(r=>r.url().endsWith('/api/workspaces/'+before.id+'/restore/1')&&r.request().method()==='POST');await page.getByRole('button').filter({has:page.getByText('修订 1 · '+before.name,{exact:true})}).click();const restoration=await restoredResponse;expect(restoration.status()).toBe(200);const restoredData=await restoration.json();expect(restoredData.saved_revision).toBe(3);await expect(page.locator('.document-loading-overlay')).not.toBeVisible();await expect(page.getByRole('dialog')).not.toBeVisible();await ready(page);const restored=await(await request.get(apiURL+'/workspaces/'+before.id)).json();expect(restored.saved_revision).toBe(3);expect(restored.layers).toEqual(before.layers);expect(restored.assemblies).toEqual(before.assemblies);expect(errors).toEqual([]);
});

test('real two-cell ZIP requires explicit cells/classes and previews actually applied updates and chart datum without field adoption',async({page,request})=>{
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await savedWorkspace(page,request);const directory=await importTab(page,{name:'noaa-two-native-cells.zip',mimeType:'application/zip',buffer:nativeZip('both')});expect(directory.cells).toHaveLength(2);expect(directory.cells.every((c:any)=>c.updates.map((u:any)=>u.number).join(',')==='1,2')).toBe(true);await expect(page.locator('.s57-directory input[type=checkbox]:checked')).toHaveCount(0);const one=await catalog(page,[cellJ]);expect(one.cells).toHaveLength(1);expect(one.cells[0].applied_update_number).toBe(2);
 await page.getByLabel('选择海图单元 '+cellK,{exact:true}).check();await expect(page.locator('.s57-catalog')).not.toBeVisible();const bothResponse=await action(page,'import/s57/catalog','读取所选单元对象类目录');expect(bothResponse.status()).toBe(200);const both=await bothResponse.json();expect(both.cells).toHaveLength(2);expect(both.classes_catalog.find((c:any)=>c.name==='SOUNDG').feature_count).toBe(6);await page.setViewportSize({width:1800,height:1400});await dismiss(page);await page.locator('.s57-catalog').scrollIntoViewIfNeeded();await page.screenshot({path:artifactPath('s57-multi-cell-native-class-directory.png'),fullPage:true});
 await page.getByLabel('S-57 图层名称前缀',{exact:true}).fill('<img src=x onerror="window.s57Bad=1">');const bundle=await preview(page,['SOUNDG']);expect(bundle.layers).toHaveLength(2);expect(bundle.summary.update_files_applied).toBe(4);expect(bundle.cells.every((c:any)=>c.dsid.DSID_UPDN==='2'&&c.datum_units.units_converted===false)).toBe(true);expect(bundle.layers.reduce((n:number,l:any)=>n+coordinatePositions(l.geojson).length,0)).toBe(2003);expect(bundle.layers.every((l:any)=>l.source.depth_is_engineering_water_depth===false)).toBe(true);await expect(page.locator('.s57-output-layers')).toContainText('<img src=x onerror="window.s57Bad=1">');expect(await page.evaluate(()=>Object.prototype.hasOwnProperty.call(window,'s57Bad'))).toBe(false);await page.getByLabel('选择 S-57 对象类 SOUNDG',{exact:true}).uncheck();await expect(page.locator('.s57-bundle-preview')).not.toBeVisible();await expect(page.getByRole('button',{name:'应用全部所选海图图层',exact:true})).toBeDisabled();expect(errors).toEqual([]);
});

test('late native success, native budgets and discontinuous updates never apply stale or partial S57 layers',async({page,request})=>{
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const before=await savedWorkspace(page,request);const directory=await importTab(page,resolve(fixtures,'US5A1KMJ.zip'));await catalog(page,[cellJ]);await preview(page,['SOUNDG']);await page.getByLabel('S-57 图层名称前缀',{exact:true}).fill('changed-name');await expect(page.locator('.s57-bundle-preview')).not.toBeVisible();await expect(page.getByRole('button',{name:'下载完整海图解析结果',exact:true})).not.toBeVisible();
 const releaseNative=await delayNativeImport(page),nativeResponse=page.waitForResponse(r=>r.url().endsWith('/api/import/s57')&&r.request().method()==='POST');await page.getByRole('button',{name:'预览所选海图图层',exact:true}).click();const actual=await nativeResponse;expect(actual.status(),await actual.text()).toBe(200);expect((await actual.json()).source.sha256).toBe(directory.source.sha256);await page.getByLabel('S-57 图层名称前缀',{exact:true}).fill('later-name');await releaseNative();await expect(page.locator('.s57-error')).toContainText('迟到');await expect(page.locator('.s57-bundle-preview')).not.toBeVisible();await expect(page.getByRole('button',{name:'应用全部所选海图图层',exact:true})).toBeDisabled();
 await page.locator('.s57-budget>summary').click();await page.getByLabel('S-57 读取工作量上限',{exact:true}).fill('1');const budget=await action(page,'import/s57/catalog','读取所选单元对象类目录');expect(budget.status()).toBe(422);await expect(page.locator('.s57-error')).toContainText('max_work_units');await expect(page.locator('.s57-chart-preview')).not.toBeVisible();await expect(page.getByRole('button',{name:'应用全部所选海图图层',exact:true})).toBeDisabled();await dismiss(page);await page.screenshot({path:artifactPath('s57-native-budget-failure-no-stale-layer.png'),fullPage:true});
 await page.getByLabel('S-57 读取工作量上限',{exact:true}).fill('');await page.getByLabel('S-57 原生海图文件',{exact:true}).setInputFiles({name:'native-missing-update.zip',mimeType:'application/zip',buffer:nativeZip('gap')});const inspected=await action(page,'import/s57/inspect','读取海图文件目录');if(inspected.status()===200){await page.getByLabel('选择海图单元 '+cellJ,{exact:true}).check();const gap=await action(page,'import/s57/catalog','读取所选单元对象类目录');expect(gap.status()).toBe(422)}else expect(inspected.status()).toBe(422);await expect(page.locator('.s57-error')).toContainText(/update|consecutive|sequence/i);await expect(page.getByRole('button',{name:'应用全部所选海图图层',exact:true})).toBeDisabled();await page.getByRole('button',{name:'取消',exact:true}).click();await ready(page);await expect(page.locator('.layer-row')).toHaveCount(before.layers.length);const stored=await(await request.get(apiURL+'/workspaces/'+before.id)).json();expect(stored).toEqual(before);expect(errors).toEqual([]);
});

test('an empty workspace imports native reference charts, saves and undoes without fabricating a route or losing orphan inventory',async({page,request})=>{
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const sample=await(await request.get(apiURL+'/sample')).json();const migrated=await(await request.post(apiURL+'/workspace/migrate',{data:{project:sample}})).json();const removed=await(await request.post(apiURL+'/workspace/action',{data:{workspace:migrated.workspace,config:{action:'remove_path',path_id:migrated.workspace.active_path_id,delete_orphan_assembly:false}}})).json();removed.workspace.name='S57 empty orphan UI '+Date.now();removed.workspace.s57_extension_guard={orphan_inventory:'explicit retained',number:37};const before=(await(await request.post(apiURL+'/workspaces',{data:removed.workspace})).json()).workspace;expect(before.paths).toEqual([]);expect(before.assemblies.length).toBeGreaterThan(0);
 await page.goto('/');await ready(page);await page.getByRole('button',{name:'打开',exact:true}).click();await page.getByRole('button').filter({has:page.getByText(before.name,{exact:true})}).click();await expect(page.locator('.empty-workspace')).toBeVisible();await page.getByRole('button',{name:'导入S-57海图',exact:true}).click();await page.getByLabel('S-57 原生海图文件',{exact:true}).setInputFiles(resolve(fixtures,'US5A1KMJ/US5A1KMJ.000'));expect((await action(page,'import/s57/inspect','读取海图文件目录')).status()).toBe(200);await catalog(page,['US5A1KMJ.000']);const bundle=await preview(page,['SOUNDG']);const apply=page.waitForResponse(r=>r.url().endsWith('/api/workspace/action')&&r.request().postDataJSON()?.config?.action==='update_shared');await page.getByRole('button',{name:'应用全部所选海图图层',exact:true}).click();const applied=await(await apply).json();await expect(page.getByRole('dialog')).not.toBeVisible();expect(applied.project).toBeNull();expect(applied.workspace.paths).toEqual([]);expect(applied.workspace.active_path_id).toBeNull();expect(applied.workspace.assemblies).toEqual(before.assemblies);expect(applied.workspace.cable_types).toEqual(before.cable_types);expect(applied.workspace.associations).toEqual(before.associations);expect(applied.workspace.s57_extension_guard).toEqual(before.s57_extension_guard);await expect(page.locator('.empty-resource').filter({has:page.getByText(bundle.layers[0].name,{exact:true})})).toBeVisible();
 await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText('工程已保存 · 修订 2',{exact:true})).toBeVisible();await page.getByRole('button',{name:'撤销 ⌘Z',exact:true}).click();await expect(page.locator('.empty-resource').filter({has:page.getByText(bundle.layers[0].name,{exact:true})})).not.toBeVisible();await page.getByRole('button',{name:'重做 ⌘⇧Z',exact:true}).click();await expect(page.locator('.empty-resource').filter({has:page.getByText(bundle.layers[0].name,{exact:true})})).toBeVisible();await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText('工程已保存 · 修订 3',{exact:true})).toBeVisible();const stored=await(await request.get(apiURL+'/workspaces/'+before.id)).json();expect(stored.paths).toEqual([]);expect(stored.assemblies).toEqual(before.assemblies);expect(stored.layers.at(-1)).toEqual(bundle.layers[0]);const exportedFile=page.waitForEvent('download');await page.getByRole('button',{name:'导出完整工作区',exact:true}).click();const exported=JSON.parse(await readFile((await(await exportedFile).path())!,'utf8'));expect(exported).toEqual(stored);await page.setViewportSize({width:1800,height:1400});await dismiss(page);await page.screenshot({path:artifactPath('s57-empty-workspace-retained-inventory.png'),fullPage:true});
 await page.getByRole('button',{name:'导入S-57海图',exact:true}).click();await page.getByLabel('S-57 原生海图文件',{exact:true}).setInputFiles(resolve(fixtures,'US5A1KMJ/US5A1KMJ.000'));const inspection=await action(page,'import/s57/inspect','读取海图文件目录');expect(inspection.status()).toBe(200);const directory=await inspection.json();await catalog(page,['US5A1KMJ.000']);await page.getByLabel('选择 S-57 对象类 DEPARE',{exact:true}).check();const releaseNative=await delayNativeImport(page),nativeResponse=page.waitForResponse(r=>r.url().endsWith('/api/import/s57')&&r.request().method()==='POST');await page.getByRole('button',{name:'预览所选海图图层',exact:true}).click();const actual=await nativeResponse;expect(actual.status(),await actual.text()).toBe(200);expect((await actual.json()).source.sha256).toBe(directory.source.sha256);await page.locator('.s57-import-panel h3').first().click();await page.keyboard.press(process.platform==='darwin'?'Meta+z':'Control+z');await releaseNative();await expect(page.locator('.s57-error')).toContainText('迟到');await expect(page.locator('.s57-bundle-preview')).not.toBeVisible();await expect(page.getByRole('button',{name:'应用全部所选海图图层',exact:true})).toBeDisabled();await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText('工程已保存 · 修订 4',{exact:true})).toBeVisible();const final=await(await request.get(apiURL+'/workspaces/'+before.id)).json();expect(final.paths).toEqual([]);expect(final.active_path_id).toBeNull();expect(final.layers).toEqual(before.layers);expect(final.assemblies).toEqual(before.assemblies);expect(final.s57_extension_guard).toEqual(before.s57_extension_guard);expect(errors).toEqual([]);
});
