import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:25000})}
async function open(page:any){await page.goto('/');await ready(page);await page.getByRole('button',{name:'敷设仿真',exact:true}).click();await page.getByRole('button',{name:'应答器 / 海流估计',exact:true}).click()}
test('transponder forward positions and accepted current estimates render actual geometry and covariance',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await open(page);
  const predicted=page.waitForResponse(r=>r.url().endsWith('/api/seismic/predict'));await page.getByRole('button',{name:'运行应答器研究',exact:true}).click();const truth=await(await predicted).json();expect(truth.snapshots[0].nodes).toHaveLength(128);expect(truth.snapshots[0].observations[0].predicted_position_m[0]).toBeCloseTo(-15.0418,3);await expect(page.locator('.seismic-observation-table tbody tr')).toHaveCount(3);await expect(page.locator('.scene-host canvas')).toBeVisible();
  await page.getByRole('button',{name:'由当前预测生成明确合成观测',exact:true}).click();await expect(page.getByText('无噪声合成研究',{exact:true})).toBeVisible();
  const estimated=page.waitForResponse(r=>r.url().endsWith('/api/seismic/estimate'));await page.getByRole('button',{name:'运行应答器研究',exact:true}).click();const response=await estimated;const fit=await response.json();expect(response.request().postDataJSON().config.current_m_s).toBeUndefined();expect(fit.summary.estimate_accepted).toBe(true);expect(fit.estimated_current_m_s[0]).toBeCloseTo(.25,5);expect(fit.estimated_current_m_s[1]).toBeCloseTo(.2,5);expect(fit.identifiability.rank).toBe(2);expect(fit.parameter_covariance_m2_s2).not.toBeNull();await expect(page.locator('.seismic-acceptance')).toContainText('估计已接受');await expect(page.locator('.seismic-matrix').first().locator('tbody tr')).toHaveCount(2);await page.locator('.seismic-layout .sim-main').evaluate((e:HTMLElement)=>e.scrollTop=750);if(await page.getByRole('button',{name:'关闭提示',exact:true}).isVisible())await page.getByRole('button',{name:'关闭提示',exact:true}).click();await page.locator('.seismic-layout .sim-settings').evaluate((e:HTMLElement)=>e.scrollTop=0);await page.screenshot({path:'artifacts/seismic-current-estimate.png',fullPage:true});await page.locator('.seismic-layout .sim-main').evaluate((e:HTMLElement)=>e.scrollTop=0);await page.screenshot({path:'artifacts/seismic-diagnostics.png',fullPage:true});const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'下载实际结果',exact:true}).click();const file=await downloaded;const result=JSON.parse(await readFile((await file.path())!,'utf8'));expect(result.ui_input_provenance.observation_source).toBe('synthetic_forward_model_no_noise');expect(result.summary.estimate_accepted).toBe(true);expect(errors).toEqual([]);
});
test('one measured component is not represented as an accepted two-component current or valid covariance',async({page})=>{
  await open(page);const p=page.waitForResponse(r=>r.url().endsWith('/api/seismic/predict'));await page.getByRole('button',{name:'运行应答器研究',exact:true}).click();const truth=await(await p).json();await page.locator('.seismic-layout .solver-tabs button').filter({has:page.getByText('水平海流估计',{exact:true})}).click();await page.getByLabel('独立稳态记录与应答器 JSON',{exact:true}).fill(JSON.stringify([{id:'partial',time_s:0,vessel_position_m:[0,0,0],ship_speed_m_s:1,heading_deg:90,observations:[{id:'only-x',arc_from_vessel_m:20,position_m:[truth.snapshots[0].observations[0].predicted_position_m[0],null,null],sigma_m:[.25,.25,.25]}]}]));const estimated=page.waitForResponse(r=>r.url().endsWith('/api/seismic/estimate'));await page.getByRole('button',{name:'运行应答器研究',exact:true}).click();const fit=await(await estimated).json();expect(fit.summary.estimate_accepted).toBe(false);expect(fit.identifiability.rank).toBeLessThan(2);expect(fit.parameter_covariance_m2_s2).toBeNull();await expect(page.locator('.seismic-acceptance')).toContainText('未接受候选');await expect(page.locator('.seismic-matrix').first()).toContainText('没有已接受的协方差');await expect(page.locator('.seismic-observation-table tbody tr')).toHaveCount(1);await expect(page.locator('.seismic-layout .inline-warning').filter({hasText:'CURRENT_NOT_IDENTIFIABLE'})).toBeVisible();
});
