import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {apiURL} from './test-environment';
import {artifactPath} from './artifact-path';

const local='+proj=aeqd +lat_0=0 +lon_0=0 +datum=WGS84 +units=m +type=crs';
async function json(request:any,path:string,data?:any){const r=data===undefined?await request.get(apiURL+path):await request.post(apiURL+path,{data});expect(r.ok(),await r.text()).toBe(true);return r.json()}
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:20000})}
async function dismiss(page:any){const b=page.getByRole('button',{name:'关闭提示',exact:true});if(await b.count())await b.click()}
async function shot(page:any,name:string,target?:string){await ready(page);await dismiss(page);await page.setViewportSize({width:1800,height:1250});if(target)await page.locator(target).first().scrollIntoViewIfNeeded();await page.screenshot({path:artifactPath(name+'.png'),fullPage:true})}
function raster(field:(x:number,y:number)=>number,nodes=3,method='linear'){
 const extent=1000,xy=Array.from({length:nodes},(_,i)=>-extent+i*2*extent/(nodes-1)),text=`DSAA\n${nodes} ${nodes}\n-${extent} ${extent}\n-${extent} ${extent}\n0 100000\n`+xy.map(y=>xy.map(x=>field(x,y)).join(' ')).join('\n')+'\n';
 return {id:'explicit-ui-terrain',name:'明确合成横坡输入 · 非实测',kind:'surfer',enabled:true,priority:100,source_crs:local,depth_positive:'down',depth_units:'m',vertical_datum:'SYNTHETIC_UI_DATUM',data_base64:Buffer.from(text).toString('base64'),sampling:{method}};
}
async function fixture(request:any,source?:any,alternative=false){
 const p=await json(request,'/sample');p.name='SideSlope '+Date.now();p.bodies=[];p.events=[];p.layers=[];p.terrain_sources=[];p.profile={samples:[],source:'declared-waypoint-depths'};p.route={...p.route,name:'明确合成北向路线',curve:'geodesic',slack_basis:'surface',mode:'flexible',points:[{id:'north-a',label:'Start',longitude:0,latitude:-.0027,depth_m:1000,note:'合成坐标与输入'},{id:'north-b',label:'End',longitude:0,latitude:.0027,depth_m:1000,note:'合成坐标与输入'}],legs:[{...p.route.legs[0],cable_type_id:p.cable_types[0].id,mode:'flexible',slack_basis:'surface',slack_pct:2,fixed_cable_length_m:null,burial:false}],custom_route_extension:{keep:true}};p.custom_side_slope_extension={nested:['user-data',0,null]};
 if(source)p.terrain_sources=[source];else p.terrain_sources=(await json(request,'/terrain/side-slopes/example',{project:p})).sources;
 const sampled=await json(request,'/terrain/profile',{project:p,config:{spacing_m:100}});let migrated=await json(request,'/workspace/migrate',{project:sampled.project});
 if(alternative)migrated=await json(request,'/workspace/action',{workspace:migrated.workspace,config:{action:'copy_path',path_id:migrated.workspace.active_path_id,name:'相同库存备选',assembly_policy:'alternative'}});
 migrated.workspace.name=p.name;migrated.workspace.custom_workspace_extension={retain:{inventory:true,values:[0,null,'x']}};return (await json(request,'/workspaces',migrated.workspace)).workspace;
}
async function open(page:any,w:any,configure=true){await page.goto('/');await ready(page);await page.getByRole('button',{name:'打开',exact:true}).click();await page.locator('.project-list button').filter({has:page.getByText(w.name,{exact:true})}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await ready(page);await page.getByRole('button',{name:'工程工具',exact:true}).click();await page.locator('.engineering-menu button').filter({has:page.getByText('侧坡与坡度规则',{exact:true})}).click();await expect(page.locator('.side-slopes-panel')).toBeVisible();if(configure)await page.getByLabel('沿线最大站距 / m',{exact:true}).fill('100')}
async function preview(page:any){const r=page.waitForResponse((r:any)=>r.url().endsWith('/api/terrain/side-slopes')&&r.request().method()==='POST');await page.getByRole('button',{name:'计算真实侧坡预览',exact:true}).click();const response=await r;expect(response.ok(),await response.text()).toBe(true);await expect(page.locator('.ss-results')).toBeVisible();return response.json()}
async function apply(page:any,label='应用侧坡记录'){const r=page.waitForResponse((r:any)=>r.url().endsWith('/api/workspace/action')&&r.request().postDataJSON()?.config?.action==='update_path');await page.getByRole('button',{name:label,exact:true}).click();const response=await r;expect(response.ok(),await response.text()).toBe(true);if(label==='应用侧坡记录')await expect(page.locator('.ss-results h3').first()).toContainText('已应用沿 KP 侧坡');else await expect(page.locator('.ss-rule-results')).not.toBeVisible();await ready(page);return response.json()}
async function save(page:any,revision:number){const r=page.waitForResponse((r:any)=>r.url().endsWith('/api/workspaces')&&r.request().method()==='POST');await page.getByRole('button',{name:'保存',exact:true}).click();const response=await r;expect(response.ok(),await response.text()).toBe(true);await expect(page.getByText('工程已保存 · 修订 '+revision,{exact:true})).toBeVisible();return response.json()}
async function addRule(page:any,limit:number,name:string){await page.getByRole('button',{name:'KP 坡度规则',exact:true}).click();await page.getByRole('button',{name:'新增坡度规则',exact:true}).click();await page.getByLabel('坡度规则 1 名称',{exact:true}).fill(name);await page.getByLabel('坡度规则 1 方向',{exact:true}).selectOption('side');await page.getByLabel('坡度规则 1 最大侧坡 / °',{exact:true}).fill(String(limit))}
async function checks(page:any){const r=page.waitForResponse((r:any)=>r.url().endsWith('/api/tools/slope-rules'));await page.getByRole('button',{name:'检查 KP 坡度规则',exact:true}).click();const response=await r;expect(response.ok(),await response.text()).toBe(true);await expect(page.locator('.ss-rule-results')).toBeVisible();return response.json()}

test('real transverse slopes apply once, survive shared-workspace save/open and preserve inventory; rules and undo remain independent',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const before=await fixture(request,undefined,true);await open(page,before);const r=await preview(page);expect(r.model).toBe('route-side-slopes-v1');expect(r.side_slopes.samples.length).toBeGreaterThan(2);expect(r.side_slopes.samples.every((s:any)=>s.complete&&s.side_slope_deg>11&&s.side_slope_deg<12)).toBe(true);expect(r.side_slopes.metadata.offset_positive).toBe('starboard');expect(r.project.profile).toEqual(before.paths.find((p:any)=>p.id===before.active_path_id).project.profile);expect(await json(request,'/workspaces/'+before.id)).toEqual(before);
 const file=page.waitForEvent('download');await page.getByRole('button',{name:'下载当前侧坡 / 规则 JSON',exact:true}).click();expect(JSON.parse(await readFile((await(await file).path())!,'utf8'))).toEqual(r);await expect(page.getByRole('img',{name:'沿 KP 左右有符号侧坡曲线',exact:true})).toBeVisible();await expect(page.getByRole('img',{name:'选定 KP 真实横向水深截面',exact:true})).toBeVisible();await page.getByRole('button',{name:'下一侧坡站位',exact:true}).click();await expect(page.locator('.ss-transect-table tbody tr').last().locator('td').nth(4)).toHaveText('不适用');await shot(page,'side-slopes-real-cross-section-and-provenance','.ss-station-picker');await shot(page,'side-slopes-real-source-attempts','.ss-transect-table');
 const applied=await apply(page);expect(applied.workspace.assemblies).toEqual(before.assemblies);expect(applied.workspace.associations).toEqual(before.associations);expect(applied.workspace.custom_workspace_extension).toEqual(before.custom_workspace_extension);await save(page,2);const saved=await json(request,'/workspaces/'+before.id),active=saved.paths.find((p:any)=>p.id===saved.active_path_id);expect(active.project.side_slopes).toEqual(r.side_slopes);expect(active.project.custom_side_slope_extension).toEqual(before.paths.find((p:any)=>p.id===before.active_path_id).project.custom_side_slope_extension);expect(saved.assemblies).toEqual(before.assemblies);expect(saved.terrain_sources).toEqual(before.terrain_sources);
 await open(page,saved,false);await expect(page.locator('.ss-stored-record')).toContainText('绑定有效');await expect(page.getByRole('img',{name:'选定 KP 真实横向水深截面',exact:true})).toBeVisible();await addRule(page,10,'真实侧坡十度阈值');const report=await checks(page);expect(report.results[0].status).toBe('violations');expect(report.results[0].violations.length).toBe(r.side_slopes.samples.length);expect(report.summary.continuous_bed_verified).toBe(false);await expect(page.locator('.ss-rule-result .ss-rule-status.violations')).toBeVisible();const ruleApplied=await apply(page,'应用坡度规则列表');expect(ruleApplied.workspace.assemblies).toEqual(before.assemblies);await save(page,3);const withRules=await json(request,'/workspaces/'+before.id);expect(withRules.paths.find((p:any)=>p.id===withRules.active_path_id).project.slope_rules[0].max_side_slope_deg).toBe(10);
 await page.getByRole('button',{name:'撤销 ⌘Z',exact:true}).click();await ready(page);await save(page,4);const undone=await json(request,'/workspaces/'+before.id);expect(undone.paths.find((p:any)=>p.id===undone.active_path_id).project.slope_rules).toBeUndefined();expect(undone.paths.find((p:any)=>p.id===undone.active_path_id).project.side_slopes).toEqual(r.side_slopes);expect(undone.assemblies).toEqual(before.assemblies);expect(errors).toEqual([]);
});

test('a V-shaped cross section cannot pass by averaging and genuine NoData remains null with incomplete rather than green rules',async({page,request})=>{
 const ridge=await fixture(request,raster(x=>1000-.1*Math.abs(x)));await open(page,ridge);const v=await preview(page);expect(v.side_slopes.samples.every((s:any)=>Math.abs(s.side_slope_deg)<.001&&s.max_sampled_abs_slope_deg>5.7&&s.port_slope_deg<0&&s.starboard_slope_deg>0)).toBe(true);await shot(page,'side-slopes-v-shaped-real-cross-section','.ss-station-info');await apply(page);await addRule(page,4,'V形不允许平均掩盖');const violated=await checks(page);expect(violated.results[0].status).toBe('violations');expect(violated.results[0].violations.every((s:any)=>s.value_deg>5.7)).toBe(true);await shot(page,'side-slopes-v-shaped-real-rule-violations','.ss-rule-results');
 const nodata=await fixture(request,raster(x=>x===-50?1.70141e38:1000+.2*x,41,'nearest'));await open(page,nodata);const missing=await preview(page);expect(missing.quality.complete).toBe(false);expect(missing.side_slopes.samples.every((s:any)=>s.port_slope_deg===null&&s.side_slope_deg===null&&s.starboard_slope_deg<-11&&s.max_sampled_abs_slope_deg>11)).toBe(true);expect(missing.side_slopes.samples[0].transect[1].depth_m).toBeNull();await expect(page.locator('.ss-transect-table .ss-nodata')).toHaveCount(1);expect(await page.locator('.side-slopes-chart .ss-port').count()).toBe(0);await expect(page.locator('.side-slopes-chart .ss-missing')).toHaveCount(1);await shot(page,'side-slopes-real-nodata-cross-section','.ss-transect-table');await apply(page);await addRule(page,89,'缺测不能判安全');const unknown=await checks(page);expect(unknown.results[0].status).toBe('incomplete');expect(unknown.results[0].components.side.coverage.complete).toBe(false);expect(unknown.results[0].components.side.coverage.missing_kps_m.length).toBeGreaterThan(0);expect(unknown.summary.all_requested_data_available).toBe(false);await expect(page.locator('.ss-rule-status.sampled_pass')).toHaveCount(0);await shot(page,'side-slopes-nodata-incomplete-rule','.ss-rule-results');
 await page.getByLabel('启用坡度规则 1',{exact:true}).uncheck();await expect(page.locator('.ss-stale')).toBeVisible();await expect(page.getByRole('button',{name:'下载当前侧坡 / 规则 JSON',exact:true})).toBeDisabled();const disabled=await checks(page);expect(disabled.summary.status).toBe('disabled');expect(disabled.results[0].status).toBe('disabled');await page.getByRole('button',{name:'删除坡度规则 1',exact:true}).click();const empty=await checks(page);expect(empty.summary.status).toBe('not_configured');expect(empty.results).toEqual([]);
});

test('held real responses, parameter or revision changes and real budget failures never permit stale cross-section export or application',async({page,request})=>{
 const w=await fixture(request);await open(page,w);let release!:()=>void,arrived!:(r:any)=>void;const gate=new Promise<void>(resolve=>release=resolve),seen=new Promise<any>(resolve=>arrived=resolve);await page.route('**/api/terrain/side-slopes',async route=>{const actual=await route.fetch();arrived(actual);await gate;await route.fulfill({response:actual})});await page.getByRole('button',{name:'计算真实侧坡预览',exact:true}).click();const response=await seen;expect(response.status(),await response.text()).toBe(200);await page.getByLabel('左右半幅宽度 / m',{exact:true}).fill('120');release();await expect(page.locator('.ss-stale')).toContainText('迟到结果已丢弃');await expect(page.getByRole('img',{name:'选定 KP 真实横向水深截面',exact:true})).not.toBeVisible();await expect(page.getByRole('button',{name:'应用侧坡记录',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'下载当前侧坡 / 规则 JSON',exact:true})).toBeDisabled();await page.unroute('**/api/terrain/side-slopes');
 await preview(page);await save(page,2);await expect(page.locator('.ss-stale')).toContainText('完整工作区已改变');await expect(page.getByRole('button',{name:'下载当前侧坡 / 规则 JSON',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'应用侧坡记录',exact:true})).toBeDisabled();expect((await json(request,'/workspaces/'+w.id)).paths[0].project.side_slopes).toBeUndefined();
 await page.locator('.ss-budget summary').first().click();await page.getByLabel('侧坡逻辑工作量上限',{exact:true}).fill('1');const budget=page.waitForResponse(r=>r.url().endsWith('/api/terrain/side-slopes'));await page.getByRole('button',{name:'计算真实侧坡预览',exact:true}).click();expect((await budget).status()).toBe(422);await expect(page.locator('.ss-error')).toContainText('work');await expect(page.getByRole('img',{name:'沿 KP 左右有符号侧坡曲线',exact:true})).not.toBeVisible();await expect(page.getByRole('button',{name:'下载当前侧坡 / 规则 JSON',exact:true})).toBeDisabled();await shot(page,'side-slopes-real-budget-error-no-old-chart','.ss-error');
});

test('a real atomic apply response cannot commit after tool parameters change or its panel is unmounted',async({page,request})=>{
 const w=await fixture(request);await open(page,w);
 async function holdApply(){let release!:()=>void,arrived!:(r:any)=>void;const gate=new Promise<void>(r=>release=r),seen=new Promise<any>(r=>arrived=r);await page.route('**/api/workspace/action',async route=>{const config=route.request().postDataJSON()?.config;if(config?.action!=='update_path'||!config?.project?.side_slopes){await route.continue();return}const actual=await route.fetch();arrived(actual);await gate;await route.fulfill({response:actual})});return {release,seen}}
 await preview(page);const first=await holdApply();await page.getByRole('button',{name:'应用侧坡记录',exact:true}).click();const native=await first.seen;expect(native.status(),await native.text()).toBe(200);expect((await native.json()).project.side_slopes.model).toBe('route-side-slopes-v1');await page.getByLabel('左右半幅宽度 / m',{exact:true}).fill('120');first.release();await expect(page.locator('.ss-error')).toContainText('候选未通过应用校验');await expect(page.locator('.ss-stale')).toBeVisible();await page.unroute('**/api/workspace/action');await save(page,2);const afterChanged=await json(request,'/workspaces/'+w.id);expect(afterChanged.paths[0].project.side_slopes).toBeUndefined();expect(afterChanged.terrain_sources).toEqual(w.terrain_sources);expect(afterChanged.assemblies).toEqual(w.assemblies);expect(afterChanged.custom_workspace_extension).toEqual(w.custom_workspace_extension);
 await preview(page);const second=await holdApply();await page.getByRole('button',{name:'应用侧坡记录',exact:true}).click();const actual=await second.seen;expect(actual.status(),await actual.text()).toBe(200);await page.locator('.engineering-menu button').filter({has:page.getByText('路线加密',{exact:true})}).click();await expect(page.locator('.side-slopes-panel')).not.toBeVisible();second.release();await expect(page.getByRole('button',{name:'保存',exact:true})).toBeEnabled();await page.unroute('**/api/workspace/action');await save(page,3);const afterUnmount=await json(request,'/workspaces/'+w.id);expect(afterUnmount.paths[0].project.side_slopes).toBeUndefined();expect(afterUnmount.assemblies).toEqual(w.assemblies);expect(afterUnmount.associations).toEqual(w.associations);expect(afterUnmount.terrain_sources).toEqual(w.terrain_sources);expect(afterUnmount.custom_workspace_extension).toEqual(w.custom_workspace_extension);
});

test('switching to a changed path while its genuine analysis response is held never treats previous-path metadata as current saved side slopes',async({page,request})=>{
 const original=await fixture(request),pathA=original.active_path_id;let output=await json(request,'/workspace/action',{workspace:original,config:{action:'set_active',path_id:pathA}});const sampled=await json(request,'/terrain/side-slopes',{project:output.project,config:{spacing_m:100,half_width_m:100,cross_spacing_m:50}});output=await json(request,'/workspace/action',{workspace:output.workspace,config:{action:'update_path',path_id:pathA,project:sampled.project,update_shared:true,assembly_policy:'auto_exclusive'}});output=await json(request,'/workspace/action',{workspace:output.workspace,config:{action:'copy_path',path_id:pathA,name:'已改变路线但保留历史侧坡',assembly_policy:'unassigned'}});const pathB=output.workspace.paths.find((p:any)=>p.id!==pathA).id;output=await json(request,'/workspace/action',{workspace:output.workspace,config:{action:'set_active',path_id:pathB}});const changed=structuredClone(output.project);changed.route.points[1].longitude+=.001;output=await json(request,'/workspace/action',{workspace:output.workspace,config:{action:'update_path',path_id:pathB,project:changed,update_shared:true,assembly_policy:'auto_exclusive'}});expect(output.analysis.active_path_analysis.side_slopes_metadata.geometry_current).toBe(false);output=await json(request,'/workspace/action',{workspace:output.workspace,config:{action:'set_active',path_id:pathA}});const stored=(await json(request,'/workspaces',output.workspace)).workspace;await open(page,stored,false);await expect(page.getByRole('img',{name:'选定 KP 真实横向水深截面',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'下载当前侧坡 / 规则 JSON',exact:true})).toBeEnabled();
 let release!:()=>void,arrived!:(r:any)=>void;const gate=new Promise<void>(r=>release=r),seen=new Promise<any>(r=>arrived=r);await page.route('**/api/analyze',async route=>{if(route.request().postDataJSON()?.id!==pathB){await route.continue();return}const actual=await route.fetch();arrived(actual);await gate;await route.fulfill({response:actual})});await page.locator('.workspace-sidebar-paths button').filter({has:page.getByText('已改变路线但保留历史侧坡',{exact:true})}).click();const native=await seen;expect(native.status(),await native.text()).toBe(200);expect((await native.json()).side_slopes_metadata.geometry_current).toBe(false);await expect(page.locator('.ss-stored-stale')).toBeVisible();await expect(page.getByRole('img',{name:'沿 KP 左右有符号侧坡曲线',exact:true})).not.toBeVisible();await expect(page.getByRole('button',{name:'下载当前侧坡 / 规则 JSON',exact:true})).toBeDisabled();release();await ready(page);await page.unroute('**/api/analyze');await expect(page.locator('.ss-stored-stale')).toBeVisible();await expect(page.getByRole('button',{name:'下载当前侧坡 / 规则 JSON',exact:true})).toBeDisabled();await shot(page,'side-slopes-path-switch-genuine-stale-analysis','.ss-stored-stale');expect(await json(request,'/workspaces/'+stored.id)).toEqual(stored);
});
