import {apiURL} from './test-environment';
import {artifactPath} from './artifact-path';
import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:20000})}
test('XYZ, GeoTIFF and Surfer convert positive-up feet to measured metre depths',async({page})=>{
  await page.goto('/');await ready(page);await page.getByRole('button',{name:'新建',exact:true}).click();await expect(page.locator('header strong')).toHaveText('未命名海缆工程');await ready(page);
  for(const [kind,label,file] of [['xyz','XYZ 测深',''],['geotiff','GeoTIFF','tests/fixtures/elevation-feet.tif'],['surfer','Surfer','tests/fixtures/elevation-feet.grd']]){
    await page.getByRole('button',{name:'导入数据',exact:true}).click();await page.getByRole('button',{name:label,exact:true}).click();await page.getByRole('combobox',{name:'源深度单位',exact:true}).selectOption('ft');await page.getByRole('combobox',{name:kind==='xyz'?'源数据垂向':'栅格水深符号',exact:true}).selectOption('up');await page.getByLabel('垂直基准',{exact:true}).fill('MSL');
    if(kind==='xyz'){await page.getByLabel('最大采样间隙 / m',{exact:true}).fill('50000');await page.getByLabel('最大采样间隙 / m',{exact:true}).blur();await page.locator('.import-text').fill('longitude,latitude,depth_m\n117.99,21.99,-100\n118.11,21.99,-100\n117.99,22.11,-100\n118.11,22.11,-100')}else{await page.locator('.file-drop input').setInputFiles(file);if(kind==='surfer')await page.getByLabel('Surfer 源坐标系',{exact:true}).fill('EPSG:4326')}
    const response=page.waitForResponse(r=>r.url().endsWith('/api/terrain/'+kind));await page.getByRole('button',{name:'导入数据',exact:true}).last().click();await expect(page.getByRole('dialog')).not.toBeVisible({timeout:30000});await ready(page);const result=await(await response).json();const samples=result.project.profile.samples.filter((p:any)=>p.depth_m!==null);expect(samples.length).toBeGreaterThan(2);expect(samples[0].depth_m).toBeCloseTo(30.48,6);await expect(page.locator('.metric').nth(1).locator('strong')).not.toHaveText('—');
  }await page.screenshot({path:artifactPath('surfer-feet.png'),fullPage:true});
});

test('a selected exact checkpoint downloads, uploads, resumes and branches through LookAhead',async({page,request})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await ready(page);await page.getByRole('button',{name:'敷设仿真',exact:true}).click();await page.locator('.solver-tabs button').filter({has:page.getByText('动态敷设',{exact:true})}).click();await page.getByLabel('模拟时长 / s',{exact:true}).fill('2');await page.getByLabel('模拟时长 / s',{exact:true}).blur();await page.getByLabel('离散节点数',{exact:true}).fill('10');await page.getByLabel('离散节点数',{exact:true}).blur();const initialResponse=page.waitForResponse(r=>r.url().endsWith('/api/simulation/dynamic'));await page.getByRole('button',{name:'运行计算',exact:true}).click();await expect(page.locator('.checkpoint-actions')).toBeVisible({timeout:30000});const initial=await(await initialResponse).json();await page.getByRole('button',{name:'跳转末帧',exact:true}).click();
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'保存所选帧状态',exact:true}).click();const file=await download;const filePath=(await file.path())!;const checkpoint=JSON.parse(await readFile(filePath,'utf8'));expect(checkpoint.schema).toBe('oceanroute.dynamic.checkpoint');expect(checkpoint.time_s).toBe(2);
  await page.locator('.checkpoint-settings summary').click();await page.locator('.checkpoint-settings .file-drop input').setInputFiles(filePath);await expect(page.getByRole('textbox',{name:'完整恢复状态 JSON',exact:true})).not.toHaveValue('');await page.getByLabel('模拟时长 / s',{exact:true}).fill('2');await page.getByLabel('模拟时长 / s',{exact:true}).blur();const continuedResponse=page.waitForResponse(r=>r.url().endsWith('/api/simulation/dynamic'));await page.getByRole('button',{name:'运行计算',exact:true}).click();await expect(page.locator('.checkpoint-actions')).toBeVisible();const continued=await(await continuedResponse).json();expect(continued.summary.start_time_s).toBe(2);expect(continued.summary.end_time_s).toBe(4);expect(continued.frames[0].nodes).toEqual(initial.frames.at(-1).nodes);
  const fullConfig={...initial.checkpoint.config,duration_s:4};const full=await(await request.post(apiURL+'/simulation/dynamic',{data:{project:await(await request.get(apiURL+'/sample')).json(),config:fullConfig}})).json();for(let i=0;i<full.frames.at(-1).nodes.length;i++)for(let j=0;j<3;j++)expect(continued.frames.at(-1).nodes[i][j]).toBeCloseTo(full.frames.at(-1).nodes[i][j],8);
  await page.getByRole('button',{name:'跳转末帧',exact:true}).click();await expect(page.locator('.sim-overlay strong')).toHaveText('t = 4.00 s');await page.getByRole('button',{name:'从所选状态前瞻',exact:true}).click();await expect(page.getByRole('textbox',{name:'前瞻初始状态 JSON',exact:true})).not.toHaveValue('');await page.getByLabel('局部模拟时长 / s',{exact:true}).fill('2');await page.getByLabel('局部模拟时长 / s',{exact:true}).blur();await page.getByLabel('评价时间窗 / s',{exact:true}).fill('1');await page.getByLabel('评价时间窗 / s',{exact:true}).blur();const aheadResponse=page.waitForResponse(r=>r.url().endsWith('/api/shipplan/lookahead'));await page.getByRole('button',{name:'计算船舶工程',exact:true}).click();await expect(page.locator('.comparison-chart')).toBeVisible({timeout:30000});const branches=await(await aheadResponse).json();expect(branches.scenarios[0].simulation.frames[0].nodes).toEqual(continued.frames.at(-1).nodes);expect(branches.scenarios[0].checkpoint.time_s).toBe(6);await page.screenshot({path:artifactPath('checkpoint-lookahead.png'),fullPage:true});expect(errors).toEqual([]);
});
