import {apiURL} from './test-environment';
import {artifactPath} from './artifact-path';
import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function ready(page:any){await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:20000})}
test('DTM renders measured input bands, preserves NoData and downloads a TIFF',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await ready(page);await page.getByRole('button',{name:'工程工具',exact:true}).click();await page.locator('.engineering-menu button').filter({has:page.getByText('测深网格与地形',{exact:true})}).click();
  await page.getByLabel('XYZ 测深源数据',{exact:true}).fill('longitude,latitude,depth_m\n118,22,100\n118.03,22,200\n118,22.03,200\n118.03,22.03,300');await page.getByLabel('网格间距 / m',{exact:true}).fill('300');await page.getByLabel('网格间距 / m',{exact:true}).blur();await page.getByLabel('等深距 / m',{exact:true}).fill('25');await page.getByLabel('等深距 / m',{exact:true}).blur();
  const response=page.waitForResponse((r:any)=>r.url().endsWith('/api/dtm/grid'));await page.getByRole('button',{name:'生成地形成果',exact:true}).click();await expect(page.locator('.terrain-preview canvas')).toBeVisible({timeout:30000});const result=await (await response).json();expect(result.metadata.valid_cells).toBeGreaterThan(0);expect(result.metadata.missing_cells).toBeGreaterThan(0);expect(result.metadata.contour_count).toBeGreaterThan(0);
  for(const band of ['坡度','坡向','地形阴影','水深']){await page.locator('.terrain-band-nav').getByRole('button',{name:band,exact:true}).click();await expect(page.locator('.terrain-preview canvas')).toBeVisible()}
  await page.locator('.terrain-preview canvas').hover({position:{x:100,y:100}});await expect(page.locator('.terrain-hover')).toBeVisible();
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'四波段 GeoTIFF',exact:true}).click();const file=await download;const data=await readFile((await file.path())!);expect(data.subarray(0,2).toString()).toBe('II');expect(data[2]).toBe(42);
  await page.getByRole('button',{name:'添加等深线到地图',exact:true}).click();await ready(page);await expect(page.locator('.layer-row')).toHaveCount(3);await page.screenshot({path:artifactPath('dtm-terrain.png'),fullPage:true});expect(errors).toEqual([]);
});
test('mixed materials and a 50 kg inline body change real nodal physics',async({page,request})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await ready(page);await page.getByRole('button',{name:'敷设仿真',exact:true}).click();await page.locator('.solver-tabs button').filter({has:page.getByText('动态敷设',{exact:true})}).click();await page.locator('.mixed-materials summary').click();await page.getByRole('button',{name:'加载混合缆与缆体算例',exact:true}).click();
  const response=page.waitForResponse((r:any)=>r.url().endsWith('/api/simulation/dynamic'));await page.getByRole('button',{name:'运行计算',exact:true}).click();await expect(page.locator('.deployed-bodies')).toBeVisible({timeout:30000});const received=await response;const mixed=await received.json();expect(mixed.frames[0].inline_bodies[0].deployed_mass_kg).toBe(50);expect(mixed.frames[0].inline_bodies[0].deployed_wet_weight_n).toBe(200);expect(mixed.frames.at(-1).segment_wet_weight_n_m[0]).toBeGreaterThan(4);
  const sample=await(await request.get(apiURL+'/sample')).json();const config={...received.request().postDataJSON().config};delete config.material_segments;delete config.inline_bodies;
  const baseline=await(await request.post(apiURL+'/simulation/dynamic',{data:{project:sample,config}})).json();const sum=(xs:number[])=>xs.reduce((a,b)=>a+b,0);expect(sum(mixed.frames[0].node_mass_kg)-sum(baseline.frames[0].node_mass_kg)).toBeCloseTo(50+(50-200/9.80665),5);const mixedLast=mixed.frames.at(-1),baseLast=baseline.frames.at(-1);const displacement=mixedLast.nodes.slice(0,Math.min(mixedLast.nodes.length,baseLast.nodes.length)).reduce((total:number,node:number[],i:number)=>total+Math.hypot(...node.map((v,j)=>v-baseLast.nodes[i][j])),0);expect(displacement).toBeGreaterThan(.01);if(mixed.frames[0].node_dry_mass_kg)expect(sum(mixed.frames[0].node_dry_mass_kg)-sum(baseline.frames[0].node_dry_mass_kg)).toBeCloseTo(50,5);
  await page.locator('.playback input').focus();await page.locator('.playback input').press('End');await expect(page.locator('.sim-overlay strong')).toHaveText('t = 20.00 s');await page.locator('.sim-main').evaluate((e:HTMLElement)=>e.scrollTop=0);await page.locator('.sim-settings').evaluate((e:HTMLElement)=>e.scrollTop=0);await page.screenshot({path:artifactPath('mixed-materials.png'),fullPage:true});expect(errors).toEqual([]);
});
