import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function open(page:any){await page.goto('/');await expect(page.locator('.calculation-status')).toHaveText('工程计算已更新',{timeout:25000});await page.getByRole('button',{name:'敷设仿真',exact:true}).click();await page.getByRole('button',{name:'持续计算 / 网格审查',exact:true}).click()}
const path='http://127.0.0.1:8765/api/voyage/jobs/';
test('240 seconds of actual continuous lay retains all material, audits real coarsening, downloads and resumes',async({page,request})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await open(page);const submitted=page.waitForResponse(r=>r.url().endsWith('/api/voyage/jobs')&&r.request().method()==='POST');await page.getByRole('button',{name:'提交后台持续计算',exact:true}).click();const job=await(await submitted).json();await expect(page.locator('.voyage-job-status>div:first-child>strong')).toHaveText('已完成请求时段',{timeout:45000});await expect(page.locator('.voyage-chunks tbody tr').first()).toBeVisible();const result=await(await request.get(path+job.id+'/result')).json();expect(result.status).toBe('completed');expect(result.summary.end_time_s).toBe(240);expect(result.summary.paid_out_m).toBeCloseTo(144,7);expect(result.summary.material_balance_residual_m).toBeLessThan(1e-8);expect(result.summary.accepted_mesh_records).toBeGreaterThanOrEqual(0);expect(result.checkpoint.mesh_history.length).toBe(result.summary.accepted_mesh_records);for(const record of result.checkpoint.mesh_history){expect(record.settlement_evidence.internal_samples).toBeGreaterThan(1);expect(record.settlement_evidence.interval_end_s-record.settlement_evidence.interval_start_s).toBeGreaterThanOrEqual(2);for(const transfer of record.transfers)expect(record.settlement_evidence.stable_material_coordinates_m.some((x:number)=>Math.abs(x-transfer.removed_material_m)<1e-6)).toBe(true);}await expect(page.locator('.scene-host canvas')).toBeVisible();await page.getByRole('button',{name:'跳转持续计算末帧',exact:true}).click();await expect(page.locator('.sim-overlay strong')).toHaveText('t = 240.00 s');
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载真实分块结果',exact:true}).click();const file=await download;const actual=JSON.parse(await readFile((await file.path())!,'utf8'));expect(actual.summary.material_balance_residual_m).toBeLessThan(1e-8);expect(actual.checkpoint.physical_checkpoint.state.rest_lengths_m.length).toBe(actual.summary.final_nodes-1);await page.locator('.voyage-layout .sim-main').evaluate((e:HTMLElement)=>e.scrollTop=0);if(await page.getByRole('button',{name:'关闭提示',exact:true}).isVisible())await page.getByRole('button',{name:'关闭提示',exact:true}).click();await page.locator('.voyage-layout .sim-settings').evaluate((e:HTMLElement)=>e.scrollTop=0);await page.screenshot({path:'artifacts/continuous-lay-completed.png',fullPage:true});await page.locator('.voyage-layout .sim-view').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/continuous-lay-geometry.png',fullPage:true});if(result.summary.accepted_mesh_records>0){await page.locator('.voyage-mesh>details').first().locator('summary').first().click();await expect(page.locator('.voyage-settlement-evidence').first()).toContainText('实际内部采样');await expect(page.locator('.voyage-probe-summary').first()).toContainText('全部材料位置最大误差');await page.locator('.voyage-mesh').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/continuous-lay-mesh-audit.png',fullPage:true});}else await expect(page.locator('.voyage-mesh')).toContainText('本次没有接受粗化');
  await page.getByLabel('请求继续计算时长 / s',{exact:true}).fill('4');await page.getByLabel('请求继续计算时长 / s',{exact:true}).blur();const resumed=page.waitForResponse(r=>r.url().endsWith('/api/voyage/jobs/'+job.id+'/resume'));await page.getByRole('button',{name:'按当前时长继续为子任务',exact:true}).click();const child=await(await resumed).json();expect(child.parent_job_id).toBe(job.id);await expect(page.locator('.voyage-job-status>div:first-child>strong')).toHaveText('已完成请求时段',{timeout:30000});await expect(page.locator('.voyage-chunks tbody tr').first()).toBeVisible();const continued=await(await request.get(path+child.id+'/result')).json();expect(continued.summary.start_time_s).toBe(240);expect(continued.summary.end_time_s).toBe(244);expect(continued.summary.paid_out_m).toBeCloseTo(146.4,6);expect(errors).toEqual([]);
});
test('cancelling preserves a completed chunk, resumes a child and failed inputs never claim completion',async({page,request})=>{
  await open(page);await page.getByLabel('请求继续计算时长 / s',{exact:true}).fill('1000');await page.getByLabel('请求继续计算时长 / s',{exact:true}).blur();const submitted=page.waitForResponse(r=>r.url().endsWith('/api/voyage/jobs')&&r.request().method()==='POST');await page.getByRole('button',{name:'提交后台持续计算',exact:true}).click();const job=await(await submitted).json();await expect(page.locator('.voyage-progress')).toContainText('完整分块已保存到',{timeout:20000});await page.getByRole('button',{name:'请求取消',exact:true}).click();await expect(page.locator('.voyage-job-status>div:first-child>strong')).toHaveText('已取消',{timeout:30000});await expect(page.getByRole('button',{name:'保存最近完整断点',exact:true})).toBeEnabled();const result=await(await request.get(path+job.id+'/result')).json();expect(result.status).toBe('cancelled');expect(result.summary.computed_duration_s).toBeGreaterThan(0);expect(result.summary.computed_duration_s).toBeLessThan(1000);expect(result.checkpoint).not.toBeNull();const cpDownload=page.waitForEvent('download');await page.getByRole('button',{name:'保存最近完整断点',exact:true}).click();const cpFile=await cpDownload;const checkpoint=JSON.parse(await readFile((await cpFile.path())!,'utf8'));expect(checkpoint.schema).toBe('oceanroute.voyage.checkpoint');expect(checkpoint.physical_checkpoint.time_s).toBe(result.summary.end_time_s);
  await page.getByLabel('请求继续计算时长 / s',{exact:true}).fill('2');await page.getByLabel('请求继续计算时长 / s',{exact:true}).blur();await page.getByRole('button',{name:'按当前时长继续为子任务',exact:true}).click();await expect(page.locator('.voyage-job-status>div:first-child>strong')).toHaveText('已完成请求时段',{timeout:30000});await expect(page.locator('.voyage-chunks tbody tr').first()).toBeVisible();await page.getByLabel('明确动态物性与作业控制 JSON',{exact:true}).fill('{"depth_m":-1}');const invalid=page.waitForResponse(r=>r.url().endsWith('/api/voyage/jobs')&&r.request().method()==='POST');await page.getByRole('button',{name:'提交后台持续计算',exact:true}).click();const bad=await(await invalid).json();await expect(page.locator('.voyage-job-status>div:first-child>strong')).toHaveText('计算失败',{timeout:20000});await expect(page.locator('.voyage-job-status')).toContainText('depth_m');const state=await(await request.get(path+bad.id)).json();expect(state.status).toBe('failed');expect(state.result_available).toBe(false);await expect(page.locator('.voyage-chunks')).toHaveCount(0);
});

test('a consumed work budget returns an actual partial stop with no invented state or completed frames',async({page,request})=>{
  await open(page);await page.getByLabel('本次总工作量上限',{exact:true}).fill('1');await page.getByLabel('本次总工作量上限',{exact:true}).blur();const submitted=page.waitForResponse(r=>r.url().endsWith('/api/voyage/jobs')&&r.request().method()==='POST');await page.getByRole('button',{name:'提交后台持续计算',exact:true}).click();const job=await(await submitted).json();await expect(page.locator('.voyage-job-status>div:first-child>strong')).toHaveText('达到限制后停止',{timeout:20000});await expect(page.getByRole('button',{name:'保存最近完整断点',exact:true})).toBeDisabled();const actual=await(await request.get(path+job.id+'/result')).json();expect(actual.status).toBe('stopped');expect(actual.summary.computed_duration_s).toBe(0);expect(actual.checkpoint).toBeNull();expect(actual.frames).toHaveLength(0);await expect(page.locator('.voyage-layout .sim-view')).toHaveCount(0);await expect(page.locator('.voyage-layout .inline-warning').filter({hasText:'不能当作请求时段已计算完成'})).toBeVisible();
});

test('a declared settled-bed case displays actual internal contact evidence and whole-material transfer errors',async({page,request})=>{
  await open(page);await page.getByLabel('请求继续计算时长 / s',{exact:true}).fill('120');await page.getByLabel('请求继续计算时长 / s',{exact:true}).blur();await page.getByLabel('每块最长时段 / s',{exact:true}).fill('10');await page.getByLabel('每块最长时段 / s',{exact:true}).blur();await page.getByLabel('明确动态物性与作业控制 JSON',{exact:true}).fill(JSON.stringify({depth_m:20,bottom_tension_n:50,wet_weight_n_m:4,ea_n:1000000,ei_n_m2:0,nodes:12,ship_speed_m_s:.5,payout_m_s:.6,internal_dt_s:.05,dt_s:1,solver_iterations:24,seabed_friction:.5,current_y_m_s:0,diameter_m:.02,mass_kg_m:.7298997321841252,drag_coefficient:1.2,water_density_kg_m3:1025,added_mass_coefficient:1,damping_ratio:.03,max_tension_n:1e12,min_bend_radius_m:0}));await page.getByLabel('误差约束海床网格策略 JSON',{exact:true}).fill('{"target_nodes":12}');const submitted=page.waitForResponse(r=>r.url().endsWith('/api/voyage/jobs')&&r.request().method()==='POST');await page.getByRole('button',{name:'提交后台持续计算',exact:true}).click();const job=await(await submitted).json();await expect(page.locator('.voyage-job-status>div:first-child>strong')).toHaveText('已完成请求时段',{timeout:45000});await expect(page.locator('.voyage-chunks tbody tr').first()).toBeVisible();const actual=await(await request.get(path+job.id+'/result')).json();expect(actual.summary.end_time_s).toBe(120);expect(actual.summary.paid_out_m).toBeCloseTo(72,7);expect(actual.summary.accepted_mesh_records).toBeGreaterThan(0);for(const record of actual.checkpoint.mesh_history){expect(record.settlement_evidence.internal_samples).toBeGreaterThan(1);for(const transfer of record.transfers)expect(record.settlement_evidence.stable_material_coordinates_m.some((x:number)=>Math.abs(x-transfer.removed_material_m)<1e-6)).toBe(true);expect(record.probe.full_material_position_error_m).toBeGreaterThanOrEqual(0);expect(record.probe.full_material_velocity_error_m_s).toBeGreaterThanOrEqual(0);}await page.locator('.voyage-mesh>details').first().locator('summary').first().click();await expect(page.locator('.voyage-settlement-evidence').first()).toContainText('实际内部采样');await expect(page.locator('.voyage-probe-summary').first()).toContainText('全部材料位置最大误差');await page.locator('.voyage-mesh').scrollIntoViewIfNeeded();if(await page.getByRole('button',{name:'关闭提示',exact:true}).isVisible())await page.getByRole('button',{name:'关闭提示',exact:true}).click();await page.screenshot({path:'artifacts/continuous-lay-mesh-audit.png',fullPage:true});
});
