import {useEffect,useRef,useState} from 'react';
import {Check,Download,Play,Scissors,Waypoints} from 'lucide-react';
import {request} from './api';
import {NumberField} from './fields';
import MapView from './MapView';
import {ProfileChart} from './Charts';
import type {Analysis,Project} from './types';
import type {Workspace,WorkspaceDocument} from './useWorkspaceDocument';
import './AltercourseTools.css';

export type AltercourseKind='split'|'radius';
export type AltercourseConfig={point_id:string;max_turn_angle_deg?:number;min_turn_distance_m?:number;radius_m?:number};
export type AltercoursePreview={workspace:Workspace;project:Project;analysis:{active_path_analysis:Analysis;[key:string]:unknown};report:Record<string,any>;tool_report:Record<string,any>;warnings:any[];operation:{kind:AltercourseKind;path_id:string;config:AltercourseConfig};result_selection_point_id:string};
export type AltercourseSnapshot={document:WorkspaceDocument;contextKey:string;point_id:string;selectionRevision:number};
export type AltercourseContext={document:WorkspaceDocument;contextKey:string;selected:string|null;selectionRevision:number;pending:boolean;onSelectPoint:(id:string)=>void;onApply:(candidate:AltercoursePreview,expected:AltercourseSnapshot,isCurrent:()=>boolean)=>Promise<boolean>};
const names:Record<string,string>={operation:'操作',mode:'制造模式',kind:'操作',point_id:'原转向点 ID',selected_point_id:'原转向点 ID',result_selection_point_id:'结果选中点 ID',inserted_points:'新增路线点',removed_points:'移除路线点',original_points:'原路线点数',new_points:'候选路线点数',max_turn_angle_deg:'最大单次转向角 / °',min_turn_distance_m:'最小转向间距 / m',radius_m:'圆弧半径 / m',sweep_deg:'圆弧转角 / °',arc_length_m:'实际弧长 / m',turn_angle_deg:'原转向角 / °',turn_deg:'转向角 / °',changed:'路线已改变',surface_length_m:'表面长度 / m',bottom_length_m:'海底长度 / m',cable_length_m:'电缆长度 / m',cost_total:'费用合计',profile_invalidation:'旧剖面失效记录',side_slopes_invalidation:'旧侧坡失效记录',base_length_before_m:'原基准长度 / m',base_length_after_m:'候选基准长度 / m',physical_length_before_m:'原制造长度 / m',physical_length_after_m:'候选制造长度 / m',base_delta_m:'基准长度变化 / m',physical_delta_m:'制造长度变化 / m',point_count:'路线点数',profile_invalidated:'旧剖面已失效',side_slopes_invalidated:'旧侧坡已失效',route_signature:'候选路线签名',leg_count:'分段数',original_turn_deg:'原转向角 / °',turns_deg:'实际转向角 / °',internal_lengths_m:'实际转向间距 / m',trim_in_m:'入线截取距离 / m',trim_out_m:'出线截取距离 / m',radius_residual_m:'半径数值残差 / m',tangent_residuals_deg:'切向数值残差 / °',endpoint_residual_m:'终点数值残差 / m',terminal_tangent_residual_deg:'末端切向数值残差 / °',common_turn_deg:'单次转向角 / °',assembly_policy:'装配核验策略',split:'分割转向点',radius:'圆弧转向点',auto_exclusive:'独占装配自动核验',flexible:'柔性',fixed:'固定',mixed:'混合',geodesic:'椭球大地线',rhumb:'恒向线'};
const display=(v:any):string=>v==null?'—':typeof v==='number'?(v!==0&&Math.abs(v)<1e-6?v.toExponential(3):v===0?'0':v.toLocaleString('zh-CN',{maximumFractionDigits:6})):typeof v==='boolean'?(v?'是':'否'):typeof v==='string'?(names[v]||v):Array.isArray(v)?v.map(display).join('，'):JSON.stringify(v);
function download(output:AltercoursePreview){const url=URL.createObjectURL(new Blob([JSON.stringify(output,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`OceanRoute-${output.operation.kind}-altercourse-preview.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}

export default function AltercourseTools({project,analysis,analysisCurrent,...context}:AltercourseContext&{project:Project;analysis:Analysis|null;analysisCurrent:boolean}){
 const {document,contextKey,selected,selectionRevision,pending,onSelectPoint,onApply}=context;
 const [kind,setKind]=useState<AltercourseKind>('split'),[angle,setAngle]=useState(45),[distance,setDistance]=useState(100),[radius,setRadius]=useState(100),[uiRevision,setUIRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[candidate,setCandidate]=useState<{output:AltercoursePreview;signature:string;snapshot:AltercourseSnapshot}|null>(null);
 const mounted=useRef(true),sequence=useRef(0),documentEpoch=useRef({document,revision:0});
 if(documentEpoch.current.document!==document)documentEpoch.current={document,revision:documentEpoch.current.revision+1};
 const signature=JSON.stringify({contextKey,documentRevision:documentEpoch.current.revision,selectionRevision,selected,kind,angle,distance,radius,uiRevision});
 const latest=useRef(signature);latest.current=signature;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;sequence.current++}},[]);
 const index=project.route.points.findIndex(p=>p.id===selected),point=index>0&&index<project.route.points.length-1?project.route.points[index]:null;
 const supported=!!point&&(!point.constraint||point.constraint==='rigid');
 const pointResult=analysisCurrent?analysis?.rpl.find(r=>r.id===selected):null;
 const current=!!candidate&&candidate.signature===signature;
 const actual=candidate?.output.analysis.active_path_analysis,previewProject=candidate?.output.project;
 const changed=candidate?.output.tool_report.changed!==false;
 const arcs=previewProject?.route.legs.map((leg,i)=>({leg,index:i,result:actual?.legs[i]})).filter(r=>r.leg.geometry?.type==='circular_arc')||[];
 const config:AltercourseConfig=kind==='split'?{point_id:point?.id||'',max_turn_angle_deg:angle,min_turn_distance_m:distance}:{point_id:point?.id||'',radius_m:radius};
 async function preview(){
  if(!point||!supported||pending||busy)return;
  const captured=signature,number=++sequence.current,snapshot:AltercourseSnapshot={document,contextKey,point_id:point.id,selectionRevision};
  setBusy(true);setError('');setCandidate(null);
  try{
   const output=await request<AltercoursePreview>('/workspace/altercourse-preview',{workspace:document.workspace,path_id:document.workspace.active_path_id,kind,config});
   if(!mounted.current||number!==sequence.current||latest.current!==captured){if(mounted.current)setError('输入、选中点或工作区在计算期间已改变，迟到预览已丢弃');return}
   if(output.workspace?.id!==document.workspace.id||output.workspace?.active_path_id!==document.workspace.active_path_id||output.workspace?.saved_revision!==document.workspace.saved_revision||output.operation?.kind!==kind||output.operation?.path_id!==document.workspace.active_path_id||output.operation?.config?.point_id!==point.id||!output.tool_report||!Array.isArray(output.workspace.paths)||output.project?.id!==document.workspace.active_path_id||!output.analysis?.active_path_analysis?.route_geometry||!output.project.route.points.some(p=>p.id===output.result_selection_point_id))throw new Error('完整预览的身份、活跃路径、真实分析或结果选中点不一致，未载入候选');
   setCandidate({output,signature:captured,snapshot});
  }catch(e){if(mounted.current&&number===sequence.current)setError(e instanceof Error?e.message:String(e))}
  finally{if(mounted.current&&number===sequence.current)setBusy(false)}
 }
 async function apply(){
  if(!candidate||!current||pending||busy||!changed)return;
  const captured=candidate.signature,number=++sequence.current;const isCurrent=()=>mounted.current&&sequence.current===number&&latest.current===captured;
  setBusy(true);setError('');
  try{if(await onApply(candidate.output,candidate.snapshot,isCurrent)){if(mounted.current){setCandidate(null);setError('')}}else if(mounted.current)setError('候选未通过应用校验；当前路线保持不变，请重新预览')}
  catch(e){if(mounted.current)setError(e instanceof Error?e.message:String(e))}
  finally{if(mounted.current&&sequence.current===number)setBusy(false)}
 }
 return <main className="engineering-main altercourse-tools" onInput={e=>{if((e.target as HTMLElement).closest('.ac-form'))setUIRevision(v=>v+1)}}>
  <div className="page-heading"><div><small>SPLIT AC / RADIUS AC</small><h2>转向点处理</h2><p>选择现有内部路线点，先核对完整工作区候选，再应用并可撤销。</p></div><button className="primary-button" onClick={preview} disabled={busy||pending||!supported}><Play size={14}/>{busy?'正在核验…':'预览转向候选'}</button></div>
  <div className="settings-card ac-form"><div className="tool-fields"><label>转向操作<select aria-label="转向操作" value={kind} onChange={e=>setKind(e.target.value as AltercourseKind)}><option value="split">分割转向点 · Split AC</option><option value="radius">圆弧转向点 · Radius AC</option></select></label><label>内部转向点<select aria-label="内部转向点" value={point?.id||''} onChange={e=>onSelectPoint(e.target.value)}><option value="" disabled>请选择实际内部路线点</option>{project.route.points.slice(1,-1).map((p,i)=><option key={p.id} value={p.id} disabled={!!p.constraint&&p.constraint!=='rigid'}>{String(i+2).padStart(2,'0')} · {p.label} · {p.id}</option>)}</select></label>{kind==='split'?<><label>最大单次转向角 / °<NumberField aria-label="最大单次转向角 / °" value={angle} min={Number.MIN_VALUE} max={179.99999999999997} onChange={v=>setAngle(v??45)}/></label><label>最小转向间距 / m<NumberField aria-label="最小转向间距 / m" value={distance} min={0.001} max={1000000} onChange={v=>setDistance(v??100)}/></label></>:<label>圆弧半径 / m<NumberField aria-label="圆弧半径 / m" value={radius} min={0.001} max={1000000} onChange={v=>setRadius(v??100)}/></label>}</div>
   {point&&!supported&&<div className="inline-warning">该点不是 Rigid 路线点；转向整形需要实际内部 Rigid 点，夹持或滑移点保持原约束。</div>}{!point?<div className="inline-warning">路线端点不能作为转向点。请从地图、侧栏或上方列表选择内部路线点。</div>:<div className="ac-selection" data-point-id={point.id}><Waypoints size={15}/><strong>{point.label}</strong><span>真实点 ID · {point.id}</span><span>表面 KP · {display(pointResult?.kp_m)} m</span><span>转向角 · {display(pointResult?.turn_angle_deg??pointResult?.turn_deg)}°</span></div>}
   <p className="explanation">{kind==='split'?'按最大转向角和最小转向间距生成实际路线点；距离不足、材料边界或制造约束会由服务明确拒绝。':'圆弧作为分段几何存储；地图显示后端真实弧线采样，RPL 只列存储的路线点。改变圆弧端点须重新构造有效几何。'} 预览不保存；应用后的路线变化可能使旧测深剖面与侧坡采样失效。</p>
  </div>
  {error&&<div className="inline-warning ac-error" role="alert">{error}</div>}
  {candidate&&!current&&<div className="inline-warning ac-stale">输入、选中点、活跃路径或保存修订已改变；以下候选已失效，请重新预览。</div>}
  {candidate&&<section className="tool-result ac-preview" data-preview-point-id={candidate.output.operation.config.point_id} data-preview-kind={candidate.output.operation.kind}>
   <div className="section-heading"><h3><Scissors size={16}/>完整转向候选</h3><div className="page-actions"><button className="secondary-button" onClick={()=>download(candidate.output)}><Download size={14}/>下载转向候选</button><button className="primary-button" onClick={apply} disabled={!current||pending||busy||!changed}><Check size={14}/>应用转向候选</button></div></div>
   {!changed&&<div className="explanation">本次核验无需改变路线，未产生可应用修改。</div>}
   <div className="tool-summary"><div><span>路线点</span><strong>{project.route.points.length} → {previewProject?.route.points.length}</strong></div><div><span>圆弧分段</span><strong>{arcs.length}</strong></div><div><span>KP 测深样本</span><strong>{project.profile.samples.length} → {previewProject?.profile.samples.length}</strong></div><div><span>侧坡样本</span><strong>{project.side_slopes?.samples.length||0} → {previewProject?.side_slopes?.samples.length||0}</strong></div>{Object.entries(candidate.output.tool_report).filter(([,v])=>v==null||['string','number','boolean'].includes(typeof v)).map(([k,v])=><div key={k}><span>{names[k]||k}</span><strong>{display(v)}</strong></div>)}</div>
   {['profile_invalidation','side_slopes_invalidation'].map(k=>{const row=candidate.output.tool_report[k];return row?<div className="inline-warning ac-invalidation" key={k}><strong>{names[k]}</strong> · {row.invalidated?'已失效，保留的旧签名不能认证新路线；须实际重新采样':row.present?'本次未改变':'无旧数据'}</div>:null})}{candidate.output.tool_report.before&&candidate.output.tool_report.after&&<div className="table-wrap ac-before-after"><table><thead><tr><th>核验项</th><th>操作前</th><th>候选结果</th></tr></thead><tbody>{Object.keys(candidate.output.tool_report.before).map(k=><tr key={k}><td>{names[k]||k}</td><td>{display(candidate.output.tool_report.before[k])}</td><td>{display(candidate.output.tool_report.after[k])}</td></tr>)}</tbody></table></div>}{candidate.output.tool_report.manufacturing&&<div className="tool-summary ac-manufacturing">{Object.entries(candidate.output.tool_report.manufacturing).filter(([,v])=>v==null||['number','string','boolean'].includes(typeof v)).map(([k,v])=><div key={k}><span>{names[k]||k}</span><strong>{display(v)}</strong></div>)}</div>}{Array.isArray(candidate.output.tool_report.manufacturing?.by_cable_type)&&<div className="table-wrap ac-materials"><table><thead><tr><th>缆型</th><th>原制造量 / m</th><th>候选制造量 / m</th><th>变化 / m</th></tr></thead><tbody>{candidate.output.tool_report.manufacturing.by_cable_type.map((r:any)=><tr key={r.cable_type_id}><td>{r.cable_type_id}</td><td>{display(r.before_m)}</td><td>{display(r.after_m)}</td><td>{display(r.delta_m)}</td></tr>)}</tbody></table></div>}{candidate.output.tool_report.invariants&&<div className="table-wrap"><table><thead><tr><th>检查项</th><th>操作前</th><th>操作后</th><th>变化</th></tr></thead><tbody>{Object.entries(candidate.output.tool_report.invariants).map(([k,v])=>{const row=v as any;return <tr key={k}><td>{names[k]||k}</td><td>{display(row.before)}</td><td>{display(row.after)}</td><td>{display(row.delta)}</td></tr>})}</tbody></table></div>}
   {candidate.output.tool_report.geometry_evidence&&<div className="tool-summary ac-geometry-evidence">{Object.entries(candidate.output.tool_report.geometry_evidence).filter(([k])=>['original_turn_deg','turns_deg','internal_lengths_m','trim_in_m','trim_out_m','radius_residual_m','tangent_residuals_deg','endpoint_residual_m','terminal_tangent_residual_deg'].includes(k)).map(([k,v])=><div key={k}><span>{names[k]||k}</span><strong>{display(v)}</strong></div>)}</div>}{arcs.length>0&&<div className="table-wrap ac-arcs"><table><thead><tr><th>圆弧分段</th><th>半径 / m</th><th>有向转角 / °</th><th>实际表面长度 / m</th><th>圆心经纬度</th></tr></thead><tbody>{arcs.map(({leg,index,result})=><tr key={index} data-arc-leg={index}><td>{previewProject?.route.points[index].label} → {previewProject?.route.points[index+1].label}</td><td>{display(leg.geometry?.radius_m)}</td><td>{display(leg.geometry?.sweep_deg)}</td><td>{display(result?.surface_length_m)}</td><td>{leg.geometry?.center.map(display).join('，')}</td></tr>)}</tbody></table></div>}
   {candidate.output.warnings.map((w,i)=><div key={i} className="inline-warning ac-warning">{typeof w==='string'?w:w.message||JSON.stringify(w)}</div>)}
   {previewProject&&actual&&<><div className="ac-preview-map"><MapView project={previewProject} analysis={actual} analysisReady geometry={actual.route_geometry?.coordinates} geometrySegments={actual.route_geometry_segments} selected={candidate.output.result_selection_point_id} onSelect={()=>{}} onMove={()=>Promise.resolve(false)} onAdd={()=>{}} editable={false} allowAdd={false} fitVersion={1}/></div><ProfileChart analysis={actual} selected={candidate.output.result_selection_point_id} onSelect={()=>{}}/><div className="table-wrap ac-rpl"><table><thead><tr><th>实际路线点</th><th>表面 KP / m</th><th>电缆 KP / m</th><th>水深 / m</th><th>后续曲线</th></tr></thead><tbody>{previewProject.route.points.map((p,i)=>{const r=actual.rpl.find(row=>row.id===p.id);return <tr key={p.id} data-point-id={p.id}><td>{p.label}</td><td>{display(r?.kp_m)}</td><td>{display(r?.cable_kp_m)}</td><td>{display(r?.depth_m)}</td><td>{previewProject.route.legs[i]?.geometry?.type==='circular_arc'?'圆弧':i<previewProject.route.legs.length?display(previewProject.route.curve):'—'}</td></tr>})}</tbody></table></div></>}
   <details><summary>完整服务核验报告</summary><pre>{JSON.stringify({operation:candidate.output.operation,tool_report:candidate.output.tool_report,workspace_report:candidate.output.report,warnings:candidate.output.warnings},null,2)}</pre></details>
  </section>}
 </main>;
}
