import {useEffect,useRef,useState} from 'react';
import {Check,Download,Play,Plus,Trash2} from 'lucide-react';
import {request} from './api';
import {productRelease} from './version';
import MapView from './MapView';
import {ProfileChart} from './Charts';
import type {Project} from './types';
import type {ArcEditConfig,ArcEditContext,ArcEditIntent,ArcEditPreview,ArcEditSnapshot,ArcOption} from './arcEdits';
import {arcEndpointIds} from './arcEdits';
import './ArcEditPanel.css';

type MoveInput={point_id:string;longitude:string;latitude:string};
type OptionInput=ArcOption&{use_radius:boolean;radius_text:string};
const f=(v:any):string=>v==null?'—':typeof v==='number'?(v!==0&&Math.abs(v)<1e-6?v.toExponential(4):v.toLocaleString('zh-CN',{maximumFractionDigits:9})):typeof v==='boolean'?(v?'是':'否'):Array.isArray(v)?v.map(f).join('，'):typeof v==='object'?JSON.stringify(v):({minor:'短弧',major:'长弧',full_circle:'完整圆'} as Record<string,string>)[String(v)]||String(v);
const labels:Record<string,string>={radius_m:'候选半径 / m',original_radius_m:'原半径 / m',radius_overridden:'半径已显式修改',branch_policy:'分支策略',signed_direction:'有向符号',old_sweep_deg:'原有向转角 / °',original_minor_major:'原短弧 / 长弧',endpoint_separation_m:'端点间测地距离 / m',original_center_side:'原圆心侧',selection:'实际选择',new_center:'候选圆心 / °',new_sweep_deg:'候选有向转角 / °',new_minor_major:'候选短弧 / 长弧',endpoint_radius_errors_m:'端点半径残差 / m',end_binding_errors_m:'端点绑定残差 / m',length_upper_bound_m:'弧长上界 / m',start_tangent_deg:'真实入端切向 / °',end_tangent_deg:'真实出端切向 / °',mode:'制造模式',fixed:'固定',flexible:'柔性',mixed:'混合',base_length_before_m:'原基准长度 / m',base_length_after_m:'候选基准长度 / m',base_delta_m:'基准长度变化 / m',physical_length_before_m:'原制造长度 / m',physical_length_after_m:'候选制造长度 / m',physical_delta_m:'制造长度变化 / m',arc_length_m:'实际弧长 / m',length_m:'实际弧长 / m',old_length_m:'原实际弧长 / m',new_length_m:'候选实际弧长 / m',length_before_m:'原实际弧长 / m',length_after_m:'候选实际弧长 / m',radius_residual_m:'半径残差 / m',endpoint_residual_m:'端点残差 / m',tangent_residuals_deg:'切向残差 / °',join_turns_deg:'接缝转向 / °',center_shift_m:'圆心移动 / m',branch:'分支',sweep_deg:'有向转角 / °',work_units:'已用工作量',max_work_units:'工作量上限'};
function optionsFor(project:Project):OptionInput[]{const result:OptionInput[]=[];const rigid=project.route.points.map((p,i)=>({p,i})).filter(({p})=>!p.constraint||p.constraint==='rigid');for(let n=1;n<rigid.length;n++){const start=rigid[n-1],end=rigid[n],arc=project.route.legs.slice(start.i,end.i).find(leg=>leg.geometry?.type==='circular_arc')?.geometry;if(arc)result.push({start_point_id:start.p.id,end_point_id:end.p.id,branch:'preserve',full_circle_policy:'reject_move',use_radius:false,radius_text:String(arc.radius_m)})}return result}
function initialMoves(project:Project,selected:string|null,intent?:ArcEditIntent):MoveInput[]{if(intent)return intent.moves.map(p=>({...p,longitude:String(p.longitude),latitude:String(p.latitude)}));const ids=arcEndpointIds(project),point=project.route.points.find(p=>p.id===selected&&ids.has(p.id)&&(!p.constraint||p.constraint==='rigid'))||project.route.points.find(p=>ids.has(p.id)&&(!p.constraint||p.constraint==='rigid'));return point?[{point_id:point.id,longitude:String(point.longitude),latitude:String(point.latitude)}]:[]}

export default function ArcEditPanel({project,intent,onApplied,...context}:ArcEditContext&{project:Project;intent?:ArcEditIntent;onApplied?:()=>void}){
 const {document,contextKey,selected,selectionRevision,pending,onSelectPoint,onApply}=context;
 const [moves,setMoves]=useState(()=>initialMoves(project,selected,intent)),[options,setOptions]=useState(()=>optionsFor(project)),[addId,setAddId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[candidate,setCandidate]=useState<{output:ArcEditPreview;signature:string;raw:number;snapshot:ArcEditSnapshot}|null>(null);
 const mounted=useRef(true),sequence=useRef(0),rawRevision=useRef(0),documentEpoch=useRef({document,revision:0});
 if(documentEpoch.current.document!==document)documentEpoch.current={document,revision:documentEpoch.current.revision+1};
 const signature=JSON.stringify({contextKey,documentEpoch:documentEpoch.current.revision,selected,selectionRevision,moves,options,rawRevision:rawRevision.current,intent:intent?.token});const latest=useRef(signature);latest.current=signature;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;++sequence.current}},[]);
 const endpoints=arcEndpointIds(project),eligible=project.route.points.filter(p=>endpoints.has(p.id)&&(!p.constraint||p.constraint==='rigid'));
 const current=!!candidate&&candidate.signature===signature&&candidate.raw===rawRevision.current;
 const actual=candidate?.output.analysis.active_path_analysis,previewProject=candidate?.output.project;
 function config():ArcEditConfig{const seen=new Set<string>();const normalized=moves.map(m=>{const point=project.route.points.find(p=>p.id===m.point_id);if(!point||point.constraint&&point.constraint!=='rigid')throw new Error('圆弧移动仅接受当前路线的实际 Rigid 点');if(seen.has(m.point_id))throw new Error('同一点只能提交一个移动目标');seen.add(m.point_id);const longitude=Number(m.longitude),latitude=Number(m.latitude);if(!m.longitude.trim()||!m.latitude.trim()||!Number.isFinite(longitude)||Math.abs(longitude)>180||!Number.isFinite(latitude)||Math.abs(latitude)>90)throw new Error('目标经纬度须为有限 WGS84 十进制度，范围 ±180° / ±90°');return {point_id:m.point_id,longitude,latitude}});const arc_options=options.filter(o=>o.use_radius||o.branch!=='preserve'||o.full_circle_policy!=='reject_move').map(o=>{const option:ArcOption={start_point_id:o.start_point_id,end_point_id:o.end_point_id,branch:o.branch,full_circle_policy:o.full_circle_policy};if(o.use_radius){const radius=Number(o.radius_text);if(!o.radius_text.trim()||!Number.isFinite(radius)||radius<.001||radius>1e6)throw new Error('圆弧半径须为 0.001–1000000 m');option.radius_m=radius}return option});if(!normalized.length&&!arc_options.length)throw new Error('请提供至少一个真实点移动或明确圆弧选项');return {moves:normalized,...(arc_options.length?{arc_options}:{})}}
 async function preview(){if(busy||pending||document.draft)return;const captured=signature,raw=rawRevision.current,number=++sequence.current,snapshot:ArcEditSnapshot={document,contextKey,selected,selectionRevision};setBusy(true);setError('');setCandidate(null);try{const submitted=config(),output=await request<ArcEditPreview>('/workspace/arc-edit-preview',{workspace:document.workspace,path_id:document.workspace.active_path_id,config:submitted});if(!mounted.current||sequence.current!==number||latest.current!==captured||rawRevision.current!==raw){if(mounted.current)setError('输入、选中点、活跃路径或保存修订在重建期间已改变，迟到圆弧预览已丢弃');return}if(output.workspace?.id!==document.workspace.id||output.workspace?.saved_revision!==document.workspace.saved_revision||output.workspace?.active_path_id!==document.workspace.active_path_id||output.project?.id!==document.workspace.active_path_id||output.operation?.kind!=='arc_edit'||output.operation.path_id!==document.workspace.active_path_id||!output.tool_report||!Array.isArray(output.tool_report.arc_changes)||!Array.isArray(output.tool_report.joins)||!Array.isArray(output.operation.config.moves)||!output.analysis?.active_path_analysis?.route_geometry||!output.project.route.points.some(p=>p.id===output.result_selection_point_id))throw new Error('圆弧候选身份、完整分析或结果点不一致，未载入候选');if(JSON.stringify(output.operation.config.moves)!==JSON.stringify(submitted.moves))throw new Error('圆弧候选的实际移动目标与提交输入不一致，未载入候选');setCandidate({output,signature:captured,raw,snapshot})}catch(e){if(mounted.current&&sequence.current===number)setError(latest.current!==captured||rawRevision.current!==raw?'输入、选中点、活跃路径或保存修订在重建期间已改变，迟到圆弧预览已丢弃':e instanceof Error?e.message:String(e))}finally{if(mounted.current&&sequence.current===number)setBusy(false)}}
 async function apply(){if(!candidate||!current||busy||pending||!candidate.output.tool_report.changed)return;const captured=candidate.signature,raw=candidate.raw,number=++sequence.current,isCurrent=()=>mounted.current&&sequence.current===number&&latest.current===captured&&rawRevision.current===raw;setBusy(true);setError('');try{if(await onApply(candidate.output,candidate.snapshot,isCurrent)){if(mounted.current){setCandidate(null);onApplied?.()}}else if(mounted.current)setError('候选未通过应用校验；当前路线保持不变，请重新预览')}catch(e){if(mounted.current)setError(e instanceof Error?e.message:String(e))}finally{if(mounted.current&&sequence.current===number)setBusy(false)}}
 function updateMove(i:number,key:'longitude'|'latitude',value:string){setMoves(rows=>rows.map((m,n)=>n===i?{...m,[key]:value}:m))}
 function updateOption(i:number,value:Partial<OptionInput>){setOptions(rows=>rows.map((o,n)=>n===i?{...o,...value}:o))}
 function download(){if(!candidate)return;const url=URL.createObjectURL(new Blob([JSON.stringify(candidate.output,null,2)],{type:'application/json'})),a=window.document.createElement('a');a.href=url;a.download=`OceanRoute-${productRelease}-arc-edit-preview.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
 const name=(id:string)=>project.route.points.find(p=>p.id===id)?.label||id;
 return <main className="engineering-main arc-edit-panel" onInputCapture={e=>{if((e.target as HTMLElement).closest('.arc-form')){++rawRevision.current}}}>
  <div className="page-heading"><div><small>WGS84 CIRCULAR ARC RECONSTRUCTION</small><h2>圆弧端点编辑</h2><p>以真实圆弧描述符重建完整工作区候选；预览不保存，应用后可撤销。</p></div><button className="primary-button" onClick={preview} disabled={busy||pending||!!document.draft||!options.length}><Play size={14}/>{busy?'正在核验…':'预览圆弧重建'}</button></div>
  <section className="settings-card arc-form"><p className="explanation">默认保留半径、未移动的另一端及原有向短弧或长弧分支，圆心随实际解变化；接缝切线由真实候选报告列出。修改相连点将一起重建相邻圆弧。半径、分支或整圈策略的显式修改会纳入同一笔事务。</p>{intent&&<p className="arc-source">移动来源：{intent.source==='map'?'地图拖动':intent.source==='rpl'?'路线位置表经纬度':'真实投影 X/Y 转换'} · 原路线点尚未修改</p>}
   <div className="table-wrap arc-moves"><table><thead><tr><th>实际移动点</th><th>目标经度 / °</th><th>目标纬度 / °</th><th>原经纬度 / °</th><th/></tr></thead><tbody>{moves.map((m,i)=>{const point=project.route.points.find(p=>p.id===m.point_id);return <tr key={m.point_id} data-point-id={m.point_id}><td><button className="text-button" onClick={()=>onSelectPoint(m.point_id)}>{point?.label||m.point_id}</button><small>{m.point_id} · {point?.constraint||'rigid'}</small></td><td><input aria-label={`${name(m.point_id)} 圆弧目标经度`} inputMode="decimal" value={m.longitude} onChange={e=>updateMove(i,'longitude',e.target.value)}/></td><td><input aria-label={`${name(m.point_id)} 圆弧目标纬度`} inputMode="decimal" value={m.latitude} onChange={e=>updateMove(i,'latitude',e.target.value)}/></td><td>{f(point?.longitude)}，{f(point?.latitude)}</td><td><button className="icon-button danger" title={'移除移动 '+m.point_id} onClick={()=>setMoves(rows=>rows.filter((_,n)=>n!==i))}><Trash2 size={13}/></button></td></tr>})}</tbody></table></div>
   <div className="page-actions"><select aria-label="添加圆弧移动点" value={addId} onChange={e=>setAddId(e.target.value)}><option value="">选择相连圆弧的实际 Rigid 点</option>{eligible.filter(p=>!moves.some(m=>m.point_id===p.id)).map(p=><option key={p.id} value={p.id}>{p.label} · {p.id}</option>)}</select><button className="secondary-button" disabled={!addId} onClick={()=>{const p=project.route.points.find(p=>p.id===addId);if(p){setMoves(rows=>[...rows,{point_id:p.id,longitude:String(p.longitude),latitude:String(p.latitude)}]);setAddId('')}}}><Plus size={13}/>添加移动目标</button><button className="secondary-button" onClick={()=>{setMoves(initialMoves(project,selected));setOptions(optionsFor(project));setAddId('');setError('')}}>载入当前圆弧点</button></div>
   <details className="arc-options"><summary>圆弧半径、分支与整圈策略</summary><div className="table-wrap"><table><thead><tr><th>实际 Rigid 骨架端点</th><th>半径 / m</th><th>有向分支</th><th>完整圆移动策略</th></tr></thead><tbody>{options.map((o,i)=><tr key={o.start_point_id+'-'+o.end_point_id}><td>{name(o.start_point_id)} → {name(o.end_point_id)}</td><td><label><input type="checkbox" aria-label={`修改圆弧半径 ${i+1}`} checked={o.use_radius} onChange={e=>updateOption(i,{use_radius:e.target.checked})}/>显式修改</label><input type="number" aria-label={`重建圆弧半径 ${i+1}`} min={.001} max={1e6} step="any" disabled={!o.use_radius} value={o.radius_text} onChange={e=>updateOption(i,{radius_text:e.target.value})}/></td><td><select aria-label={`圆弧分支 ${i+1}`} value={o.branch} onChange={e=>updateOption(i,{branch:e.target.value as ArcOption['branch']})}><option value="preserve">保留原方向与短弧 / 长弧</option><option value="minor">短弧</option><option value="major">长弧</option><option value="left">左侧分支</option><option value="right">右侧分支</option></select></td><td><select aria-label={`整圈移动策略 ${i+1}`} value={o.full_circle_policy} onChange={e=>updateOption(i,{full_circle_policy:e.target.value as ArcOption['full_circle_policy']})}><option value="reject_move">默认拒绝完整圆移动</option><option value="preserve_endpoint_center_bearing">闭合端同移时保留端点至圆心方位</option></select></td></tr>)}</tbody></table></div><p className="chart-meta">180° 弧可能需要明确左右分支。完整圆仅保留原有向整圈；移动闭合端须显式选择完整圆策略，默认拒绝移动。单端移动不能自由闭合，服务返回实际 typed 错误。</p></details>
   {!options.length&&<div className="inline-warning">当前路径没有可重建的真实圆弧；先使用圆弧转向工具建立分段几何。</div>}{document.draft&&<div className="inline-warning">当前路径草稿正在核验，完成后再预览圆弧重建。</div>}
  </section>
  {error&&<div className="inline-warning arc-error" role="alert">{error}</div>}{candidate&&!current&&<div className="inline-warning arc-stale">输入、选中点、工作区或保存修订已改变；以下圆弧候选已失效，请重新预览。</div>}
  {candidate&&<section className="tool-result arc-preview"><div className="section-heading"><h3>完整圆弧重建候选</h3><div className="page-actions"><button className="secondary-button" onClick={download}><Download size={13}/>下载圆弧候选</button><button className="primary-button" disabled={!current||busy||pending||!candidate.output.tool_report.changed} onClick={apply}><Check size={13}/>应用圆弧候选</button></div></div>{!candidate.output.tool_report.changed&&<p className="explanation">本次实际核验未改变路线，不产生可应用修改。</p>}
   <div className="tool-summary"><div><span>实际表面长度 / m</span><strong>{f(candidate.output.tool_report.before.surface_length_m)} → {f(candidate.output.tool_report.after.surface_length_m)}</strong></div><div><span>真实路线点数</span><strong>{candidate.output.tool_report.before.point_count} → {candidate.output.tool_report.after.point_count}</strong></div><div><span>重建圆弧</span><strong>{candidate.output.tool_report.arc_changes.length}</strong></div><div><span>实际制造边界点</span><strong>{candidate.output.tool_report.generated_marker_ids.length}</strong></div></div>
   <div className="table-wrap arc-changes"><table><thead><tr><th>实际圆弧</th><th>原圆心 → 候选圆心 / °</th><th>半径 / m</th><th>有向转角 / °</th><th>实际弧长与重建证据</th></tr></thead><tbody>{candidate.output.tool_report.arc_changes.map((r,i)=><tr key={i} data-arc-change={i}><td>{name(r.start_point_id)} → {name(r.end_point_id)}<small>原分段索引：{r.source_leg_indexes.join('，')}</small></td><td>{f(r.old_geometry.center)}<small>→ {f(r.new_geometry.center)}</small></td><td>{f(r.old_geometry.radius_m)} → {f(r.new_geometry.radius_m)}</td><td>{f(r.old_geometry.sweep_deg)} → {f(r.new_geometry.sweep_deg)}</td><td>{Object.entries(r.evidence).filter(([k])=>['length_m','new_minor_major','endpoint_radius_errors_m','end_binding_errors_m','start_tangent_deg','end_tangent_deg'].includes(k)).map(([k,v])=><div key={k}>{labels[k]||k}：{f(v)}</div>)}<details><summary>实际接缝、数值残差与预算</summary><pre>{JSON.stringify({evidence:r.evidence,budget:r.budget},null,2)}</pre></details></td></tr>)}</tbody></table></div>
   <div className="table-wrap arc-joins"><table><thead><tr><th>实际接缝点</th><th>原入切向 / °</th><th>候选入切向 / °</th><th>原出切向 / °</th><th>候选出切向 / °</th><th>原转角 / °</th><th>候选转角 / °</th></tr></thead><tbody>{candidate.output.tool_report.joins.map(r=><tr key={r.point_id} data-point-id={r.point_id}><td>{name(r.point_id)}</td><td>{f(r.before.incoming_tangent_deg)}</td><td>{f(r.after.incoming_tangent_deg)}</td><td>{f(r.before.outgoing_tangent_deg)}</td><td>{f(r.after.outgoing_tangent_deg)}</td><td>{f(r.before.turn_deg)}</td><td>{f(r.after.turn_deg)}</td></tr>)}</tbody></table></div><p className="chart-meta">入切向为实际前段到达端切线，出切向为实际后段起点切线。端点缺少邻腿时显示“—”；本操作不隐含保持接缝光滑。</p>
   <div className="tool-summary arc-manufacturing">{Object.entries(candidate.output.tool_report.manufacturing).filter(([,v])=>v==null||['number','string','boolean'].includes(typeof v)).map(([k,v])=><div key={k}><span>{labels[k]||k}</span><strong>{typeof v==='string'?labels[v]||v:f(v)}</strong></div>)}</div>{Array.isArray(candidate.output.tool_report.manufacturing.by_cable_type)&&<div className="table-wrap"><table><thead><tr><th>缆型</th><th>原制造量 / m</th><th>候选制造量 / m</th><th>变化 / m</th></tr></thead><tbody>{candidate.output.tool_report.manufacturing.by_cable_type.map((r:any)=><tr key={r.cable_type_id}><td>{r.cable_type_id}</td><td>{f(r.before_m)}</td><td>{f(r.after_m)}</td><td>{f(r.delta_m)}</td></tr>)}</tbody></table></div>}
   {(['profile_invalidation','side_slopes_invalidation'] as const).map(k=>{const r=candidate.output.tool_report[k];return r&&<div className="inline-warning arc-invalidation" key={k}><strong>{k==='profile_invalidation'?'原测深剖面':'原侧坡采样'}</strong> · {r.invalidated?'已失效，须实际重新采样；不补造水深':r.present?'未失效':'没有旧样本'}</div>})}{candidate.output.warnings.map((w,i)=><div className="inline-warning" key={i}>{typeof w==='string'?w:w.message||JSON.stringify(w)}</div>)}
   {previewProject&&actual&&<><div className="arc-preview-map"><MapView project={previewProject} analysis={actual} analysisReady geometry={actual.route_geometry?.coordinates} geometrySegments={actual.route_geometry_segments} selected={candidate.output.result_selection_point_id} onSelect={()=>{}} onMove={()=>Promise.resolve(false)} onAdd={()=>{}} fitVersion={1} editable={false} allowAdd={false}/></div><ProfileChart analysis={actual} selected={candidate.output.result_selection_point_id} onSelect={()=>{}}/><div className="table-wrap arc-result-rpl"><table><thead><tr><th>实际路线点</th><th>表面 KP / m</th><th>电缆 KP / m</th><th>水深 / m</th><th>实际接缝转角 / °</th><th>后续几何</th></tr></thead><tbody>{previewProject.route.points.map((p,i)=>{const r=actual.rpl.find(row=>row.id===p.id);return <tr key={p.id} data-point-id={p.id}><td>{p.label}</td><td>{f(r?.kp_m)}</td><td>{f(r?.cable_kp_m)}</td><td>{f(r?.depth_m)}</td><td>{f(r?.turn_deg)}</td><td>{previewProject.route.legs[i]?.geometry?.type==='circular_arc'?'真实圆弧':i<previewProject.route.legs.length?previewProject.route.curve:'—'}</td></tr>})}</tbody></table></div></>}
   <details><summary>完整服务核验、制造接缝与失效报告</summary><pre>{JSON.stringify({operation:candidate.output.operation,tool_report:candidate.output.tool_report,workspace_report:candidate.output.report,warnings:candidate.output.warnings},null,2)}</pre></details>
  </section>}
 </main>;
}
