import type {Analysis,Project} from './types';
import {Activity,GitBranch} from 'lucide-react';
const fmt=(v:unknown,d=2)=>typeof v==='number'?v.toLocaleString('zh-CN',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
export function ProfileChart({analysis,selected,onSelect}:{analysis:Analysis|null;selected:string|null;onSelect:(id:string)=>void}){
  const data=analysis?.profile||[],rpl=analysis?.rpl||[],w=1000,h=185,left=50,right=22,top=18,bottom=35;
  const valid=data.filter(p=>typeof p.depth_m==='number'),maxX=Math.max(...data.map(p=>p.kp_m),1),maxY=Math.max(...valid.map(p=>p.depth_m),100)*1.1;
  const x=(v:number)=>left+v/maxX*(w-left-right),y=(v:number)=>top+v/maxY*(h-top-bottom);
  let path='',prev=false;for(const p of data){if(typeof p.depth_m!=='number'){prev=false;continue}path+=`${prev?'L':'M'}${x(p.kp_m)},${y(p.depth_m)} `;prev=true}
  return <div className="chart-card"><div className="panel-heading"><span><Activity size={15}/>海底剖面 <small>SEABED PROFILE</small></span><span className="chart-meta">水深向下为正 · 表面 KP / km</span></div>{valid.length?<svg viewBox={`0 0 ${w} ${h}`} className="profile-svg" role="img" aria-label="海底水深剖面"><defs><linearGradient id="profileFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#0e8b87" stopOpacity=".05"/><stop offset="1" stopColor="#0e8b87" stopOpacity=".2"/></linearGradient></defs>{[0,.25,.5,.75,1].map(f=><g key={f}><line x1={left} x2={w-right} y1={y(f*maxY)} y2={y(f*maxY)} stroke="#e2e9ed"/><text x={left-9} y={y(f*maxY)+4} textAnchor="end">{Math.round(f*maxY)} m</text><line x1={x(f*maxX)} x2={x(f*maxX)} y1={top} y2={h-bottom} stroke="#eaf0f3"/><text x={x(f*maxX)} y={h-12} textAnchor="middle">{fmt(f*maxX/1000,1)}</text></g>)}<path d={path} fill="none" stroke="#11847e" strokeWidth="2.5"/>{rpl.filter(p=>typeof p.depth_m==='number').map(p=><g key={p.id} onClick={()=>onSelect(p.id)} className="chart-point"><line x1={x(p.kp_m)} x2={x(p.kp_m)} y1={top} y2={h-bottom} stroke={p.id===selected?'#d89a45':'transparent'} strokeDasharray="4 4"/><circle cx={x(p.kp_m)} cy={y(p.depth_m)} r={p.id===selected?5:3} fill={p.id===selected?'#d89a45':'#11847e'}/><title>{p.label} · KP {fmt(p.kp_m/1000)} km · {fmt(p.depth_m)} m</title></g>)}</svg>:<div className="chart-empty">导入 KP–Depth 测深剖面后显示海底曲线。未测水深不会作为零处理。</div>}</div>;
}
export function SLD({analysis,project}:{analysis:Analysis|null;project:Project}){
  const items=(analysis?.sld||[]).filter(s=>s.kind==='cable'),max=Math.max(analysis?.summary.cable_length_m||1,1),colors=['#11847e','#2c6285','#dea345','#7b84a9'];
  return <div className="chart-card sld-card"><div className="panel-heading"><span><GitBranch size={15}/>电缆单线图 <small>SLD</small></span><span className="chart-meta">电缆累计距离 / km</span></div><svg className="sld-svg" viewBox="0 0 1000 116" role="img" aria-label="电缆装配单线图"><line x1="40" y1="54" x2="960" y2="54" stroke="#dfe7eb" strokeWidth="11"/>{items.map((s,i)=>{const start=40+s.start_m/max*920,end=40+s.end_m/max*920;return <g key={i}><line x1={start} y1="54" x2={end} y2="54" stroke={colors[project.cable_types.findIndex(c=>c.id===s.cable_type_id)%colors.length]||colors[0]} strokeWidth="9"/><line x1={start} y1="43" x2={start} y2="65" stroke="#102b3b"/><text x={(start+end)/2} y="32" textAnchor="middle">{s.cable_type_id}</text><title>{s.name} · {fmt((s.end_m-s.start_m)/1000)} km</title></g>})}{(analysis?.sld||[]).filter(s=>s.kind==='body').map((b,i)=><g key={b.id||i}><path d={`M ${40+b.start_m/max*920} 44 l 10 10 l -10 10 l -10 -10 Z`} fill="#e6ac54" stroke="#fff"/><text x={40+b.start_m/max*920} y="90" textAnchor="middle">{b.name}</text><title>{b.name} · KP {fmt(b.start_m/1000)} km</title></g>)}{(analysis?.sld||[]).filter(s=>s.kind==='reference').map((r,i)=><g key={r.id||i}><line x1={40+r.start_m/max*920} x2={40+r.start_m/max*920} y1="38" y2="76" stroke="#6d82af" strokeWidth="2" strokeDasharray="3 2"/><text x={40+r.start_m/max*920} y="80" textAnchor="middle">{r.name}</text><title>{r.name} · 制造参考 · 不占长度</title></g>)}<circle cx="40" cy="54" r="7" fill="#fff" stroke="#102b3b" strokeWidth="2"/><circle cx="960" cy="54" r="7" fill="#fff" stroke="#102b3b" strokeWidth="2"/><text x="40" y="108">0.000 km</text><text x="960" y="108" textAnchor="end">{fmt(max/1000,3)} km</text></svg></div>;
}
