import ArcEditPanel from './ArcEditPanel';
import type {ArcEditContext,ArcMove} from './arcEdits';
import {useEffect,useRef,useState} from 'react';
import {Scissors,Combine,Waypoints,ArrowRightLeft,Layers,Calculator,Play,Check,Download,Plus,Trash2,ChevronRight,ArrowUp,ArrowDown,FolderOpen,Mountain} from 'lucide-react';
import {NumberField} from './fields';
import {request} from './api';
import TerrainPanel from './TerrainPanel';
import TerrainSourcesPanel from './TerrainSourcesPanel';
import type {WorkspaceTerrainContext} from './WorkspaceTerrainPreview';
import ProjectedCoordinateEditor from './ProjectedCoordinateEditor';
import RouteSearch from './RouteSearch';
import ConstraintPanel from './ConstraintPanel';
import SurveyPanel from './SurveyPanel';
import SideSlopesPanel from './SideSlopesPanel';
import AutomaticRulesPanel from './AutomaticRulesPanel';
import type {AutomaticRulesContext} from './AutomaticRulesPanel';
import AltercourseTools from './AltercourseTools';
import type {AltercourseContext} from './AltercourseTools';
import type {Project,Analysis} from './types';
const tools=[{id:'arc-edit',name:'圆弧端点编辑',sub:'WGS84 ARC RECONSTRUCTION',icon:Waypoints},{id:'altercourse',name:'转向点处理',sub:'SPLIT AC / RADIUS AC',icon:Scissors},{id:'automatic-rules',name:'自动规则检查',sub:'AUTOMATIC RULE CHECKER',icon:Check},{id:'side-slopes',name:'侧坡与坡度规则',sub:'SIDE SLOPES & KP RULES',icon:Mountain},{id:'terrain-sources',name:'多源测深库',sub:'SOURCE PRIORITY & PROVENANCE',icon:Layers},{id:'coordinates',name:'投影坐标编辑',sub:'HORIZONTAL CRS',icon:ArrowRightLeft},{id:'survey',name:'实敷调查对账',sub:'AS-LAID SURVEY',icon:Waypoints},{id:'constraints',name:'约束点与制造域',sub:'PATH LINK DOMAINS',icon:Layers},{id:'subdivide',name:'路线加密',sub:'SUBDIVISION',icon:Waypoints},{id:'depth-cables',name:'按水深分配缆型',sub:'DEPTH BANDS',icon:Layers},{id:'slack-template',name:'余缆模板',sub:'SLACK TEMPLATE',icon:ArrowRightLeft},{id:'split',name:'工程拆分',sub:'SPLIT PROJECT',icon:Scissors},{id:'merge',name:'工程合并',sub:'MERGE PROJECTS',icon:Combine},{id:'routing',name:'避障候选搜索',sub:'INDEPENDENT A*',icon:Waypoints},{id:'dtm',name:'测深网格与地形',sub:'DIGITAL TERRAIN',icon:Mountain},{id:'geodetic',name:'大地计算器',sub:'GEODETIC',icon:Calculator}];
type Band={min_depth_m:number;max_depth_m:number|null;cable_type_id:string;slack_pct:number;slack_basis:string};
const labels:Record<string,string>={operation:'操作',mode:'模式',inserted_points:'新增点数',original_points:'原始点数',new_points:'结果点数',changed_legs:'修改分段',fixed_policy:'固定长度策略',split_kp_m:'拆分表面 KP / m',split_cable_kp_m:'拆分电缆 KP / m',surface_length_m:'表面长度 / m',bottom_length_m:'海底长度 / m',cable_length_m:'电缆长度 / m',material_length_m:'缆材长度 / m',body_length_m:'缆体长度 / m',cost_total:'费用合计',distance_m:'距离 / m',bearing_deg:'正向方位角 / °',reverse_bearing_deg:'反向方位角 / °',longitude:'经度 / °E',latitude:'纬度 / °N',name:'名称',sources:'来源工程',new_connectors:'新增连接段',curve:'曲线模型',warning_count:'审查提示数',band_count:'水深带数量'};
function value(v:any):string{return v==null?'—':typeof v==='number'?v.toLocaleString('zh-CN',{maximumFractionDigits:4}):typeof v==='boolean'?(v?'是':'否'):Array.isArray(v)?v.map(value).join(', '):typeof v==='object'?JSON.stringify(v):String(v)}
function download(data:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
export default function EngineeringTools({project,analysis,selected,onApply,notify,workspaceTerrain,coordinateContextKey,onCoordinateApply,onSideSlopesApply,analysisCurrent=true,automaticRulesContext,altercourseContext,arcEditContext,onArcEdit}:{project:Project;analysis:Analysis|null;analysisCurrent?:boolean;selected:string|null;onApply:(p:Project)=>void;notify:(text:string,error?:boolean)=>void;workspaceTerrain?:WorkspaceTerrainContext;coordinateContextKey?:string;onCoordinateApply?:(p:Project,key:string)=>boolean;onSideSlopesApply?:(p:Project,key:string,isCurrent?:()=>boolean)=>boolean|Promise<boolean>;automaticRulesContext?:AutomaticRulesContext;altercourseContext?:AltercourseContext;arcEditContext?:ArcEditContext;onArcEdit?:(moves:ArcMove[],key:string)=>boolean}){
  const latestProject=useRef(project);latestProject.current=project;
  const [kind,setKind]=useState('subdivide'),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[spacing,setSpacing]=useState(10000),[subMode,setSubMode]=useState('same_curve'),[range,setRange]=useState<{start:number;end:number|null}>({start:0,end:null}),[bands,setBands]=useState<Band[]>(project.cable_types.map((c,i)=>({min_depth_m:i===0?0:[100,500,1500][Math.min(i-1,2)]||1500,max_depth_m:i===project.cable_types.length-1?null:[100,500,1500][Math.min(i,2)]||1500,cable_type_id:c.id,slack_pct:project.route.slack_pct,slack_basis:'surface'}))),[templates,setTemplates]=useState<Record<string,{slack_pct:number;slack_basis:string}>>(Object.fromEntries(project.cable_types.map(c=>[c.id,{slack_pct:project.route.slack_pct,slack_basis:'surface'}]))),[fixedPolicy,setFixedPolicy]=useState('keep'),[splitBy,setSplitBy]=useState('point'),[splitPoint,setSplitPoint]=useState(Math.max(1,Math.min(project.route.points.length-2,project.route.points.findIndex(p=>p.id===selected)))),[splitKP,setSplitKP]=useState((analysis?.summary.surface_length_m||0)/2),[available,setAvailable]=useState<any[]>([]),[mergeIds,setMergeIds]=useState<string[]>([]),[includeCurrent,setIncludeCurrent]=useState(true),[connect,setConnect]=useState(false),[joinTolerance,setJoinTolerance]=useState(.01),[mergeName,setMergeName]=useState('合并工程'),[resultSignature,setResultSignature]=useState(''),[geodeticMode,setGeodeticMode]=useState('inverse'),[geo,setGeo]=useState({longitude1:project.route.points[0].longitude,latitude1:project.route.points[0].latitude,longitude2:project.route.points.at(-1)!.longitude,latitude2:project.route.points.at(-1)!.latitude,distance_m:10000,bearing_deg:90,curve:'rhumb'});
  useEffect(()=>{if(kind==='merge')request<any[]>('/projects').then(setAvailable).catch(e=>notify(String(e),true));},[kind]);
  const inputSignature=JSON.stringify({project,kind,spacing,subMode,range,bands,templates,fixedPolicy,splitBy,splitPoint,splitKP,mergeIds,includeCurrent,connect,joinTolerance,mergeName,geodeticMode,geo});const stale=!!result&&inputSignature!==resultSignature;
  const ranged=(config:any)=>({...config,start_kp_m:range.start,...(range.end===null?{}:{end_kp_m:range.end})});
  useEffect(()=>setResult(null),[project]);
  async function run(){setBusy(true);setResult(null);const snapshot=inputSignature;try{let config:any={};if(kind==='subdivide')config={spacing_m:spacing,mode:subMode};if(kind==='depth-cables')config=ranged({bands,convert_fixed:fixedPolicy==='convert'});if(kind==='slack-template')config=ranged({by_cable_type:templates,fixed_policy:fixedPolicy});if(kind==='split')config=splitBy==='point'?{point_index:splitPoint}:{kp_m:splitKP};if(kind==='merge'){const sources=await Promise.all(mergeIds.map(pid=>request<Project>('/projects/'+encodeURIComponent(pid))));config={projects:[...(includeCurrent?[project]:[]),...sources],connect_gaps:connect,join_tolerance_m:joinTolerance,name:mergeName}}
    if(kind==='geodetic')config=geodeticMode==='inverse'?{longitude1:geo.longitude1,latitude1:geo.latitude1,longitude2:geo.longitude2,latitude2:geo.latitude2,curve:geo.curve}:{from:{longitude:geo.longitude1,latitude:geo.latitude1},distance_m:geo.distance_m,bearing_deg:geo.bearing_deg,curve:geo.curve};
    const output=await request<any>('/tools/'+kind,{project,config});if(latestProject.current!==project)throw new Error('工程已在计算期间修改，请重新生成预览');setResult(output);setResultSignature(snapshot);notify('工程工具计算完成，请查看结果')
  }catch(e){notify(e instanceof Error?e.message:String(e),true)}finally{setBusy(false)}}
  async function saveVariants(){if(!result?.projects)return;setBusy(true);try{const saved=[];for(const p of result.projects)saved.push(await request<any>('/projects',p));setResult({...result,projects:saved.map(v=>v.project),saved:true});notify(`已保存 ${saved.length} 条拆分工程`)}catch(e){notify(String(e),true)}finally{setBusy(false)}}
  function apply(p:Project){if(stale){notify('工具参数已更改，请重新计算',true);return}onApply(p);setResult(null);notify('计算结果已应用到工作空间')}
  const report=result?.report||result;const invariants=report?.invariants;const isGeo=kind==='geodetic';
  return <div className="engineering-layout"><aside className="engineering-menu"><div className="section-label">工程工具</div>{tools.map(t=><button className={kind===t.id?'active':''} key={t.id} onClick={()=>{setKind(t.id);setResult(null)}}><t.icon size={17}/><span><strong>{t.name}</strong><small>{t.sub}</small></span><ChevronRight size={13}/></button>)}<div className="explanation">工具先生成可检查的结果，应用后可撤销。拆分后的两条工程可分别保存和继续编辑。</div></aside>{kind==='arc-edit'?arcEditContext?<ArcEditPanel {...arcEditContext} project={project}/>:<main className="engineering-main"><div className="inline-warning">工作区上下文尚未就绪</div></main>:kind==='altercourse'?altercourseContext?<AltercourseTools {...altercourseContext} project={project} analysis={analysis} analysisCurrent={analysisCurrent}/>:<main className="engineering-main"><div className="inline-warning">工作区上下文尚未就绪，请等待载入完成。</div></main>:kind==='automatic-rules'?automaticRulesContext?<AutomaticRulesPanel {...automaticRulesContext} notify={notify}/>:<main className="engineering-main"><div className="inline-warning">工作区上下文尚未就绪，请等待载入完成。</div></main>:kind==='side-slopes'?<SideSlopesPanel project={project} analysis={analysisCurrent?analysis:null} contextKey={coordinateContextKey} pending={workspaceTerrain?.pending} onApply={(p,key,isCurrent)=>onSideSlopesApply?onSideSlopesApply(p,key,isCurrent):onCoordinateApply&&key?onCoordinateApply(p,key):onApply(p)} notify={notify}/>:kind==='terrain-sources'?<TerrainSourcesPanel project={project} onApply={onApply} notify={notify} workspaceTerrain={workspaceTerrain}/>:kind==='coordinates'?<ProjectedCoordinateEditor selectionRevision={arcEditContext?.selectionRevision} onArcEdit={onArcEdit} project={project} selected={selected} contextKey={coordinateContextKey} onApply={(p,key)=>onCoordinateApply&&key?onCoordinateApply(p,key):onApply(p)} notify={notify}/>:kind==='survey'?<SurveyPanel project={project} onApply={onApply} notify={notify}/>:kind==='constraints'?<ConstraintPanel project={project} analysis={analysis} onApply={onApply} notify={notify}/>:kind==='routing'?<RouteSearch project={project} analysis={analysis} onApply={onApply} notify={notify}/>:kind==='dtm'?<TerrainPanel project={project} onApply={onApply} notify={notify}/>:<main className="engineering-main"><div className="page-heading"><div><small>ENGINEERING UTILITIES</small><h2>{tools.find(t=>t.id===kind)?.name}</h2><p>{kind==='subdivide'?'沿选定路线按距离插点；保留材料分段和剖面关联。':kind==='depth-cables'?'根据有效海床水深，在水深带边界处插点并分配缆型。':kind==='slack-template'?'按缆型设置余缆目标，可限定表面 KP 范围。':kind==='split'?'在内部路线点或给定表面 KP 拆分，组件与材料里程随子工程重新定位。':kind==='merge'?'依次连接工程路线，核对接续点、缆型与费用条件。':'WGS84 恒向线或椭球大地线的距离、方位与正反算。'}</p></div><button className="primary-button" onClick={run} disabled={busy}><Play size={14}/>{busy?'正在计算…':'计算结果'}</button></div>
    <div className="tool-form settings-card">
    {kind==='subdivide'&&<div className="tool-fields"><label>目标点间距 / m<NumberField value={spacing} min={1} onChange={v=>setSpacing(v??10000)}/></label><label>加密方式<select value={subMode} onChange={e=>setSubMode(e.target.value)}><option value="same_curve">沿现有曲线加密</option><option value="geodesic_as_rhumb">大地线插点后以恒向线连接</option></select></label></div>}
    {(kind==='depth-cables'||kind==='slack-template')&&<><div className="tool-fields"><label>起始表面 KP / m<NumberField value={range.start} min={0} onChange={v=>setRange({...range,start:v??0})}/></label><label>终止表面 KP / m（空白为全线）<NumberField value={range.end} nullable min={0} onChange={v=>setRange({...range,end:v})}/></label><label>固定缆长区间<select value={fixedPolicy} onChange={e=>setFixedPolicy(e.target.value)}><option value="keep">保留制造缆长</option><option value="convert">转为柔性模式</option>{kind==='slack-template'&&<option value="reject">检测到固定区间时停止</option>}</select></label></div>
    {kind==='depth-cables'?<><div className="table-wrap"><table><thead><tr><th>最小水深 / m</th><th>最大水深 / m</th><th>缆型</th><th>目标余缆 / %</th><th>基准</th><th/></tr></thead><tbody>{bands.map((b,i)=><tr key={i}><td><NumberField value={b.min_depth_m} min={0} onChange={v=>setBands(bands.map((x,j)=>j===i?{...x,min_depth_m:v??0}:x))}/></td><td><NumberField value={b.max_depth_m} nullable min={0} onChange={v=>setBands(bands.map((x,j)=>j===i?{...x,max_depth_m:v}:x))}/></td><td><select value={b.cable_type_id} onChange={e=>setBands(bands.map((x,j)=>j===i?{...x,cable_type_id:e.target.value}:x))}>{project.cable_types.map(c=><option key={c.id} value={c.id}>{c.id} · {c.name}</option>)}</select></td><td><NumberField value={b.slack_pct} onChange={v=>setBands(bands.map((x,j)=>j===i?{...x,slack_pct:v??0}:x))}/></td><td><select value={b.slack_basis} onChange={e=>setBands(bands.map((x,j)=>j===i?{...x,slack_basis:e.target.value}:x))}><option value="surface">表面</option><option value="bottom">海底</option></select></td><td><button className="icon-button" title="移除水深带" onClick={()=>setBands(bands.filter((_,j)=>j!==i))}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div><button className="secondary-button" onClick={()=>setBands([...bands,{min_depth_m:bands.at(-1)?.max_depth_m??3000,max_depth_m:null,cable_type_id:project.cable_types.at(-1)!.id,slack_pct:project.route.slack_pct,slack_basis:'surface'}])}><Plus size={14}/>新增水深带</button><div className="explanation">最大深度留空代表无上限。水深带不能重叠；海底基准需要有效剖面。</div></>:<div className="table-wrap"><table><thead><tr><th>缆型</th><th>目标余缆 / %</th><th>余缆基准</th></tr></thead><tbody>{project.cable_types.map(c=><tr key={c.id}><td>{c.id} · {c.name}</td><td><NumberField value={templates[c.id]?.slack_pct??project.route.slack_pct} onChange={v=>setTemplates({...templates,[c.id]:{...templates[c.id],slack_pct:v??0}})}/></td><td><select value={templates[c.id]?.slack_basis||'surface'} onChange={e=>setTemplates({...templates,[c.id]:{...templates[c.id],slack_basis:e.target.value}})}><option value="surface">表面</option><option value="bottom">海底</option></select></td></tr>)}</tbody></table></div>}</>}
    {kind==='split'&&<div className="tool-fields"><label>拆分定位方式<select value={splitBy} onChange={e=>setSplitBy(e.target.value)}><option value="point">路线点</option><option value="kp">表面 KP</option></select></label>{splitBy==='point'?<label>内部路线点<select value={splitPoint} onChange={e=>setSplitPoint(Number(e.target.value))}>{project.route.points.slice(1,-1).map((p,i)=><option value={i+1} key={p.id}>{String(i+2).padStart(2,'0')} · {p.label}</option>)}</select></label>:<label>拆分表面 KP / m<NumberField value={splitKP} min={0} onChange={v=>setSplitKP(v??0)}/></label>}</div>}
    {kind==='merge'&&<><div className="tool-fields"><label>结果工程名称<input value={mergeName} onChange={e=>setMergeName(e.target.value)}/></label><label>接续容差 / m<NumberField value={joinTolerance} min={0} onChange={v=>setJoinTolerance(v??.01)}/></label><label>接续不连续处<select value={String(connect)} onChange={e=>setConnect(e.target.value==='true')}><option value="false">要求端点连续</option><option value="true">新增连接分段</option></select></label></div><label className="checkbox-label"><input type="checkbox" checked={includeCurrent} onChange={e=>setIncludeCurrent(e.target.checked)}/>当前工作空间作为第一条路线</label><div className="merge-sources"><div><h3>可用保存工程</h3>{available.filter(p=>!mergeIds.includes(p.id)).map(p=><button key={p.id} onClick={()=>setMergeIds([...mergeIds,p.id])}><FolderOpen size={14}/><span>{p.name}</span><Plus size={14}/></button>)}{!available.length&&<p>尚无已保存工程。</p>}</div><div><h3>接续顺序</h3>{includeCurrent&&<div className="merge-item"><strong>当前</strong><span>{project.name}</span></div>}{mergeIds.map((pid,i)=><div className="merge-item" key={pid}><strong>{i+1+(includeCurrent?1:0)}</strong><span>{available.find(p=>p.id===pid)?.name||pid}</span><button title="上移" disabled={i===0} onClick={()=>{const next=[...mergeIds];[next[i-1],next[i]]=[next[i],next[i-1]];setMergeIds(next)}}><ArrowUp size={12}/></button><button title="下移" disabled={i===mergeIds.length-1} onClick={()=>{const next=[...mergeIds];[next[i+1],next[i]]=[next[i],next[i+1]];setMergeIds(next)}}><ArrowDown size={12}/></button><button title="移除来源" onClick={()=>setMergeIds(mergeIds.filter(v=>v!==pid))}><XIcon/></button></div>)}</div></div></>}
    {isGeo&&<><div className="tool-fields"><label>计算方法<select value={geodeticMode} onChange={e=>setGeodeticMode(e.target.value)}><option value="inverse">反算：坐标 → 距离与方位</option><option value="direct">正算：距离与方位 → 终点</option></select></label><label>路线模型<select value={geo.curve} onChange={e=>setGeo({...geo,curve:e.target.value})}><option value="rhumb">WGS84 恒向线</option><option value="geodesic">WGS84 椭球大地线</option></select></label></div><div className="tool-fields">{([['longitude1','起点经度 / °E'],['latitude1','起点纬度 / °N'],...(geodeticMode==='inverse'?[['longitude2','终点经度 / °E'],['latitude2','终点纬度 / °N']]:[['distance_m','正算距离 / m'],['bearing_deg','正算方位 / °']])] as [keyof typeof geo,string][]).map(([key,label])=><label key={key}>{label}<NumberField value={geo[key] as number} onChange={v=>setGeo({...geo,[key]:v??0})}/></label>)}</div></>}
    </div>
    {result&&<div className="tool-result"><div className="section-heading"><h3>计算结果</h3><div className="page-actions"><button className="secondary-button" onClick={()=>download(result,`OceanRoute-${kind}-result.json`)}><Download size={14}/>下载结果</button>{result.project&&<button className="primary-button" disabled={stale} onClick={()=>apply(result.project)}><Check size={14}/>应用到工作空间</button>}{result.projects&&!result.saved&&<button className="primary-button" onClick={saveVariants} disabled={busy||stale}><Check size={14}/>保存两条子工程</button>}</div></div>{stale&&<div className="inline-warning">工具输入已修改，当前为上次结果；重新计算后才能应用或保存。</div>}{invariants&&<div className="table-wrap"><table><thead><tr><th>检查项</th><th>操作前</th><th>操作后</th><th>变化</th></tr></thead><tbody>{Object.entries(invariants).map(([key,v])=>{const row=v as any;return <tr key={key}><td>{labels[key]||key}</td><td>{value(row.before)}</td><td>{value(row.after)}</td><td>{value(row.delta)}</td></tr>})}</tbody></table></div>}<div className="tool-summary">{Object.entries(report||{}).filter(([key])=>!['invariants','project','projects','points','warnings','segments'].includes(key)).map(([key,v])=><div key={key}><span>{labels[key]||key}</span><strong>{value(v)}</strong></div>)}</div>{isGeo&&result.to&&<div className="geodetic-destination"><span>计算终点</span><strong>{value(result.to.longitude)}° E / {value(result.to.latitude)}° N</strong></div>}{result.projects&&<div className="variant-grid">{result.projects.map((p:Project,i:number)=><div className="variant-card" key={p.id}><strong>{p.name}</strong><p>{p.route.points.length} 个路线点 · {p.bodies.length} 个组件</p><button className="secondary-button" disabled={stale} onClick={()=>apply(p)}>打开子工程 {i+1}<ChevronRight size={14}/></button></div>)}</div>}{(result.warnings||[]).map((w:any,i:number)=><div className="inline-warning" key={i}>{typeof w==='string'?w:w.message}</div>)}</div>}
    {!result&&<div className="tool-empty"><Calculator size={27}/><span>设置参数并计算，检查结果后应用到当前工程。</span></div>}
  </main>}</div>;
}
function XIcon(){return <Trash2 size={12}/>}
