import './equilibrium.css';
import {useEffect,useRef,useState} from 'react';
import {request} from './api';
import type {Project} from './types';
const f=(v:any):string=>v==null?'不适用':typeof v==='number'?v.toLocaleString('zh-CN',{maximumFractionDigits:8}):typeof v==='boolean'?v?'是':'否':Array.isArray(v)?v.map(f).join(', '):String(v);
export function EquilibriumDiagnostics({value}:{value:any}){const proof=value?.provenance||value?.initialization;if(proof?.schema!=='oceanroute.dynamic.initial-equilibrium.provenance.v1')return null;return <section className="sim-results equilibrium-diagnostics"><div className="panel-heading">实际定端初态求解与独立验收</div><div className="summary-fields">{[['初始活动自然库存 / m',proof.initial_material_length_m],['初态最老端制造里程 / m',proof.initial_suspended_material_m],['初态累计新放缆 / m',proof.initial_paid_out_m],['最大节点净力残差 / N',proof.verification?.max_node_force_residual_n],['力容限 / N',proof.verification?.force_tolerance_n],['初始化归一化计算额度',proof.solver?.estimated_work_units],['初始化额度上限',proof.solver?.max_work_units],['实际静力迭代',proof.solver?.iterations],['实际函数评估',proof.solver?.function_evaluations]].map(([label,v])=><div key={String(label)}><span>{label}</span><strong>{f(v)}</strong></div>)}</div><p className="chart-meta">真实求解、几何与力验收通过后才进入积分。初态为零节点速度；船舶运动与放缆从第一个真实内部步开始。固定锚端可离床，实际无接触时触地点与底张力不适用。不是施工历史重建或现场精度证明。</p><details><summary>完整初态来源、材料与力证据</summary><pre>{JSON.stringify(proof,null,2)}</pre></details></section>}
export default function EquilibriumInitialPanel({project,mode,onMode,text,onText,disabled,signature,buildConfig,onExample}:{project:Project;mode:string;onMode:(v:string)=>void;text:string;onText:(v:string)=>void;disabled:boolean;signature:string;buildConfig:()=>Record<string,any>;onExample:()=>void}){const [preview,setPreview]=useState<any>(null),[previewSignature,setPreviewSignature]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const latest=useRef(signature);latest.current=signature;const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);const current=preview&&signature===previewSignature;
async function prepare(){const snapshot=signature;setBusy(true);setPreview(null);setError('');try{const result=await request<any>('/simulation/prepare-equilibrium-initial',{project,config:buildConfig()});if(mounted.current&&latest.current===snapshot){setPreview(result);setPreviewSignature(snapshot)}}catch(e){if(mounted.current&&latest.current===snapshot)setError(e instanceof Error?e.message:String(e))}finally{if(mounted.current)setBusy(false)}}
return <details className="advanced-environment equilibrium-initial-settings" open={mode==='equilibrium'}><summary>动态初态来源</summary><label>新计算初态方法<select aria-label="动态初态方法" disabled={disabled} value={mode} onChange={e=>onMode(e.target.value)}><option value="approx">原水平悬链线 / 床面投影近似</option><option value="equilibrium">明确定端自然长 · 实际平衡求解</option></select></label>{disabled&&<p>续算保留完整状态及原始初态证据，不重新求解或替换初态。</p>}{mode==='equilibrium'&&<><label className="text-config">明确动态定端初态 JSON<textarea aria-label="明确动态定端初态 JSON" disabled={disabled} value={text} onChange={e=>onText(e.target.value)} spellCheck={false} placeholder={'{"schema":"oceanroute.dynamic.initial-equilibrium.v1","vessel_position_m":[0,0,0],"anchor_position_m":[-20,0,-10],"natural_length_m":25}'}/></label><p className="chart-meta">配套完整二维床格，坐标均为其局部米。声明自然材料长或逐段自然长；节点草图只作数值初值。初始活动区间要求同湿重 / EA、EI=0、无已投入实体、无流无波。未来混材与实体由实际材料模型处理；数值容限和计算预算超限明确拒绝。</p><button className="secondary-button" disabled={disabled||busy} onClick={prepare}>{busy?'实际求解和验收中…':'预备并独立验证动态初态'}</button>{error&&<div className="inline-warning equilibrium-initial-error" role="alert">{error}</div>}{preview&&!current&&<p className="inline-warning">输入已变，旧初态证据隐藏，请重新预备。</p>}{current&&<EquilibriumDiagnostics value={preview}/>}</>}<button className="secondary-button" disabled={disabled} onClick={onExample}>加载明确合成定端平衡动态算例</button></details>}
