import {useState} from 'react';
import {Plus} from 'lucide-react';
import {NumberField} from './fields';
import type {Workspace,WorkspaceResult} from './useWorkspaceDocument';

export default function NewWorkspacePath({workspace,disabled,onAction,notify}:{workspace:Workspace;disabled:boolean;onAction:(config:Record<string,any>)=>Promise<WorkspaceResult>;notify:(message:string,error?:boolean)=>void}){
 const [name,setName]=useState(''),[cable,setCable]=useState(''),[curve,setCurve]=useState('rhumb'),[slack,setSlack]=useState(0),[policy,setPolicy]=useState('independent'),[busy,setBusy]=useState(false),[points,setPoints]=useState([{longitude:null as number|null,latitude:null as number|null,depth_m:null as number|null},{longitude:null as number|null,latitude:null as number|null,depth_m:null as number|null}]);
 const complete=!!name.trim()&&workspace.cable_types.some(c=>c.id===cable)&&points.every(p=>p.longitude!==null&&p.latitude!==null);
 async function add(){if(!complete||disabled||busy)return;setBusy(true);try{const project={schema_version:1,id:crypto.randomUUID(),name:name.trim(),crs:'EPSG:4326',route:{id:crypto.randomUUID(),name:name.trim(),curve,mode:'flexible',slack_basis:'surface',slack_pct:slack,points:points.map((p,i)=>({...p,id:crypto.randomUUID(),label:i?'终点':'起点',note:''})),legs:[{cable_type_id:cable,slack_pct:slack,mode:'flexible',slack_basis:'surface'}]},cable_types:workspace.cable_types,layers:workspace.layers,terrain_sources:workspace.terrain_sources||[],bodies:[],profile:{samples:[],source:'用户明确输入；未提供测深时保留缺测'},costs:{currency:workspace.currency},rules:{}};const result=await onAction({action:'add_path',project,assembly_policy:policy});notify(result.warnings?.length?result.warnings.map((w:any)=>w.message||w).join('；'):'已按明确坐标加入第一条路线，原库存与共享资源保持')}catch(e){notify(e instanceof Error?e.message:String(e),true)}finally{setBusy(false)}}
 return <section className="settings-card new-workspace-path"><div className="section-heading"><div><h3>明确新增第一条路线</h3><p className="chart-meta">填写真实 WGS84 起终点并选择现有共享缆型。水深和材料物性未提供时保持缺失。</p></div></div><div className="tool-fields"><label>新增路线名称<input aria-label="空工作区新增路线名称" value={name} onChange={e=>setName(e.target.value)}/></label><label>选择当前共享缆型<select aria-label="空工作区新增路线缆型" value={cable} onChange={e=>setCable(e.target.value)}><option value="">请明确选择</option>{workspace.cable_types.map(c=><option key={c.id} value={c.id}>{c.name||c.id} · {c.id}</option>)}</select></label><label>几何模型<select value={curve} onChange={e=>setCurve(e.target.value)}><option value="rhumb">恒向线 Rhumb</option><option value="geodesic">WGS84 测地线</option></select></label><label>表面余缆 / %<NumberField value={slack} onChange={v=>setSlack(v??0)}/></label><label>新增路径的制造关系<select aria-label="空工作区新增制造关系" value={policy} onChange={e=>setPolicy(e.target.value)}><option value="independent">捕获独立装配 · 明确增加采购量</option><option value="unassigned">未绑定 · 只加入规划路线</option></select></label></div><div className="new-path-coordinates">{points.map((p,i)=><div key={i}><strong>{i?'终点':'起点'} · WGS84</strong>{([['longitude','经度 / °E',-180,180],['latitude','纬度 / °N',-90,90],['depth_m','水深 / m',0,undefined]] as const).map(([key,label,min,max])=><label key={key}>{label}<NumberField aria-label={`空工作区${i?'终点':'起点'}${label}`} value={p[key]} nullable min={min} max={max} onChange={value=>setPoints(points.map((point,j)=>j===i?{...point,[key]:value}:point))}/></label>)}</div>)}</div><p className="chart-meta">初始路线为柔性模式、表面余缆基准。未声明费用费率采用内核缺省 0；不由库存长度推断坐标或敷设路线。</p><button className="primary-button" disabled={disabled||busy||!complete} onClick={add}><Plus size={14}/>{busy?'正在核验新路线…':'核验并加入第一条路线'}</button></section>
}
