import type {ArcMove} from './arcEdits';
import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {Crosshair,Download,Minus,Plus,Play,MousePointer2,Trash2,X,LoaderCircle} from 'lucide-react';
import {request} from './api';
import {NumberField} from './fields';
import {layerOpacity,layerDrawingOrder} from './layerDisplay';
import {terrainDownload} from './TerrainSlicePanel';
import type {Analysis,Project,RuleLocationView} from './types';
import type {PathOverlay} from './MapView';
import {previewProjectedPointEdit,projectedPointLocked,removeRoutePoint,StaleProjectedEdit} from './projectedPointEdits';
import {ruleGeographicCircle} from './automaticRuleLocation';
type XY=[number,number];
type Camera={x:number;y:number;span:number};
type Props={project:Project;geometry?:number[][];geometrySegments?:number[][][];selected:string|null;onSelect:(id:string)=>void;fitVersion:number;pathOverlays:PathOverlay[];onPathPick?:(id:string)=>void;editable?:boolean;allowAdd?:boolean;contextKey?:string;analysis?:Analysis|null;analysisReady?:boolean;onProjectedApply?:(project:Project,expectedContext:string,selected:string|null)=>boolean|Promise<boolean>;ruleLocation?:RuleLocationView|null;onArcEdit?:(moves:ArcMove[],expectedContext:string)=>boolean};
type Gesture={kind:'pan'|'point'|'add';clientX:number;clientY:number;camera:Camera;pointerId:number;width:number;rect:DOMRect;pointId?:string;xy?:XY;context:string;inputs:string;moved:boolean};
type EditInfo={status:'processing'|'submitted'|'rejected';message:string;action?:string;target?:XY;actual?:XY;longitude?:number;latitude?:number;warnings?:any[];report?:any};
const f=(v:number)=>v.toLocaleString('zh-CN',{maximumFractionDigits:3});
function segmentsGeometry(segments:number[][][]){return segments.length===1?{type:'LineString',coordinates:segments[0]}:{type:'MultiLineString',coordinates:segments}}
function color(kind:string){return kind==='survey_measured'?'#208ca4':kind==='survey_residuals'?'#c66b73':['cable','routing_original'].includes(kind)?'#c59445':['restricted','exclusion','hazard','routing_blocked'].includes(kind)?'#bc5865':'#657ea6'}
function Geometry({geometry,toScreen,name,stroke,selectedPoint,onPick}:{geometry:any;toScreen:(p:XY)=>XY;name:string;stroke:string;selectedPoint?:boolean;onPick?:()=>void}){
 if(!geometry)return null;
 const line=(points:XY[],closed=false)=>points.map((p,i)=>{const q=toScreen(p);return `${i?'L':'M'} ${q[0]} ${q[1]}`}).join(' ')+(closed?' Z':'');
 const common={stroke,strokeWidth:selectedPoint?4:2,fill:'none',vectorEffect:'non-scaling-stroke' as const};
 const path=(d:string,polygon=false)=><path d={d} {...common} fill={polygon?stroke:'none'} fillOpacity={polygon?0.13:undefined} fillRule="evenodd" onPointerDown={e=>{if(onPick)e.stopPropagation()}} onClick={e=>{e.stopPropagation();onPick?.()}}><title>{name}</title></path>;
 switch(geometry.type){
 case 'FeatureCollection':return <>{geometry.features?.map((g:any,i:number)=><Geometry key={i} geometry={g} toScreen={toScreen} name={name} stroke={stroke} onPick={onPick}/>)}</>;
 case 'Feature':return <Geometry geometry={geometry.geometry} toScreen={toScreen} name={name} stroke={stroke} onPick={onPick}/>;
 case 'GeometryCollection':return <>{geometry.geometries?.map((g:any,i:number)=><Geometry key={i} geometry={g} toScreen={toScreen} name={name} stroke={stroke} onPick={onPick}/>)}</>;
 case 'Point':{const p=toScreen(geometry.coordinates);return <circle cx={p[0]} cy={p[1]} r={4} fill={stroke} onClick={e=>{e.stopPropagation();onPick?.()}}><title>{name}</title></circle>}
 case 'MultiPoint':return <>{geometry.coordinates.map((p:XY,i:number)=><Geometry key={i} geometry={{type:'Point',coordinates:p}} toScreen={toScreen} name={name} stroke={stroke} onPick={onPick}/>)}</>;
 case 'LineString':return path(line(geometry.coordinates));
 case 'MultiLineString':return <>{geometry.coordinates.map((p:XY[],i:number)=><g key={i}>{path(line(p))}</g>)}</>;
 case 'Polygon':return path(geometry.coordinates.map((p:XY[])=>line(p,true)).join(' '),true);
 case 'MultiPolygon':return <>{geometry.coordinates.map((rings:XY[][],i:number)=><g key={i}>{path(rings.map(p=>line(p,true)).join(' '),true)}</g>)}</>;
 default:return null;
 }
}
function gridStep(span:number){const raw=Math.max(1e-9,span/7),power=10**Math.floor(Math.log10(raw)),ratio=raw/power;return (ratio<=1?1:ratio<=2?2:ratio<=5?5:10)*power}
function activeBounds(result:any){const active=result?.routes?.find((r:any)=>r.role==='active');if(!active)return result?.bounds;const box=[Infinity,Infinity,-Infinity,-Infinity];function visit(coords:any){if(typeof coords?.[0]==='number'){box[0]=Math.min(box[0],coords[0]);box[1]=Math.min(box[1],coords[1]);box[2]=Math.max(box[2],coords[0]);box[3]=Math.max(box[3],coords[1])}else if(Array.isArray(coords))coords.forEach(visit)}visit(active.geometry.coordinates);return Number.isFinite(box[0])?box:result.bounds}
export default function ProjectedMapView({project,geometry,geometrySegments,selected,onSelect,fitVersion,pathOverlays,onPathPick,editable=true,allowAdd=true,contextKey,analysis=null,analysisReady=false,onProjectedApply,ruleLocation,onArcEdit}:Props){
 const [crs,setCrs]=useState(''),[density,setDensity]=useState(5000),[maxVertices,setMaxVertices]=useState(100000),[maxOperations,setMaxOperations]=useState(2048),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<any>(null),[resultSignature,setResultSignature]=useState(''),[camera,setCamera]=useState<Camera>({x:0,y:0,span:100}),[cursor,setCursor]=useState<XY|null>(null),[size,setSize]=useState({width:1000,height:500});
 const [adding,setAdding]=useState(false),[editBusy,setEditBusy]=useState(false),[editInfo,setEditInfo]=useState<EditInfo|null>(null),[ghost,setGhost]=useState<{xy:XY;context:string;inputs:string}|null>(null),[autoRefresh,setAutoRefresh]=useState(false);
 const [addLabel,setAddLabel]=useState(''),[addCable,setAddCable]=useState(''),[addMode,setAddMode]=useState<'flexible'|'fixed'>(project.route.mode==='fixed'?'fixed':'flexible'),[addFixed,setAddFixed]=useState('');
 const [ruleProjection,setRuleProjection]=useState<{key:string;point:XY;ring:XY[]}|null>(null),[ruleProjectionError,setRuleProjectionError]=useState('');
 const [fitPending,setFitPending]=useState(false);
 const pendingFit=useRef<{signature:string;sequence:number;bounds:number[]}|null>(null);
 const ruleSequence=useRef(0);
 const svg=useRef<SVGSVGElement>(null),host=useRef<HTMLDivElement>(null),gesture=useRef<Gesture|null>(null),editSequence=useRef(0),mapSequence=useRef(0),mounted=useRef(true),suppressClick=useRef(false);
 const selectionEpoch=useRef({id:selected,revision:0});if(selectionEpoch.current.id!==selected)selectionEpoch.current={id:selected,revision:selectionEpoch.current.revision+1};
 const arcPending=project.route.legs.some(leg=>leg.geometry?.type==='circular_arc')&&!analysisReady;
 const segments=useMemo(()=>arcPending?[]:geometrySegments?.length?geometrySegments:geometry?.length?[geometry]:[],[geometrySegments,geometry,arcPending]);
 const routes=useMemo(()=>[...(segments.length?[{id:project.id,name:project.name,role:'active',geometry:segmentsGeometry(segments)}]:[]),...pathOverlays.filter(p=>p.segments.length).map(p=>({id:p.id,name:p.name,role:p.role,geometry:segmentsGeometry(p.segments)}))],[segments,project.id,project.name,pathOverlays]);
 const payload=useMemo(()=>({target_crs:crs.trim(),routes,points:project.route.points.map(p=>({id:p.id,label:p.label,longitude:p.longitude,latitude:p.latitude})),layers:project.layers.map(l=>({id:l.id,name:l.name,kind:l.kind,visible:l.visible,geojson:l.geojson})).sort((a,b)=>a.id.localeCompare(b.id)),config:{max_vertices:maxVertices,densify_max_distance_m:density,max_operation_selections:maxOperations}}),[crs,routes,project.route.points,project.layers,maxVertices,density,maxOperations]);
 const signature=useMemo(()=>JSON.stringify(payload),[payload]),context=contextKey||JSON.stringify(project),inputs=JSON.stringify({crs:crs.trim(),density,maxVertices,maxOperations,adding,addLabel,addCable,addMode,addFixed});
 const latest=useRef({signature,context,inputs,editable});latest.current={signature,context,inputs,editable};
 const current=!!result&&resultSignature===signature,drawable=current&&result.can_display&&!fitPending,canEdit=editable&&!!onProjectedApply&&drawable&&!busy&&!editBusy;
 const lockedSelected=!!selected&&projectedPointLocked(project,selected),structureLocked=!!project.route.constraint_state;
 const cableId=addCable||project.route.legs.at(-1)?.cable_type_id||project.cable_types[0]?.id||'';
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;editSequence.current++;mapSequence.current++}},[]);
 useEffect(()=>{if(!host.current)return;const observer=new ResizeObserver(entries=>{const box=entries[0]?.contentRect;if(box?.width&&box.height)setSize({width:box.width,height:box.height})});observer.observe(host.current);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!allowAdd||structureLocked)setAdding(false)},[allowAdd,structureLocked]);
 const aspectRef=useRef(.5);
 const aspect=size.height/Math.max(1,size.width),screenH=1000*aspect,scale=1000/camera.span;
 aspectRef.current=aspect;
 const toScreen=(p:XY):XY=>[500+(p[0]-camera.x)*scale,screenH/2-(p[1]-camera.y)*scale];
 const fromScreen=(x:number,y:number):XY=>[camera.x+(x-500)/scale,camera.y-(y-screenH/2)/scale];
 function fit(bounds=result?.bounds,actualAspect=aspectRef.current){if(!bounds||bounds.length!==4)return;const [xmin,ymin,xmax,ymax]=bounds;setCamera({x:(xmin+xmax)/2,y:(ymin+ymax)/2,span:Math.max(1,xmax-xmin,(ymax-ymin)/Math.max(.1,actualAspect))*1.25});setCursor(null)}
 // Metadata is laid out before the plane becomes visible or editable. Measure
 // that real canvas and commit its size and camera together before paint.
 useLayoutEffect(()=>{const pending=pendingFit.current;if(!fitPending||!current||!result.can_display||!pending||pending.signature!==signature||pending.sequence!==mapSequence.current)return;const box=host.current?.getBoundingClientRect();if(!box||box.width<=0||box.height<=0)return;setSize({width:box.width,height:box.height});fit(pending.bounds,box.height/box.width);pendingFit.current=null;setFitPending(false)},[fitPending,current,result,signature]);
 useEffect(()=>{if(drawable)fit()},[fitVersion]);
 const ruleProjectionKey=JSON.stringify({view:ruleLocation,signature,context});
 useEffect(()=>{const seq=++ruleSequence.current;setRuleProjection(null);setRuleProjectionError('');const view=ruleLocation;if(!drawable||!view||view.location.path_id!==project.id)return;const p=view.location,key=ruleProjectionKey,mapSnapshot=signature,contextSnapshot=context;let cancelled=false;
  (async()=>{try{const boundary=view.circle?await ruleGeographicCircle(p):[];if(cancelled||!mounted.current||ruleSequence.current!==seq)return;const points=[{id:'rule-location',x:p.longitude,y:p.latitude},...boundary.map(([x,y],i)=>({id:'rule-radius-'+i,x,y}))],output=await request<any>('/coordinates/transform',{source_crs:'EPSG:4326',target_crs:crs.trim(),points,error_policy:'reject'});if(cancelled||!mounted.current||ruleSequence.current!==seq||latest.current.signature!==mapSnapshot||latest.current.context!==contextSnapshot)return;if(output.can_apply!==true||output.points.some((r:any)=>!r.accepted||!Number.isFinite(r.output?.x)||!Number.isFinite(r.output?.y)))throw new Error('规则位置或距离圈投影未全部通过，未显示部分结果');const actual:XY[]=output.points.map((r:any)=>[r.output.x,r.output.y]),center=actual[0],ring=actual.slice(1);setRuleProjection({key,point:center,ring});if(view.center){if(ring.length){const xs=ring.map(q=>q[0]),ys=ring.map(q=>q[1]);fit([Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)])}else setCamera(c=>({...c,x:center[0],y:center[1]}))}}catch(e){if(!cancelled&&mounted.current&&ruleSequence.current===seq)setRuleProjectionError(e instanceof Error?e.message:String(e))}})();return()=>{cancelled=true;ruleSequence.current++}
 },[ruleProjectionKey,drawable,project.id]);
 async function run(refit=true){const snapshot=signature,sequence=++mapSequence.current;setBusy(true);setError('');if(refit){pendingFit.current=null;setFitPending(true);setResult(null)}try{if(!crs.trim())throw new Error('请明确填写地图显示的水平投影 CRS，如 EPSG:32650');if(!segments.length)throw new Error('请等待活跃路线实际分析完成，再投影路线几何');const actual=await request<any>('/maps/project',payload);if(!mounted.current||latest.current.signature!==snapshot||sequence!==mapSequence.current)return;if(actual.can_display&&refit)pendingFit.current={signature:snapshot,sequence,bounds:activeBounds(actual)};else if(refit)setFitPending(false);setResult(actual);setResultSignature(snapshot);setCursor(null)}catch(e){if(mounted.current&&latest.current.signature===snapshot&&sequence===mapSequence.current){pendingFit.current=null;setFitPending(false);setError(e instanceof Error?e.message:String(e))}}finally{if(mounted.current&&sequence===mapSequence.current)setBusy(false)}}
 // An edit refreshes actual analyzed geometry without resetting the engineering viewport.
 useEffect(()=>{if(!autoRefresh||!crs.trim()||!segments.length||current||editBusy)return;const timer=setTimeout(()=>{run(false)},100);return()=>clearTimeout(timer)},[autoRefresh,signature,editBusy]);
 function local(e:{clientX:number;clientY:number}){const rect=svg.current!.getBoundingClientRect();return {x:(e.clientX-rect.left)*1000/rect.width,y:(e.clientY-rect.top)*screenH/rect.height}}
 function zoom(factor:number,at?:XY){setCamera(c=>{const span=Math.max(1e-6,Math.min(1e12,c.span*factor));return at?{span,x:at[0]+(c.x-at[0])*factor,y:at[1]+(c.y-at[1])*factor}:{...c,span}})}
 function cancel(){editSequence.current++;gesture.current=null;setGhost(null);setEditBusy(false);setEditInfo(null)}
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')cancel()};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[]);
 async function submit(action:'move'|'add',pointId:string,xy:XY,snapshotContext=context,snapshotInputs=inputs){
  const sequence=++editSequence.current,snapshot=project,sourceCRS=crs.trim(),selection=selectionEpoch.current.revision;
  const valid=()=>mounted.current&&sequence===editSequence.current&&selectionEpoch.current.revision===selection&&latest.current.context===snapshotContext&&latest.current.inputs===snapshotInputs;
  setEditBusy(true);setError('');setGhost({xy,context:snapshotContext,inputs:snapshotInputs});setEditInfo({status:'processing',message:'正在真实反算 WGS84 并校核制造域…',action,target:xy});
  try{
   if(!valid())throw new StaleProjectedEdit();
   const append=action==='add'?{label:addLabel,cable_type_id:cableId,mode:addMode,...(addMode==='fixed'?{fixed_cable_length_m:addFixed.trim()?Number(addFixed):undefined}:{})}:undefined;
   const preview=await previewProjectedPointEdit(snapshot,sourceCRS,[{id:pointId,x:xy[0],y:xy[1]}],valid,append,!!onArcEdit);
   if(preview.arc_moves){if(!valid()||!onArcEdit?.(preview.arc_moves,snapshotContext))throw new StaleProjectedEdit();setGhost(null);setEditInfo({status:'submitted',message:'真实投影目标已进入圆弧重建候选；原路线尚未修改',action,target:xy});return}
   if(!preview.transform.can_apply||!preview.project)throw new Error(preview.transform.errors?.map((e:any)=>e.message).join('；')||'坐标转换未通过，路线保持原值');
   const actual=preview.project.route.points.find(p=>p.id===pointId)!;
   const forward=await request<any>('/coordinates/transform',{source_crs:'EPSG:4326',target_crs:sourceCRS,points:[{id:pointId,x:actual.longitude,y:actual.latitude}],error_policy:'collect'});
   if(!valid())throw new StaleProjectedEdit();
   if(!forward.can_apply)throw new Error('制造域求解后的实际点不能显示于当前投影：'+forward.errors?.map((e:any)=>e.message).join('；'));
   const actualXY:XY=[forward.points[0].output.x,forward.points[0].output.y];
   if(!latest.current.editable||!onProjectedApply||await onProjectedApply(preview.project,snapshotContext,pointId)===false)throw new StaleProjectedEdit();
   setGhost(null);setAutoRefresh(true);
   setEditInfo({status:'submitted',message:'点位已提交为草稿；路线与制造关系继续校核',action,target:xy,actual:actualXY,longitude:actual.longitude,latitude:actual.latitude,warnings:[...(preview.transform.warnings||[]),...preview.constraint_warnings,...(forward.warnings||[])],report:preview.constraint_report});
  }catch(e){if(mounted.current&&sequence===editSequence.current){setGhost(null);setEditInfo({status:'rejected',message:e instanceof Error?e.message:String(e),action,target:xy})}}finally{if(mounted.current&&sequence===editSequence.current)setEditBusy(false)}
 }
 async function remove(){if(!selected||!onProjectedApply)return;const snapshotContext=context,sequence=++editSequence.current;setEditBusy(true);setGhost(null);setEditInfo(null);try{const candidate=removeRoutePoint(project,selected,analysis,analysisReady);const index=project.route.points.findIndex(p=>p.id===selected),nextSelected=candidate.route.points[Math.max(0,index-1)]?.id||null;if(latest.current.context!==snapshotContext||!latest.current.editable||await onProjectedApply(candidate,snapshotContext,nextSelected)===false)throw new StaleProjectedEdit();setAutoRefresh(true);setEditInfo({status:'submitted',message:'点位删除已提交；分段数量与制造关系继续校核',action:'delete'})}catch(e){if(mounted.current&&sequence===editSequence.current)setEditInfo({status:'rejected',message:e instanceof Error?e.message:String(e),action:'delete'})}finally{if(mounted.current&&sequence===editSequence.current)setEditBusy(false)}}
 function pointerStart(e:React.PointerEvent<SVGSVGElement>,point?:any){
  if(e.button!==0)return;if(point){e.stopPropagation();onSelect(point.id);if(!canEdit||adding||projectedPointLocked(project,point.id))return}else if(editBusy)return;
  const rect=svg.current!.getBoundingClientRect();gesture.current={kind:point?'point':adding&&canEdit&&allowAdd?'add':'pan',pointId:point?.id,xy:point?.coordinates,clientX:e.clientX,clientY:e.clientY,camera:{...camera},pointerId:e.pointerId,width:rect.width,rect,context,inputs,moved:false};svg.current!.setPointerCapture(e.pointerId);
  if(point){setEditInfo(null);setGhost({xy:point.coordinates,context,inputs})}
 }
 function pointerMove(e:React.PointerEvent<SVGSVGElement>){const p=local(e);setCursor(fromScreen(p.x,p.y));const d=gesture.current;if(!d||d.pointerId!==e.pointerId)return;const dx=e.clientX-d.clientX,dy=e.clientY-d.clientY;d.moved=d.moved||Math.hypot(dx,dy)>3;if(d.kind==='pan')setCamera({...d.camera,x:d.camera.x-dx/d.width*d.camera.span,y:d.camera.y+dy/d.width*d.camera.span});else if(d.kind==='point'&&d.xy)setGhost({xy:[d.xy[0]+dx/d.width*d.camera.span,d.xy[1]-dy/d.width*d.camera.span],context:d.context,inputs:d.inputs})}
 function pointerEnd(e:React.PointerEvent<SVGSVGElement>){const d=gesture.current;if(!d||d.pointerId!==e.pointerId)return;gesture.current=null;if(svg.current?.hasPointerCapture(e.pointerId))svg.current.releasePointerCapture(e.pointerId);suppressClick.current=d.moved;if(d.kind==='point'&&d.xy&&d.moved){const xy:XY=[d.xy[0]+(e.clientX-d.clientX)/d.width*d.camera.span,d.xy[1]-(e.clientY-d.clientY)/d.width*d.camera.span];void submit('move',d.pointId!,xy,d.context,d.inputs)}else if(d.kind==='add'&&!d.moved){const xy:XY=[d.camera.x+((e.clientX-d.rect.left)/d.width-.5)*d.camera.span,d.camera.y+((d.rect.top+d.rect.height/2-e.clientY)/d.width)*d.camera.span];void submit('add',crypto.randomUUID(),xy,d.context,d.inputs)}else setGhost(null)}
 const xmin=camera.x-camera.span/2,xmax=camera.x+camera.span/2,ymin=camera.y-camera.span*aspect/2,ymax=camera.y+camera.span*aspect/2,step=gridStep(camera.span),gridX:number[]=[],gridY:number[]=[];
 for(let x=Math.ceil(xmin/step)*step;x<=xmax&&gridX.length<50;x+=step)gridX.push(x);for(let y=Math.ceil(ymin/step)*step;y<=ymax&&gridY.length<50;y+=step)gridY.push(y);
 const axis=result?.target_crs?.axis_units||[],unit=(i:number)=>axis[i]?.name||'CRS 原生单位',reference=result?.points?.find((p:any)=>p.id===selected)||result?.points?.[0],localAxes=reference?.local_axes,north=localAxes?.north_vector_native_units_per_m,east=localAxes?.east_vector_native_units_per_m;
 const displayedRule=ruleProjection?.key===ruleProjectionKey?ruleProjection:null;
 const shownGhost=ghost&&ghost.context===context&&ghost.inputs===inputs?toScreen(ghost.xy):null;
 return <div className="projected-map-shell">
  <div className="projected-map-config"><label>地图显示 CRS<input aria-label="地图显示投影 CRS" value={crs} onChange={e=>{setCrs(e.target.value);setAutoRefresh(false)}} placeholder="明确 EPSG / WKT / PROJ"/></label><button className="secondary-button" disabled={busy||!segments.length||editBusy} onClick={()=>run()}><Play size={12}/>{busy?'投影中…':'计算真实投影视图'}</button><details className="projected-map-options"><summary>投影参数</summary><label>GIS 最大加密步长 / m<NumberField value={density} min={1} onChange={v=>setDensity(v??5000)}/></label><label>顶点总预算<NumberField value={maxVertices} min={2} max={100000} step={1} onChange={v=>setMaxVertices(v??100000)}/></label><label>地区转换操作选择预算<NumberField value={maxOperations} min={1} max={10000} step={1} onChange={v=>setMaxOperations(v??2048)}/></label><p>GIS 边按 GeoJSON 经纬度直线参数加密；路线使用已分析的实际曲线。投影原生 X/Y 通过真实水平反算后才修改 WGS84 点。</p></details></div>
  {onProjectedApply&&<div className="projected-edit-tools"><button aria-label="选择与拖动投影路线点" title="选择与拖动投影路线点" className={!adding?'active':''} disabled={editBusy} onClick={()=>setAdding(false)}><MousePointer2 size={14}/>选取 / 拖动</button><button aria-label="在投影画布点击追加路线点" title="在投影画布点击追加路线点" className={adding?'active':''} disabled={!canEdit||!allowAdd||structureLocked} onClick={()=>setAdding(v=>!v)}><Plus size={14}/>追加点</button><button aria-label="删除投影选中路线点" title="删除投影选中路线点" disabled={!canEdit||!selected||structureLocked||project.route.points.length<=2} onClick={remove}><Trash2 size={14}/>删除点</button><span>{lockedSelected?'Fixed Sliding：只能编辑实物 KP':structureLocked?'制造域启用：可移点，结构增删须先明确解除':adding?'背景点击追加：水深保持未测量':'拖点释放后真实转换与求解；每次提交可撤销'}</span></div>}
  {adding&&<div className="projected-add-options"><label>新点名称<input aria-label="投影追加点名称" value={addLabel} onChange={e=>setAddLabel(e.target.value)} placeholder={`WP-${project.route.points.length+1}`}/></label><label>新段缆型<select aria-label="投影追加段缆型" value={cableId} onChange={e=>setAddCable(e.target.value)}>{project.cable_types.map(c=><option key={c.id} value={c.id}>{c.id} · {c.name||'未命名'}</option>)}</select></label><label>新段模式<select aria-label="投影追加段模式" value={addMode} onChange={e=>setAddMode(e.target.value as 'flexible'|'fixed')}><option value="flexible">柔性目标余缆</option><option value="fixed">固定制造量</option></select></label>{addMode==='fixed'&&<label>明确制造缆长 / m<input aria-label="投影追加固定缆长 / m" inputMode="decimal" value={addFixed} onChange={e=>setAddFixed(e.target.value)} placeholder="须填写；不补零"/></label>}</div>}
  {ruleProjectionError&&<div className="projected-rule-location-error" role="status">检查位置投影失败：{ruleProjectionError}</div>}
  {error&&<div className="projected-map-error">{error}</div>}
  {result&&!current&&<div className="projected-map-stale">CRS、路径、GIS 或投影参数已改变，旧投影已隐藏；{autoRefresh?'等待新路线分析并重投影。':'请重新计算。'}</div>}
  {current&&!result.can_display&&<div className="projected-map-error">全部几何投影未通过，未显示部分成功结果。{result.errors?.map((e:any,i:number)=><p key={i}>{e.message||JSON.stringify(e)}</p>)}</div>}
  {editInfo&&<div className={`projected-edit-status ${editInfo.status}`} role="status"><div><strong>{editInfo.status==='processing'?<LoaderCircle className="spin" size={12}/>:null}{editInfo.message}</strong>{editInfo.target&&<span className="projected-edit-target" data-target-x={editInfo.target[0]} data-target-y={editInfo.target[1]}>目标 X {f(editInfo.target[0])} {unit(0)} / Y {f(editInfo.target[1])} {unit(1)}</span>}{editInfo.actual&&<span className="projected-edit-actual" data-actual-x={editInfo.actual[0]} data-actual-y={editInfo.actual[1]}>实际 X {f(editInfo.actual[0])} / Y {f(editInfo.actual[1])} · WGS84 {editInfo.longitude?.toFixed(8)}°, {editInfo.latitude?.toFixed(8)}°</span>}{editInfo.warnings?.map((w:any,i:number)=><p key={i}>{w.message||String(w)}</p>)}{editInfo.report&&<details><summary>本次真实制造域求解</summary><pre>{JSON.stringify(editInfo.report,null,2)}</pre></details>}</div><button title="取消投影点位操作 / 关闭结果" onClick={cancel}><X size={14}/></button></div>}
  <div className={`projected-map-canvas ${adding?'adding':''}`} ref={host}>
   {drawable?<svg ref={svg} role="img" aria-label="实际投影路线与 GIS 工程平面" data-camera-x={camera.x} data-camera-y={camera.y} data-camera-span={camera.span} viewBox={`0 0 1000 ${screenH}`} preserveAspectRatio="none" onWheel={e=>{e.preventDefault();if(gesture.current?.kind==='point'||editBusy)return;const p=local(e);zoom(e.deltaY>0?1.2:1/1.2,fromScreen(p.x,p.y))}} onPointerDown={e=>pointerStart(e)} onPointerMove={pointerMove} onPointerUp={pointerEnd} onPointerCancel={cancel} onPointerLeave={()=>{if(!gesture.current)setCursor(null)}}>
    <rect width="1000" height={screenH} fill="#eef3f6"/>
    {gridX.map(x=>{const q=toScreen([x,0]);return <g key={'x'+x} className="projected-grid"><line x1={q[0]} x2={q[0]} y1="0" y2={screenH}/><text x={q[0]+4} y={screenH-10}>X {f(x)}</text></g>})}
    {gridY.map(y=>{const q=toScreen([0,y]);return <g key={'y'+y} className="projected-grid"><line x1="0" x2="1000" y1={q[1]} y2={q[1]}/><text x="8" y={q[1]-4}>Y {f(y)}</text></g>})}
    {layerDrawingOrder((result.layers||[]).filter((l:any)=>l.visible),project.layers).map((l:any)=><g key={l.id} className="projected-gis-layer" data-layer-id={l.id} opacity={layerOpacity(project.layers.find(source=>source.id===l.id))}><Geometry geometry={l.geojson} toScreen={toScreen} name={l.name} stroke={color(l.kind)}/></g>)}
    {result.routes?.map((r:any)=><g key={r.id} className="projected-route" data-route-id={r.id}><Geometry geometry={r.geometry} toScreen={toScreen} name={r.name} stroke={r.role==='active'?'#128982':r.role==='alternative'?'#b49147':'#6d86a9'} selectedPoint={r.role==='active'} onPick={editable&&r.role!=='active'&&onPathPick?()=>onPathPick(r.id):undefined}/></g>)}
    {result.points?.map((p:any,i:number)=>{const q=toScreen(p.coordinates),locked=projectedPointLocked(project,p.id);return <g key={p.id} className={`projected-route-point ${locked?'locked':''}`} data-point-id={p.id} data-x={p.coordinates[0]} data-y={p.coordinates[1]} data-locked={locked} onPointerDown={e=>pointerStart(e as unknown as React.PointerEvent<SVGSVGElement>,p)} onClick={e=>{e.stopPropagation();if(suppressClick.current){suppressClick.current=false;return}onSelect(p.id)}}><circle cx={q[0]} cy={q[1]} r="11" fill={selected===p.id?'#0d8580':'#fff'} stroke="#168783" strokeWidth="2"/><text x={q[0]} y={q[1]+4} fill={selected===p.id?'#fff':'#12736f'} textAnchor="middle">{i+1}</text><title>{p.label} · X {f(p.coordinates[0])} {unit(0)} / Y {f(p.coordinates[1])} {unit(1)}{locked?' · Fixed Sliding 已锁定':canEdit?' · 拖动修改水平坐标':''}</title></g>})}
    {displayedRule&&<g className="projected-rule-location" data-location-kp={ruleLocation!.location.kp_m} data-location-x={displayedRule.point[0]} data-location-y={displayedRule.point[1]}><circle cx={toScreen(displayedRule.point)[0]} cy={toScreen(displayedRule.point)[1]} r="7" fill="#fff2f3"/>{ruleLocation?.circle&&(displayedRule.ring.length?<path d={displayedRule.ring.map((q,i)=>{const actual=toScreen(q);return `${i?'L':'M'} ${actual[0]} ${actual[1]}`}).join(' ')+' Z'}/>:<circle cx={toScreen(displayedRule.point)[0]} cy={toScreen(displayedRule.point)[1]} r="18" fill="none"/>)}<text x={toScreen(displayedRule.point)[0]+12} y={toScreen(displayedRule.point)[1]-12}>检查 KP {f(ruleLocation!.location.kp_m)} m{displayedRule.ring.length?' · 32 点 WGS84 距离圈':''}</text></g>}
    {shownGhost&&<g className="projected-candidate-point" aria-label="尚未提交的投影点位" data-candidate-x={ghost!.xy[0]} data-candidate-y={ghost!.xy[1]}><circle cx={shownGhost[0]} cy={shownGhost[1]} r="15" fill="#d6983622" stroke="#c99747" strokeWidth="2" strokeDasharray="4 3"/><line x1={shownGhost[0]-20} x2={shownGhost[0]+20} y1={shownGhost[1]} y2={shownGhost[1]}/><line x1={shownGhost[0]} x2={shownGhost[0]} y1={shownGhost[1]-20} y2={shownGhost[1]+20}/></g>}
    {north&&east&&<g className="projected-local-directions"><rect x="12" y="10" width="135" height="88" rx="5" fill="#ffffffde"/>{[[north,'N','#31796c'],[east,'E','#6381a4']].map(([vector,label,c]:any)=>{const norm=Math.hypot(vector[0],vector[1]),dx=vector[0]/norm,dy=-vector[1]/norm,x=52+26*dx,y=47+26*dy;return <g key={label}><line x1="52" y1="47" x2={x} y2={y} stroke={c} strokeWidth="2"/><path d={`M ${x} ${y} L ${x-7*dx+3*dy} ${y-7*dy-3*dx} L ${x-7*dx-3*dy} ${y-7*dy+3*dx} Z`} fill={c}/><text x={x+5} y={y-3} fill={c}>{label}</text></g>})}<text x="20" y="87" fill="#647e8d">{reference.label} · 局部真北 / 东</text></g>}
   </svg>:<div className="projected-map-empty">{busy?'正在运行真实坐标转换…':autoRefresh?'旧投影已隐藏，等待当前路线分析与重新投影；失败时保留草稿并检查地形/制造关系。':'明确声明投影 CRS 后计算路线与图层显示。工程经纬度和测地分析保持原值。'}</div>}
   {drawable&&<><div className="projected-navigation"><button title="投影视图放大" disabled={editBusy} onClick={()=>zoom(1/1.4)}><Plus size={17}/></button><button title="投影视图缩小" disabled={editBusy} onClick={()=>zoom(1.4)}><Minus size={17}/></button><button title="定位活跃路线投影" disabled={editBusy} onClick={()=>fit(activeBounds(result))}><Crosshair size={17}/></button><button title="定位完整投影几何" disabled={editBusy} onClick={()=>fit()}><Crosshair size={17}/></button><button title="下载实际地图投影结果" disabled={editBusy} onClick={()=>terrainDownload(JSON.stringify(result,null,2),'OceanRoute-projected-map.json','application/json')}><Download size={16}/></button></div><div className="projected-map-coordinate" data-cursor-x={cursor?.[0]} data-cursor-y={cursor?.[1]}>{cursor?`X ${f(cursor[0])} ${unit(0)} · Y ${f(cursor[1])} ${unit(1)}`:'拖动背景平移 · 滚轮缩放 · 选点 / 拖点'}</div></>}
  </div>
  {current&&result.can_display&&<details className="projected-map-metadata"><summary>{result.target_crs.name} · xy · X {unit(0)} / Y {unit(1)} · 显示与编辑采用真实坐标转换</summary><div><p>轴方向：{axis.map((a:any)=>`${a.axis_name} / ${a.direction} / ${a.name}`).join('；')}。此窗口无在线底图；网格为目标 CRS 原生 X/Y。水平编辑不转换水深或垂直基准。</p>{localAxes&&<p className="projected-local-scale">{reference.label} 局部东 / 北水平比例 {f(localAxes.east_scale)} / {f(localAxes.north_scale)} · 局部真北相对网格 Y 的顺时针角 {f(localAxes.grid_north_clockwise_deg)}°。基于真实水平转换差分，不含高程或地面综合比例。</p>}{result.operations?.map((o:any,i:number)=><p key={i}>{o.description} · 最佳操作 {o.best_available===true?'可用':'未声明'} · 精度 {o.accuracy_m==null?'未知':f(o.accuracy_m)+' m'}</p>)}{result.warnings?.map((w:any,i:number)=><p key={i}>{w.message||JSON.stringify(w)}</p>)}<pre>{JSON.stringify({budget:result.budget,operations:result.operations},null,2)}</pre></div></details>}
 </div>;
}
