import {useEffect,useMemo,useRef,useState} from 'react';
import {Route,Play,Check,Download,Upload,FlaskConical,AlertTriangle} from 'lucide-react';
import {NumberField} from './fields';
import {request} from './api';
import MapView from './MapView';
import type {Project,Analysis,Layer} from './types';

const fmt=(v:any)=>v==null?'—':typeof v==='number'?v.toLocaleString('zh-CN',{maximumFractionDigits:3}):typeof v==='boolean'?(v?'通过':'未通过'):String(v);
const forbiddenKinds=['restricted','exclusion','hazard','land'];
const numericFields=[['grid_spacing_m','搜索网格间距 / m'],['padding_m','搜索边界扩展 / m'],['clearance_m','禁止区域净距 / m'],['cable_clearance_m','既有海缆净距 / m'],['crossing_penalty_m','海缆穿越罚距 / m']] as const;
function download(data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='OceanRoute-route-candidate.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
export default function RouteSearch({project,analysis,onApply,notify}:{project:Project;analysis:Analysis|null;onApply:(p:Project)=>void;notify:(message:string,error?:boolean)=>void}){
  const latestProject=useRef(project);latestProject.current=project;
  const [config,setConfig]=useState({grid_spacing_m:1000,padding_m:10000,clearance_m:100,cable_clearance_m:100,crossing_penalty_m:0,slope_weight:0,start_point_index:0,end_point_index:project.route.points.length-1,length_policy:'preserve',avoid_existing_cables:false});
  const [obstacles,setObstacles]=useState(project.layers.filter(l=>forbiddenKinds.includes(l.kind)).map(l=>l.id)),[allowed,setAllowed]=useState<string[]>([]),[via,setVia]=useState<number[]>([]),[terrainText,setTerrainText]=useState(''),[terrainName,setTerrainName]=useState(''),[terrainLimits,setTerrainLimits]=useState<{max_slope_deg:number|null;min_depth_m:number|null;max_depth_m:number|null}>({max_slope_deg:null,min_depth_m:null,max_depth_m:null}),[weightedLayers,setWeightedLayers]=useState<Record<string,number>>({}),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[resultSignature,setResultSignature]=useState('');
  const inputSignature=JSON.stringify({project,config,obstacles,allowed,via,terrainText,terrainLimits,weightedLayers});const stale=!!result&&inputSignature!==resultSignature;
  useEffect(()=>setResult(null),[project]);
  async function run(){setBusy(true);setResult(null);const snapshot=inputSignature;try{const payload={...config,obstacle_layer_ids:obstacles,allowed_layer_ids:allowed,via_point_indices:via.filter(i=>i>config.start_point_index&&i<config.end_point_index).sort((a,b)=>a-b),weighted_areas:project.layers.filter(l=>weightedLayers[l.id]>0).map(l=>({geojson:l.geojson,cost_per_m:weightedLayers[l.id]})),...(terrainText.trim()?{terrain_grid:JSON.parse(terrainText),...terrainLimits}:{})};const output=await request<any>('/routing/search',{project,config:payload});const computed=await request<Analysis>('/analyze',output.project);if(latestProject.current!==project)throw new Error('工程已在计算期间修改，请重新生成预览');setResult({...output,analysis:computed,source:project,source_geometry:analysis?.route_geometry?.coordinates});setResultSignature(snapshot);notify('避障候选已生成，请复核约束、缆量和测深提示')}catch(e){notify(e instanceof Error?e.message:String(e),true)}finally{setBusy(false)}}
  async function terrainFile(file?:File){if(!file)return;setTerrainText(await file.text());setTerrainName(file.name)}
  function toggle(ids:string[],id:string,set:(v:string[])=>void){set(ids.includes(id)?ids.filter(v=>v!==id):[...ids,id])}
  const previewProject=useMemo(()=>{if(!result)return null;const layers:Layer[]=[...result.project.layers];const original=result.source_geometry||result.source.route.points.map((p:any)=>[p.longitude,p.latitude]);layers.push({id:'search-original',name:'搜索前路由',kind:'routing_original',visible:true,geojson:{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:original}}});if(result.preview.blocked_area?.coordinates?.length)layers.push({id:'search-blocked',name:'考虑净距后的禁止区域',kind:'routing_blocked',visible:true,geojson:{type:'Feature',properties:{},geometry:result.preview.blocked_area}});if(result.preview.allowed_area)layers.push({id:'search-allowed',name:'允许搜索区域',kind:'routing_allowed',visible:true,geojson:{type:'Feature',properties:{},geometry:result.preview.allowed_area}});return {...result.project,layers}},[result]);
  const report=result?.report,before=report?.before_summary,after=report?.after_summary;
  return <main className="engineering-main route-search"><div className="page-heading"><div><small>INDEPENDENT ROUTE SEARCH</small><h2>避障候选搜索</h2><p>独立 A* 网格增强：在选定区域与工程约束下生成一条可复核候选。</p></div><button className="primary-button" disabled={busy} onClick={run}><Play size={14}/>{busy?'正在搜索…':'搜索候选路线'}</button></div><div className="explanation"><FlaskConical size={15}/>采用局部投影与有限网格，候选须结合测深和施工条件复核。搜索目标以等效米计，不是成本报价；不承诺连续空间或全工程全局最优。</div>
    <div className="settings-card"><h3>搜索范围与目标</h3><div className="tool-fields"><label>搜索起点<select value={config.start_point_index} onChange={e=>setConfig({...config,start_point_index:Number(e.target.value)})}>{project.route.points.slice(0,-1).map((p,i)=><option key={p.id} value={i}>{i+1} · {p.label}</option>)}</select></label><label>搜索终点<select value={config.end_point_index} onChange={e=>setConfig({...config,end_point_index:Number(e.target.value)})}>{project.route.points.map((p,i)=><option key={p.id} value={i}>{i+1} · {p.label}</option>)}</select></label>{numericFields.map(([key,label])=><label key={key}>{label}<NumberField value={config[key]} min={key==='grid_spacing_m'?1:0} onChange={v=>setConfig({...config,[key]:v??0})}/></label>)}<label>材料长度策略<select value={config.length_policy} onChange={e=>setConfig({...config,length_policy:e.target.value})}><option value="preserve">保留已有制造缆量</option><option value="recalculate">按新路线重新计算柔性缆量</option></select></label></div><label className="checkbox-label"><input type="checkbox" checked={config.avoid_existing_cables} onChange={e=>setConfig({...config,avoid_existing_cables:e.target.checked})}/>将既有海缆及其净距作为禁止穿越区域</label><p className="chart-meta">保留缆量会将搜索区间转为固定分段；路径增长可能造成缆量不足，结果中会显示实际余缆警告。</p>{project.route.points.length>2&&<details className="advanced-environment"><summary>保留必经路线点</summary><div className="routing-via">{project.route.points.map((p,i)=>i>config.start_point_index&&i<config.end_point_index?<label className="checkbox-label" key={p.id}><input type="checkbox" checked={via.includes(i)} onChange={()=>setVia(via.includes(i)?via.filter(v=>v!==i):[...via,i])}/>{i+1} · {p.label}</label>:null)}</div></details>}</div>
    <div className="settings-card"><h3>约束图层</h3><p className="chart-meta">约束是否参与搜索由这里的选择决定，地图显示开关不会取消工程约束。允许区域须为多边形。</p><div className="table-wrap"><table><thead><tr><th>图层</th><th>禁止穿越</th><th>允许范围</th><th>区域单位罚距</th></tr></thead><tbody>{project.layers.map(l=><tr key={l.id}><td>{l.name}<small className="routing-layer-kind">{l.kind}</small></td><td><input type="checkbox" aria-label={'禁止穿越 '+l.name} checked={obstacles.includes(l.id)} onChange={()=>toggle(obstacles,l.id,setObstacles)}/></td><td><input type="checkbox" aria-label={'允许范围 '+l.name} checked={allowed.includes(l.id)} onChange={()=>toggle(allowed,l.id,setAllowed)}/></td><td><NumberField aria-label={'区域罚距 '+l.name} value={weightedLayers[l.id]||0} min={0} onChange={v=>setWeightedLayers({...weightedLayers,[l.id]:v??0})}/></td></tr>)}</tbody></table>{!project.layers.length&&<div className="table-empty">当前工程没有 GIS 约束图层。可先从工具栏导入。</div>}</div></div>
    <details className="settings-card routing-terrain"><summary>二维测深与坡度约束（可选）</summary><p>先在测深网格工具生成并下载网格 JSON，再上传到此处。预览网格按其实际分辨率使用；缺测及覆盖区外不外推。</p><label className="file-drop"><Upload size={18}/><span>{terrainName||'上传 OceanRoute DTM 网格 JSON'}</span><input type="file" accept=".json" onChange={e=>terrainFile(e.target.files?.[0])}/></label><textarea aria-label="二维地形网格 JSON" value={terrainText} onChange={e=>setTerrainText(e.target.value)} placeholder="包含 metadata 和 preview 的 DTM JSON" spellCheck={false}/><fieldset disabled={!terrainText.trim()} className="tool-fields">{([['max_slope_deg','最大坡度 / °'],['min_depth_m','最小水深 / m'],['max_depth_m','最大水深 / m']] as const).map(([key,label])=><label key={key}>{label}<NumberField value={terrainLimits[key]} nullable min={0} onChange={v=>setTerrainLimits({...terrainLimits,[key]:v})}/></label>)}<label>坡度罚距系数<NumberField value={config.slope_weight} min={0} onChange={v=>setConfig({...config,slope_weight:v??0})}/></label></fieldset></details>
    {result&&previewProject?<div className="routing-result"><div className="section-heading"><h3>候选预览与工程变化</h3><div className="page-actions"><button className="secondary-button" onClick={()=>download(result)}><Download size={14}/>下载候选结果</button><button className="primary-button" disabled={stale} onClick={()=>{if(stale)return;onApply(result.project);setResult(null);notify('避障候选已应用，可使用撤销恢复原工程')}}><Check size={14}/>应用候选到工程</button></div></div>{stale&&<div className="inline-warning">搜索条件已修改，当前为上次候选；重新搜索后才能应用。</div>}<div className="routing-map"><MapView project={previewProject} geometry={result.analysis.route_geometry?.coordinates} selected={null} onSelect={()=>{}} onMove={()=>{}} onAdd={()=>{}} fitVersion={0} editable={false}/><div className="ship-map-legend"><i/>搜索候选<b/>原有路由<em/>禁止区域</div></div><div className="table-wrap"><table><thead><tr><th>工程量</th><th>搜索前</th><th>候选</th><th>变化</th></tr></thead><tbody>{([['surface_length_m','表面长度 / m'],['cable_length_m','装配缆长 / m'],['material_length_m','材料缆长 / m'],['cost_total','工程费用']] as const).map(([key,name])=><tr key={key}><td>{name}</td><td>{fmt(before?.[key])}</td><td>{fmt(after?.[key])}</td><td>{fmt(before?.[key]==null||after?.[key]==null?null:after[key]-before[key])}</td></tr>)}</tbody></table></div><div className="tool-summary"><div><span>搜索网格</span><strong>{report.grid_width} × {report.grid_height}</strong></div><div><span>评价连边数</span><strong>{fmt(report.evaluated_edges)}</strong></div><div><span>结果路线点数</span><strong>{fmt(report.transformations?.point_count)}</strong></div><div><span>选中范围约束检查</span><strong>{fmt(report.constraint_validation?.selected_section_passed)}</strong></div>{Object.entries(report.objective_m_equivalent||{}).filter(([key])=>key!=='crossing_units').map(([key,v])=><div key={key}><span>{({total:'目标值合计 / 等效m',distance_m:'距离项 / m',slope_cost_m:'坡度罚距 / m',crossing_cost_m:'海缆穿越罚距 / m',zone_cost_m:'区域罚距 / m'} as Record<string,string>)[key]||key}</span><strong>{fmt(v)}</strong></div>)}</div>{[...(result.warnings||[]),...(result.analysis.warnings||[])].map((w:any,i:number)=><div className="inline-warning" key={i}><AlertTriangle size={14}/>{typeof w==='string'?w:w.message}</div>)}<div className="assumptions"><strong>搜索假设与数据状态</strong>{report.assumptions?.map((s:string,i:number)=><p key={i}>{s}</p>)}</div></div>:<div className="tool-empty"><Route size={30}/><span>搜索会生成独立预览；检查通过后再应用到当前工程。</span></div>}
  </main>;
}
