import {useEffect,useMemo,useRef,useState} from 'react';
import {AlertTriangle,CheckCircle2,Download,Layers,Search,Upload} from 'lucide-react';
import './s57.css';

type Row=Record<string,any>;
type Props={contextKey:string;pending:boolean;onApply:(layers:Row[],expectedDocument:string,isCurrent:()=>boolean)=>Promise<boolean>;onCancel:()=>void;notify:(message:string,error?:boolean)=>void};
const limits=[['max_cells','读取单元上限'],['max_layers','输出图层上限'],['max_features','对象数量上限'],['max_vertices','几何顶点上限'],['max_work_units','读取工作量上限'],['max_output_bytes','JSON 输出字节上限'],['timeout_s','原生读取超时 / s']] as const;
const f=(v:any)=>v==null?'未知':typeof v==='number'?v.toLocaleString('zh-CN',{maximumFractionDigits:6}):String(v);
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
function Warnings({items}:{items:Row[]}){return items.length?<div className="s57-warnings">{items.map((w,i)=><div key={i}><AlertTriangle size={14}/><span><strong>{w.code||'告警'}</strong>{w.message||JSON.stringify(w)}</span></div>)}</div>:null}
function Datum({cell}:{cell:Row}){const d=cell.datum_units;return <><div className="s57-cell-heading"><strong>{cell.path}</strong><span>{cell.updates?.length||0} 个更新文件</span></div><div className="s57-cell-metadata">{d?<><span>水平基准代码 <b>{f(d.horizontal_datum_code)}</b></span><span>垂直基准代码 <b>{f(d.vertical_datum_code)}</b></span><span>测深基准代码 <b>{f(d.sounding_datum_code)}</b></span><span>深度单位 <b>{d.depth_units||'未知'} · 代码 {f(d.depth_unit_code)}</b></span><span>高度单位代码 <b>{f(d.height_unit_code)}</b></span><span>坐标单位代码 <b>{f(d.coordinate_unit_code)}</b></span></>:<span>尚未调用原生 reader，基准和对象类未知。</span>}</div>{cell.dsid&&<div className="s57-cell-metadata"><span>有效版次 <b>{f(cell.dsid.DSID_EDTN)}</b></span><span>基础更新号 <b>{f(cell.base_dsid?.DSID_UPDN)}</b></span><span>已应用更新号 <b>{f(cell.applied_update_number)}</b></span></div>}{cell.updates?.length>0&&<div className="s57-updates">{cell.updates.map((u:Row)=><span key={u.path}>{u.path} · 更新 {u.number} · {f(u.bytes)} bytes</span>)}</div>}{cell.dsid&&<details><summary>完整 DSID / DSSI / DSPM 原字段</summary><pre>{JSON.stringify(cell.dsid,null,2)}</pre></details>}</>}
function positions(g:Row):number[][]{if(!g)return [];if(g.type==='Feature')return positions(g.geometry);if(g.type==='FeatureCollection')return g.features.flatMap((x:Row)=>positions(x));if(g.type==='GeometryCollection')return g.geometries.flatMap((x:Row)=>positions(x));const out:number[][]=[];function visit(c:any){if(Array.isArray(c)&&typeof c[0]==='number'){if(Number.isFinite(c[0])&&Number.isFinite(c[1]))out.push(c)}else if(Array.isArray(c))c.forEach(visit)}visit(g.coordinates);return out}
function ChartPreview({layer}:{layer:Row}){
 const data=useMemo(()=>{const input=layer.geojson?.features||[];const shown=input.slice(0,250).filter((feature:Row)=>positions(feature).length<=5000);const pts:number[][]=shown.flatMap((feature:Row)=>positions(feature));if(!pts.length)return null;const bounds=[Infinity,Infinity,-Infinity,-Infinity];for(const p of pts){bounds[0]=Math.min(bounds[0],p[0]);bounds[1]=Math.min(bounds[1],p[1]);bounds[2]=Math.max(bounds[2],p[0]);bounds[3]=Math.max(bounds[3],p[1])}return {shown,shownCount:shown.length,allCount:input.length,bounds}},[layer]);
 if(!data)return <div className="table-empty">本图层无可显示二维几何。</div>;
 const [xmin,ymin,xmax,ymax]=data.bounds,cx=(xmin+xmax)/2,cy=(ymin+ymax)/2,span=Math.max(xmax-xmin,(ymax-ymin)*1.7,1e-6)*1.08;
 const xy=(p:number[])=>[450+(p[0]-cx)/span*860,200-(p[1]-cy)/span*860];const line=(ring:number[][])=>ring.map((p,i)=>{const [x,y]=xy(p);return `${i?'L':'M'}${x},${y}`}).join(' ');
 function geometry(g:Row,key:string):any{if(!g)return null;if(g.type==='GeometryCollection')return g.geometries.map((v:Row,i:number)=>geometry(v,key+i));if(g.type==='Point'){const [x,y]=xy(g.coordinates);return <circle key={key} cx={x} cy={y} r={3}/>}if(g.type==='MultiPoint')return g.coordinates.map((p:number[],i:number)=>geometry({type:'Point',coordinates:p},key+i));if(g.type==='LineString')return <path key={key} d={line(g.coordinates)} fill="none"/>;if(g.type==='MultiLineString')return g.coordinates.map((r:number[][],i:number)=>geometry({type:'LineString',coordinates:r},key+i));if(g.type==='Polygon')return <path key={key} d={g.coordinates.map((r:number[][])=>line(r)+' Z').join(' ')} fillRule="evenodd"/>;if(g.type==='MultiPolygon')return g.coordinates.map((r:number[][][],i:number)=>geometry({type:'Polygon',coordinates:r},key+i));return null}
 return <div className="s57-chart-preview"><svg role="img" aria-label="S-57 实际对象经纬度预览" viewBox="0 0 900 400"><defs><pattern id="s57-grid" width="45" height="40" patternUnits="userSpaceOnUse"><path d="M45 0H0V40" fill="none" stroke="#dfe9ee" strokeWidth=".7"/></pattern></defs><rect width="900" height="400" fill="url(#s57-grid)"/><g stroke="#448492" strokeWidth="1.3" fill="#649ca733">{data.shown.map((feature:Row,i:number)=>geometry(feature.geometry,String(i)))}</g><text x="16" y="22">{f(xmin)}° … {f(xmax)}°E</text><text x="16" y="384">{f(ymin)}° … {f(ymax)}°N · WGS84</text></svg><p>实际 reader 几何的经纬度平面预览，显示 {data.shownCount} / {data.allCount} 个对象；最多 250 个对象，单对象超过 5,000 顶点不在此缩略图绘制。应用与下载仍使用完整所选图层。第三维海图值不参与平面位置。</p></div>
}
export default function S57ImportPanel({contextKey,pending,onApply,onCancel,notify}:Props){
 const [file,setFile]=useState<File|null>(null),[fileToken,setFileToken]=useState(''),[name,setName]=useState('S-57海图'),[cells,setCells]=useState<string[]>([]),[classes,setClasses]=useState<string[]>([]),[settings,setSettings]=useState<Record<string,string>>({}),[directory,setDirectory]=useState<Row|null>(null),[catalog,setCatalog]=useState<Row|null>(null),[catalogSignature,setCatalogSignature]=useState(''),[preview,setPreview]=useState<Row|null>(null),[previewSignature,setPreviewSignature]=useState(''),[operation,setOperation]=useState(''),[error,setError]=useState(''),[search,setSearch]=useState(''),[layerIndex,setLayerIndex]=useState(0),[stale,setStale]=useState(false);
 const catalogKey=JSON.stringify({fileToken,cells,settings}),previewKey=JSON.stringify({catalogKey,classes,name,contextKey});const latest=useRef({catalogKey,previewKey,contextKey,fileToken});latest.current={catalogKey,previewKey,contextKey,fileToken};const mounted=useRef(true),sequence=useRef(0);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;sequence.current++}},[]);
 const previousContext=useRef(contextKey);useEffect(()=>{if(previousContext.current!==contextKey){previousContext.current=contextKey;if(preview)setStale(true);setPreview(null);setPreviewSignature('');setError('')}},[contextKey]);
 const currentCatalog=!!catalog&&catalogSignature===catalogKey,currentPreview=!!preview&&previewSignature===previewKey;const available=currentCatalog?catalog.classes_catalog||[]:[];const listed=available.filter((c:Row)=>!search||String(c.name).toLowerCase().includes(search.toLowerCase()));const busy=!!operation;const canApply=currentPreview&&preview.can_apply===true&&preview.accepted===true&&preview.layers?.length>0&&!busy&&!pending;
 function invalidate(){if(preview)setStale(true);setPreview(null);setPreviewSignature('');setError('')}
 function chooseFile(value?:File){sequence.current++;setOperation('');setFile(value||null);setFileToken(crypto.randomUUID());setDirectory(null);setCatalog(null);setCatalogSignature('');setCells([]);setClasses([]);setPreview(null);setPreviewSignature('');setError('');setStale(false);setName(value?.name.replace(/\.[^.]+$/,'')||'S-57海图')}
 function cellSelection(path:string,checked:boolean){invalidate();setCatalog(null);setCatalogSignature('');setClasses([]);setCells(old=>checked?[...old,path].sort():old.filter(p=>p!==path))}
 function classSelection(value:string,checked:boolean){invalidate();setClasses(old=>checked?[...old,value].sort():old.filter(c=>c!==value))}
 function config(stage:string){const out:Row={};for(const [key,value] of Object.entries(settings))if(value.trim()){const n=Number(value);if(!Number.isSafeInteger(n)||n<=0)throw new Error('读取预算须为正的安全整数');out[key]=n}if(stage!=='inspect')out.cells=[...cells];if(stage==='import'){out.classes=[...classes];out.name=name.trim()||'S-57海图'}return out}
 async function run(stage:'inspect'|'catalog'|'import'){
  if(!file)return;const token=++sequence.current,snapshot={...latest.current};const unchanged=()=>mounted.current&&sequence.current===token&&latest.current.previewKey===snapshot.previewKey;setOperation(stage);setError('');setPreview(null);setPreviewSignature('');setStale(false);if(stage==='inspect'){setDirectory(null);setCatalog(null);setCatalogSignature('')}if(stage==='catalog'){setCatalog(null);setCatalogSignature('')}
  try{if(file.size>128*1024*1024)throw new Error('S-57 上传超过 128 MiB');const form=new FormData();form.append('file',file);form.append('config_json',JSON.stringify(config(stage)));const response=await fetch('/api/import/s57'+(stage==='import'?'':'/'+stage),{method:'POST',body:form});if(!response.ok){let message=await response.text();try{const data=JSON.parse(message);message=typeof data.detail==='string'?data.detail:JSON.stringify(data.detail)}catch{}throw new Error(message||'原生海图读取失败')}const actual=await response.json();if(!unchanged()){if(mounted.current&&sequence.current===token){setStale(true);setError('文件、选择或完整工作区已改变，迟到的海图响应已丢弃')}return}if(actual.schema!=='oceanroute.s57.bundle.v1'||actual.stage!==stage||actual.accepted!==true)throw new Error('海图 reader 未返回当前阶段的已接受结果');if(directory?.source?.sha256&&actual.source?.sha256!==directory.source.sha256)throw new Error('海图 binary 摘要不一致，请重新读取文件目录');
   if(stage==='inspect'){if(!Array.isArray(actual.cells))throw new Error('海图目录缺少 cells');setDirectory(actual);setCells([]);setClasses([])}else if(stage==='catalog'){if(!Array.isArray(actual.classes_catalog))throw new Error('原生目录缺少对象类列表');setCatalog(actual);setCatalogSignature(snapshot.catalogKey);setClasses([])}else{if(actual.can_apply!==true||!actual.layers?.length)throw new Error('所选海图对象未生成完整可应用图层');setPreview(actual);setPreviewSignature(snapshot.previewKey);setLayerIndex(0);notify('海图解析预览完成，尚未修改当前工程')}
  }catch(e){if(unchanged())setError(e instanceof Error?e.message:String(e));else if(mounted.current&&sequence.current===token){setStale(true);setError('输入或工作区已改变，迟到的失败响应也已丢弃')}}finally{if(mounted.current&&sequence.current===token)setOperation('')}
 }
 async function apply(){if(!canApply)return;const signature=previewKey,doc=contextKey,token=++sequence.current;setOperation('apply');setError('');try{const accepted=await onApply(preview!.layers,doc,()=>mounted.current&&sequence.current===token&&latest.current.previewKey===signature);if(!accepted&&mounted.current&&latest.current.previewKey===signature)setError('海图图层未应用，当前工程保持原状态；请核对提示后重新预览')}finally{if(mounted.current&&sequence.current===token)setOperation('')}}
 const active=preview?.layers?.[layerIndex];const features=active?.geojson?.features||[];const nativeCells=currentPreview?preview.cells:currentCatalog?catalog.cells:directory?.cells||[];
 return <div className="s57-import-panel"><p className="explanation">读取原生 S-57 .000 或包含单元及连续更新的 ZIP。先读取目录，明确选择单元和对象类，再预览实际结果。全部所选对象只加入共享参考图层；不修改路线、工程测深剖面或地形来源库，也不等同完整航海图符号显示。</p><div className="s57-input-row"><label className="file-drop"><Upload size={20}/><span>{file?`${file.name} · ${f(file.size)} bytes`:'选择原生 .000 或 S-57 ZIP'}</span><input aria-label="S-57 原生海图文件" type="file" accept=".000,.zip" onChange={e=>chooseFile(e.target.files?.[0])}/></label><button className="secondary-button" disabled={!file||busy} onClick={()=>run('inspect')}><Search size={14}/>{operation==='inspect'?'正在读取目录…':'读取海图文件目录'}</button></div>
 <details className="s57-budget"><summary>原生读取预算（空值使用后端默认，不自动增大）</summary><div className="s57-limit-fields">{limits.map(([key,label])=><label key={key}>{label}<input aria-label={'S-57 '+label} type="number" min={1} step={1} value={settings[key]||''} placeholder="后端默认" onChange={e=>{invalidate();setCatalog(null);setCatalogSignature('');setClasses([]);setSettings({...settings,[key]:e.target.value})}}/></label>)}</div></details>
 {directory&&<section className="s57-directory"><h3>1 · 文件单元目录</h3><p className="chart-meta">目录阶段只检查容器。对象数量、基准和 native class 需下一步实际读取；不会把未知数量显示为零。</p><div className="table-wrap"><table><thead><tr><th>明确选择</th><th>原生基础单元</th><th>文件大小</th><th>同组更新</th></tr></thead><tbody>{directory.cells.map((cell:Row)=><tr key={cell.path}><td><input type="checkbox" aria-label={'选择海图单元 '+cell.path} checked={cells.includes(cell.path)} onChange={e=>cellSelection(cell.path,e.target.checked)}/></td><td>{cell.path}</td><td>{f(cell.base?.bytes)} bytes</td><td>{cell.updates?.length?cell.updates.map((u:Row)=>u.path).join('、'):'无更新文件'}</td></tr>)}</tbody></table></div><div className="s57-actions"><span>已明确选择 {cells.length} 个单元</span><button className="secondary-button" disabled={!cells.length||busy} onClick={()=>run('catalog')}>{operation==='catalog'?'正在读取原生对象类…':'读取所选单元对象类目录'}</button></div><Warnings items={directory.warnings||[]}/><details><summary>原始文件摘要与容器诊断</summary><pre>{JSON.stringify({source:directory.source,summary:directory.summary,budget:directory.budget},null,2)}</pre></details></section>}
 {currentCatalog&&<section className="s57-catalog"><h3>2 · 实际原生对象类目录</h3><div className="s57-class-toolbar"><label>查找对象类<input aria-label="查找 S-57 对象类" value={search} onChange={e=>setSearch(e.target.value)} placeholder="SOUNDG / DEPARE…"/></label><button className="secondary-button" onClick={()=>{invalidate();setClasses(available.map((c:Row)=>c.name).sort())}}>明确选择全部对象类</button><button className="secondary-button" onClick={()=>{invalidate();setClasses([])}}>清空对象类选择</button></div><div className="table-wrap s57-classes-table"><table><thead><tr><th>明确选择</th><th>对象类</th><th>实际对象数</th><th>几何类型</th><th>所在单元</th></tr></thead><tbody>{listed.map((c:Row)=><tr key={c.name}><td><input type="checkbox" aria-label={'选择 S-57 对象类 '+c.name} checked={classes.includes(c.name)} onChange={e=>classSelection(c.name,e.target.checked)}/></td><td><strong>{c.name}</strong>{c.name==='SOUNDG'&&<small>海图测深值 · 非工程测深</small>}</td><td>{f(c.feature_count)}</td><td>{c.geometry_types?.map((g:string|null)=>g||'无几何').join('、')||'未知'}</td><td>{c.cells?.join('、')}</td></tr>)}</tbody></table></div><div className="s57-datums">{nativeCells.filter((c:Row)=>c.selected).map((c:Row)=><div key={c.path}><Datum cell={c}/><details><summary>该单元完整对象类字段目录</summary><pre>{JSON.stringify(c.object_classes,null,2)}</pre></details></div>)}</div><Warnings items={catalog.warnings||[]}/><label className="s57-name">导入图层名称前缀<input aria-label="S-57 图层名称前缀" value={name} onChange={e=>{invalidate();setName(e.target.value)}}/></label><div className="s57-actions"><span>已明确选择 {classes.length} / {available.length} 个对象类</span><button className="secondary-button" disabled={!classes.length||busy} onClick={()=>run('import')}>{operation==='import'?'正在解析实际海图…':'预览所选海图图层'}</button></div></section>}
 {error&&<div className="s57-error" role="alert"><AlertTriangle size={16}/><span>{error}</span></div>}{stale&&!currentPreview&&<div className="inline-warning s57-stale">输入、选择或工作区已改变，旧海图预览不能应用。请重新预览。</div>}
 {currentPreview&&<section className="s57-bundle-preview"><h3>3 · 实际海图结果 · 尚未应用</h3><div className="s57-preview-summary"><CheckCircle2 size={19}/><strong>{preview.layers.length} 个完整参考图层</strong><span>{preview.layers.reduce((n:number,l:Row)=>n+(l.geojson?.features?.length||0),0).toLocaleString('zh-CN')} 个实际输出对象</span><span>{f(preview.summary?.imported_vertices)} 个实际顶点</span><span>WGS84 · 共享所有路径</span></div><div className="inline-warning s57-sounding-notice">SOUNDG 第三维 Z 保留为源海图测深值，通常向下为正；单位及基准以各单元实际 metadata 为准，未转换为模型海面高度。不会未经声明采纳到工程测深、profile 或 terrain_sources。</div><div className="table-wrap s57-output-layers"><table><thead><tr><th>将一并应用的图层</th><th>类型</th><th>实际对象数</th></tr></thead><tbody>{preview.layers.map((l:Row)=><tr key={l.id}><td>{l.name}</td><td>{l.kind==='reference'?'参考图层':l.kind}</td><td>{f(l.geojson?.features?.length)}</td></tr>)}</tbody></table></div><label className="s57-layer-choice">查看实际输出图层<select aria-label="S-57 预览图层" value={layerIndex} onChange={e=>setLayerIndex(Number(e.target.value))}>{preview.layers.map((l:Row,i:number)=><option key={l.id} value={i}>{l.name}</option>)}</select></label>{active&&<><ChartPreview layer={active}/><details className="s57-feature-samples"><summary>实际输出前 {Math.min(features.length,30)} 个对象的属性与坐标（保留 Z）</summary><pre>{JSON.stringify(features.slice(0,30),null,2)}</pre></details></>}<div className="s57-datums">{preview.cells.filter((c:Row)=>c.selected).map((c:Row)=><div key={c.path}><Datum cell={c}/></div>)}</div>{preview.missing_classes_by_cell?.length>0&&<details open><summary>所选类在部分单元中不存在</summary><pre>{JSON.stringify(preview.missing_classes_by_cell,null,2)}</pre></details>}<Warnings items={preview.warnings||[]}/><details><summary>实际 reader、数量、预算与完整来源诊断</summary><pre>{JSON.stringify({source:preview.source,summary:preview.summary,budget:preview.budget,reader:preview.reader},null,2)}</pre></details><button className="secondary-button" onClick={()=>download(preview,'OceanRoute-S57-native-bundle.json')}><Download size={14}/>下载完整海图解析结果</button></section>}
 <div className="modal-actions"><span>{pending?'当前工作区尚在核验，请等待后重新预览。':'预览不修改工程；应用全部所选层为一次可撤销操作。'}</span><button className="secondary-button" onClick={onCancel}>取消</button><button className="primary-button" disabled={!canApply} onClick={apply}><Layers size={14}/>{operation==='apply'?'正在核验共享图层…':'应用全部所选海图图层'}</button></div>
 </div>
}
