import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import type {Frame,BathymetryGrid} from './types';
export type ComparisonPoint={id:string;predicted:number[];observed?:number[]};
const emptyComparison:ComparisonPoint[]=[];
export default function Scene3D({frame,depth,seabed,seabedGrid,showShip=true,comparisonPoints=emptyComparison,seaSurfaceZ=0}:{frame:Frame|null;depth:number;seabed?:{x_m:number;depth_m:number}[];seabedGrid?:BathymetryGrid;showShip?:boolean;comparisonPoints?:ComparisonPoint[];seaSurfaceZ?:number}){
  const element=useRef<HTMLDivElement>(null),[error,setError]=useState('');
  useEffect(()=>{
    if(!element.current||!frame)return;const parent=element.current;let renderer:THREE.WebGLRenderer;
    try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false})}catch{setError('当前环境无法创建 WebGL 视图。下方节点表仍可查看计算结果。');return}
    setError('');const scene=new THREE.Scene();scene.background=new THREE.Color('#eff5f7');
    const bedPoints=seabedGrid?seabedGrid.y_m.flatMap((y,j)=>seabedGrid.x_m.flatMap((x,i)=>Number.isFinite(seabedGrid.z_m[j]?.[i])?[[x,y,seabedGrid.z_m[j][i] as number]]:[])):[];
    const all=[...frame.nodes,frame.ship,...comparisonPoints.flatMap(p=>[p.predicted,...(p.observed?[p.observed]:[])])];const extent=showShip?Math.max(depth,50,Math.max(...all.map(p=>p[0]))-Math.min(...all.map(p=>p[0])),Math.max(...all.map(p=>p[1]))-Math.min(...all.map(p=>p[1])))*1.3:Math.max(30,Math.max(...all.map(p=>p[0]))-Math.min(...all.map(p=>p[0])),Math.max(...all.map(p=>p[2]))-Math.min(...all.map(p=>p[2])))*1.6;
    scene.fog=new THREE.Fog('#eff5f7',extent*4,extent*12);
    const convert=(p:number[])=>new THREE.Vector3(p[0],p[2],-p[1]);
    const camera=new THREE.PerspectiveCamera(40,parent.clientWidth/Math.max(parent.clientHeight,1),.1,extent*40);const center=new THREE.Box3().setFromPoints(all.map(convert)).getCenter(new THREE.Vector3());camera.position.copy(center).add(new THREE.Vector3(extent*1.2,extent*.7,extent*1.15));
    const controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(center);controls.enableDamping=true;controls.update();
    renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(parent.clientWidth,parent.clientHeight);parent.appendChild(renderer.domElement);
    scene.add(new THREE.AmbientLight('#ffffff',1.8));const light=new THREE.DirectionalLight('#ffffff',2);light.position.set(1,3,2);scene.add(light);
    const floor=new THREE.GridHelper(extent*5,40,'#7f9ca4','#c3d3d8');floor.position.set(center.x,seaSurfaceZ-Math.max(depth,...(seabed||[]).map(p=>p.depth_m)),center.z);if(!seabedGrid)scene.add(floor);else{floor.geometry.dispose();const materials=Array.isArray(floor.material)?floor.material:[floor.material];materials.forEach(m=>m.dispose())}if(seabedGrid&&bedPoints.length){const xyz:number[]=[],colors:number[]=[];const zValues=bedPoints.map(p=>p[2]),low=Math.min(...zValues),high=Math.max(...zValues);const color=new THREE.Color();const add=(p:number[])=>{const v=convert(p);xyz.push(v.x,v.y,v.z);color.setHSL(.43-.10*(p[2]-low)/Math.max(high-low,.0001),.20,.62);colors.push(color.r,color.g,color.b)};for(let j=0;j<seabedGrid.y_m.length-1;j++)for(let i=0;i<seabedGrid.x_m.length-1;i++){const corners=[[i,j],[i+1,j],[i+1,j+1],[i,j+1]].map(([a,b])=>[seabedGrid.x_m[a],seabedGrid.y_m[b],seabedGrid.z_m[b]?.[a]]);if(corners.every(p=>Number.isFinite(p[2]))){for(const index of [0,1,2,0,2,3])add(corners[index] as number[])}}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(xyz,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geometry.computeVertexNormals();const bed=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1,side:THREE.DoubleSide,transparent:true,opacity:.84}));scene.add(bed);scene.add(new THREE.LineSegments(new THREE.WireframeGeometry(geometry),new THREE.LineBasicMaterial({color:'#6c8b83',transparent:true,opacity:.23})));}if(seabed?.length){const bed=new THREE.Line(new THREE.BufferGeometry().setFromPoints(seabed.map(p=>new THREE.Vector3(p.x_m,-p.depth_m,0))),new THREE.LineBasicMaterial({color:'#77938c'}));scene.add(bed)}
    const sea=new THREE.Mesh(new THREE.PlaneGeometry(extent*5,extent*5),new THREE.MeshBasicMaterial({color:'#60b2cc',transparent:true,opacity:.11,side:THREE.DoubleSide,depthWrite:false}));sea.rotation.x=-Math.PI/2;sea.position.set(center.x,seaSurfaceZ,center.z);if(showShip)scene.add(sea);else{sea.geometry.dispose();(sea.material as THREE.Material).dispose();}
    const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(frame.nodes.map(convert)),new THREE.LineBasicMaterial({color:'#0b8884',linewidth:3}));scene.add(line);
    const sphereGeo=new THREE.SphereGeometry(extent*.005,8,8),nodeMat=new THREE.MeshBasicMaterial({color:'#147f80'}),contactMat=new THREE.MeshBasicMaterial({color:'#cd8343'});frame.nodes.forEach((p,i)=>{if(i%2===0||frame.node_contact_mask?.[i]){const dot=new THREE.Mesh(sphereGeo,frame.node_contact_mask?.[i]?contactMat:nodeMat);dot.position.copy(convert(p));scene.add(dot)}});
    if(showShip){const ship=new THREE.Mesh(new THREE.BoxGeometry(extent*.09,extent*.018,extent*.035),new THREE.MeshStandardMaterial({color:'#203c4f',roughness:.6}));ship.position.copy(convert(frame.ship));scene.add(ship);
    const td=new THREE.Mesh(new THREE.SphereGeometry(extent*.012,16,16),new THREE.MeshBasicMaterial({color:'#dba146'}));if(frame.touchdown){td.position.copy(convert(frame.touchdown));scene.add(td)}}
    if(frame.anchor_position_m){const support=new THREE.Mesh(new THREE.BoxGeometry(extent*.013,extent*.013,extent*.013),new THREE.MeshBasicMaterial({color:'#6b7990'}));support.position.copy(convert(frame.anchor_position_m));scene.add(support)}
    for(const b of frame.inline_bodies||[]){if(b.deployed_fraction>0&&b.position?.length===3){const body=new THREE.Mesh(new THREE.SphereGeometry(extent*.009,12,12),new THREE.MeshStandardMaterial({color:'#a7683c',roughness:.7}));body.position.copy(convert(b.position));scene.add(body)}}
    for(const p of comparisonPoints){const predicted=new THREE.Mesh(new THREE.SphereGeometry(extent*.011,12,12),new THREE.MeshBasicMaterial({color:'#5e82b0'}));predicted.position.copy(convert(p.predicted));scene.add(predicted);if(p.observed){const observed=new THREE.Mesh(new THREE.SphereGeometry(extent*.012,12,12),new THREE.MeshBasicMaterial({color:'#d39c43'}));observed.position.copy(convert(p.observed));scene.add(observed);scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([convert(p.predicted),convert(p.observed)]),new THREE.LineBasicMaterial({color:'#c66875'})))}}
    const axes=new THREE.AxesHelper(extent*.25);axes.position.set(center.x-extent*.4,seaSurfaceZ-Math.max(depth,...(seabed||[]).map(p=>p.depth_m)),center.z+extent*.4);scene.add(axes);
    let handle=0;const animate=()=>{handle=requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)};animate();
    const observer=new ResizeObserver(()=>{const w=parent.clientWidth,h=parent.clientHeight;renderer.setSize(w,h);camera.aspect=w/Math.max(h,1);camera.updateProjectionMatrix()});observer.observe(parent);
    return()=>{cancelAnimationFrame(handle);observer.disconnect();controls.dispose();scene.traverse(object=>{if(object instanceof THREE.Mesh||object instanceof THREE.Line){object.geometry.dispose();const mats=Array.isArray(object.material)?object.material:[object.material];mats.forEach(m=>m.dispose())}});renderer.dispose();renderer.domElement.remove();};
  },[frame,depth,seabed,seabedGrid,showShip,comparisonPoints,seaSurfaceZ]);
  return <div className="scene-host" ref={element}>{error?<div className="scene-placeholder">{error}</div>:!frame?<div className="scene-placeholder"><div className="wire-cube">3D</div><strong>敷设计算工作空间</strong><span>设置材料、海流与作业参数，运行求解器后查看真实计算节点。</span></div>:null}<div className="scene-legend"><i/>缆形节点 <b/>{showShip?(frame?.touchdown===null?'无实际触地点':'触地点'):'海床剖面'}{seabedGrid&&<em>真实二维床面 · 缺测格不绘 · 橙色：接触节点</em>}{frame?.anchor_position_m&&<em>灰：固定支持点，独立于触地点</em>}{comparisonPoints.length>0&&<em>蓝：预测应答器 · 金：观测 · 红：残差</em>} <span>拖动旋转 · 滚轮缩放 · 右键平移</span></div></div>;
}
