import {useMemo,useState} from 'react';
import {Ship,ChartNoAxesCombined,Target,Play,Download,ChevronRight,Plus,Trash2,FlaskConical,Settings2,CheckCircle2,AlertTriangle,Upload,X} from 'lucide-react';
import {NumberField,TextField} from './fields';
import {request} from './api';
import type {Project,Frame} from './types';
import MapView from './MapView';
import Scene3D from './Scene3D';
import CheckpointActions from './CheckpointActions';
const options=[{id:'create',name:'船舶作业计划',sub:'SHIP PLAN',icon:Ship},{id:'lookahead',name:'前瞻方案比较',sub:'LOOK AHEAD',icon:ChartNoAxesCombined},{id:'optimize',name:'目标张力搜索',sub:'TENSION SEARCH',icon:Target}];
const configLabels:Record<string,string>={sample_spacing_m:'路线采样间距 / m',max_samples:'最大样本数',body_pause_s:'缆体作业停顿 / s',transition_speed_m_s:'转向过渡船速 / m·s⁻¹',event_payout_m_s:'定点放缆速度 / m·s⁻¹',bottom_tension_n:'初始海底张力 / N',ship_speed_m_s:'基准船速 / m·s⁻¹',payout_m_s:'基准放缆速度 / m·s⁻¹',depth_m:'初始水深 / m',duration_s:'局部模拟时长 / s',dt_s:'输出帧间隔 / s',heading_deg:'船艏向 / °',nodes:'离散节点数',internal_dt_s:'内部步长 / s',solver_iterations:'求解迭代次数',current_x_m_s:'X 向海流 / m·s⁻¹',current_y_m_s:'Y 向海流 / m·s⁻¹',evaluation_window_s:'评价时间窗 / s',target_bottom_tension_n:'目标海底张力 / N',tension_tolerance_n:'目标允许误差 / N',payout_min_m_s:'最小放缆速度 / m·s⁻¹',payout_max_m_s:'最大放缆速度 / m·s⁻¹',max_evaluations:'最大求解次数'};
const outputLabels:Record<string,string>={duration_s:'计划 / 模拟时长 / s',vessel_track_length_m:'船舶轨迹长度 / m',route_length_m:'路由长度 / m',assembly_length_m:'装配长度 / m',paid_out_m:'累计放缆 / m',operator_extra_cable_m:'操作额外缆长 / m',material_balance_residual_m:'材料长度平衡残差 / m',instruction_count:'作业指令数',sample_count:'采样点数',effective_sample_spacing_m:'实际采样间距 / m',pause_duration_s:'累计停顿 / s',transition_duration_s:'累计过渡时间 / s',scenario_count:'比较方案数',output_interval_s:'输出间隔 / s',evaluation_window_s:'评价时间窗 / s',all_solvers_converged:'全部方案求解收敛',evaluation_count:'实际求解次数',valid_evaluations:'有效求解次数',max_evaluations:'最大求解次数',payout_min_m_s:'最小放缆速度 / m·s⁻¹',payout_max_m_s:'最大放缆速度 / m·s⁻¹'};
const fmt=(n:any,d=3)=>n==null?'—':typeof n==='number'?n.toLocaleString('zh-CN',{maximumFractionDigits:d}):typeof n==='boolean'?(n?'是':'否'):String(n);
function download(data:unknown,name:string,csv=false){const url=URL.createObjectURL(new Blob([csv?'\ufeff'+data:JSON.stringify(data,null,2)],{type:csv?'text/csv;charset=utf-8':'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
function csvCell(v:any){let text=v==null?'':String(v);if(/^[=+@-]/.test(text)&&typeof v!=='number')text="'"+text;return '"'+text.replaceAll('"','""')+'"'}
type Scenario={name:string;overrides:{ship_speed_m_s:number;payout_m_s:number;current_x_m_s:number;current_y_m_s:number;heading_deg?:number}};
export default function ShipPlanning({project,notify,initialCheckpoint,onRestore}:{project:Project;notify:(message:string,error?:boolean)=>void;initialCheckpoint?:any;onRestore?:(state:any)=>void}){
  const active=initialCheckpoint?.state?.plan?.[initialCheckpoint.state.plan_index];
  const [kind,setKind]=useState(initialCheckpoint?'lookahead':'create'),[config,setConfig]=useState<Record<string,number>>({sample_spacing_m:20000,max_samples:100,body_pause_s:0,transition_speed_m_s:.5,event_payout_m_s:.2,bottom_tension_n:1000,ship_speed_m_s:1.5,payout_m_s:1.53,depth_m:500,dt_s:1,nodes:16,internal_dt_s:.1,solver_iterations:16,current_x_m_s:0,current_y_m_s:.2,evaluation_window_s:3,target_bottom_tension_n:1000,tension_tolerance_n:100,payout_min_m_s:1.3,payout_max_m_s:1.7,max_evaluations:7,heading_deg:90,...Object.fromEntries(Object.entries(initialCheckpoint?.config||{}).filter(([,v])=>typeof v==='number')),...(active?{ship_speed_m_s:active.speed_m_s,heading_deg:active.heading_deg,payout_m_s:active.payout_m_s}:{}),duration_s:10}),[cable,setCable]=useState(project.cable_types[0]?.id),[scenarios,setScenarios]=useState<Scenario[]>([{name:'基准方案',overrides:{ship_speed_m_s:active?.speed_m_s??1.5,payout_m_s:active?.payout_m_s??1.53,heading_deg:active?.heading_deg??90,current_x_m_s:initialCheckpoint?.config.current_x_m_s??0,current_y_m_s:initialCheckpoint?.config.current_y_m_s??.2}},{name:'增加放缆',overrides:{ship_speed_m_s:1.5,payout_m_s:1.6,current_x_m_s:0,current_y_m_s:.2}},{name:'增大海流',overrides:{ship_speed_m_s:1.5,payout_m_s:1.53,current_x_m_s:0,current_y_m_s:.4}}]),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[selectedScenario,setSelectedScenario]=useState(0),[frameIndex,setFrameIndex]=useState(0),[events,setEvents]=useState(''),[resultDepth,setResultDepth]=useState(500),[resultInputs,setResultInputs]=useState(''),[checkpointText,setCheckpointText]=useState(initialCheckpoint?JSON.stringify(initialCheckpoint,null,2):'');
  const fields=kind==='create'?['sample_spacing_m','max_samples','body_pause_s','bottom_tension_n','ship_speed_m_s','transition_speed_m_s','event_payout_m_s','current_x_m_s','current_y_m_s']:['depth_m','bottom_tension_n','ship_speed_m_s','heading_deg','payout_m_s','current_x_m_s','current_y_m_s','duration_s','dt_s','nodes','internal_dt_s','solver_iterations','evaluation_window_s',...(kind==='optimize'?['target_bottom_tension_n','tension_tolerance_n','payout_min_m_s','payout_max_m_s','max_evaluations']:[])];
  const inputSignature=JSON.stringify({kind,config,cable,scenarios,events,checkpointText});
  async function run(){setBusy(true);setResult(null);const snapshot=inputSignature;const computedDepth=config.depth_m;try{let body:any={...config,cable_type_id:cable,include_frames:true,...(kind==='create'&&events.trim()?{events:JSON.parse(events)}:{})};if(kind!=='create'){body.save_checkpoints=true;if(checkpointText.trim()){body={resume_state:JSON.parse(checkpointText),duration_s:config.duration_s,evaluation_window_s:config.evaluation_window_s,include_frames:true,save_checkpoints:true};if(kind==='optimize')for(const key of ['target_bottom_tension_n','tension_tolerance_n','payout_min_m_s','payout_max_m_s','max_evaluations'])body[key]=config[key]}}const data=await request<any>('/shipplan/'+kind,{project,config:body,...(kind==='lookahead'?{scenarios}:{})});setResult(data);setResultDepth(body.resume_state?.config.depth_m??computedDepth);setResultInputs(snapshot);setSelectedScenario(0);setFrameIndex(0);notify('船舶工程计算完成')}catch(e){notify(e instanceof Error?e.message:String(e),true)}finally{setBusy(false)}}
  function restoreState(state:any){if(state.schema!=='oceanroute.dynamic.checkpoint')throw new Error('请选择完整动态状态 JSON');setCheckpointText(JSON.stringify(state,null,2));setResult(null);setKind('lookahead');setFrameIndex(0)}
  async function readState(file?:File){if(!file)return;try{restoreState(JSON.parse(await file.text()));notify('完整动态状态已载入，后续方案从保存状态分支')}catch(e){notify(e instanceof Error?e.message:String(e),true)}}
  const vesselProject=useMemo(()=>{if(!result?.vessel_waypoints?.length)return project;return {...project,layers:[...project.layers,{id:'computed-vessel-track',name:'计算船舶轨迹',kind:'vessel',visible:true,geojson:{type:'FeatureCollection',features:[{type:'Feature',properties:{name:'Ship Plan 计算轨迹'},geometry:{type:'LineString',coordinates:result.vessel_waypoints.map((v:any)=>[v.vessel_longitude,v.vessel_latitude])}}]}}]}},[result,project]);
  const simulation=kind==='lookahead'?result?.scenarios?.[selectedScenario]?.simulation:result?.simulation;const frames:Frame[]=simulation?.frames||[],frame=frames[Math.min(frameIndex,frames.length-1)]||null;
  const branches=result?.scenarios||[],maxTension=Math.max(1,...branches.map((b:any)=>b.metrics.mean_bottom_tension_n));
  function instructionsCSV(){const keys=['time_s','end_time_s','duration_s','kind','name','kp_start_m','kp_end_m','cable_start_m','cable_end_m','cable_type_id','speed_m_s','heading_deg','payout_m_s'];const lines=[keys.map(csvCell).join(','),...(result.instructions||[]).map((row:any)=>keys.map(k=>csvCell(row[k])).join(','))];download(lines.join('\r\n'),'OceanRoute-ship-plan.csv',true)}
  function useScenario(i:number){setSelectedScenario(i);setFrameIndex(0)}
  return <div className="simulation-layout ship-planning"><aside className="sim-settings"><div className="section-label">船舶工程工作流</div><div className="solver-tabs">{options.map(o=><button className={kind===o.id?'active':''} key={o.id} onClick={()=>{setKind(o.id);setResult(null)}}><strong>{o.name}</strong><small>{o.sub}</small><ChevronRight size={14}/></button>)}</div><div className="section-label"><Settings2 size={14}/>计算参数</div>{kind!=='create'&&<label className="cable-selector">研究缆型<select value={cable} onChange={e=>setCable(e.target.value)}>{project.cable_types.map(c=><option key={c.id} value={c.id}>{c.id} · {c.name}</option>)}</select></label>}<div className="sim-fields">{fields.map(key=><label key={key}>{configLabels[key]}<NumberField value={config[key]} disabled={kind!=='create'&&!!checkpointText.trim()&&!['duration_s','evaluation_window_s','target_bottom_tension_n','tension_tolerance_n','payout_min_m_s','payout_max_m_s','max_evaluations'].includes(key)} onChange={v=>setConfig({...config,[key]:v??0})}/></label>)}</div>{kind!=='create'&&<details className="advanced-environment checkpoint-settings" open={!!checkpointText.trim()}><summary>从已保存状态分支</summary><label className="file-drop"><Upload size={17}/><span>上传完整动态状态 JSON</span><input type="file" accept=".json" onChange={e=>readState(e.target.files?.[0])}/></label><label className="text-config">前瞻初始状态 JSON<textarea value={checkpointText} onChange={e=>setCheckpointText(e.target.value)} placeholder="原始 checkpoint 对象，包含完整状态与 checksum" spellCheck={false}/></label>{checkpointText.trim()&&<><button className="secondary-button" onClick={()=>{setCheckpointText('');setResult(null)}}><X size={13}/>改用解析初始状态</button><p className="chart-meta">分支保留保存的物性、材料、锚点、海床、速度场和时钟；方案表中的控制覆盖后续作业。</p></>}</details>}{kind==='create'&&<details className="advanced-environment"><summary>额外作业事件</summary><label className="text-config">事件 JSON<textarea value={events} onChange={e=>setEvents(e.target.value)} placeholder={'[{"kp_m":10000,"name":"停顿","duration_s":60,"payout_m_s":0}]'}/></label></details>}<button className="primary-button sim-run" disabled={busy} onClick={run}><Play size={14}/>{busy?'正在求解…':'计算船舶工程'}</button><div className="research-note"><FlaskConical size={16}/><p>{kind==='create'?'根据稳态偏移计算预备船位和分段作业计划。材料平衡、缆体事件和转向过渡均在结果中列明。':kind==='lookahead'?'从同一初始缆形分别运行真实动态方案；比较末段时间窗内的张力与触地点偏移。':'在限定放缆速度区间运行有限次数动态搜索；报告是否达到目标及每次求解的实际结果。'}</p></div></aside><main className="sim-main"><div className="sim-heading"><div><small>SHIP INSTALLATION PLANNING</small><h2>{options.find(o=>o.id===kind)?.name}</h2></div><span className="tag warning">研究工作流</span><button className="secondary-button" onClick={()=>download(result,`OceanRoute-${kind}-result.json`)} disabled={!result}><Download size={15}/>结果 JSON</button>{kind==='create'&&<button className="primary-button" disabled={!result} onClick={instructionsCSV}><Download size={15}/>指令 CSV</button>}</div>
    {kind==='lookahead'&&<div className="scenario-editor"><div className="section-heading"><h3>比较方案</h3><button className="secondary-button" disabled={scenarios.length>=6} onClick={()=>setScenarios([...scenarios,{name:`方案 ${scenarios.length+1}`,overrides:{ship_speed_m_s:config.ship_speed_m_s,payout_m_s:config.payout_m_s,current_x_m_s:config.current_x_m_s,current_y_m_s:config.current_y_m_s}}])}><Plus size={14}/>新增方案</button></div><div className="table-wrap"><table><thead><tr><th>方案名称</th><th>船速 / m·s⁻¹</th><th>艏向 / °</th><th>放缆 / m·s⁻¹</th><th>X 海流 / m·s⁻¹</th><th>Y 海流 / m·s⁻¹</th><th/></tr></thead><tbody>{scenarios.map((s,i)=><tr key={i}><td><TextField value={s.name} onChange={v=>setScenarios(scenarios.map((row,j)=>j===i?{...row,name:v}:row))}/></td>{(['ship_speed_m_s','heading_deg','payout_m_s','current_x_m_s','current_y_m_s'] as const).map(key=><td key={key}><NumberField value={s.overrides[key]??config[key]} onChange={v=>setScenarios(scenarios.map((row,j)=>j===i?{...row,overrides:{...row.overrides,[key]:v??0}}:row))}/></td>)}<td><button className="icon-button" title="删除方案" disabled={scenarios.length<=1} onClick={()=>setScenarios(scenarios.filter((_,j)=>j!==i))}><Trash2 size={13}/></button></td></tr>)}</tbody></table></div></div>}
    {result&&<>{inputSignature!==resultInputs&&<div className="inline-warning">计算参数已修改。当前结果按上次计算条件显示；重新计算后更新。</div>}<div className="sim-results ship-summary"><div className="panel-heading">计算摘要 <small>{result.model}</small></div><div className="summary-fields">{Object.entries(result.summary||{}).map(([key,v])=><div key={key}><span>{outputLabels[key]||key}</span><strong>{fmt(v)}</strong></div>)}</div></div>
    {kind==='create'&&<><div className="ship-map"><MapView project={vesselProject} geometry={result.target_route?.map((p:any)=>[p.longitude,p.latitude])} selected={null} onSelect={()=>{}} onAdd={()=>{}} onMove={()=>{}} fitVersion={0} editable={false}/><div className="ship-map-legend"><i/>目标缆路由<b/>稳态偏移后的船舶轨迹</div></div><div className="section-heading"><h3>时间与放缆指令</h3><span className="chart-meta">表面 KP 与材料缆里程分别记录</span></div><div className="table-wrap ship-instructions"><table><thead><tr><th>#</th><th>时间 / h</th><th>作业类型</th><th>缆型</th><th>表面 KP 起 / km</th><th>KP 止 / km</th><th>缆里程止 / km</th><th>船速 / m·s⁻¹</th><th>艏向 / °</th><th>放缆 / m·s⁻¹</th></tr></thead><tbody>{result.instructions?.map((r:any,i:number)=><tr key={i}><td>{i+1}</td><td>{fmt(r.time_s/3600)} → {fmt(r.end_time_s/3600)}</td><td>{({lay:'敷设',offset_transition:'船位过渡',body_pause:'缆体停顿',operator_pause:'操作停顿',additional_material:'额外材料'} as Record<string,string>)[r.kind]||r.kind}</td><td>{r.cable_type_id}</td><td>{fmt(r.kp_start_m/1000)}</td><td>{fmt(r.kp_end_m/1000)}</td><td>{fmt(r.cable_end_m/1000)}</td><td>{fmt(r.speed_m_s)}</td><td>{fmt(r.heading_deg,1)}</td><td>{fmt(r.payout_m_s)}</td></tr>)}</tbody></table></div><details className="nodes-table"><summary>查看地理船位与路由采样（{result.vessel_waypoints?.length||0} 点）</summary><table><thead><tr><th>表面 KP / km</th><th>时间 / h</th><th>船舶经度</th><th>船舶纬度</th><th>路由水深 / m</th><th>缆型</th></tr></thead><tbody>{result.vessel_waypoints?.map((v:any,i:number)=><tr key={i}><td>{fmt(v.kp_m/1000)}</td><td>{fmt(v.time_s/3600)}</td><td>{fmt(v.vessel_longitude,6)}</td><td>{fmt(v.vessel_latitude,6)}</td><td>{fmt(v.depth_m)}</td><td>{v.cable_type_id}</td></tr>)}</tbody></table></details></>}
    {kind==='lookahead'&&<><div className="comparison-chart"><div className="panel-heading">评价时间窗 · 平均海底张力 <small>N</small></div>{branches.map((b:any,i:number)=><button key={b.name} className={selectedScenario===i?'selected':''} onClick={()=>useScenario(i)}><span>{b.name}</span><div><i style={{width:`${b.metrics.mean_bottom_tension_n/maxTension*100}%`,background:['#188b80','#517ca0','#d2a453','#8e89b0'][i%4]}}/></div><strong>{fmt(b.metrics.mean_bottom_tension_n,2)} N</strong></button>)}</div><div className="table-wrap"><table><thead><tr><th>方案</th><th>平均海底张力 / N</th><th>标准差 / N</th><th>峰值顶部张力 / N</th><th>触地点相对偏移 / m</th><th>最小半径 / m</th><th>收敛</th></tr></thead><tbody>{branches.map((b:any,i:number)=><tr key={b.name} className={selectedScenario===i?'selected':''} onClick={()=>useScenario(i)}><td>{b.name}</td><td>{fmt(b.metrics.mean_bottom_tension_n)}</td><td>{fmt(b.metrics.bottom_tension_std_n)}</td><td>{fmt(b.metrics.peak_top_tension_n)}</td><td>{fmt(b.metrics.touchdown_shift_m)}</td><td>{fmt(b.metrics.minimum_bend_radius_m)}</td><td>{fmt(b.metrics.solver_converged)}</td></tr>)}</tbody></table></div>{branches[selectedScenario]?.warnings?.map((w:any,i:number)=><div className="inline-warning" key={i}>{w.message||w}</div>)}</>}
    {kind==='optimize'&&<><div className={`optimization-result ${result.target_met?'met':''}`}>{result.target_met?<CheckCircle2 size={23}/>:<AlertTriangle size={23}/>}<div><strong>{result.target_met?'已达到目标容差':'当前搜索未达到目标容差'}</strong><span>最接近方案：放缆 {fmt(result.payout_m_s,4)} m/s · 平均海底张力 {fmt(result.achieved_bottom_tension_n)} N · 目标 {fmt(result.target_bottom_tension_n)} N · 误差 {fmt(result.error_n)} N</span></div></div><div className="table-wrap"><table><thead><tr><th>求解 #</th><th>放缆速度 / m·s⁻¹</th><th>海底张力 / N</th><th>RMS 误差 / N</th><th>收敛</th></tr></thead><tbody>{(result.evaluations||result.history||[]).map((e:any,i:number)=><tr key={i}><td>{i+1}</td><td>{fmt(e.payout_m_s,4)}</td><td>{fmt(e.metrics?.mean_bottom_tension_n??e.achieved_bottom_tension_n)}</td><td>{fmt(e.rms_error_n)}</td><td>{fmt(e.metrics?.solver_converged??e.converged)}</td></tr>)}</tbody></table></div>{result.search_failures?.map((f:any,i:number)=><div className="inline-warning" key={i}>{fmt(f.payout_m_s)} m/s：{f.message||f.error}</div>)}</>}
    {simulation&&<><CheckpointActions result={simulation} time={frame?.time_s} onResume={onRestore||restoreState} onLookAhead={restoreState}/><div className="sim-view"><Scene3D frame={frame} depth={resultDepth} seabedGrid={simulation?.seabed?.grid}/><div className="sim-overlay"><span>{kind==='lookahead'?branches[selectedScenario]?.name:'搜索所得最接近方案'}</span><strong>t = {fmt(frame?.time_s,2)} s</strong></div></div><div className="playback"><input aria-label="方案结果帧" type="range" min="0" max={Math.max(0,frames.length-1)} value={frameIndex} onChange={e=>setFrameIndex(Number(e.target.value))}/><span>{frameIndex+1} / {frames.length} 帧</span></div></>}
    <div className="assumptions"><strong>计算假设与适用条件</strong>{result.assumptions?.map((s:string,i:number)=><p key={i}>{s}</p>)}</div>{result.warnings?.map((w:any,i:number)=><div className="inline-warning" key={i}>{w.message||w}</div>)}</>}
    {!result&&<div className="tool-empty"><Ship size={35}/><span>设置计算条件后运行，查看实际船位、作业指令或方案对比结果。</span></div>}
  </main></div>;
}
