import {useEffect,useRef,useState} from 'react';
import {Check,ChevronLeft,ChevronRight,Download,Play,Plus,Trash2} from 'lucide-react';
import {request} from './api';
import type {Project,Analysis,SideSlopeSample,SideSlopes,SlopeRule,TerrainSource} from './types';
import './sideSlopes.css';

type Props={project:Project;analysis:Analysis|null;contextKey?:string;pending?:boolean;onApply:(project:Project,key:string,isCurrent?:()=>boolean)=>boolean|void|Promise<boolean|void>;notify:(message:string,error?:boolean)=>void};
type SamplingDraft={spacing_m:string;half_width_m:string;cross_spacing_m:string;start_kp_m:string;end_kp_m:string;vertical_datum:string;max_query_points:string;max_work_units:string;max_output_bytes:string};
type RuleDraft=Omit<SlopeRule,'start_kp_m'|'end_kp_m'|'max_inline_slope_deg'|'max_side_slope_deg'>&{start_kp_m:string;end_kp_m:string;max_inline_slope_deg:string;max_side_slope_deg:string};
type Result={kind:'sampling'|'rules';data:any;signature:string;contextKey:string};
const defaults:SamplingDraft={spacing_m:'1000',half_width_m:'100',cross_spacing_m:'50',start_kp_m:'0',end_kp_m:'',vertical_datum:'',max_query_points:'50000',max_work_units:'30000000',max_output_bytes:'16777216'};
const statuses:Record<string,string>={sampled_pass:'仅采样通过',violations:'实际采样超限',incomplete:'数据不完整 / 含不确定来源',unknown:'缺少有效或当前数据',disabled:'已禁用',not_configured:'尚未配置规则'};
const coverageLabels:Record<string,string>={complete:'覆盖完整',requested_range_m:'请求 KP 范围 / m',covered_ranges_m:'已有覆盖 / m',unknown_ranges_m:'未知区间 / m',covered_length_m:'已有覆盖长度 / m',unknown_length_m:'未知长度 / m',data_range_m:'数据范围 / m',sampled_kps_m:'域内实际站位 / m',supporting_kps_m:'支持站位 / m',missing_kps_m:'缺测站位 / m',uncertain_kps_m:'来源不确定站位 / m',sampling_gaps_m:'采样间隙 / m',sampling_only:'仅采样检查',continuous_bed_verified:'连续海床已验明'};
function finite(value:unknown):value is number{return typeof value==='number'&&Number.isFinite(value)}
function f(value:unknown,digits=3):string{return finite(value)?value.toLocaleString('zh-CN',{maximumFractionDigits:digits}):value==null?'缺测':typeof value==='boolean'?(value?'是':'否'):typeof value==='object'?JSON.stringify(value):String(value)}
function number(text:string,label:string,nullable=false){if(!text.trim()){if(nullable)return null;throw new Error(label+'不能为空')}const value=Number(text);if(!Number.isFinite(value))throw new Error(label+'须为有限数值');return value}
function ruleDraft(rule:SlopeRule):RuleDraft{return {...rule,name:rule.name||'',enabled:rule.enabled!==false,start_kp_m:String(rule.start_kp_m??0),end_kp_m:rule.end_kp_m==null?'':String(rule.end_kp_m),max_inline_slope_deg:rule.max_inline_slope_deg==null?'':String(rule.max_inline_slope_deg),max_side_slope_deg:rule.max_side_slope_deg==null?'':String(rule.max_side_slope_deg)}}
function ruleInput(rule:RuleDraft):SlopeRule{return {id:rule.id,name:rule.name,enabled:rule.enabled,kind:rule.kind,start_kp_m:number(rule.start_kp_m,'规则起始 KP')!,end_kp_m:number(rule.end_kp_m,'规则终止 KP',true),...(rule.kind!=='side'?{max_inline_slope_deg:number(rule.max_inline_slope_deg,'纵坡阈值')!}:{}),...(rule.kind!=='inline'?{max_side_slope_deg:number(rule.max_side_slope_deg,'侧坡阈值')!}:{})}}
function download(content:string,name:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
function coverageValue(value:unknown){if(Array.isArray(value)&&value.length>12)return JSON.stringify(value.slice(0,12))+' … 共 '+value.length+' 项（完整内容见 JSON）';return f(value)}
function csv(rows:unknown[][]){return rows.map(row=>row.map(v=>v==null?'':'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n')+'\n'}
function chunks<T>(rows:T[],isValid:(row:T)=>boolean){const result:T[][]=[];let current:T[]=[];for(const row of rows){if(isValid(row))current.push(row);else if(current.length){result.push(current);current=[]}}if(current.length)result.push(current);return result}

function AlongSlopes({samples,selected,onSelect}:{samples:SideSlopeSample[];selected:number;onSelect:(index:number)=>void}){
 const x0=samples[0]?.kp_m??0,x1=samples.at(-1)?.kp_m??1,magnitude=samples.reduce((m,s)=>Math.max(m,...[s.port_slope_deg,s.starboard_slope_deg].filter(finite).map(Math.abs)),1),x=(kp:number)=>58+(kp-x0)/Math.max(x1-x0,1)*870,y=(v:number)=>118-v/magnitude*83;
 return <div className="side-slopes-chart"><svg viewBox="0 0 1000 250" role="img" aria-label="沿 KP 左右有符号侧坡曲线" onClick={e=>{if(!samples.length)return;const box=e.currentTarget.getBoundingClientRect(),kp=x0+(((e.clientX-box.left)/box.width*1000-58)/870)*(x1-x0);let best=0;for(let i=1;i<samples.length;i++)if(Math.abs(samples[i].kp_m-kp)<Math.abs(samples[best].kp_m-kp))best=i;onSelect(best)}}>
 {[magnitude,0,-magnitude].map(v=><g key={v}><line x1="58" x2="928" y1={y(v)} y2={y(v)} className="ss-grid"/><text x="50" y={y(v)+4} textAnchor="end">{f(v,2)}°</text></g>)}
 {(['port_slope_deg','starboard_slope_deg'] as const).map(key=>chunks(samples,s=>finite(s[key])).map((section,i)=><polyline key={key+i} className={key==='port_slope_deg'?'ss-port':'ss-starboard'} points={section.map(s=>`${x(s.kp_m)},${y(s[key]!)}`).join(' ')} />))}
 {samples[selected]&&<line className="ss-selected" x1={x(samples[selected].kp_m)} x2={x(samples[selected].kp_m)} y1="27" y2="207"/>}{[x0,(x0+x1)/2,x1].map((kp,i)=><text key={i} x={x(kp)} y="230" textAnchor="middle">{f(kp/1000)} km</text>)}<text x="58" y="18">有符号角 / ° · 正值为右舷上坡</text>
 </svg><div className="ss-legend"><span><i className="port"/>左舷半幅坡</span><span><i className="starboard"/>右舷半幅坡</span><span>点击曲线选择最近真实站位；缺测处断线。</span></div></div>
}
function Transect({sample}:{sample:SideSlopeSample}){
 const rows=sample.transect||[],valid=rows.filter(r=>finite(r.depth_m));if(!rows.length)return <p className="chart-meta">该站没有横断面探点。</p>;const x0=rows[0].offset_m,x1=rows.at(-1)!.offset_m,lo=valid.reduce((v,r)=>Math.min(v,r.depth_m!),Infinity),hi=valid.reduce((v,r)=>Math.max(v,r.depth_m!),-Infinity),pad=Math.max(1,(hi-lo)*.1),x=(o:number)=>62+(o-x0)/Math.max(x1-x0,1)*866,y=(d:number)=>35+(d-lo+pad)/Math.max(hi-lo+2*pad,1)*160;
 return <div className="side-slopes-chart"><svg viewBox="0 0 1000 247" role="img" aria-label="选定 KP 真实横向水深截面">
 {valid.length>0&&[lo,(lo+hi)/2,hi].map((d,i)=><g key={i}><line x1="62" x2="928" y1={y(d)} y2={y(d)} className="ss-grid"/><text x="54" y={y(d)+4} textAnchor="end">{f(d,2)}</text></g>)}<line x1={x(0)} x2={x(0)} y1="28" y2="202" className="ss-selected"/>{chunks(rows,r=>finite(r.depth_m)).map((group,i)=><polyline key={i} className="ss-depth" points={group.map(r=>`${x(r.offset_m)},${y(r.depth_m!)}`).join(' ')}/>)}
 {rows.map((r,i)=>finite(r.depth_m)?<circle key={i} cx={x(r.offset_m)} cy={y(r.depth_m)} r="3" className={r.fallback?'ss-fallback':'ss-depth-point'}><title>{`${f(r.offset_m)} m · ${f(r.depth_m)} m · ${r.source_id||'未知来源'}`}</title></circle>:<g key={i} className="ss-missing"><path d={`M${x(r.offset_m)-4},180 l8,8 m-8,0 l8,-8`}/><title>{`${f(r.offset_m)} m 缺测`}</title></g>)}<text x="62" y="17">水深 / m · 向下为正</text><text x="62" y="225">左舷 {f(x0)} m</text><text x={x(0)} y="225" textAnchor="middle">路线 0</text><text x="928" y="225" textAnchor="end">右舷 +{f(x1)} m</text>
 </svg>{!valid.length&&<p className="inline-warning">该横断面全部缺测，没有可绘制水深。</p>}</div>
}

export default function SideSlopesPanel({project,analysis,contextKey='',pending=false,onApply,notify}:Props){
 const [tab,setTab]=useState<'sampling'|'rules'>('sampling'),[sampling,setSampling]=useState<SamplingDraft>(defaults),[sourceDraft,setSourceDraft]=useState<TerrainSource[]|null>(null),[rules,setRules]=useState<RuleDraft[]>(()=> (project.slope_rules||[]).map(ruleDraft)),[ruleBudget,setRuleBudget]=useState({max_rules:'128',max_work_units:'5000000',max_output_bytes:'16777216'}),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[discarded,setDiscarded]=useState(false),[selected,setSelected]=useState(0),[stationPage,setStationPage]=useState(0),[transectPage,setTransectPage]=useState(0),[savedView,setSavedView]=useState(true);
 const lastPath=useRef(project.id);useEffect(()=>{if(lastPath.current!==project.id){lastPath.current=project.id;setSourceDraft(null);setResult(null);setError('');setDiscarded(false);setSavedView(true);setSelected(0);setStationPage(0);setTransectPage(0)}},[project.id]);
 const rulesSource=JSON.stringify(project.slope_rules||[]),loadedRules=useRef(rulesSource);useEffect(()=>{if(loadedRules.current!==rulesSource){loadedRules.current=rulesSource;setRules((project.slope_rules||[]).map(ruleDraft))}},[rulesSource,project.slope_rules]);
 const signature=JSON.stringify({project,contextKey,sampling,sourceDraft,rules,ruleBudget}),latest=useRef(signature);latest.current=signature;const mounted=useRef(true),sequence=useRef(0);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;sequence.current++}},[]);
 const current=!!result&&result.signature===signature,binding=analysis?.side_slopes_metadata,storedValid=!!project.side_slopes&&binding?.geometry_current===true&&binding?.library_current===true&&binding?.source_binding_current===true;
 const storedCurrent=!result&&!error&&!discarded&&!busy&&!pending&&savedView&&!sourceDraft&&storedValid;
 const side:SideSlopes|undefined=current&&result?.kind==='sampling'?result.data.side_slopes:storedCurrent?project.side_slopes:undefined,samples=side?.samples||[],station=samples[Math.min(selected,samples.length-1)],actual=current?result?.data:storedCurrent?{side_slopes:project.side_slopes,sources:project.terrain_sources,metadata:binding,stored_record:true}:null;
 const sources=sourceDraft||project.terrain_sources||[],sourceNames=new Map<string,string>((actual?.sources||sources).map((s:any)=>[s.id,s.name||s.id])),datums=[...new Set(sources.filter(s=>s.enabled!==false).map(s=>s.vertical_datum).filter(Boolean))];
 function changeSampling(key:keyof SamplingDraft,value:string){setSampling(old=>({...old,[key]:value}));setSavedView(false)}
 function sampleConfig(){return {...Object.fromEntries(Object.entries(sampling).filter(([k])=>k!=='vertical_datum'&&k!=='end_kp_m').map(([k,v])=>[k,number(v,k)])),...(sampling.end_kp_m.trim()?{end_kp_m:number(sampling.end_kp_m,'终止 KP')}:{}),...(sampling.vertical_datum.trim()?{vertical_datum:sampling.vertical_datum.trim()}:{})}}
 async function run(kind:'sampling'|'rules'){
  const snapshot=signature,requestId=++sequence.current;setBusy(true);setResult(null);setError('');setDiscarded(false);setSavedView(false);
  try{const config=kind==='sampling'?sampleConfig():{rules:rules.map(ruleInput),...Object.fromEntries(Object.entries(ruleBudget).map(([k,v])=>[k,number(v,k)]))},data=await request<any>(kind==='sampling'?'/terrain/side-slopes':'/tools/slope-rules',{project:kind==='sampling'&&sourceDraft?{...project,terrain_sources:sourceDraft}:project,config});if(!mounted.current||sequence.current!==requestId)return;if(latest.current!==snapshot){setDiscarded(true);notify('计算期间输入或工作区已改变，迟到侧坡 / 规则结果未采纳',true);return}if(kind==='sampling'&&(!data.side_slopes||!Array.isArray(data.side_slopes.samples)))throw new Error('侧坡响应缺少真实采样记录');if(kind==='rules'&&!Array.isArray(data.results))throw new Error('坡度规则响应缺少逐规则检查');setResult({kind,data,signature:snapshot,contextKey});setSelected(0);setStationPage(0);setTransectPage(0);notify(kind==='sampling'?'侧坡真实采样完成，请检查缺测和来源后明确应用':'坡度规则实际检查完成；规则配置尚未应用')
  }catch(e){if(mounted.current&&sequence.current===requestId&&latest.current===snapshot)setError(e instanceof Error?e.message:String(e))}finally{if(mounted.current&&sequence.current===requestId)setBusy(false)}
 }
 async function example(){const snapshot=signature,requestId=++sequence.current;setBusy(true);setResult(null);setError('');setDiscarded(false);setSavedView(false);try{const data=await request<any>('/terrain/side-slopes/example',{project});if(!mounted.current||sequence.current!==requestId)return;if(latest.current!==snapshot){setDiscarded(true);return}if(!Array.isArray(data.sources)||!data.config)throw new Error('合成输入响应缺少来源或采样配置');setSourceDraft(data.sources);setSampling({...defaults,...Object.fromEntries(Object.entries(data.config).filter(([k])=>k in defaults).map(([k,v])=>[k,v==null?'':String(v)]))});notify('已载入明确合成的测深源草稿；未改变当前工程，须真实采样并明确应用')}catch(e){if(mounted.current&&latest.current===snapshot)setError(e instanceof Error?e.message:String(e))}finally{if(mounted.current&&sequence.current===requestId)setBusy(false)}}
 async function apply(){if(!current||busy||pending||!result?.data.project){notify('输入或工作区已改变，不能应用旧候选',true);return}const snapshot=signature,candidate=result,requestId=++sequence.current,isCurrent=()=>mounted.current&&sequence.current===requestId&&latest.current===snapshot;setBusy(true);try{const accepted=await Promise.resolve(onApply(candidate.data.project,candidate.contextKey,isCurrent));if(!mounted.current)return;if(accepted===false){setError('工作区候选未通过应用校验；原工程保留，请重新预览');return}setResult(null);setSourceDraft(null);setSavedView(true);notify(candidate.kind==='sampling'?'已应用真实侧坡记录；完整工作区校验和保存仍使用现有工程流程':'已应用坡度规则列表；未修改测深或制造量')}catch(e){if(mounted.current&&latest.current===snapshot)setError(e instanceof Error?e.message:String(e))}finally{if(mounted.current)setBusy(false)}}
 function loadSavedParameters(){const m=project.side_slopes?.metadata;if(!m)return;setSampling({...defaults,...Object.fromEntries(Object.keys(defaults).filter(k=>m[k]!=null).map(k=>[k,String(m[k])])),end_kp_m:m.end_kp_m==null?'':String(m.end_kp_m),vertical_datum:typeof m.vertical_datum==='string'?m.vertical_datum:''});setSourceDraft(null);setSavedView(false);setError('');setDiscarded(false)}
 function editRule(index:number,patch:Partial<RuleDraft>){setRules(old=>old.map((r,i)=>i===index?{...r,...patch}:r));setSavedView(false)}
 function choose(index:number){setSelected(index);setTransectPage(0);setStationPage(Math.floor(index/100))}
 function slopesCsv(){return csv([['kp_m','longitude','latitude','heading_deg','port_slope_deg','starboard_slope_deg','side_slope_deg','max_sampled_abs_slope_deg','complete','source_boundary'],...samples.map(s=>[s.kp_m,s.longitude,s.latitude,s.heading_deg,s.port_slope_deg,s.starboard_slope_deg,s.side_slope_deg,s.max_sampled_abs_slope_deg,s.complete,s.source_boundary])])}
 function transectCsv(){return csv([['kp_m','offset_m','longitude','latitude','depth_m','source_id','source_fingerprint','fallback','slope_to_next_deg','source_boundary_to_next'],...(station?.transect||[]).map(s=>[station?.kp_m,s.offset_m,s.longitude,s.latitude,s.depth_m,s.source_id,s.source_fingerprint,s.fallback,s.slope_to_next_deg,s.source_boundary_to_next])])}
 return <main className="engineering-main side-slopes-panel"><div className="page-heading"><div><small>ROUTE SIDE SLOPES & KP RULES</small><h2>侧坡与坡度规则</h2><p>在真实路线站位建立横断面，按已应用共享测深库采样；纵坡与侧坡分别审查。</p></div></div>
 <div className="explanation">表面 KP 使用当前 WGS84 路线曲线；航向在路线转折处取出段单侧方向，终点取入段。偏移正值为右舷，水深向下为正，所有有符号侧坡角正值为右舷上坡。左右半幅和相邻探点最大绝对坡分别保留，不能用平均掩盖 V 形。采样完整不代表连续海床已测清，也不等同原厂算法精度。</div>
 <nav className="workflow-nav"><button className={tab==='sampling'?'active':''} onClick={()=>setTab('sampling')}>真实侧坡采样</button><button className={tab==='rules'?'active':''} onClick={()=>setTab('rules')}>KP 坡度规则</button></nav>
 {tab==='sampling'?<section className="settings-card"><div className="section-heading"><h3>测深来源 · {sources.filter(s=>s.enabled!==false).length} 个启用</h3>{project.side_slopes&&<button className="secondary-button" onClick={loadSavedParameters}>载入已应用侧坡的采样参数</button>}</div><p className="chart-meta">在“多源测深库”管理真实来源。本工具不从一维水深剖面挤出横向地形，不采纳 S-57 SOUNDG 作为工程测深。</p><div className="ss-sources">{sources.filter(s=>s.enabled!==false).map(s=><span key={s.id}>{s.name} · {s.kind.toUpperCase()} · 优先级 {s.priority} · {s.vertical_datum}</span>)}{!sources.some(s=>s.enabled!==false)&&<span className="inline-warning">尚无启用的共享测深源。请先明确应用真实来源，或载入标明合成的输入草稿。</span>}</div><div className="page-actions"><button className="secondary-button" disabled={busy||pending} onClick={example}>生成明确合成的侧坡源输入</button>{sourceDraft&&<button className="secondary-button" onClick={()=>{setSourceDraft(null);setSavedView(false)}}>放弃合成源草稿，使用工程共享源</button>}</div>{sourceDraft&&<div className="inline-warning ss-source-draft">当前是明确合成的来源草稿，不是现场测深；未改工程。应用采样候选时会同时应用这些来源，其他路径关联仍须完整工作区核验。</div>}
 <div className="tool-fields">{([['spacing_m','沿线最大站距 / m'],['half_width_m','左右半幅宽度 / m'],['cross_spacing_m','横向最大探点间距 / m'],['start_kp_m','采样起始表面 KP / m'],['end_kp_m','采样终止表面 KP / m（空白全线）']] as const).map(([key,label])=><label key={key}>{label}<input type="number" step="any" value={sampling[key]} onChange={e=>changeSampling(key,e.target.value)}/></label>)}<label>侧坡采样垂直基准<select value={sampling.vertical_datum} onChange={e=>changeSampling('vertical_datum',e.target.value)}><option value="">不筛选 · 启用源须同基准</option>{datums.map(d=><option value={d} key={d}>{d}</option>)}</select></label></div>
 <details className="ss-budget"><summary>侧坡采样预算 · 超限会明确拒绝</summary><div className="tool-fields">{([['max_query_points','侧坡查询点上限'],['max_work_units','侧坡逻辑工作量上限'],['max_output_bytes','侧坡输出字节上限']] as const).map(([key,label])=><label key={key}>{label}<input type="number" step="1" value={sampling[key]} onChange={e=>changeSampling(key,e.target.value)}/></label>)}</div></details><button className="primary-button" onClick={()=>run('sampling')} disabled={busy||pending}><Play size={14}/>{busy?'正在真实计算…':'计算真实侧坡预览'}</button></section>:<section className="settings-card"><div className="section-heading"><h3>按 KP 范围配置规则</h3><button className="secondary-button" onClick={()=>{setRules([...rules,ruleDraft({id:crypto.randomUUID(),name:'新坡度规则',enabled:true,kind:'both',start_kp_m:0,end_kp_m:null,max_inline_slope_deg:15,max_side_slope_deg:15})]);setSavedView(false)}}><Plus size={14}/>新增坡度规则</button></div><p className="chart-meta">纵坡使用当前有效沿线剖面；侧坡使用已应用、签名仍有效的侧坡记录。先应用侧坡预览，再检查规则。仅检查规则不会保存；缺测、过期和来源边界不显示绿色通过。</p>
 <div className="ss-rule-list">{rules.map((rule,i)=><article className="ss-rule-editor" key={rule.id}><div className="ss-rule-title"><label className="checkbox-label"><input aria-label={`启用坡度规则 ${i+1}`} type="checkbox" checked={rule.enabled!==false} onChange={e=>editRule(i,{enabled:e.target.checked})}/>启用</label><label>规则 {i+1} 名称<input aria-label={`坡度规则 ${i+1} 名称`} value={rule.name||''} onChange={e=>editRule(i,{name:e.target.value})}/></label><button className="icon-button danger" aria-label={`删除坡度规则 ${i+1}`} onClick={()=>{setRules(rules.filter((_,j)=>j!==i));setSavedView(false)}}><Trash2 size={15}/></button></div><div className="tool-fields"><label>检查方向<select aria-label={`坡度规则 ${i+1} 方向`} value={rule.kind} onChange={e=>{const kind=e.target.value as SlopeRule['kind'];editRule(i,{kind,max_inline_slope_deg:rule.max_inline_slope_deg||'15',max_side_slope_deg:rule.max_side_slope_deg||'15'})}}><option value="inline">仅纵坡</option><option value="side">仅侧坡</option><option value="both">纵坡与侧坡</option></select></label><label>规则起始 KP / m<input aria-label={`坡度规则 ${i+1} 起始 KP / m`} type="number" value={rule.start_kp_m} onChange={e=>editRule(i,{start_kp_m:e.target.value})}/></label><label>规则终止 KP / m · 空白全线<input aria-label={`坡度规则 ${i+1} 终止 KP / m`} type="number" value={rule.end_kp_m} onChange={e=>editRule(i,{end_kp_m:e.target.value})}/></label>{rule.kind!=='side'&&<label>最大绝对纵坡 / °<input aria-label={`坡度规则 ${i+1} 最大纵坡 / °`} type="number" step="any" value={rule.max_inline_slope_deg} onChange={e=>editRule(i,{max_inline_slope_deg:e.target.value})}/></label>}{rule.kind!=='inline'&&<label>最大绝对侧坡 / °<input aria-label={`坡度规则 ${i+1} 最大侧坡 / °`} type="number" step="any" value={rule.max_side_slope_deg} onChange={e=>editRule(i,{max_side_slope_deg:e.target.value})}/></label>}</div><small className="chart-meta">规则 ID：{rule.id}</small></article>)}{!rules.length&&<p className="chart-meta">尚无 KP 坡度规则。空列表检查会明确返回未配置，也可应用空列表移除现有规则。</p>}</div>
 <details className="ss-budget"><summary>规则检查预算</summary><div className="tool-fields">{([['max_rules','规则数量上限'],['max_work_units','规则逻辑工作量上限'],['max_output_bytes','规则输出字节上限']] as const).map(([key,label])=><label key={key}>{label}<input type="number" step="1" value={ruleBudget[key]} onChange={e=>{setRuleBudget({...ruleBudget,[key]:e.target.value});setSavedView(false)}}/></label>)}</div></details><button className="primary-button" disabled={busy||pending} onClick={()=>run('rules')}><Play size={14}/>{busy?'正在真实计算…':'检查 KP 坡度规则'}</button></section>}
 {project.side_slopes&&<p className="chart-meta ss-stored-record">工程中已有 {project.side_slopes.samples?.length??0} 站侧坡记录 · {storedValid?'当前路线与来源绑定有效':'待验或已过期，不能据记录存在称为有效'}。{storedValid&&!result&&<button className="ss-kp-button" onClick={()=>{setSourceDraft(null);setError('');setDiscarded(false);setSavedView(true)}}>查看当前有效已应用记录</button>}</p>}{project.side_slopes&&!storedValid&&<div className="inline-warning ss-stored-stale">已应用侧坡记录的路线 / 来源绑定尚未通过当前校验，不能绘制为当前结果或下载。请重新采样。</div>}
 {error&&<div className="inline-warning ss-error" role="alert">计算或应用失败：{error}。旧图表不作为本次结果。</div>}{discarded&&<div className="inline-warning ss-stale" role="status">输入或工作区在计算期间改变；迟到结果已丢弃，请重新计算。</div>}{result&&!current&&<div className="inline-warning ss-stale">输入、路径、来源或完整工作区已改变，旧预览失效；图表已隐藏，不可应用或下载。</div>}
 <div className="ss-result-actions page-actions"><button className="primary-button" disabled={!current||busy||pending||!actual?.project} onClick={apply}><Check size={14}/>{result?.kind==='rules'?'应用坡度规则列表':'应用侧坡记录'}</button><button className="secondary-button" disabled={(!current&&!storedCurrent)||busy||pending} onClick={()=>actual&&download(JSON.stringify(actual,null,2),'OceanRoute-side-slopes-'+(result?.kind||'saved')+'.json','application/json')}><Download size={14}/>下载当前侧坡 / 规则 JSON</button>{side&&<button className="secondary-button" disabled={busy||pending} onClick={()=>download(slopesCsv(),'OceanRoute-side-slopes.csv','text/csv;charset=utf-8')}><Download size={14}/>下载实际侧坡 CSV</button>}</div>
 {side&&<section className="ss-results"><div className="section-heading"><h3>{storedCurrent?'已应用':'预览'}沿 KP 侧坡 · {samples.length} 个真实站位</h3><span className="ss-data-state">{samples.filter(s=>s.complete).length} 站采样完整 · {samples.filter(s=>s.source_boundary).length} 站含来源边界</span></div><AlongSlopes samples={samples} selected={selected} onSelect={choose}/><div className="ss-station-picker"><button className="secondary-button" aria-label="上一侧坡站位" disabled={selected<=0} onClick={()=>choose(selected-1)}><ChevronLeft size={14}/></button><label>查看真实横断面站位<select value={Math.min(selected,samples.length-1)} onChange={e=>choose(Number(e.target.value))}>{samples.map((s,i)=><option key={i} value={i}>KP {f(s.kp_m)} m · {s.complete?'采样完整':'保留缺测'}{s.source_boundary?' · 来源边界':''}</option>)}</select></label><button className="secondary-button" aria-label="下一侧坡站位" disabled={selected>=samples.length-1} onClick={()=>choose(selected+1)}><ChevronRight size={14}/></button></div>
 {station&&<><div className="ss-station-info tool-summary">{[['KP / m',station.kp_m],['实际航向 / °',station.heading_deg],['左舷半幅坡 / °',station.port_slope_deg],['右舷半幅坡 / °',station.starboard_slope_deg],['全幅端点坡 / °',station.side_slope_deg],['最大探点绝对坡 / °',station.max_sampled_abs_slope_deg]].map(([label,v])=><div key={String(label)}><span>{String(label)}</span><strong>{f(v)}</strong></div>)}</div>{!station.complete&&<div className="inline-warning">该站包含真实缺测；需要穿过缺测的左右半幅 / 全幅坡保持空值，相邻有效探点最大值仍只是已采样部分。</div>}{station.source_boundary&&<div className="inline-warning">该站跨测深来源边界；库优先级不代表精度，接缝坡度不能自动认定为真实连续海床坡。</div>}<Transect sample={station}/><div className="section-heading"><h3>该站逐探点来源与缺测</h3><button className="secondary-button" disabled={busy||pending} onClick={()=>download(transectCsv(),'OceanRoute-cross-section-'+station.kp_m+'.csv','text/csv;charset=utf-8')}><Download size={14}/>下载选定横断面 CSV</button></div><div className="table-wrap ss-transect-table"><table><thead><tr><th>偏移 / m</th><th>经度 / °</th><th>纬度 / °</th><th>水深 / m</th><th>至下一探点坡 / °</th><th>实际来源 / 指纹</th><th>回退 / 来源尝试</th></tr></thead><tbody>{station.transect.slice(transectPage*100,transectPage*100+100).map((row,i)=><tr key={i} className={row.depth_m==null?'ss-nodata':''}><td>{f(row.offset_m)}</td><td>{f(row.longitude,7)}</td><td>{f(row.latitude,7)}</td><td>{f(row.depth_m)}</td><td>{transectPage*100+i===station.transect.length-1?'不适用':f(row.slope_to_next_deg)}</td><td>{row.source_id?sourceNames.get(row.source_id)||row.source_id:'无有效来源'}{row.source_fingerprint&&<small title={row.source_fingerprint}>{row.source_fingerprint.slice(0,16)}…</small>}</td><td>{row.fallback?`真实回退 ${row.fallback_count} 次`:'未回退'}{(row.attempts||[]).map((a:any,j:number)=><small key={j}>{sourceNames.get(a.source_id)||a.source_id} · {a.method} · {a.status}</small>)}</td></tr>)}</tbody></table></div>{station.transect.length>100&&<div className="pagination"><button disabled={!transectPage} onClick={()=>setTransectPage(transectPage-1)}>上一页探点</button><span>{transectPage+1} / {Math.ceil(station.transect.length/100)}</span><button disabled={(transectPage+1)*100>=station.transect.length} onClick={()=>setTransectPage(transectPage+1)}>下一页探点</button></div>}</>}
 <div className="table-wrap ss-stations-table"><table><thead><tr><th>表面 KP / m</th><th>左舷半幅坡 / °</th><th>右舷半幅坡 / °</th><th>全幅端点坡 / °</th><th>最大探点绝对坡 / °</th><th>采样与来源</th></tr></thead><tbody>{samples.slice(stationPage*100,stationPage*100+100).map((s,i)=><tr key={i} className={stationPage*100+i===selected?'selected':''} onClick={()=>choose(stationPage*100+i)}><td><button className="ss-kp-button" aria-label={`查看侧坡 KP ${s.kp_m} m`}>{f(s.kp_m)}</button></td><td>{f(s.port_slope_deg)}</td><td>{f(s.starboard_slope_deg)}</td><td>{f(s.side_slope_deg)}</td><td>{f(s.max_sampled_abs_slope_deg)}</td><td>{s.complete?'已采样点完整':'缺测'}{s.source_boundary?' · 来源边界':''}</td></tr>)}</tbody></table></div>{samples.length>100&&<div className="pagination"><button disabled={!stationPage} onClick={()=>setStationPage(stationPage-1)}>上一页站位</button><span>{stationPage+1} / {Math.ceil(samples.length/100)}</span><button disabled={(stationPage+1)*100>=samples.length} onClick={()=>setStationPage(stationPage+1)}>下一页站位</button></div>}</section>}
 {current&&result?.kind==='rules'&&<section className="ss-rule-results"><div className="section-heading"><h3>真实逐规则检查</h3><span className={`ss-rule-status ${actual.summary?.status||'unknown'}`}>{statuses[actual.summary?.status]||actual.summary?.status||'状态未提供'}</span></div><p className="chart-meta">超限 {f(actual.summary?.violation_count,0)} 项 · 数据是否全部可用：{actual.summary?.all_requested_data_available===true?'是 · 仅指请求的实际采样':'否 / 未知'}。即使存在超限，也继续展示同时存在的缺测与来源不确定性。</p>{actual.results.map((r:any,i:number)=><article className="ss-rule-result" key={r.id||i}><div className="section-heading"><h3>{r.name||r.id}</h3><span className={`ss-rule-status ${r.status}`}>{statuses[r.status]||r.status}</span></div><p className="chart-meta">{({inline:'纵坡',side:'侧坡',both:'纵坡与侧坡'} as Record<string,string>)[r.kind]} · KP {f(r.start_kp_m)} — {f(r.end_kp_m)} m</p>{Object.entries(r.components||{}).map(([key,v])=>{const c=v as any;return <div className="ss-rule-component" key={key}><strong>{key==='inline'?'纵坡':'侧坡'}：{statuses[c.status]||c.status}</strong><div className="ss-coverage">{Object.entries(c.coverage||{}).map(([k,value])=><span key={k}>{coverageLabels[k]||k}：{coverageValue(value)}</span>)}</div></div>})}{(r.violations||[]).length>0&&<div className="table-wrap"><table><thead><tr><th>方向</th><th>起始 KP / m</th><th>终止 KP / m</th><th>坡度 / °</th><th>阈值 / °</th><th>不确定性</th></tr></thead><tbody>{r.violations.map((v:any,j:number)=><tr key={j}><td>{v.kind==='inline'?'纵坡':'侧坡'}</td><td>{f(v.start_kp_m??v.kp_m)}</td><td>{f(v.end_kp_m??v.kp_m)}</td><td>{f(v.value_deg)}</td><td>{f(v.limit_deg)}</td><td>{v.uncertain?'来源 / 数据不确定':'无附加标记'}</td></tr>)}</tbody></table></div>}{(r.diagnostics||[]).map((d:any,j:number)=><div key={j} className="inline-warning">{d.code} · {d.message}</div>)}</article>)}{!actual.results.length&&<div className="inline-warning">没有配置规则，本次没有可称为通过的坡度检查。</div>}</section>}
 {actual&&<><div className="ss-warnings">{(actual.warnings||[]).map((w:any,i:number)=><div className="inline-warning" key={i}>{typeof w==='string'?w:`${w.code} · ${w.message}`}</div>)}</div><details className="ss-diagnostics"><summary>实际签名、质量、预算与适用限制</summary><pre>{JSON.stringify({metadata:side?.metadata||actual.metadata,route_signature:side?.route_signature,quality:actual.quality,summary:actual.summary,budget:actual.budget,assumptions:actual.assumptions},null,2)}</pre></details></>}
 </main>
}
