import {useEffect,useRef,useState,type MouseEvent} from 'react';
export const bands=[{id:'depth_m',name:'水深',unit:'m'},{id:'slope_deg',name:'坡度',unit:'°'},{id:'aspect_deg',name:'坡向',unit:'°'},{id:'hillshade',name:'地形阴影',unit:'0–1'}];
export const terrainFormat=(v:any)=>v==null?'—':typeof v==='number'?v.toLocaleString('zh-CN',{maximumFractionDigits:3}):String(v);
export function Heatmap({preview,band}:{preview:any;band:string}){
  const ref=useRef<HTMLCanvasElement>(null),[hover,setHover]=useState<any>(null);const matrix:(number|null)[][]=preview[band],rows=matrix.length,cols=matrix[0]?.length||0;const finite=matrix.flat().filter((v):v is number=>typeof v==='number'),low=band==='aspect_deg'?0:band==='hillshade'?0:(finite.length?Math.min(...finite):0),high=band==='aspect_deg'?360:band==='hillshade'?1:(finite.length?Math.max(...finite):0);
  function color(v:number){const f=Math.max(0,Math.min(1,(v-low)/(high-low||1)));if(band==='hillshade'){const g=Math.round(f*245);return `rgb(${g},${g},${g})`}if(band==='aspect_deg')return `hsl(${v},55%,58%)`;if(band==='slope_deg')return `hsl(${45-f*35},${45+f*30}%,${87-f*42}%)`;return `hsl(${175+f*42},${35+f*15}%,${88-f*59}%)`}
  useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const w=900,h=420;canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);const dx=w/cols,dy=h/rows;matrix.forEach((row,j)=>row.forEach((v,i)=>{ctx.fillStyle=v===null?((i+j)%2?'#e3e8ec':'#eff2f5'):color(v);ctx.fillRect(i*dx,(rows-1-j)*dy,Math.ceil(dx+.3),Math.ceil(dy+.3))}));},[preview,band]);
  function move(e:MouseEvent<HTMLCanvasElement>){const bounds=e.currentTarget.getBoundingClientRect(),i=Math.min(cols-1,Math.max(0,Math.floor((e.clientX-bounds.left)/bounds.width*cols))),j=Math.min(rows-1,Math.max(0,rows-1-Math.floor((e.clientY-bounds.top)/bounds.height*rows)));setHover({x:preview.x_m[i],y:preview.y_m[j],depth:preview.depth_m[j][i],value:matrix[j][i],i,j})}
  return <div className="terrain-preview"><div className="heatmap-axis y-axis">Y / m · 北 ↑</div><canvas ref={ref} onMouseMove={move} onMouseLeave={()=>setHover(null)} aria-label={`${bands.find(b=>b.id===band)?.name}网格预览`}/><div className="heatmap-axis x-axis">X / m · 东 → <span>{terrainFormat(preview.x_m[0])} – {terrainFormat(preview.x_m.at(-1))}</span></div><div className="terrain-legend"><span>{terrainFormat(low)} {bands.find(b=>b.id===band)?.unit}</span><i style={{background:band==='hillshade'?'linear-gradient(90deg,#111,#eee)':band==='aspect_deg'?'linear-gradient(90deg,#cc5555,#c9cc55,#55cc5f,#55c9cc,#6655cc,#cc55c9,#cc5555)':band==='slope_deg'?'linear-gradient(90deg,#f7f2d7,#d76427)':'linear-gradient(90deg,#d6edec,#164e72)'}}/><span>{terrainFormat(high)} {bands.find(b=>b.id===band)?.unit}</span><b/>缺测</div>{hover&&<div className="terrain-hover"><strong>网格 {hover.i+1}, {hover.j+1}</strong><span>X {terrainFormat(hover.x)} m / Y {terrainFormat(hover.y)} m</span><span>{bands.find(b=>b.id===band)?.name}：{terrainFormat(hover.value)} {bands.find(b=>b.id===band)?.unit}{hover.value===null?'（NoData）':''}</span><span>水深：{terrainFormat(hover.depth)} m</span></div>}</div>;
}
